### ISSUE TITLE
node email templates integration?

### ISSUE THREAD

**Issue by niftylettuce** [Mailtrain-org/mailtrain#1]
https://github.com/niftylettuce/node-email-templates

**Comment by andris9** [comment]
I'm not sure. node-email-templates feels a bit heavy and by the README does not work well in Windows. Some kind of templating support would be great though, especially considering CSS inlining. Currently the only templating done is by [this function](https://github.com/andris9/mailtrain/blob/54fa30701ee8b75151dae485e14056ed679e44f5/lib/tools.js#L150-L171).

**Comment by MiguelPortela** [comment]
Hey Andris9  Nice Job.

**Comment by robsalasco** [comment]
A simple form-based templating would be nice :)

**Comment by forgeOneHQ** [comment]
I am closing this issue again. Please open a new one if still a topic.
