### ISSUE TITLE
Feature Request: eCommerce Automation

### ISSUE THREAD

**Issue by fthobe** [Mailtrain-org/mailtrain#1000]
## Scope
Implement features to allow covering following 4 features: 
1. Building Blocks for User Synchronisation
2. Abandoned Cart Emails
3. Follow Up on Purchase Emails

For that purpose it's necessary to store a history in the subscriber list that contains: 

1. Products purchased by a subscriber or alternatively Order History

I would suggest for that purpose to build up a product database inside Mailtrain that covers: 
1. Product Image
2. Product Link
3. Product Title
4. Product Description
5. Product Price

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by fthobe** [comment]
> We are going to start with the development and testing of mailtrain v3 in the next weeks.
> 
> 
> 
> You are welcome to help us with the testing as soon as the first release candidate is available.

Hey, absolutely. Has this feature request been completed? We would be absolutely willing to sponsor it.

**Comment by saschafoerster** [comment]
@fthobe Do you know Mautic? We use Mailtrain mostly for newsletters and Mautic for all kinds of marketing automations. Maybe Mautic is better suited to your needs? http://mautic.org
