### ISSUE TITLE
Webhooks accepting Click- and Open-Events

### ISSUE THREAD

**Issue by sltsm** [Mailtrain-org/mailtrain#1001]
Hi Folks,

I understand there are Webhooks to accept **Bounce**- & **Complaint**-notifications via SNS, but those routes won't handle events of type **Click** or **Open** currently. 

Click and Open events are handled via the /links route, directed to by the mailtrain-generated tracking-links (if click-tracking is enabled).

Is there any particular reason the Webhooks won't accept Those events too? Wouldn't it easily be possible to fire the links.countClick() method with its required arguments from within the webhooks-route too?

The advantage of managing click-events via SNS might be slightly better performance but mostly higher reliability. In case the Mailtrain server is down / restarting, recipients that click a link in the mail won't reach the Target-Website at all. I trust aws better to keep their serves available, than myself.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
