### ISSUE TITLE
Getting lots of SQL timestamp related errors using the docker image

### ISSUE THREAD

**Issue by PaulVipond** [Mailtrain-org/mailtrain#1003]
I'm using the latest Docker image behind a Traefik proxy. On the admin site I'm getting SQL errors on the following pages: Templates, Campaigns, Reports and Administration->Send Configurations. As an example, the error on the Templates page is:

`select count(*) as `recordsFiltered` from (select `templates`.`id` from `templates` inner join `namespaces` on `namespaces`.`id` = `templates`.`namespace` inner join (select distinct `entity` from `permissions_template` where `user` = 2 and `operation` in ('view')) as `permitted__template` on `permitted__template`.`entity` = `templates`.`id` where (`templates`.`name` like '%%' or `templates`.`description` like '%%' or `templates`.`type` like '%%' or `templates`.`tag_language` like '%%' or `templates`.`created` like '%%' or `namespaces`.`name` like '%%')) as `records` limit 1 - ER_WRONG_VALUE: Incorrect TIMESTAMP value: '%%'`

The other errors are similar - in each case, the system is attempting to create SQL which uses a LIKE operator on a timestamp field. I'd appreciate any advice on how to fix this - once the error occurs, you can't access functions on the page.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
