### ISSUE TITLE
V2 User Editable Field Designation - Feature Request

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#1008]
It would be nice if there was some idea of user editable fields.
Example: When a users clicks `manage preferences` link they can edit any field in the list. However, we have some fields that might define where/when/how the user made it into the list or partner codes that help us determine any sort of revenue sharing that may be associated with that user.

It would be nice if we could have a couple options on the list fields:
- Ability to make field invisible to user
- Ability to make field disabled to user changes

There may be other use cases for field customization but those two option I believe would add lots of flexibility for different scenarios.

**Comment by bures** [comment]
But you can make a field invisible to user. You just select that it is omitted from the edit form. Doesn't this work for you? Thanks.

**Comment by ericuldall** [comment]
Yes, that works as needed. Thank @bures
