### ISSUE TITLE
(V2) How to schedule an email -> Changing UTF Zone & X:XX am/pm Time? - Broadcast / Automation modes

### ISSUE THREAD

**Issue by dgulias** [Mailtrain-org/mailtrain#1009]
Hello there. I like very much this app.

After setting up everything I need, templates, Regular Campaignes and Automation (Triggered) Campaigns, I just didn't understand one thing:

How to setup scheld time?

Is not possible on every Account in Send Configuration we setup the UTF zone time of this account? And on every Regular Campaign or Triggered Campaign we just say to deliver Now or Schedule to "X:XX PM" or "X:XX AM" according to the Email Sender UFT zone? 

Cheers.

**Comment by bures** [comment]
Is this v1 or v2? In v2, you can set the timezone if you schedule a campaign. Does this not work for you?

**Comment by dgulias** [comment]
> Is this v1 or v2? In v2, you can set the timezone if you schedule a campaign. Does this not work for you?

This is the V2 develepment branch. I can't see timezone schedule options. Can you show me a print of this option in action?
I didn't update from development to new default V2 yet. Need to see how to do this without lose the campaigns, templates and lists data.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by dgulias** [comment]
> We are going to start with the development and testing of mailtrain v3 in the next weeks.
> 
> You are welcome to help us with the testing as soon as the first release candidate is available.

This is amazing... Tell me when ready so I will do my best to help you.
