### ISSUE TITLE
Feature: POST to subscription form

### ISSUE THREAD

**Issue by jloh** [Mailtrain-org/mailtrain#101]
Is it possible to embed/POST data to the subscription forms at this stage? I'd like to embed/have a signup form in another website instead of linking to mailtrain directly. Apologies if this is already possible!

**Comment by wallydz** [comment]
Personally as i had no choice i had to create a curl script and manage that via API

**Comment by witzig** [comment]
There's now an experimental [Subscription Widget](https://github.com/Mailtrain-org/mailtrain#subscription-widget) available in master branch.

**Comment by sokulski** [comment]
@witzig Hello. Looks like the anchor you were originally linking to has been removed.

I see you're using the widget.js in your Mailtrain Wordpress plugin. Is there any additional detail available on the functionality of the Subscription Widget?

**Comment by hiyukoim** [comment]
I know we already have a widget, but I would like to see POST integration, too.
There's a lot of other services and software which integrate with HTML tag like this.
`<form action="https://domain.com/xxxxxxx/subscription" ....`

**Comment by t3hmrman** [comment]
I've made a tiny utility for getting a POST-able endpoint using the mailtrain API, for those that can host a process alongside their `mailtrain` instance, check it out @ https://gitlab.com/mrman/mailtrain-form-post-sidecar (I've [written about it as well if you're into k8s](https://vadosware.io/post/setting-up-mailtrain-on-k8s/))
