### ISSUE TITLE
(V2) Simple Opt-in not working

### ISSUE THREAD

**Issue by jacksparrowid** [Mailtrain-org/mailtrain#1010]
# what happen ?

Whatever we enter into the field "unsubscription" into a list, every user who subscribe receive a email for confirmation

![image](https://user-images.githubusercontent.com/13906379/108211471-02d65500-712d-11eb-95f9-3ae53bf615d1.png)

and the forms show this confirmation page 
![image](https://user-images.githubusercontent.com/13906379/108216019-44b5ca00-7132-11eb-827b-b2d0df1351cc.png)

# What is expected ?

What's expected is when we choose option "one-step xxxx" in parameteres of a list, the user must not receive nor the email for confirmation, nor the confirmation page.

**Comment by bures** [comment]
This settings is for unsubscription only. The subscription is always two step process.
