### ISSUE TITLE
Gutenberg editor?

### ISSUE THREAD

**Issue by strarsis** [Mailtrain-org/mailtrain#1012]
Would it make sense to add support for newsletter/email editing using the [Gutenberg editor](https://github.com/WordPress/gutenberg)?
It ist he new default Wordpress editor, so adoption may be easier.

**Comment by janus-reith** [comment]
Here is an example how Gutenberg can be used to create mjml-based emails, made by Automattic:
https://github.com/Automattic/newspack-newsletters

I had the same idea and was happy to find out they already did that.
Recreating the actual php-based logic to convert the blocks to mjml templates would probably be rather simple, but overall getting gutenberg with all the toolbars and functionality to run outside wp and in some normal react environment involves quite a bit of effort, tried it myself.

I'm still looking for some solution to use a block-based editor and not rely on PHP, although I had some custom nodejs/react/graphql solution in mind and not necessarily Mailtrain as I'm really unsure about how active this still is.

As a more custom and lighter solution I consider [craft.js](https://github.com/prevwong/craft.js/) as base for a custom email editor and played with that a bit, still not 100% decided wether to stick with that or use Gutenberg.

**Comment by forgeOneHQ** [comment]
I am closing the issue since it is more a feature request. You are welcome to participate on this project for implementing additional editors :)
