### ISSUE TITLE
Same template two days later... won't send images

### ISSUE THREAD

**Issue by Wuuuuuuuuuuuuuuuuuuuu** [Mailtrain-org/mailtrain#1014]
A few days ago, I used a test template and test mail accounts, it worked well.
Today, with the same template and same test accounts, the reference to a image in the template is sent as a link to a url, not an attachment. The server is local, unreachable from outside.
A few days ago, it was sent as a reference to an attachment.
What have I done wrong?
Thanks!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
