### ISSUE TITLE
How do I set the subject line of an RSS subcampaign to [ENTRY_TITLE]?

### ISSUE THREAD

**Issue by jordanurbs** [Mailtrain-org/mailtrain#1016]
If this is possible, it's not very intuitive. And putting the [ENTRY_TITLE] merge tag in the RSS campaign subject line does not work.. needs to work per subcampaign. Thanks for any tips.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
