### ISSUE TITLE
(feature/nice-to-have) honor DATABASE_URL 

### ISSUE THREAD

**Issue by fwolfst** [Mailtrain-org/mailtrain#1020]
I am not sure where this convention comes from but afaik it is implemented in Heroku, dokku and Ruby on Rails:

It would be great if mailtrain would respect these environment variables to define the database connections:

```bash
REDIS_URL=redis://:SOME_PASSWORD@dokku-redis-lolipop:6379/lolipop
DATABASE_URL=mysql://lolipop:SOME_PASSWORD@dokku-mysql-lolipop:3306/lolipop
```
(these are taken from the respective dokku plugins).

Btw I outlined the steps for a quick and easy dokku deploy (v1) here: https://fwolfst.github.io/devops/dokku/2021/03/07/mailtrain_dokku.html .

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
