### ISSUE TITLE
Cors issue when email already registered

### ISSUE THREAD

**Issue by Linch1** [Mailtrain-org/mailtrain#1021]
I'm working on ubuntu with dockers on a Two step email list.
I'm embending the subscription form inside my website. I have already enabled the `cors` property my domain ( actually localhost )  and it works correctly, so i can succesfully register new users to a list and get the confirmationb e-mail.  I made various tests to check if all was working but when i try to register an already present email I correctly recive the email saying i am already registered but on the frontend I get a cors issue for redirect. Here the thrown erros

![Schermata da 2021-03-08 14-54-54](https://user-images.githubusercontent.com/47044850/110330850-98734f00-801e-11eb-9485-44df825cab8f.jpg)

**Comment by bures** [comment]
Honestly, not sure. I have not yet had the need to implement the subscription widget. The one it is in v2 was taken from v1 and never properly tested. If you figure out the issue, I will be happy for a PR with a fix.

**Comment by ngearhart** [comment]
This may be a misconfiguration of urls - there are requests going to `localhost` and `localhost:3000` (two different domains according to CORS) - is this intentional?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
