### ISSUE TITLE
V2: Campaign Links Statistics Not Rendering

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#1024]
I've verified that campaign_links table is being updated however those clicks are not showing up in the UI of mailtrain.

**Comment by forgeOneHQ** [comment]
@ericuldall can you provide us some more infos on this?

Screenshots can also help!

**Comment by ericuldall** [comment]
![image](https://user-images.githubusercontent.com/3223296/132261643-e80efca3-400f-468b-b943-5c827fc69002.png)

Clicked is always 0, even when there's plenty of clicks.

**Comment by forgeOneHQ** [comment]
@ericuldall , what does the systemctl -u mailtrain.service says?

We need details about how did you deployed mailtrain (Docker or directly on OS with installer) and log files, thanks!

**Comment by ericuldall** [comment]
We run it on Docker in Kubernetes.
Something to note, our stage instance works fine running the same image so may be related to the fact we have trillions of rows in our links table, but can't be sure. I'll have to check if there's any relevant logs but I don't recall seeing anything.

**Comment by forgeOneHQ** [comment]
Sounds for me like it cannot write the information to the database. The question is why so would be good if you can check the log files. Try to get into the container and log the journal. Should work with systemctl -u mailtrain.service -f, so you can try open the newsletter and make a click. Something has to be locked in the application.

**Comment by ericuldall** [comment]
This might be the only useful log I see:
```
E 2021-09-06T21:47:03.381610549Z verb HTTP Error: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'link' at row 1
 
E 2021-09-06T21:47:03.381714168Z verb HTTP     at Query.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
 
E 2021-09-06T21:47:03.381722378Z verb HTTP     at Query.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
 
E 2021-09-06T21:47:03.381727261Z verb HTTP     at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
 
E 2021-09-06T21:47:03.381757247Z verb HTTP     at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
 
E 2021-09-06T21:47:03.381761984Z verb HTTP     at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
 
E 2021-09-06T21:47:03.381766718Z verb HTTP     at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
 
E 2021-09-06T21:47:03.381771009Z verb HTTP     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)
 
E 2021-09-06T21:47:03.381775617Z verb HTTP     at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)
 
E 2021-09-06T21:47:03.381780003Z verb HTTP     at Socket.emit (events.js:198:13)
 
E 2021-09-06T21:47:03.381784154Z verb HTTP     at Socket.EventEmitter.emit (domain.js:448:20)
 
E 2021-09-06T21:47:03.381788234Z verb HTTP     at addChunk (_stream_readable.js:287:12)
 
E 2021-09-06T21:47:03.381792286Z verb HTTP     at readableAddChunk (_stream_readable.js:268:11)
 
E 2021-09-06T21:47:03.381796410Z verb HTTP     at Socket.Readable.push (_stream_readable.js:223:10)
 
E 2021-09-06T21:47:03.381800700Z verb HTTP     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
 
E 2021-09-06T21:47:03.381804880Z verb HTTP     --------------------
 
E 2021-09-06T21:47:03.381808924Z verb HTTP     at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
 
E 2021-09-06T21:47:03.381829299Z verb HTTP     at Connection.query (/app/server/node_modules/mysql/lib/Connection.js:201:25)
 
E 2021-09-06T21:47:03.381836039Z verb HTTP     at /app/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
 
E 2021-09-06T21:47:03.381840711Z verb HTTP     at Promise._execute (/app/server/node_modules/bluebird/js/release/debuggability.js:384:9)
 
E 2021-09-06T21:47:03.381861787Z verb HTTP     at Promise._resolveFromExecutor (/app/server/node_modules/bluebird/js/release/promise.js:518:18)
 
E 2021-09-06T21:47:03.381866371Z verb HTTP     at new Promise (/app/server/node_modules/bluebird/js/release/promise.js:103:10)
 
E 2021-09-06T21:47:03.381870583Z verb HTTP     at Client_MySQL._query (/app/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
 
E 2021-09-06T21:47:03.381875797Z verb HTTP     at Client_MySQL.query (/app/server/node_modules/knex/lib/client.js:192:17)
 
E 2021-09-06T21:47:03.381880059Z verb HTTP     at /app/server/node_modules/knex/lib/transaction.js:232:21
 
E 2021-09-06T21:47:03.381884147Z verb HTTP     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 
E 2021-09-06T21:47:03.381888360Z verb HTTP     at Function.Promise.attempt.Promise.try (/app/server/node_modules/bluebird/js/release/method.js:39:29)
 
E 2021-09-06T21:47:03.381892578Z verb HTTP     at Client_MySQL.trxClient.query (/app/server/node_modules/knex/lib/transaction.js:229:33)
 
E 2021-09-06T21:47:03.381912861Z verb HTTP     at Runner.<anonymous> (/app/server/node_modules/knex/lib/runner.js:138:36)
 
E 2021-09-06T21:47:03.381917559Z verb HTTP     at Runner.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 
E 2021-09-06T21:47:03.381921853Z verb HTTP     at Runner.query (/app/server/node_modules/bluebird/js/release/method.js:15:34)
 
E 2021-09-06T21:47:03.381926048Z verb HTTP     at /app/server/node_modules/knex/lib/runner.js:47:21
 
E 2021-09-06T21:47:03.381930158Z verb HTTP     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 
E 2021-09-06T21:47:03.381934343Z verb HTTP     at /app/server/node_modules/bluebird/js/release/using.js:185:26
 
E 2021-09-06T21:47:03.381938578Z verb HTTP     at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
 
E 2021-09-06T21:47:03.381943003Z verb HTTP     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:547:31)
 
E 2021-09-06T21:47:03.381947266Z verb HTTP     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:604:18)
 
E 2021-09-06T21:47:03.381951473Z verb HTTP     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:649:10)
 

```

**Comment by forgeOneHQ** [comment]
@bures have you seen such error before?

**Comment by ericuldall** [comment]
Also, we don't run mysql in a container. We use a large managed SQL database.

**Comment by ericuldall** [comment]
The links table is problematic though in concept. Let's say I have a small list (100k users) and I have a template with 10 links. I'm generating 1MM rows in the links table every time I send that list.

In reality we have many lists that are much larger than that. As a failover we run our own pixel system for opens and clicks, but it's designed to be stateless. All of the data is encoded into the link and we only track engagements, so it reduces our data footprint by a lot.

I think if mailtrain aims to serve larger use cases there will come a time to implement something similar. I'm happy to share notes.

**Comment by ericuldall** [comment]
Would also be great if the way pixels were added to templates was configurable. Just allow me to put in my own pixel easily and have mailtrain apply it to every link/template footer.

**Comment by forgeOneHQ** [comment]
@ericuldall we need to get first a base for mailtrain to have a stable development team beside @bures who is managing mostly of it at the moment. I am helping out to close issues, collect them and develop a bit.

Everyone who wants to participate is welcome :)

**Comment by bures** [comment]
Nope. I have not seen such error.

**Comment by ericuldall** [comment]
After a quick search of that error:
https://stackoverflow.com/questions/14284494/mysql-error-1264-out-of-range-value-for-column
It seems that we've exceeded the maximum integer and so mysql is throwing that out of range error. This is pretty clearly due to the fact that our link table grows too large.

A couple solutions I can see:

1. move to the system where we only track links that have been clicked
2. move away from auto increment integer to some other sort uuid... something alpha numeric would give us a larger keyspace but not sure that wouldn't present other problems

**Comment by ericuldall** [comment]
We could also move to BIGINT on those, but that would simply kick the can down the road...how far I know not. Perhaps some garbage collection would be worthwhile to consider.

**Comment by bures** [comment]
Which table is it? How many rows in the table? Thanks.

**Comment by ericuldall** [comment]
you know what...looks like the issue is in the campaign_links table. A bunch of the links have link id set to -1

**Comment by ericuldall** [comment]
links table is unsigned INT and campaign_links table link column is not unsigned. Not sure if that's problematic during joins.

**Comment by ericuldall** [comment]
So looks like -1 is supposed to be for opens so maybe that's not the issue.

**Comment by ericuldall** [comment]
aaah, this makes sense now.

links table is using unsigned INT with a max value of 4,294,967,295
campaign_links table is using INT with a max value of 2,147,483,647

This means once your links table reaches an ID of 2147483647 you can no longer write to the campaign_links table, because it has half the size in positive integers.

So the problem is not too many rows in campaign_links, the problem is it's referencing a value in the link column that is too large for the schema.

**Comment by ericuldall** [comment]
could probably change the schema to have a type column. 0= opens, 1 = clicks. Then just move the link schema to unsigned INT to match. At least that way you'll run out of space at the same time.

**Comment by bures** [comment]
And how many rows do you have?

**Comment by ericuldall** [comment]
In this instance we're at 2,491,379,453

**Comment by ericuldall** [comment]
Probably best practice to make sure a foreign key shares the same schema in both tables :D

**Comment by bures** [comment]
As a quick fix, just delete some old entries for which you don't need statistics any more. I may have a developer working on scalability and HA for MailTrain. @talheim-it, could you create a new feature request in scalability in which we could start collecting these issues? Thanks.

**Comment by ericuldall** [comment]
I have to think about this a bit. I would have to delete a lot of entries and it may be easier to move those values to BIGINT and buy myself more time

**Comment by ericuldall** [comment]
@bures after more thought, deleting rows doesn't solve the problem. The only way to solve the problem is either to increase the integer size of the link column in campaign links or reset the auto increment on the links table.

**Comment by bures** [comment]
@ericuldall - You are probably right. As a short term solution this sounds the best. I'm a bit hesitant to introduce it to the main Mailtrain branch. However, I don't see any problem why you couldn't just change the schema of the table in your db to use BIGINT. Let us then know if it works or if you experience any problems. Thanks.

**Comment by bures** [comment]
As for the long-term solution, my thoughts go in the direction of using another storage backend (e.g. Mongo instead of MySQL) for the things which have to scale. This concerns mainly the campaign_messages and campaign_links tables. I'm thinking Mongo because it would give us horizontal scalability, which would be handy when making the sending process horizontally scalable. 
Alternatively, we could create a new set of tables for each campaign. This was the v1 solution, but it has other downsides. Maybe, we could also have a hybrid solution, where the campaign_links is stored in MySQL split to table per campaign and the campaign_messages, which is more like a persistent queue, would be located in Mongo. We will have to evaluate the options. That's why it's important to me if you have any performance issues probably attributable to MySQL.

**Comment by ericuldall** [comment]
I think something like that is going the right direction. In general most of our large scale applications have metrics decoupled from functional data. We store all our metrics in a data warehouse rather than a transactional DB.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
