### ISSUE TITLE
Checkbox custom field not working on form due to javascript

### ISSUE THREAD

**Issue by carda-momo** [Mailtrain-org/mailtrain#1026]
When I include a checkbox custom field in my subscription form, when I load it on Firefox or Chrome, I get a message saying javascript needs to be enabled. I dont have anything on my browser blocking Javascript so I don't know if this has to be enabled at a Mailtrain level.
Thanks in advance.

**Comment by bures** [comment]
Can you post a screenshot?

**Comment by forgeOneHQ** [comment]
@carda-momo please open a new issue with all infos so that we can help you with debugging it. :)
