### ISSUE TITLE
Security: GHSL-2021-032

### ISSUE THREAD

**Issue by agustingianni** [Mailtrain-org/mailtrain#1028]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by elitzer2** [comment]
@bures

**Comment by agustingianni** [comment]
Hello @elitzer2 & @bures I was wondering if you got my emails with the security report. Thank you.

**Comment by bures** [comment]
@agustingianni - thanks for the report. You can use my as the maintainer. The master branch (v1) is obsolete, so I think it's the time we move the devel (v2) to master and officially deprecate the master. We won't actively bugfixing v1.

**Comment by agustingianni** [comment]
Thank you for the answer, do you think it is ok and we go ahead with the publication of the report since v1 is deprecated? Thank you again.

**Comment by bures** [comment]
I think it is OK since we already have the patch. I'll officially deprecate v1 during the weekend. Thank you.

**Comment by agustingianni** [comment]
Great, thanks, but I would like to point out that the patch only addresses one instance of the pattern. The report contains a link to a private www.lgtm.com with all the places that call the function in an insecure way. If you still are ok with me going ahead and publishing let me know.  I will add a note in the report that the branch is deprecated to avoid any confusion.

Thanks

**Comment by bures** [comment]
Then please give me till next week. I'll take a look at it during the weekend and I'll officially deprecate v1. Where do I find the report you are referring to? Thanks.

**Comment by agustingianni** [comment]
I sent it to the email listed on your github profile but I don't think it reached you. If you don't want to publish your email maybe you can contact us at securitylab@github.com and I will reply with the report.

**Comment by agustingianni** [comment]
Thanks for the email @bures I received yours and replied with the report. I hope this time it goes trorough.
