### ISSUE TITLE
Problem uploading images with Mosaico (and GrapeJS) - Unexpected error (Bad Gateway) 

### ISSUE THREAD

**Issue by camillem** [Mailtrain-org/mailtrain#1030]
Hi, 
Just to let you know that some problem for uploading images may arise with nodejs version prior to v8.
Root cause being related to 
https://github.com/aguidrevitch/jquery-file-upload-middleware/issues/85
Cheers,
Camille

**Comment by gramakri** [comment]
@bures We hit this in Cloudron as well. I see that the mailtrain 1 branch (master) is lagging in package updates and node support. Is there interest in keeping mailtarin 1 maintained? When v2 is out will v1 be deprecated (I couldn't find any release time line or initial release for v2). I can submit PRs for updating v1.

**Comment by forgeOneHQ** [comment]
@gramakri V2 is out, I think maybe we can close that issue and look to go on V2 since I also get some deprecation warnings here and they should be fixed.
