### ISSUE TITLE
The security token included in the request is invalid - AWS SES

### ISSUE THREAD

**Issue by Mostela** [Mailtrain-org/mailtrain#1031]
Hi, I have a problem in send a email market to my users, error is "_SMTP response: The security token included in the request is invalid._" I used AWS SES, my keys is right but a have this error in send emails to her.

I try In other application with python 3 and boto3 and send emails normal. 

But no time long ago, I need change my method send mail to AWS because is obsolete. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/45977530/113933031-7a8a3d00-97ca-11eb-99c1-4d819c868f1f.png)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
