### ISSUE TITLE
Feature request: creation of access tokens with config

### ISSUE THREAD

**Issue by cortopy** [Mailtrain-org/mailtrain#1046]
I'm using mailtrain in a CI environment with docker. I'd like to query the API but in order to do that I have to create an access token using a browser, which is not that easy in a CI headless setup.

I can see that v1 had some kid of toml file with the possibility of setting it up. Would it be possible to bring this back? Or maybe just an `ACCESS_TOKENS` environment variable that does just that?

**Comment by bures** [comment]
The problem with access tokens is that they are tied to a user. In Mailtrain v1, there was only a single user, which made this configuration easier. We could have a way to set up the access token for admin user. In my view, this would be done best in docker-entrypoint.sh. I could image two additional paramters: `ADMIN_ACCESS_TOKEN` and `ADMIN_PASSWORD`. The docker-entrypoint.sh would replicate the functionality from server/models/users.js to set the password and access token for user 1.

I can implement it, but I don't have the time to setup a test environment to test that it works properly. So if you are willing to test it, we can give it a go.

**Comment by cortopy** [comment]
thanks @bures! I ended up writing a sql query for this: `UPDATE mailtrain.users SET access_token='${accessToken}' WHERE id=1;` when setting up my tests but this approach would be so much better.

Using ADMIN_ACCESS_TOKEN and ADMIN_PASSWORD sounds ideal to me. That's how database images work in order to create the first users.

I can test any changes you do. I guess I'd only need to build the image with the Dockerfile in a git branch?

**Comment by bures** [comment]
It's this branch: https://github.com/Mailtrain-org/mailtrain/tree/fix-1046

Please give it a try and let me know.

**Comment by cortopy** [comment]
I've just done a little bit of testing. I can see a token created but I'm not sure I get how it works.

By setting `ADMIN_ACCESS_TOKEN` to `access_token` and `ADMIN_PASSWORD` to `admin_password` this is what gets created in mariadb

![image](https://user-images.githubusercontent.com/8725825/121254853-a8f7c780-c8a2-11eb-8499-9df349560a33.png)

It looks as if `ADMIN_PASSWORD` sets the token. Is this right?

**Comment by bures** [comment]
My mistake. Try it now please.

**Comment by cortopy** [comment]
It's working now!!! thank you!

**Comment by bures** [comment]
Perfect. Thanks. I'll merge it to v2 then.
