### ISSUE TITLE
V2:updating from v2 branch

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#1047]
I tried to update with git, but the renaming of the branches caused my git not to download nor update anything. I am by no means expert of git, so I tried a few things and may have royally messed up my production environment. .. I have made a backup, so I can return to a previous point in time. 

Can anyone explain to me which commands I should give to update a system based on the old "development" branch to one that works from the actual v2 branch? 

thank you so much. 

ah and I have noticed some strange behaviour, strange mails and error messages sent from mailtrain, which I hope are not linked to the recent security issues.. :(

**Comment by bures** [comment]
You cannot update the repo. Mailtrain v2 is a completely new product. There is almost no codebase that survived from v1. You have to clone it anew.

Here the steps:
Backup the DB. Clone the repository anew. Do the npm install where needed (there are a couple of places). Do npm run build in client. Create server/config/production.yaml and put your specific configuration there. Then you can run it.

Alternatively, you can use the installation scripts or the docker image. After you install it, just empty the DB and restore your backup there. Or just start with an empty DB, if you don't have campaigns you want to preserve.

**Comment by GadisDEV** [comment]
sorry I wasn't clear. I was using v2 of the previous ' v2 development' branch. which does not exist anymore.

**Comment by GadisDEV** [comment]
and, Tomas, I want to thank you so much for maintaining this project. ciao!

**Comment by joker-x** [comment]
I don't test it, but I think that could be work:

```
cd /opt/mailtrain
git checkout v2
git pull origin v2
source setup/functions
reinstallAllModules
```

**Comment by forgeOneHQ** [comment]
@GadisDEV if you facing any issues on v2 just reopen a new issue.

We also created a slack channel for this project.
https://mailtrainorg.slack.com
