### ISSUE TITLE
Support Mastodon

### ISSUE THREAD

**Issue by nickolgb** [Mailtrain-org/mailtrain#1050]
I want to know if it is possible in the "create templates" block to set up a social network block that leads to mastodon, as it is an open code social network I think it would be pertinent to put it together with instagram, facebook, and the others.
if a company has a social account in mastodon, users cannot access through the newsletter.

**Comment by bures** [comment]
Honestly, never heard about this. But you are of course welcome to add it and issue a PR. Thanks.

**Comment by forgeOneHQ** [comment]
You are welcome to participate on this :)

On v2 it shoul be easier to create something like this I think.
