### ISSUE TITLE
Duplicate translation keys

### ISSUE THREAD

**Issue by MarcelWaldvogel** [Mailtrain-org/mailtrain#1055]
The translation files contain the following duplicate keys:
*   "disableClickedTracking"
*   "disableOpenedTracking"
*   "save"
*   "saveAndLeave"
*   "saving"
*   "sendConfiguration"
*   "sendConfiguration_plural"

I can gladly create a pull request to remove those (presuming that the entries further down in the file are later additions). However, I fear that they might reappear later.

What is the mechanism that has created those duplicate entries and is this mechanism still active (i.e., they will reappear)?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
