### ISSUE TITLE
login and password default not working

### ISSUE THREAD

**Issue by Eliasssaber** [Mailtrain-org/mailtrain#1061]
You have just installed "mailtrain" in local ubuntu 18 04 LTS
but login and password default not working

**Comment by Eliasssaber** [comment]
@bures 🙏  can you help me please 🙏

**Comment by bures** [comment]
I'm afraid you don't provide any details. I can't imagine anyone could help you unless you provide detailed logs etc. to help analyze the issue.

**Comment by Eliasssaber** [comment]
Hi @bures 
Thank you for your reply.
I installed "vmware" after I installed "Ubuntu 18 04 05 LTS" on it. Then I installed "mailtrain" successfully. After completion, I went to the browser and tried to log in with the username "admin" and the password "test", but it didn't work.
What should I do, please. 🙏

**Comment by bures** [comment]
I'm afraid, still not enough detail.

**Comment by Eliasssaber** [comment]
What exactly are the details you want ??

**Comment by Eliasssaber** [comment]
@bures  What exactly are the details you want ??

**Comment by PhilippeAccorsi** [comment]
I think it is necessary to explain each command/config you done on your virtual server.

- Do you use docker ?
- by default configuration use localhost so if you ise mailtrain in vm bit try to connecte from another machine, this is not working.

**Comment by forgeOneHQ** [comment]
@Eliasssaber please try again.

I installed it without issues with the latest branch on Ubuntu 20.04.3 

If you still need help we can investigate together if you provide all infos.

Welcome to use on the slack channel: https://mailtrainorg.slack.com
