### ISSUE TITLE
Include unlayer/react-email editor as Template Generator 

### ISSUE THREAD

**Issue by l4b4r4b4b4** [Mailtrain-org/mailtrain#1066]
Hey,
As an enhancement suggestion, it just crossed my mind to include https://github.com/unlayer/react-email-editor as an email template editor based on react, which has excellent user experience.

Greets
Luke

**Comment by bures** [comment]
Looks nice, but it seems to be a paid plugin. Also, from my experience with setting up templates for users, this editor is way too complicated. I had the best experience with custom MJML-based Mosaico templates in Mailtrain. The user gets only a few blocks to choose from and these blocks already come with pre-set styling. So in the end, it's just a sort of very simple rich-text editor into which the user writes the message and drops in a picture. Nothing can be broken, nothing can be accidentally changed.

**Comment by l4b4r4b4b4** [comment]
I get your point, in keeping it simple for the end user, so nothing can be broken ;)

Didn't see it to be a paid component through. where did you see that?

**Comment by bures** [comment]
You are right. I was too quick to asses. It's MIT license. Well, I don't see much difference to GrapeJS. The good thing about Mosaico is that you can define a Mosaico template as a set of blocks that are available to the end-user to compose the content. Thanks to this, the end-user is not confronted with all the low level settings. Of course, if you want to integrate the Unlayer editor, I'll be happy to review the PR and accept it if it's done well. But I don't think I see a need on my side for yet another low-level editor.  WIth my end-users, I'm happy with Mosaico. Of course, if we had a newer alternative for Mosaico-like editor, where one could define the available blocks in a similar way like it is implemented in Mailtrain with Mosaico templates, it would be a different question.

**Comment by l4b4r4b4b4** [comment]
Well i really do enjoy the modern look and feel of the unlayer editor. Will see when I get the time to get my head around a template function in the context of mailtrain to have it implemented as a valid alternative to Mosaico.
