### ISSUE TITLE
PostfixBounce socket is not defined

### ISSUE THREAD

**Issue by ironhacker** [Mailtrain-org/mailtrain#1074]
Setup PostfixBounce on V2 new install with pipe method.  Was not working so I set logging to verbose and got this:

`(node:64819) UnhandledPromiseRejectionWarning: ReferenceError: socket is not defined
at Socket.readNextChunks (/opt/mailtrain/server/services/postfix-bounce-server.js:24:23)`

**Comment by ironhacker** [comment]
Not a Node developer, but these changes fixed it for me:

```
16c16
< async function readNextChunks() {
---
> async function readNextChunks(socket) {
94c94
<         socket.on('readable', readNextChunks);
---
>         socket.on('readable', () => readNextChunks(socket));
```

**Comment by forgeOneHQ** [comment]
@ironhacker please use the latest v2 version and open a new ticket if you still struggle. Best think is to use the included zone-mta :)
