### ISSUE TITLE
[Question] Default admin user with CAS and LDAP login

### ISSUE THREAD

**Issue by joker-x** [Mailtrain-org/mailtrain#1076]
Now, when login with CAS or LDAP the user is created with the role of newUserRole value in config file, usually nobody. The problem is nobody can change role or namespace from GUI. We can change it in database or set newUserRole to master for a while. For easier setup, I think to add two new keys in config file:

- defaultAdminUsers: An array of usernames of the users that will be global admins
- defaultAdminRole: String of default global admin role (usually master)

@bures what do you think about??

**Comment by bures** [comment]
Fine we me. 

Alternatively, we could also use some condition over LDAP attributes than equality of names to determine the admin role.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
