### ISSUE TITLE
Define Quota per namespace

### ISSUE THREAD

**Issue by MaraScott** [Mailtrain-org/mailtrain#1079]
Hi,

is there any plan to assign a monthly quota to namespace, I would like to assign 2 different websites to mailtrain but I would like to liit their capabilities to send more than X email per month.

If not could I talk with someone to plan it ?

**Comment by bures** [comment]
I'm afraid I have no plan implementing this. 

If you wanted to implement it yourself, this is how I believe it should be done:
- The accounting of sent emails should be associated with a send configuration. We could for instance have a daily counter, weekly counter and a monthly counter. 
- In addition to the counters, the send configuration could also have quotas.
- A namespace could have quotas too. The send emails counts in a namespace could be counted as a sum of sent emails of all send configurations that are transitively located in the namespace.

**Comment by forgeOneHQ** [comment]
@davask , you are welcome to help with the implementation on this since mailtrain is an open source project :)

I close this ticket for now since it is a feature request and not an issue.
