### ISSUE TITLE
Language configuration fails for generated forms, e.g. subscription web form, for locale de-DE

### ISSUE THREAD

**Issue by usrflo** [Mailtrain-org/mailtrain#1095]
A setting of the following values in server/config/production.yml is recognized in the admin ui processing at mailtrain.domain.tld:

```
enabledLanguages:
- en-US
- de-DE
```
That means the admin ui can be switched to de-DE correctly.

But these config settings do not apply to generated forms, e.g. a subscription form at https://lists.domain.tld/subscription/xyz?locale=de-DE; the generated labels are shown in the default locale en-US instead.

Looking at
https://github.com/Mailtrain-org/mailtrain/blob/5add1541d6b2c4c2e3422e85597330933e216374/server/lib/translate.js#L15
I see some hard coded language file inclusions. If I add `loadLanguage('de-DE');` the generated forms are translated to German correctly. Is a bugfix required or is there another config option for languages in generated forms?

**Comment by bures** [comment]
The `loadLanguage('de-DE');` should be present also in the in translate.js. All the supported languages have to be loaded there. The config file determines only which of those supported ones are enabled. Please submit a PR. Thanks a lot.

**Comment by usrflo** [comment]
Thank you.
