### ISSUE TITLE
Adding locale as hidden input field to form

### ISSUE THREAD

**Issue by usrflo** [Mailtrain-org/mailtrain#1099]
The subscription web form can be called with a locale parameter like https://lists.domain.tld/subscription/mxhRsZxVKw?locale=de-DE; but it does not POST the locale value to https://lists.domain.tld/subscription/mxhRsZxVKw/confirm-subscription-notice so the labels on the target page are not translated correctly.

So I tried to add `<input type="hidden" name="locale" value="{{locale}}">` at https://github.com/Mailtrain-org/mailtrain/blob/2e68b3b686c2bc4452bd3faf8e41192c64ae4565/server/views/subscription/partials/subscription-subscribe-form.hbs#L13 but the generated form does not reflect this change (the additional hidden input is not generated).

What needs to be done to update the template files? (some cache reset?)
Can `{{locale}}` be used to access the locale URL param inside the page?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
