### ISSUE TITLE
Plugin gjs-mjml not found

### ISSUE THREAD

**Issue by icetee** [Mailtrain-org/mailtrain#1100]
I create new template with GrapeJS editor (mjml), but no show import button, doesn't editable. I get error message in console `Plugin gjs-mjml not found`.

And I install Mailtrain with Docker (no develop edition).

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
