### ISSUE TITLE
Issue while creating list

### ISSUE THREAD

**Issue by pjoshi-fintechgblc** [Mailtrain-org/mailtrain#1110]
Hi While creating new lists I am getting the following error CHARSET=utf8mb4 COLLATE utf8mb4_general_ci; ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes with the table create syntax has anyone faced this issue? I don't see any reference to this on the documents

**Comment by joker-x** [comment]
It is a bug in Maria DB 10.1. You can upgrade database or apply this configuration to solve it:

/etc/mysql/mariadb.conf.d/60-fix-key-length.cnf
```
[mysqld]
innodb_file_format = Barracuda
innodb_file_per_table = on
innodb_default_row_format = dynamic
innodb_large_prefix = 1
innodb_file_format_max = Barracuda
```

**Comment by forgeOneHQ** [comment]
@joker-x thanks for the info. I am closing this issue.
