### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by cindyker** [Mailtrain-org/mailtrain#1112]
I installed MailTrain on to Ubuntu following the directions.

When I try to go to the sites, I am getting Too Many Redirects error.   
Any ideas what I need to look at to correct this problem?

Thank you!

**Comment by cindyker** [comment]
I'm still trying to figure out my problem.  In finding and reviewing logs, it looks like the Mailtrain server may be running out of memory while trying to start up.
I am installing this on a VM that I spun up for the purpose of this service.  I am going to update it to more memory to see it fixes this.

/var/log# less syslog

Jul  2 17:45:54 Newsletter kernel: [ 1279.830788] Out f memory: Killed process 3154 (mailtrain) total-vm:886276kB, anon-rss:84688kB, file-rss:1708kB, shmem-rss:0kB, UID:1000 pgtables:2880kB oom_score_adj:0
Jul  2 17:45:54 Newsletter kernel: [ 1279.838136] oom_reaper: reaped process 3154 (mailtrain), now anon-rss:0kB, file-rss:0kB, shmem-rss:0
Jul  2 17:45:54 Newsletter systemd[1]: mailtrain.service: Main process exited, code=killed, status=9/KILL
Jul  2 17:45:55 Newsletter systemd[1]: mailtrain.service: Failed with result 'signal'.
Jul  2 17:46:05 Newsletter systemd[1]: mailtrain.service: Scheduled restart job, restart counter is at 10.
Jul  2 17:46:05 Newsletter systemd[1]: Stopped Mailtrain server.
Jul  2 17:46:05 Newsletter systemd[1]: Started Mailtrain server.

**Comment by forgeOneHQ** [comment]
@cindyker can you give me your wenserver config? 

What is necessary is how you deployed mailtrain like docker or directly on the machine with the install scripts.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
