### ISSUE TITLE
Every time I restart the docker container, admin password is reset to default

### ISSUE THREAD

**Issue by jigawot** [Mailtrain-org/mailtrain#1115]
I followed all the direction and started up Mailtrain using docker-compose. When I first logged in with `admin:test`, I went and changed the admin password to something more secure. Logging out and back in works with the new password. So far, so good. If I then stop and restart the docker stack with `docker-compose restart`, wait for the application to be ready, and log in, my new password for `admin` doesn't work. The old `admin:test` credentials work. This seems to happen every time I start my docker container. If I create a new user, the password remains between restarts, but `admin` resets each time the container starts.

**Comment by timaivanov** [comment]
I have some problem

**Comment by PhilippeAccorsi** [comment]
If you create a new admin user, the password is saved correctly ? If yes, just add this new user and delete default admin ;)

**Comment by timaivanov** [comment]
> If you create a new admin user, the password is saved correctly ? If yes, just add this new user and delete default admin ;)

Thank you)

**Comment by jonathanmmm** [comment]
@PhilippeAccorsi Thanks for advice, I created a new user, but:
I can't delete the old admin. I could rename it and create a new user with the exact same username. But I can't delete the admin or withdraw his Role. If I do it just jumps back to Global Master.
(can't=it does not let me, I will see "Admin cannot be deleted"

**Comment by jonathanmmm** [comment]
@jigawot @PhilippeAccorsi Security Risk, please Read:

This pull request updates the README.md
https://github.com/Mailtrain-org/mailtrain/pull/1176

If you don't set ADMIN_PASSWORD as ENV in docker, after every restart your admin password is reset to `test`, making your hole instance vurnerable.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
