### ISSUE TITLE
Add reverse proxy that makes these endpoints publicly available over HTTPS (Nginx)

### ISSUE THREAD

**Issue by Rustiks** [Mailtrain-org/mailtrain#1116]
I want to use Nginx as a Docker container and also use SSL (for https). I found a suitable instruction on the web on how to deploy a reverse proxy from the container and get a certificate.  https://andreyex.ru/linux/ispolzovanie-docker-dlya-nastrojki-obratnogo-proksi-nginx-s-avtomaticheskoj-generatsiej-ssl/ 
Stuck at step 4, how to run docker-compose up -d using Mailtrain. I use the parameters in the docker-compose.yml file:
networks:
 default:
  external:
   name: net
Running docker-compose up -d unfortunately does not work.
Help to find a working solution.

**Comment by programster** [comment]
There are many tutorials on the internet explaining how to use [jwilder nginx reverse proxy](https://hub.docker.com/r/jwilder/nginx-proxy). E.g. I have my own at: https://blog.programster.org/jwilder-reverse-proxy-with-wildcard-ssl
Have you tried using it?

You shouldn't need to specify networking in the docker-compose as the default is to create a single network that all the services are connected to, which should be fine I believe.

**Comment by forgeOneHQ** [comment]
@Rustiks since @programster sent an howto, if you need further help just open another issue.
