### ISSUE TITLE
Widget not working, can't figure out what's wrong

### ISSUE THREAD

**Issue by Playerdue** [Mailtrain-org/mailtrain#1117]
Hi everyone,
This week I started configuring Mailtrain on my server, I'm liking it a lot and I can't wait to start using it! I'm not very expert, so my question may be dumb, sorry for that. :P 

I'm trying to set the CORS to use the widget on wordpress, but it's not working and I don't know what I am doing wrong.

I installed Mailtrain with docker on my ubuntu server. I added these lines of code in production.yaml inside app/server/config

![cors_production](https://user-images.githubusercontent.com/87466173/125744287-2fab5d45-2f61-49d5-8aa9-c83c1bd9a976.png)

But the widget doesn't work, you can see it on the right side of the page https://www.playerdue.com/  under the "Newsletter" section.

This is the setup of the widget on wordpress:

![Widget](https://user-images.githubusercontent.com/87466173/125744861-1a2cdd39-728d-44f2-a969-03b6ad90818f.png)

And this is the address of the Mailtrain subscription form: http://playerdue.com:3004/subscription/eToFiUNipD/

Where did I mess up?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
