### ISSUE TITLE
Clone template results in - EACCES: permission denied, mkdir '/opt/mailtrain/server/files/template/file/10'

### ISSUE THREAD

**Issue by MickyBizzle** [Mailtrain-org/mailtrain#1122]
When trying to clone a GrapeJS template I get a EACCES: permission denied, mkdir '/opt/mailtrain/server/files/template/file/10' error. I'm guessing it's a permission issue on the server (I'm running Ubuntu with no docker) If anyone can help that would be very much appreciated!

**Comment by bures** [comment]
Make sure that the directories are owned by mailtrain.mailtrain

**Comment by MickyBizzle** [comment]
That did it, thanks
