### ISSUE TITLE
v2 fresh installation via Docker not run websites 

### ISSUE THREAD

**Issue by clamattu** [Mailtrain-org/mailtrain#1123]
Build 2021-05-25-0915

It happens on MacOs 11.5.1 and CentOs8.
Apparently http://localhost:3000 - trusted endpoint works but

- http://localhost:3003 - sandbox endpoint

- http://localhost:3004 - public endpoint

This is the log of Docker-compose up and 3 http connection to my local MacOs. On Centos8 i have tried throught an SSH tunnel and the answer is the same...

I don't know if there is some other log to check

Attaching to mailtrain_1, mongo_1, mysql_1, redis_1
mysql_1      | 2021-07-30 15:44:39+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1      | 2021-07-30 15:44:39+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.4.20+maria~focal started.
mongo_1      | 2021-07-30T15:44:39.098+0000 I STORAGE  [main] Max cache overflow file size custom option: 0
mongo_1      | 2021-07-30T15:44:39.106+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=ae22bef21c48
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] db version v4.0.12
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] git version: 5776e3cbf9e7afe86e6b29e22520ffb6766e95d4
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] modules: none
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] build environment:
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1      | 2021-07-30T15:44:39.114+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongo_1      | 2021-07-30T15:44:39.116+0000 I STORAGE  [initandlisten] 
mongo_1      | 2021-07-30T15:44:39.116+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1      | 2021-07-30T15:44:39.116+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1      | 2021-07-30T15:44:39.117+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=482M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mysql_1      | 2021-07-30 15:44:39+00:00 [Note] [Entrypoint]: Initializing database files
mongo_1      | 2021-07-30T15:44:39.600+0000 I STORAGE  [initandlisten] WiredTiger message [1627659879:600825][1:0x7f7f15376a80], txn-recover: Set global recovery timestamp: 0
mongo_1      | 2021-07-30T15:44:39.605+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo_1      | 2021-07-30T15:44:39.615+0000 I CONTROL  [initandlisten] 
mongo_1      | 2021-07-30T15:44:39.615+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1      | 2021-07-30T15:44:39.615+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1      | 2021-07-30T15:44:39.615+0000 I CONTROL  [initandlisten] 
mongo_1      | 2021-07-30T15:44:39.620+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 003c5e15-4565-4f98-9033-d84e33144349
mongo_1      | 2021-07-30T15:44:39.627+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
mongo_1      | 2021-07-30T15:44:39.630+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 8fdd9b54-d8ec-43f7-a2d3-efa83171b5c0
mongo_1      | 2021-07-30T15:44:39.637+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1      | 2021-07-30T15:44:39.638+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongo_1      | 2021-07-30T15:44:39.645+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: 7a070a2d-71fa-4de1-9084-ede90affd17a
mongo_1      | 2021-07-30T15:44:39.654+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
mongo_1      | 2021-07-30T15:44:39.654+0000 I INDEX    [LogicalSessionCacheRefresh] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:39.655+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
mysql_1      | 
mysql_1      | 
mysql_1      | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
mysql_1      | To do so, start the server, then issue the following commands:
mysql_1      | 
mysql_1      | '/usr/bin/mysqladmin' -u root password 'new-password'
mysql_1      | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
mysql_1      | 
mysql_1      | Alternatively you can run:
mysql_1      | '/usr/bin/mysql_secure_installation'
mysql_1      | 
mysql_1      | which will also give you the option of removing the test
mysql_1      | databases and anonymous user created by default.  This is
mysql_1      | strongly recommended for production servers.
mysql_1      | 
mysql_1      | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
mysql_1      | MySQL manual for more instructions.
mysql_1      | 
mysql_1      | Please report any problems at http://mariadb.org/jira
mysql_1      | 
mysql_1      | The latest information about MariaDB is available at http://mariadb.org/.
mysql_1      | You can find additional information about the MySQL part at:
mysql_1      | http://dev.mysql.com
mysql_1      | Consider joining MariaDB's strong and vibrant community:
mysql_1      | https://mariadb.org/get-involved/
mysql_1      | 
mysql_1      | 2021-07-30 15:44:41+00:00 [Note] [Entrypoint]: Database files initialized
mysql_1      | 2021-07-30 15:44:41+00:00 [Note] [Entrypoint]: Starting temporary server
mysql_1      | 2021-07-30 15:44:41+00:00 [Note] [Entrypoint]: Waiting for server startup
mysql_1      | 2021-07-30 15:44:41 0 [Note] mysqld (mysqld 10.4.20-MariaDB-1:10.4.20+maria~focal) starting as process 116 ...
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Using Linux native AIO
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Uses event mutexes
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Number of pools: 1
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Using SSE2 crc32 instructions
mysql_1      | 2021-07-30 15:44:41 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Waiting for purge to start
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: 10.4.20 started; log sequence number 60967; transaction id 20
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1      | 2021-07-30 15:44:41 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql_1      | 2021-07-30 15:44:41 0 [Warning] 'user' entry 'root@4f1ca4af40dc' ignored in --skip-name-resolve mode.
mysql_1      | 2021-07-30 15:44:41 0 [Warning] 'proxies_priv' entry '@% root@4f1ca4af40dc' ignored in --skip-name-resolve mode.
mysql_1      | 2021-07-30 15:44:41 0 [Note] InnoDB: Buffer pool(s) load completed at 210730 15:44:41
mysql_1      | 2021-07-30 15:44:41 0 [Note] Reading of all Master_info entries succeeded
mysql_1      | 2021-07-30 15:44:41 0 [Note] Added new Master_info '' to hash table
mysql_1      | 2021-07-30 15:44:41 0 [Note] mysqld: ready for connections.
mysql_1      | Version: '10.4.20-MariaDB-1:10.4.20+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
mysql_1      | 2021-07-30 15:44:42+00:00 [Note] [Entrypoint]: Temporary server started.
mysql_1      | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1      | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
mysql_1      | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mysql_1      | 2021-07-30 15:44:43 10 [Warning] 'proxies_priv' entry '@% root@4f1ca4af40dc' ignored in --skip-name-resolve mode.
mysql_1      | 2021-07-30 15:44:43+00:00 [Note] [Entrypoint]: Creating database mailtrain
mysql_1      | 2021-07-30 15:44:43+00:00 [Note] [Entrypoint]: Creating user mailtrain
mysql_1      | 2021-07-30 15:44:43+00:00 [Note] [Entrypoint]: Giving user mailtrain access to schema mailtrain
mysql_1      | 
mysql_1      | 2021-07-30 15:44:43+00:00 [Note] [Entrypoint]: Stopping temporary server
mysql_1      | 2021-07-30 15:44:43 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
mysql_1      | 2021-07-30 15:44:43 0 [Note] Event Scheduler: Purging the queue. 0 events
mysql_1      | 2021-07-30 15:44:43 0 [Note] InnoDB: FTS optimize thread exiting.
mysql_1      | 2021-07-30 15:44:43 0 [Note] InnoDB: Starting shutdown...
mysql_1      | 2021-07-30 15:44:43 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
mysql_1      | 2021-07-30 15:44:43 0 [Note] InnoDB: Buffer pool(s) dump completed at 210730 15:44:43
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Shutdown completed; log sequence number 60976; transaction id 21
mysql_1      | 2021-07-30 15:44:45 0 [Note] mysqld: Shutdown complete
mysql_1      | 
mysql_1      | 2021-07-30 15:44:45+00:00 [Note] [Entrypoint]: Temporary server stopped
mysql_1      | 
mysql_1      | 2021-07-30 15:44:45+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.
mysql_1      | 
mysql_1      | 2021-07-30 15:44:45 0 [Note] mysqld (mysqld 10.4.20-MariaDB-1:10.4.20+maria~focal) starting as process 1 ...
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Using Linux native AIO
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Uses event mutexes
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Number of pools: 1
mysql_1      | 2021-07-30 15:44:45 0 [Note] InnoDB: Using SSE2 crc32 instructions
mysql_1      | 2021-07-30 15:44:45 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: Waiting for purge to start
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: 10.4.20 started; log sequence number 60976; transaction id 20
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1      | 2021-07-30 15:44:46 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql_1      | 2021-07-30 15:44:46 0 [Note] Server socket created on IP: '::'.
mysql_1      | 2021-07-30 15:44:46 0 [Note] InnoDB: Buffer pool(s) load completed at 210730 15:44:46
mysql_1      | 2021-07-30 15:44:46 0 [Warning] 'proxies_priv' entry '@% root@4f1ca4af40dc' ignored in --skip-name-resolve mode.
mysql_1      | 2021-07-30 15:44:46 0 [Note] Reading of all Master_info entries succeeded
mysql_1      | 2021-07-30 15:44:46 0 [Note] Added new Master_info '' to hash table
mysql_1      | 2021-07-30 15:44:46 0 [Note] mysqld: ready for connections.
mysql_1      | Version: '10.4.20-MariaDB-1:10.4.20+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mailtrain_1  | Info: Waiting for Redis Server
mysql_1      | 2021-07-30 15:44:46 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.18.0.2' (This connection closed normally without authentication)
mailtrain_1  | Info: Waiting for MongoDB Server
mongo_1      | 2021-07-30T15:44:46.937+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59624 #1 (1 connection now open)
mongo_1      | 2021-07-30T15:44:46.938+0000 I NETWORK  [conn1] end connection 172.18.0.2:59624 (0 connections now open)
mailtrain_1  | info sql SQL not set up, initializing
mailtrain_1  | info sql Loading tables from mailtrain.sql
mailtrain_1  | info sql Database check completed
mysql_1      | 2021-07-30 15:44:49 10 [Warning] Aborted connection 10 to db: 'mailtrain' user: 'mailtrain' host: '172.18.0.2' (Got an error reading communication packets)
mailtrain_1  | info Using local auth 
mailtrain_1  | info sql Database check completed
mailtrain_1  | info Executor Executor process started.
mailtrain_1  | info ZoneMTA Starting built-in Zone MTA process
mongo_1      | 2021-07-30T15:44:52.978+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59636 #2 (1 connection now open)
mongo_1      | 2021-07-30T15:44:52.984+0000 I NETWORK  [conn2] received client metadata from 172.18.0.2:59636 conn2: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }
mongo_1      | 2021-07-30T15:44:52.992+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59638 #3 (2 connections now open)
mongo_1      | 2021-07-30T15:44:52.993+0000 I NETWORK  [conn3] received client metadata from 172.18.0.2:59638 conn3: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }
mongo_1      | 2021-07-30T15:44:52.996+0000 I STORAGE  [conn3] createCollection: zone-mta.mail.files with generated UUID: fabf76fc-8e43-427a-917f-06ddbf74e8b0
mongo_1      | 2021-07-30T15:44:53.006+0000 I INDEX    [conn3] build index on: zone-mta.mail.files properties: { v: 2, key: { uploadDate: 1 }, name: "mailupload", ns: "zone-mta.mail.files" }
mongo_1      | 2021-07-30T15:44:53.007+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.007+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.010+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59640 #4 (3 connections now open)
mongo_1      | 2021-07-30T15:44:53.011+0000 I NETWORK  [conn4] received client metadata from 172.18.0.2:59640 conn4: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }
mongo_1      | 2021-07-30T15:44:53.014+0000 I INDEX    [conn3] build index on: zone-mta.mail.files properties: { v: 2, key: { filename: 1 }, name: "mailfile", ns: "zone-mta.mail.files" }
mongo_1      | 2021-07-30T15:44:53.015+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.015+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.017+0000 I STORAGE  [conn4] createCollection: zone-mta.suppressionlist with generated UUID: 80d1b89b-6c40-48f1-b3b5-ad69dfedfd85
mongo_1      | 2021-07-30T15:44:53.028+0000 I INDEX    [conn4] build index on: zone-mta.suppressionlist properties: { v: 2, key: { address: 1 }, name: "suppressed_address", ns: "zone-mta.suppressionlist" }
mongo_1      | 2021-07-30T15:44:53.028+0000 I INDEX    [conn4] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.028+0000 I INDEX    [conn4] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.033+0000 I INDEX    [conn3] build index on: zone-mta.suppressionlist properties: { v: 2, key: { domain: 1 }, name: "suppressed_domain", ns: "zone-mta.suppressionlist" }
mongo_1      | 2021-07-30T15:44:53.033+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.035+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.039+0000 I INDEX    [conn4] build index on: zone-mta.suppressionlist properties: { v: 2, key: { created: -1 }, name: "list_by_newer", ns: "zone-mta.suppressionlist" }
mongo_1      | 2021-07-30T15:44:53.040+0000 I INDEX    [conn4] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.040+0000 I INDEX    [conn4] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.041+0000 I STORAGE  [conn3] createCollection: zone-mta.zone-queue with generated UUID: 34cbed4f-d6ec-4f82-8403-9e7b5c5f6e6b
mongo_1      | 2021-07-30T15:44:53.050+0000 I INDEX    [conn3] build index on: zone-mta.zone-queue properties: { v: 2, key: { created: 1 }, name: "findall", ns: "zone-mta.zone-queue" }
mongo_1      | 2021-07-30T15:44:53.050+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.051+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.056+0000 I INDEX    [conn4] build index on: zone-mta.zone-queue properties: { v: 2, key: { sendingZone: 1, queued: 1, locked: 1, assigned: 1, domain: 1 }, name: "search_next", ns: "zone-mta.zone-queue" }
mongo_1      | 2021-07-30T15:44:53.056+0000 I INDEX    [conn4] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.057+0000 I INDEX    [conn4] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.062+0000 I INDEX    [conn3] build index on: zone-mta.zone-queue properties: { v: 2, key: { queued: 1 }, name: "find_all_queued", ns: "zone-mta.zone-queue" }
mongo_1      | 2021-07-30T15:44:53.062+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.063+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.070+0000 I INDEX    [conn4] build index on: zone-mta.zone-queue properties: { v: 2, key: { id: 1, seq: 1 }, name: "delivery", ns: "zone-mta.zone-queue" }
mongo_1      | 2021-07-30T15:44:53.070+0000 I INDEX    [conn4] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.071+0000 I INDEX    [conn4] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.075+0000 I INDEX    [conn3] build index on: zone-mta.zone-queue properties: { v: 2, key: { locked: 1, assigned: 1, lockTime: 1 }, name: "message_locking", ns: "zone-mta.zone-queue" }
mongo_1      | 2021-07-30T15:44:53.075+0000 I INDEX    [conn3] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1      | 2021-07-30T15:44:53.076+0000 I INDEX    [conn3] build index done.  scanned 0 total records. 0 secs
mongo_1      | 2021-07-30T15:44:53.507+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59646 #5 (4 connections now open)
mongo_1      | 2021-07-30T15:44:53.513+0000 I NETWORK  [conn5] received client metadata from 172.18.0.2:59646 conn5: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }
mongo_1      | 2021-07-30T15:44:53.591+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59654 #6 (5 connections now open)
mongo_1      | 2021-07-30T15:44:53.596+0000 I NETWORK  [conn6] received client metadata from 172.18.0.2:59654 conn6: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }
mongo_1      | 2021-07-30T15:44:54.064+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59660 #7 (6 connections now open)
mongo_1      | 2021-07-30T15:44:54.068+0000 I NETWORK  [conn7] received client metadata from 172.18.0.2:59660 conn7: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }
mongo_1      | 2021-07-30T15:44:54.541+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59666 #8 (7 connections now open)
mongo_1      | 2021-07-30T15:44:54.546+0000 I NETWORK  [conn8] received client metadata from 172.18.0.2:59666 conn8: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }
mailtrain_1  | info ZoneMTA ZoneMTA process started
mailtrain_1  | info Express WWW server [trusted] listening on port 3000
mailtrain_1  | info Express WWW server [sandbox] listening on port 3003
mailtrain_1  | info Express WWW server [public] listening on port 3004
mailtrain_1  | info Importer Importer process started
mailtrain_1  | info Feed Feedcheck process started
mailtrain_1  | info Senders Worker process 0 started
mailtrain_1  | info Senders Worker process 2 started
mailtrain_1  | info Senders Worker process 1 started
mailtrain_1  | info Senders Worker process 3 started
mailtrain_1  | info Senders Worker process 4 started
mailtrain_1  | info Senders Master sender process started
mailtrain_1  | info Triggers Starting trigger check service
mailtrain_1  | info GDPR Starting GDPR cleanup service
mailtrain_1  | info ReportProcessor Trying to start worker because runningWorkersCount=0 maxWorkersCount=1
mailtrain_1  | info ReportProcessor No more reports to start a worker for
mailtrain_1  | info Service All services started
mailtrain_1  | info HTTP GET / 200 138.895 ms - -
mailtrain_1  | info HTTP GET /static-npm/popper.min.js 200 11.010 ms - -
mailtrain_1  | info HTTP GET /static-npm/jquery.min.js 200 10.739 ms - -
mailtrain_1  | info HTTP GET /client/mailtrain.css 200 17.369 ms - -
mailtrain_1  | info HTTP GET /static-npm/bootstrap.min.js 200 13.533 ms - -
mailtrain_1  | info HTTP GET /static-npm/coreui.min.js 200 16.650 ms - -
mailtrain_1  | info HTTP GET /client/root.js 200 18.188 ms - -
**mailtrain_1  | info HTTP GET / 404 26.499 ms - 139**
mailtrain_1  | info HTTP GET /static-npm/fontawesome/fa-solid-900.woff2 200 3.836 ms - 78196
mailtrain_1  | info HTTP GET /static/favicon.ico 200 4.444 ms - -
mailtrain_1  | info HTTP GET /static/favicon.ico 304 3.086 ms - -
**mailtrain_1  | info HTTP GET / 404 2.570 ms - 139**
mailtrain_1  | info HTTP POST /rest/login 200 286.347 ms - -
mailtrain_1  | info HTTP GET / 200 35.057 ms - -
mailtrain_1  | info HTTP GET /client/mailtrain.css 304 36.303 ms - -
mailtrain_1  | info HTTP GET /static-npm/popper.min.js 304 24.597 ms - -
mailtrain_1  | info HTTP GET /static-npm/jquery.min.js 304 31.599 ms - -
mailtrain_1  | info HTTP GET /static-npm/coreui.min.js 304 34.507 ms - -
mailtrain_1  | info HTTP GET /static-npm/bootstrap.min.js 304 34.346 ms - -
mailtrain_1  | info HTTP GET /client/root.js 304 36.588 ms - -
mailtrain_1  | info HTTP GET /static-npm/fontawesome/fa-solid-900.woff2 304 5.219 ms - -
mailtrain_1  | info HTTP GET /rest/settings 200 15.684 ms - 215
mongo_1      | 2021-07-30T15:45:53.069+0000 I NETWORK  [listener] connection accepted from 172.18.0.2:59748 #9 (8 connections now open)
mongo_1      | 2021-07-30T15:45:53.076+0000 I NETWORK  [conn9] received client metadata from 172.18.0.2:59748 conn9: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.10.25-linuxkit" }, platform: "'Node.js v10.24.1, LE (unified)" }

**Comment by catbadger** [comment]
seeing the same..
mailtrain_app | info HTTP GET / 404 17.368 ms - 139

**Comment by bures** [comment]
Check the developer's console in the web-browser. My 2c is that your url bases are wrong. I think "localhost" is almost never the right settings when using docker. The url base should be the same as the url that you type in your browser to connect to mailtrain.

**Comment by catbadger** [comment]
I don't have localhost set. i am using the container name which is also the container hostname in my nginx proxy config, and getting nothing.

**Comment by bures** [comment]
And what does the developers console in the webbrowser say?

**Comment by catbadger** [comment]
it's a 404.

**Comment by phtmgt** [comment]
Same issue here, and I suspect it's got to do with either the --withProxy setting or the domain settings. It is not clear in the docs how to set this up properly. It is mentioned it's got to be done via MAILTRAIN_SETTINGS, but the only remotely similar option there is WWW_PROXY (and it makes no difference setting it to true, 1 or omitting it).

Here's the log:

```
mailtrain_1  | info HTTP GET /links/fnPIhOGUbn/AwSMhOmVff/avMUPbRrHn/PslmVMhZry 302 34.856 ms - 100
mailtrain_1  | info HTTP GET /links/fnPIhOGUbn/AwSMhOmVff/avMUPbRrHn/PslmVMhZry 404 5.042 ms - 188
```

The first request is done with lynx from cli on the machine running docker. The second (404) is via the nginx proxy.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
