### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by stacymarshall2286** [Mailtrain-org/mailtrain#1125]
I get this error when importing the initial SQL data to the mailtrain database by using the following command::

mariadb -u mtuser -p mailtrain < /var/www/mailtrain/setup/sql/mailtrain.sql

I am on Ubuntu 20.04 and following this guide:
https://www.linuxbabe.com/ubuntu/install-mailtrain-v1-24-ubuntu-20-04-without-docker
Any idea how to solve it? 
Thanks in advance.

**Comment by tripleee** [comment]
See also https://stackoverflow.com/questions/68644816/mailtrain-installation-giving-errors but probably try to find an instruction which isn't badly out of date instead.

**Comment by stacymarshall2286** [comment]
> See also https://stackoverflow.com/questions/68644816/mailtrain-installation-giving-errors but probably try to find an instruction which isn't badly out of date instead.

Thank you very much for your help.
