### ISSUE TITLE
Test/Check SMTP configuration

### ISSUE THREAD

**Issue by programster** [Mailtrain-org/mailtrain#1127]
I'm filling out the "Edit Send Configuration" form in the latest Mailtrain (2). In the original one, thre was a handy button in the bottom-right where you fill in the settings to check they are correct, as shown below:

![Selection_135](https://user-images.githubusercontent.com/5709838/128158882-3db9f75d-c331-4140-a514-b1918c708b6c.png)

However, I can't see that on the new form. Do I need to go somewhere else to test the configuration? I'd rather check it here where I set the username/password rather than having to go to the templates and actually try to send a test email campaign if possible.

![Selection_136](https://user-images.githubusercontent.com/5709838/128159292-f9fe5e01-73aa-4640-8289-8a070b24d9f9.png)

Side Comment: Congratulations on getting Mailtrain 2.0 out. It's great that this tool is getting updated/maintained.

**Comment by bures** [comment]
I'm afraid I dropped this functionality when developing v2. It was a bit too difficult to support it for the varioius mail providers and email settings. In the end, the only way to know you configured everything correctly is to send the email to some service like mail-tester.com. Not only will you know that your connection to MTA work, it will also tell you whether your SPF, DKIM and DMAR records are configured correctly.
Thanks, happy that you like it.

**Comment by programster** [comment]
Okay, no worries. Thanks for letting me know.
