### ISSUE TITLE
[Question] Emails sending speed

### ISSUE THREAD

**Issue by chemexus** [Mailtrain-org/mailtrain#1129]
Hi @bures,

We are trying to increase email sending speed because it doesn't work fast enough. It's the same problem as already mentioned [here](https://github.com/Mailtrain-org/mailtrain/issues/1106).
I wonder if Redis affect emails sending speed? I really appreciate any help you can provide.

**Comment by bures** [comment]
I doubt Redis would be an issue, but you can investigate it. I can try to help you, but it's hard to do it without details of your setup. Also, you would have to be able to do various experiments yourself. Be ready that tuning performance problems is hard and time-consuming.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
