### ISSUE TITLE
Difference between total subscribers on list and total subscribers on a campaign

### ISSUE THREAD

**Issue by Playerdue** [Mailtrain-org/mailtrain#1130]
Hi, I tried sending a campaign with a small list, but as you can see in the picture there is a difference between the total on the list and the actual users that received the campaign.

What could be the problem? The SMTP I'm using doesn't seem to have any issue.
 
![Mailtrain_difference](https://user-images.githubusercontent.com/87466173/128876611-12d0863a-95c0-4890-9a93-4edbfe442cf7.jpg)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
