### ISSUE TITLE
CERTIFICATE INVALID ON MAILTRAIN.ORG

### ISSUE THREAD

**Issue by BloodyIron** [Mailtrain-org/mailtrain#1134]
https://mailtrain.org

Hey guys, the Let's Encrypt cert expired:

Issued On	Friday, 30 April 2021 at 06:04:18
Expires On	Thursday, 29 July 2021 at 06:04:18

YOU NEED TO FIX THIS. This is really a lot of egg on the face.

**Comment by jonathanmmm** [comment]
Found it as well, 17 days or so expired, if you go to the website you could think mailtrain was hacked or so (if you don't look at the reason why the browser warns you).

**Comment by bures** [comment]
Good point. I think we will drop the website and let the URL point to the GitHub landing page directly. No one's maintaining the website anyway.

**Comment by bures** [comment]
As a quick solution I set up a permanent redirect. THanks for reporting it.

**Comment by mailanetworks** [comment]
Sorry guys, an update on the certbot application was required to continue working automatic.
Now with redirect it's not working.
To apply the renew I need to have the domain pointing back to the old IP.

Thanks.

**Comment by bures** [comment]
Thanks. But I believe we need a new website anyway. The old one was showcasing Mailtrain v1, which is obsolete. We already release v2. I believe it is connected to #999. 

@talheim-it - please were you able to setup the new website related to v2?

Thanks to all of you.

**Comment by BloodyIron** [comment]
I actually rather liked the website. I think it would be a good idea to keep using the website (with the solved cert problem), as it visually makes the tool look "more desirable" for those making decisions on tool selection, so to say.

But since you are interested in a new site, perhaps build it with Concrete CMS? It's open source and really awesome to work with!

Either way, I'm glad this is being responded to so positively! And I look forward to the new website :D

**Comment by jonathanmmm** [comment]
Same, choosing a tool and seeing just github makes it seem more complicated and let someone go more likely to another tool. Maybe the website could be pulled from a directory in github but still be hosted normally.

**Comment by bures** [comment]
I agree. If anyone wants to create the content and grab screenshots from V2, I would certainly appreciate it.

**Comment by jonathanmmm** [comment]
Also like an explanation what a List, a Channel is and so on, somewhere would be great. I found out Channels are like Template Campaigns (if I am not mistaken), but only trying around.

**Comment by bures** [comment]
Yes. A Channel is a collection of default settings for a campaign. The idea is that if you are sending for instance a quote of a day, then Channel can be used to group them and speed up creation of a new campaign with the same settings.

**Comment by forgeOneHQ** [comment]
I am going to prepare something in the near future. I also had a customer asking what is this and that, and I wrote it down.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
