### ISSUE TITLE
Mailtrain-user discussion list

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#1137]
Would the Mailtrain maintainers be interested in creating and advertising a [discussion list](https://en.wikipedia.org/wiki/Electronic_mailing_list#Discussion_list)?

Running a Mailtrain instance, I often have questions that seem too small or inappropriate for an issue tracker. I don't want to add noise here with questions that can most likely be answered quickly by others Mailtrain users. A simple email list could provide an avenue for these sorts of things - with the bonus that non-GitHub users would be able to participate too. The list's archive might also prove to be a useful source of ad-hoc documentation and answered questions.

[Sourcehut](https://sourcehut.org/) offer free mailing lists designed for use by software projects; so running this list wouldn't have to mean a new maintanance burden.

**Comment by forgeOneHQ** [comment]
@coragcybb I am not sure what a mailing list makes sense? For quick stuff we could also make a slack channel or anything like that. More mails in the inbox makes from my side not much sense. 

But more activity is also very welcome from my side.

**Comment by forgeOneHQ** [comment]
@coragcybb , I talked to @bures to open a slack channel. That is the best way to go since a lot open source projects using it.

I am managing it for the community and answer questions and filter it a bit since the others have not much time at the moment.
Slack: https://mailtrainorg.slack.com/

**Comment by ghost** [comment]
Thanks @talheim-it  :)

I suggested a mailing list instead of something like Slack because it wouldn't require anyone to sign up to a new service or install a new app for something that they'd probably use very infrequently, but I appreciate this as well.

**Comment by ghost** [comment]
How does someone sign-up for this Slack workspace?
