### ISSUE TITLE
Feature request: Only send emails during business hours

### ISSUE THREAD

**Issue by ganeshkrishnan1** [Mailtrain-org/mailtrain#1138]
Hubspot has this feature to allow send emails during business hours and business days. its not any more refined that that. 

The emails will only go out Monday to Fri 9 am to 5pm system time.
Is it possible to add that feature to mailtrain as well?

**Comment by bures** [comment]
You can schedule a campaign to go out at a particular time/date.

**Comment by bures** [comment]
If this is not what you had in mind, please feel free to reopen this issue.
