### ISSUE TITLE
Unsubscribe forms don't work

### ISSUE THREAD

**Issue by davidwindell** [Mailtrain-org/mailtrain#1139]
On the latest Mailtrain (v2 2021-06-09), despite having the below config:

![screenshot-2021 08 20-17_47_21](https://user-images.githubusercontent.com/1720090/130268682-9db91f78-a7f6-444d-8274-49d0528ba287.png)

No users can unsubscribe themselves without emailing:

![screenshot-email edge-servers com-2021 08 20-18_04_28](https://user-images.githubusercontent.com/1720090/130268929-70eeac01-82fc-4544-878f-9efd86f8455b.png)

**Comment by forgeOneHQ** [comment]
@davidfurlong how did you install it?

Docker or directly on an Ubuntu or CentOS server?

**Comment by forgeOneHQ** [comment]
@davidfurlong I cannot reproduce it in the latest setup I run. The only issue came up because of a memory issue which ran into an 504 error.

I try to fixed it with increasing the memory of for node. 
https://www.codegrepper.com/code-examples/javascript/increase+nodejs+heap+memory+ubuntu

**Comment by davidwindell** [comment]
@talheim-it Looks like you are pinging the wrong person so I missed these messages.

We've installed it on Docker with a pretty vanilla install of v2 2021-06-09.

Any idea how we can resolve this?
