### ISSUE TITLE
Info - Cleaning up issue list and Update

### ISSUE THREAD

**Issue by forgeOneHQ** [Mailtrain-org/mailtrain#1143]
Hello Mailtrain community!

I am working at the moment on cleaning up the issue list to get an overview of the latest valid issues and start to create a pull request to update all packages to the latest version.

I also plan to create an ansible-playbook for mailtrain deployment in the upcoming months. 

After I talked to @bures  I also created a slack channel https://mailtrainorg.slack.com for having a better communication flow and get more activity into the project.

I also plan to create a template for opening an issues since a lot information are missing which help us to understand the issues you are struggling with.

Yours faithfully,
Mathias

**Comment by forgeOneHQ** [comment]
Pending tasks (need update):
Documentation: #301 
feature request: #793 
Hosting Mailtrain.org: #375 
Future of Mailtrain: #373 
Issue: #598
Issue: #1075

**Comment by ghost** [comment]
🥳 How does one actually join the Slack workspace?

**Comment by forgeOneHQ** [comment]
>  How does one actually join the Slack workspace?

As to any other slack channel, by signing in:
https://mailtrainorg.slack.com/

If you have issues let me know! :)

**Comment by ghost** [comment]
Surely I need to create an account first! Slack workspaces are generaly invite only.

**Comment by ghost** [comment]
Bump. :3

**Comment by ghost** [comment]
@talheim-it Can you share an invite link to the Slack? As it is there is no way for someone to join.

**Comment by saschafoerster** [comment]
@talheim-it I also would be happy to be invited. I tried to register but without invitation via Mail or link I can’t join.

**Comment by forgeOneHQ** [comment]
@LiamMcM @saschafoerster I check it why it is not possible and come back asap, latestly tomorrow!

**Comment by saschafoerster** [comment]
@talheim-it https://slack.com/intl/de-de/help/articles/115004856503-Verwalten-wie-Leute-deinem-Workspace-beitreten Maybe this helps.

**Comment by forgeOneHQ** [comment]
https://join.slack.com/t/mailtrainorg/shared_invite/zt-17tpvix6s-De3hnOYxk4UJPB6xC5~5JQ

I generated a new one. The situation is I thought there is a way to let everyone join but that link expires after a time.
https://join.slack.com/t/mailtrainorg/shared_invite/zt-17tpvix6s-De3hnOYxk4UJPB6xC5~5JQ

Can you try this one out?

**Comment by saschafoerster** [comment]
@talheim-it This one worked out.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
