### ISSUE TITLE
Migrating from v1 to v2 errors

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#1144]
Hello, I am trying to migrate v1 mailtrain to v2 version. After the installation I stop the mailtrain service and set the old database in place and restarted, but after a while, I get these errors in an infinite loop:

```
Aug 30 17:54:40 mailtrain node[2166]: migration file "20170506102634_v1_to_v2.js" failed
Aug 30 17:54:40 mailtrain node[2166]: migration failed with error: Cannot read property 'value' of undefined
Aug 30 17:54:40 mailtrain node[2166]: ERR! TypeError: Cannot read property 'value' of undefined
```

Any  help?
thanks

**Comment by forgeOneHQ** [comment]
@afanjul you need to migrate the data to a new database.

You cannot make an inplace upgrade.

1. Export all infos and reimport it into the new over the interface.
2. Make a mysql dump, install v2 and update the tables for reimporting them into v2.

**Comment by afanjul** [comment]
Thanks for your response @talheim-it  but sadly I don't understand your process... according to the homepage of the project "If you are upgrading from Mailtrain v1, backup the DB and use it for Mailtrain v2. Mailtrain v2 should be able to upgrade the DB to the new schema." so from my understanding, the platform itselfs should upgrade the DB to the new schema...isn't it?

Otherwise, could you please extend a bit more on your response? what do you mean by export all infos and reimport them? I mean, I have dozens of campaigns, dozens of lists, dozens of segments, dozens of custom fields... And if you ask me to export and re-import all the data in the new database, why do I need to do the step 2 making a mysql dump? and how do I export and re-import all of the data?

Sorry I'm a bit confusing...

**Comment by afanjul** [comment]
Could somebody please **provide a step by step migration process from v1 to v2 of mailtrain**? I mean the real steps (not concepts or assumptions):

Example:
0-install new mailtrain v2 according to the installation process
1- stop your mailtrain service with: service mailtrain stop
2-delete your database mailtrain
3-copy your old database in place (or whatever)
4-start your mailtrain service with: service mailtrain start
5-watch your log for possible errors with: journalctl -u mailtrain

It's pretty frustrating that there isn't any upgrade instructions in all the website (or at least I didn't find them)
Many thanks

**Comment by afanjul** [comment]
Please, I'm stuck with the migration, any help on this?

**Comment by bures** [comment]
1) Make a backup of your v1 database
2) Stop+delete v1 installation
3) Delete mailtrain's DB and DB user
3) Get v2 and do a fresh install (don't start it), the install will create an empty DB and a user
4) Restore the content of the v1 DB backup into the database created by the installer
5) Start v2

**Comment by afanjul** [comment]
Hi @bures , thanks for your clear response, however I have a question, what is the best way to do the step 5? I mean, 
-If I just export the old content (without structure) and restore in the new v2 DB, the importing process fails  (for example there are no tables called attachments, or tables from campaign_1 to campaign__235, etc.) so it fails. 
-If I use the restore with structure option, obviously the process also fails because try to create some existing tables.
-If I use the restore with structure and "drop table" options, all works fine, but I finally end with the v1 table schemas, so I think its not a good deal...

So what it the best option? thanks in advance

**Comment by bures** [comment]
You must not start Mailtrain v2. If you do, it will create it's own tables and then the restore will fail. If you started it already and have the v2 schema, then drop the DB a recreate it (alternatively drop all tables in the DB). Then restore the backup to the empty DB.

**Comment by afanjul** [comment]
Sorry @bures but Im getting the same errors that showed in my first comment... In deed, now I'm realizing that I'm doing the same thing as days ago, because I started my attempt to migration using the same old database...


`Sep 02 09:46:03 mailtrain systemd[1]: Started Mailtrain server.
Sep 02 09:46:05 mailtrain node[23602]: info Using local auth
Sep 02 09:46:06 mailtrain node[23602]: info sql Database check completed
Sep 02 09:46:06 mailtrain node[23602]: migration file "20170506102634_v1_to_v2.js" failed
Sep 02 09:46:06 mailtrain node[23602]: migration failed with error: Cannot read property 'value' of undefined
Sep 02 09:46:06 mailtrain node[23602]: ERR! TypeError: Cannot read property 'value' of undefined
Sep 02 09:46:06 mailtrain node[23602]: ERR!     at migrateBase (/opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:84:65)
Sep 02 09:46:06 mailtrain node[23602]: ERR!     at async /opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:1280:5
Sep 02 09:46:06 mailtrain node[23602]: ERR!  TypeError: Cannot read property 'value' of undefined
Sep 02 09:46:06 mailtrain node[23602]: ERR!     at migrateBase (/opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:84:65)
Sep 02 09:46:06 mailtrain node[23602]: ERR!     at async /opt/mailtrain/server/setup/knex/migrations/20170506102634_v1_to_v2.js:1280:5
Sep 02 09:46:06 mailtrain systemd[1]: mailtrain.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 09:46:06 mailtrain systemd[1]: mailtrain.service: Failed with result 'exit-code'.`

**Comment by bures** [comment]
@afanjul - You would have to post the whole stack trace. This contains too little info.

**Comment by afanjul** [comment]
Looking for the error, it seems that the problem occurs when the migration process try to look for a "db_schema_version" in the "settings" table:  [https://github.com/Mailtrain-org/mailtrain/blob/5add1541d6b2c4c2e3422e85597330933e216374/server/setup/knex/migrations/20170506102634_v1_to_v2.js#L84](https://github.com/Mailtrain-org/mailtrain/blob/5add1541d6b2c4c2e3422e85597330933e216374/server/setup/knex/migrations/20170506102634_v1_to_v2.js#L84)

But we don't have such key in the old database (neither is present in the new v2 by the way). 

![image](https://user-images.githubusercontent.com/2046424/131825796-50a7bc7e-b883-496c-bb4e-c46d144d184f.png)

**Comment by afanjul** [comment]
I think it's the same problem that was happening to this person too:
https://github.com/Mailtrain-org/mailtrain/issues/1128#issue-963770655

**Comment by afanjul** [comment]
Ok, we think we now probably know the problem: the matter is that I hid some information in this thread to not distorted the most difficult problem. The information I hid is that BEFORE that "**Cannot read property 'value' of undefined**" error we had the typical "relation integrity" issue that is easily solved, BUT even when you solve that problem (after start the service) the process get stuck with some new tables inserted, so when you start again the service (after the integrity check problem is solved), the process complains with such "**Cannot read property 'value' of undefined**" errors.

**So the real deal for anyone having any kind of integrity (sql execution) problem (that could be common) from his old database, you have to SOLVE ALL OF THEM BEFORE starting the mailtrain service for the first time.**, otherwise the first execution process will fail, and the subsequence executions will also fail. 

So if it fails in the first execution, stop the service, just delete all tables from mailtrain, re-import the old tables again AND solve the problems before the next service execution.

**Comment by afanjul** [comment]
Now we have jumped the "value" error by now, and keep going with the next error:

`Sep 02 10:41:53 mailtrain node[24829]: ERR!   code: 'ER_BAD_FIELD_ERROR',
Sep 02 10:41:53 mailtrain node[24829]: ERR!   errno: 1054,
Sep 02 10:41:53 mailtrain node[24829]: ERR!   sqlMessage: "Unknown column 'list' in 'custom_forms'",
Sep 02 10:41:53 mailtrain node[24829]: ERR!   sqlState: '42S22',
Sep 02 10:41:53 mailtrain node[24829]: ERR!   index: 0,
Sep 02 10:41:53 mailtrain node[24829]: ERR!   sql: 'ALTER TABLE `custom_forms` MODIFY `list` int unsigned not null'`

**Comment by afanjul** [comment]
Thanks @bures, finally I got to migrate the v1 to v2 version 🤪 taking care of not having any "integrity problems" in the old v1 database. Also I had to remove some attachments from the old database due to it seems it not well covered by the migration process.

However, now in the UI if I go to Templates this error is thrown: do you have any clue of the problem?

![image](https://user-images.githubusercontent.com/2046424/131893634-c90ea10a-917b-46ab-a76e-d90a7dc588ec.png)

**Comment by bures** [comment]
It seems that you migration process wasn't completely successful.  It looks like the templates table contains some null or unsupported type.

Maybe do this: `select distinct type from templates;` and post it here.

**Comment by afanjul** [comment]
Hi @bures thank you for your great support, I owe you a beer :D Finally we got some stable version (still cannot access to the content of campaigns due to the wrong migration of the field "data" but anyways we are dealing with this...
Thanks anyway, I will close the thread. 👍

**Comment by bures** [comment]
Thanks.

**Comment by JanGross** [comment]
I'm currently struggling with migrations as well.
I have updated my old installation to the latest v1.8. 
db_schema_version is at 33
Then I clean installed v2
imported my v1 db into an empty database
started v2 for the first time and it threw this error:
```
Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   code: 'ER_BAD_FIELD_ERROR',
Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   errno: 1054,
Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   sqlMessage: "Unknown column 'role' in 'field list'",
Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   sqlState: '42S22',
Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   index: 0,
Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   sql: "update `users` set `role` = 'master' where `id` = 1"
```
There is no role column in my users table.

**Comment by afanjul** [comment]
> I'm currently struggling with migrations as well.
> I have updated my old installation to the latest v1.8.
> db_schema_version is at 33
> Then I clean installed v2
> imported my v1 db into an empty database
> started v2 for the first time and it threw this error:
> 
> ```
> Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   code: 'ER_BAD_FIELD_ERROR',
> Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   errno: 1054,
> Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   sqlMessage: "Unknown column 'role' in 'field list'",
> Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   sqlState: '42S22',
> Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   index: 0,
> Sep 14 02:53:44 lhv-ostfriesland.de node[28079]: ERR!   sql: "update `users` set `role` = 'master' where `id` = 1"
> ```
> 
> There is no role column in my users table.

In my experience, whenever you find an error, you have to stop mailtrain, drop the database and importing again into an empty one (so it restart from the beginning), solve the problems you have found (missmatching columns/fields errors, etc.)  (before re-starting mailtrain), and then starting mailtrain again so it starts from the very beginning.
