### ISSUE TITLE
Site http(s)://www.mailtrain.org/ seems to be down

### ISSUE THREAD

**Issue by clamattu** [Mailtrain-org/mailtrain#1147]
`404 Not Found
Code: NoSuchBucket
Message: The specified bucket does not exist
BucketName: www.mailtrain.org
RequestId: PR26KSNN6R7NJX7M
HostId: 8u5uzZ+TnUk3tkrhUyxtgAjeUk4H+DOYIdgTCEn5tVu7w4TA4p47hTSlq+Wb5YzNu+nCkzv3hmU=`

**Comment by almereyda** [comment]
Currently it redirects to this GitHub repository.

Yet docs.mailtrain.org are also down now.

What can we do?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
