### ISSUE TITLE
Api /subscriptions with query columns and custom fields

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#1148]
Hi @bures, in the v1 mailtrain we added a feature to allow use the api /subscriptions endpoint passing a queryData and be able to use custom fields, you can check it out here:
https://github.com/afanjul/mailtrain/commit/217bbc709fae6c699ac3dbbf364c639b74f84fae
https://github.com/afanjul/mailtrain/commit/ab22d8b610310f2c99963719eb157a67683d185e
https://github.com/afanjul/mailtrain/commit/1e2c1b631ade68f10283300c4f70ebdf671bb296
https://github.com/afanjul/mailtrain/commit/9a7386fd727e0505dd04dd3cd41a86fd9e3157d6
https://github.com/afanjul/mailtrain/commit/ebb6be470f1a7807f927a911b7ae28ef3f43fed0

However that feature its not present in the v2 version of Mailtrain. However the "framework" code used for query database has changed... 

If you don't like the feature, could you please give us a pseudocode (with the new framework) to implement it on our side? Or if you like it and you don't mind could you upload a first approach of the code?, we could test it and fix any bugs...

Thanks in advance

**Comment by bures** [comment]
No problem bringing it in. However, I'm afraid I don't have the capacity to port it from v1. However, if you want to take care of it and it is consistent with the rest, I'll be happy to accept a PR.

**Comment by afanjul** [comment]
thanks @bures Could you give us a pseudocode or some indications on how to proceed using the new "db query" framework ?

**Comment by bures** [comment]
What do you mean by the new db framework? Knew.js?

**Comment by afanjul** [comment]
I mean, in v1 we had to:
Add queryData parameter to the list function in the api endoint:
`subscriptions.list(req.params.listId, start, limit, queryData, (err, subscriptions, total) => {`
But to allow that parameter we had to add the queryData parameter to the tableHelper list function call inside the subscription s.js list function 
`tableHelpers.list('subscription__' + listId, ['*'], 'email', queryData, start, limit, (err, rows, total) => {`

In v2, things are not doing the same way, even tableHelpers doesn't exist anymore... and for the query functions I think you are using now a tx function not used before...

Finally we added [this commit](https://github.com/afanjul/mailtrain/commit/1e2c1b631ade68f10283300c4f70ebdf671bb296) to allow using/retrieving the custom fields... surely there are a better way to do it now...

Sorry, our node.js knowledge tends to 0... we are from the php background, so any help with some implementation clues will be very helpful...

**Comment by afanjul** [comment]
Any help on this @bures ? we are about to start to coding...

**Comment by afanjul** [comment]
Ok, never mind, I think its done

**Comment by afanjul** [comment]
There is a pull request for this feature: https://github.com/Mailtrain-org/mailtrain/pull/1151

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
