### ISSUE TITLE
External MongoDB

### ISSUE THREAD

**Issue by mzimmer-ra** [Mailtrain-org/mailtrain#1149]
Hi, 
is it possible to use an external MongoDB Database in a Docker deployment?

I tried to use something like this as MONGO_HOST:
`mongodb://username:password@url:port/database`

Thank you.
Marko

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
