### ISSUE TITLE
Links in RSS campaigns don't get tracked

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#1153]
Hi @bures, the links in RSS campaigns don't get tracked because they are rendered as raw links instead of "proxied", even if the "disable click tracking" is off. 

If its not quick for you to solve it, **Could you tell me where I have to look** to solve this issue so I can send you a PR? I cannot debug the app so it's pretty difficult for me to track the code ... 

Just for your information, in Mailtrain v1 they were correctly tracked with the corresponding link hash.

thanks in advance

**Comment by kenschnetz** [comment]
> Hi @bures, the links in RSS campaigns don't get tracked because they are rendered as raw links instead of "proxied", even if the "disable click tracking" is off.
> 
> If its not quick for you to solve it, **Could you tell me where I have to look** to solve this issue so I can send you a PR? I cannot debug the app so it's pretty difficult for me to track the code ...
> 
> Just for your information, in Mailtrain v1 they were correctly tracked with the corresponding link hash.
> 
> thanks in advance

We are experiencing the same issue. Any luck with this?

**Comment by kenschnetz** [comment]
This is a major issue for our case. Can someone point us in the right direction for implementing a fix?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
