### ISSUE TITLE
How to properly update from [Mailtrain 2 beta Build 2020-07-25-1024] to [V2]

### ISSUE THREAD

**Issue by Coriolan-Bataille** [Mailtrain-org/mailtrain#1156]
What would be the proper way to update from beta v2 to v2 for a production server?
[Ubuntu]

**Comment by forgeOneHQ** [comment]
The way to go:

How to:
1.) Backup everything including mysql
2.) git pull latest branch
3.) /opt/mailtrain/setup/reinstall-modules.sh
4.) Fix errors (if possible for depencies of packages) and update packages npm
5.) /opt/mailtrain/client/ > npm run build
6.) Restart the server > systemctl restart mailtrain.service

I need to look to update versions. I did it for all my customers who use mailtrain including myself. 

If you need further help you are welcome.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
