### ISSUE TITLE
multiple cors origins

### ISSUE THREAD

**Issue by catbadger** [Mailtrain-org/mailtrain#1158]
Is there a way to have multiple cors origins? I'd like to be able to have the staging server be able to render the widget.

**Comment by ghost** [comment]
Yes, the cors.origins configuration item takes a list. For example:

```yaml
cors:
  origins: ['https://www.example.com', 'https://staging.example.com']
```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
