### ISSUE TITLE
local install and access via client

### ISSUE THREAD

**Issue by Terminator81** [Mailtrain-org/mailtrain#1161]
I just installed Mailtrain on a Centos via the script "install-centos7-local.sh". Now I want to access via the IP of the system from another client which is on the same network. Unfortunately I can't get into the mailtrain or no page is opened. The status page of the Apache or httpd installation is displayed.

what to do?

**Comment by forgeOneHQ** [comment]
@Terminator81 can you post your apache2 configuration? Would be helpful.

Do you work with any local dns entries for it?

**Comment by Terminator81** [comment]
@talheim-it 

Sorry for the late reply, which variant should I try?
 I would actually like to have the one with the DNS entries ...afterwards I would want to include a certificate from my internal CA.

**Comment by Terminator81** [comment]
sorry I had thought I have initial also described my other attempt.

would it be possible to add a query to https if you want to use letsencrypt or one you created yourself?

then you could either include this in the exception or exchange this with one of the CA.

**Comment by Terminator81** [comment]
where can i find the config of the http server?

systemd....mailtrain.service:
`[Unit]
Description=Mailtrain server
After=syslog.target network.target mariadb.service redis.service mongod.service

[Service]
Environment="NODE_ENV=production"
WorkingDirectory=/opt/mailtrain/server
ExecStart=/usr/bin/node index.js
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
`

**Comment by Terminator81** [comment]
service do not start
``
systemctl status mailtrain
● mailtrain.service - Mailtrain server
   Loaded: loaded (/etc/systemd/system/mailtrain.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Di 2021-11-09 10:00:14 CET; 5s ago
  Process: 6154 ExecStart=/usr/bin/node index.js (code=exited, status=1/FAILURE)
 Main PID: 6154 (code=exited, status=1/FAILURE)

Nov 09 10:00:14 xxxxx systemd[1]: mailtrain.service: main process exited, code=exited, status=1/FAILURE
Nov 09 10:00:14 xxxxx systemd[1]: Unit mailtrain.service entered failed state.
Nov 09 10:00:14 xxxxx systemd[1]: mailtrain.service failed.
``

**Comment by Terminator81** [comment]
i think the mysql has a problem:

`Nov  9 10:02:55 SV-VWMB systemd: mailtrain.service holdoff time over, scheduling restart.
Nov  9 10:02:55 SV-VWMB systemd: Stopped Mailtrain server.
Nov  9 10:02:55 SV-VWMB systemd: Started Mailtrain server.
Nov  9 10:02:57 SV-VWMB node: info Using local auth
Nov  9 10:02:58 SV-VWMB node: info sql Database check completed
Nov  9 10:02:58 SV-VWMB node: migration file "20200824160149_convert_to_utf8mb4.js" failed
Nov  9 10:02:58 SV-VWMB node: migration failed with error: ALTER TABLE blacklist CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaign_links CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaign_lists CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaign_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaigns CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE channel_lists CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE channels CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE confirmations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE custom_fields CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE custom_forms CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE custom_forms_data CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE file_cache CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_campaign_attachment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_campaign_file CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_mosaico_template_block CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_mosaico_template_file CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_template_file CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE generated_role_names CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE import_failed CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE import_runs CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE imports CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE knex_migrations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE knex_migrations_lock CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE links CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE lists CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE mosaico_templates CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE namespaces CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_campaign CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_channel CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_custom_form CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_list CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_mosaico_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_namespace CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_report CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_report_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_send_configuration CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE queued CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE report_templates CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE reports CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE rss CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE segments CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE send_configurations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE settings CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_campaign CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_channel CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_custom_form CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_list CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_mosaico_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_namespace CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_report CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_report_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_send_configuration CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE template_dep_campaigns CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE templates CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE test_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE trigger_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE tzoffset CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; - ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
Nov  9 10:02:58 SV-VWMB node: ERR! Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
Nov  9 10:02:58 SV-VWMB node: ERR!     at Query.Sequence._packetToError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Query.ErrorPacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Protocol._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Parser._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Parser.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Protocol.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:91:28)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.emit (events.js:400:28)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.emit (domain.js:475:12)
Nov  9 10:02:58 SV-VWMB node: ERR!     at addChunk (internal/streams/readable.js:293:12)
Nov  9 10:02:58 SV-VWMB node: ERR!     at readableAddChunk (internal/streams/readable.js:267:9)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.Readable.push (internal/streams/readable.js:206:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     --------------------
Nov  9 10:02:58 SV-VWMB node: ERR!     at Protocol._enqueue (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Connection.query (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:201:25)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._execute (/opt/mailtrain/server/node_modules/bluebird/js/release/debuggability.js:384:9)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._resolveFromExecutor (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:518:18)
Nov  9 10:02:58 SV-VWMB node: ERR!     at new Promise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:103:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Client_MySQL._query (/opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Client_MySQL.query (/opt/mailtrain/server/node_modules/knex/lib/client.js:192:17)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/transaction.js:232:21
Nov  9 10:02:58 SV-VWMB node: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Function.Promise.attempt.Promise.try (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:39:29)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Client_MySQL.trxClient.query (/opt/mailtrain/server/node_modules/knex/lib/transaction.js:229:33)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Runner.<anonymous> (/opt/mailtrain/server/node_modules/knex/lib/runner.js:138:36)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Runner.tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Runner.query (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:15:34)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/runner.js:47:21
Nov  9 10:02:58 SV-VWMB node: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Nov  9 10:02:58 SV-VWMB node: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)
Nov  9 10:02:58 SV-VWMB node: ERR!  Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
Nov  9 10:02:58 SV-VWMB node: ERR!     at Query.Sequence._packetToError (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Query.ErrorPacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Protocol._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Parser._parsePacket (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Parser.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Protocol.write (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:91:28)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.<anonymous> (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.emit (events.js:400:28)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.emit (domain.js:475:12)
Nov  9 10:02:58 SV-VWMB node: ERR!     at addChunk (internal/streams/readable.js:293:12)
Nov  9 10:02:58 SV-VWMB node: ERR!     at readableAddChunk (internal/streams/readable.js:267:9)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Socket.Readable.push (internal/streams/readable.js:206:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     --------------------
Nov  9 10:02:58 SV-VWMB node: ERR!     at Protocol._enqueue (/opt/mailtrain/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Connection.query (/opt/mailtrain/server/node_modules/mysql/lib/Connection.js:201:25)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:144:18
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._execute (/opt/mailtrain/server/node_modules/bluebird/js/release/debuggability.js:384:9)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._resolveFromExecutor (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:518:18)
Nov  9 10:02:58 SV-VWMB node: ERR!     at new Promise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:103:10)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Client_MySQL._query (/opt/mailtrain/server/node_modules/knex/lib/dialects/mysql/index.js:135:12)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Client_MySQL.query (/opt/mailtrain/server/node_modules/knex/lib/client.js:192:17)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/transaction.js:232:21
Nov  9 10:02:58 SV-VWMB node: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Function.Promise.attempt.Promise.try (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:39:29)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Client_MySQL.trxClient.query (/opt/mailtrain/server/node_modules/knex/lib/transaction.js:229:33)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Runner.<anonymous> (/opt/mailtrain/server/node_modules/knex/lib/runner.js:138:36)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Runner.tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Runner.query (/opt/mailtrain/server/node_modules/bluebird/js/release/method.js:15:34)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/knex/lib/runner.js:47:21
Nov  9 10:02:58 SV-VWMB node: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Nov  9 10:02:58 SV-VWMB node: ERR!     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)
Nov  9 10:02:58 SV-VWMB node: ERR!     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10) {
Nov  9 10:02:58 SV-VWMB node: ERR!   code: 'ER_TOO_LONG_KEY',
Nov  9 10:02:58 SV-VWMB node: ERR!   errno: 1071,
Nov  9 10:02:58 SV-VWMB node: ERR!   sqlMessage: 'Specified key was too long; max key length is 767 bytes',
Nov  9 10:02:58 SV-VWMB node: ERR!   sqlState: '42000',
Nov  9 10:02:58 SV-VWMB node: ERR!   index: 4,
Nov  9 10:02:58 SV-VWMB node: ERR!   sql: 'ALTER TABLE blacklist CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaign_links CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaign_lists CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaign_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE campaigns CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE channel_lists CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE channels CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE confirmations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE custom_fields CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE custom_forms CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE custom_forms_data CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE file_cache CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_campaign_attachment CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_campaign_file CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_mosaico_template_block CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_mosaico_template_file CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE files_template_file CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE generated_role_names CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE import_failed CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE import_runs CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE imports CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE knex_migrations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE knex_migrations_lock CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE links CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE lists CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE mosaico_templates CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE namespaces CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_campaign CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_channel CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_custom_form CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_list CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_mosaico_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_namespace CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_report CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_report_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_send_configuration CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE permissions_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE queued CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE report_templates CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE reports CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE rss CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE segments CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE send_configurations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE settings CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_campaign CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_channel CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_custom_form CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_list CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_mosaico_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_namespace CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_report CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_report_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_send_configuration CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE shares_template CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE template_dep_campaigns CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE templates CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE test_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE trigger_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE triggers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE tzoffset CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;ALTER TABLE users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;'
Nov  9 10:02:58 SV-VWMB node: ERR! }
Nov  9 10:02:58 SV-VWMB systemd: mailtrain.service: main process exited, code=exited, status=1/FAILURE
Nov  9 10:02:58 SV-VWMB systemd: Unit mailtrain.service entered failed state.
Nov  9 10:02:58 SV-VWMB systemd: mailtrain.service failed.
`

**Comment by joker-x** [comment]
@Terminator81 see: https://github.com/Mailtrain-org/mailtrain/issues/1110#issuecomment-868257865

**Comment by Terminator81** [comment]
thanks.
i tried centos7 local ....which webserver is installed in this package?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
