### ISSUE TITLE
Issue with node-gyp / asmcrypto / posix modules

### ISSUE THREAD

**Issue by yvangodard** [Mailtrain-org/mailtrain#1162]
Hi,
trying to install mailtrain on Ubuntu Server 20.04, following this : https://www.linuxbabe.com/ubuntu/install-mailtrain-v2-ubuntu-20-04.
I noticed some issues when trying to install node modules : 

--- 
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > asmcrypto.js@2.3.0 prepare /home/localadmin/.npm/_cacache/tmp/git-clone-65fa6c8d
npm ERR! prepareGitDep > node -r esm build.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! prepareGitDep file:///home/localadmin/.npm/_cacache/tmp/git-clone-65fa6c8d/build.js:1
npm ERR! prepareGitDep SyntaxError: Error parsing /home/localadmin/.npm/_cacache/tmp/git-clone-65fa6c8d/node_modules/fs-extra/package.json: Unexpected token , in JSON at position 2565
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
npm ERR! prepareGitDep   path: '/home/localadmin/.npm/_cacache/tmp/git-clone-65fa6c8d/node_modules/fs-extra/package.json'
npm ERR! prepareGitDep }
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! asmcrypto.js@2.3.0 prepare: `node -r esm build.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the asmcrypto.js@2.3.0 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/localadmin/.npm/_logs/2021-11-05T08_04_11_906Z-debug.log
npm ERR! prepareGitDep 
---
make: *** [posix.target.mk:111: Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory '/home/localadmin/mailtrain/server/node_modules/posix/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.4.0-89-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/localadmin/mailtrain/server/node_modules/posix
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
---

And when trying to manually install asmcrypto module  :  
Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! asmcrypto.js@0.22.0 test: `grunt test`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the asmcrypto.js@0.22.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/localadmin/.npm/_logs/2021-11-05T08_06_17_996Z-debug.log

Any idea to solve that ?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
