### ISSUE TITLE
docs on installation from source 

### ISSUE THREAD

**Issue by infoomatic** [Mailtrain-org/mailtrain#1164]
Hi,
Could we please have an updated version of the readme to install mailtrain from source? Would like to install it on FreeBSD, but I guess other *BSDs and Solaris users will probably also find it helpful to setup mailtrain. The old docs from version before 2 do not work, "npm install --production" complains about the missing package.json.

**Comment by joker-x** [comment]
In v2, you have to execute "npm install --production" in each folders:
```
client
shared 
server 
zone-mta 
mvis/client 
mvis/server 
mvis/test-embed 
mvis/ivis-core/client 
mvis/ivis-core/server 
mvis/ivis-core/shared 
mvis/ivis-core/embedding
```
(extracted from https://github.com/Mailtrain-org/mailtrain/blob/v2/setup/functions#L271)

**Comment by forgeOneHQ** [comment]
@infoomatic there are scripts for ubuntu and for centos, if you follow the steps adopted to bsd it should work.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
