### ISSUE TITLE
Settings page is not showing after installation

### ISSUE THREAD

**Issue by Ranjithkumarreddy12** [Mailtrain-org/mailtrain#1169]
Once installation done I logged in to the mailtrain and updated password. 

Now I'm trying to configure AWS SES details under settings But I'm not getting this settings option.

![image](https://user-images.githubusercontent.com/70330941/145522056-0c52c6ae-f7c4-4cff-a8b2-2d6a664091a7.png)

**Comment by forgeOneHQ** [comment]
@Ranjithkumarreddy12 how did you install mailtrain? Docker or via script?

**Comment by Ranjithkumarreddy12** [comment]
To add AWS SES we need to go to Administration ---> Send Configurations in Mailtrain v2.
