### ISSUE TITLE
Global Custom Fields

### ISSUE THREAD

**Issue by HamburgerJungeJr** [Mailtrain-org/mailtrain#117]
Hi,

is it possible to create a global custom field? 
I would like to use this to implement the preview text, which is shown in the emailclient of the reciepients. 
Therefor the text should be invisible to the client

Thanks

**Comment by andris9** [comment]
I don't get it, could you give a more detailed example?

**Comment by HamburgerJungeJr** [comment]
I would like to use this
[https://www.campaignmonitor.com/blog/email-marketing/2011/12/a-practical-guide-to-email-preheaders/](https://www.campaignmonitor.com/blog/email-marketing/2011/12/a-practical-guide-to-email-preheaders/)

But when the text is invisible it is impossible to edit the text, so I thought it would be possble to use an customfield for this but it is not practical to add the previewtext, which will not differ for each reciepient, into the reciepients list.

So I thought of an global customfield.

I hope its clearer now.

**Comment by andris9** [comment]
What about editing the HTML code of the template directly? Then the text would not be invisible?
