### ISSUE TITLE
sandbox intended for public?

### ISSUE THREAD

**Issue by 8191** [Mailtrain-org/mailtrain#1172]
There are now three end-points for Mailtrain: public, sandbox and trusted. For public and trusted the thing is quite clear, I'd say:
  * _public_ needs to be accessible for all recipients of a campaign
  * _trusted_ should only be accessible for administrators and campaign creators
  * What about _sandbox_? Who needs to have access to the sandbox?

Background of the question: I'm using mosaico and my template contains static images (e.g. `img/header.jpg`, which is located in `/opt/mailtrain/client/static/mosaico/templates/mytpl/img/header.jpg`). When sending a mailing the `img/header.jpg` resource translates to the sandbox URL, which I _assumed_ is not needed for the public.

I my assumption not correct? Or is this an error in the mailing generator for mosaico templates? Or did I create my mosaico template wrong?

_Note: same is valid for the social buttons in the Versafix One template._

**Comment by forgeOneHQ** [comment]
@8191 the sandbox is primarly for the editing in the backend before sending. It should be correct rendered when sent.

So sandbox is primarly for creating the newsletter.

I will check it and come back to you.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
