### ISSUE TITLE
Send Configuration - Throttling question

### ISSUE THREAD

**Issue by datdamnzotz** [Mailtrain-org/mailtrain#1173]
So  I am warming up my IP and I initially set the Throttling to 5.
Per the description it says:
```Maximum number of messages to send in an hour. Leave empty or zero for no throttling. If your provider uses a different speed limit (messages/minute or messages/second) then convert this limit into messages/hour (1m/s => 3600m/h). This limit is per sending process.```

In a 24 hr period mailtrain sent 614 emails when it should have only sent around 120.
![image](https://user-images.githubusercontent.com/3913859/147609258-11fdbcf0-99c5-487b-b9db-787a8cc284fb.png)

msg per hour x 24 hrs = max sent in 24 hrs right?

5 x 24 = 120 
Am I missing something?  That's off by a lot.

Second question - Changing the Throttling while a campaign is currently sending  - does how does this affect the campaign's sending rate.  Does it re-evaluate the new throttle value?  Or do you have to pause restart?

**Comment by bures** [comment]
I don't recall, how the throttling has been implemented, but it says "This limit is per sending process." How many sender-workers do you have? I guess 5?

**Comment by datdamnzotz** [comment]
*ding* Light bulb.  Yes 5.  5 x 5 x 24 is indeed 600.
Do you know if it re-evaluate the new throttle value upon change? Or do you have to pause restart?

**Comment by bures** [comment]
It should become effective upon the value change (with some minor delay).

**Comment by datdamnzotz** [comment]
Yup confirmed by switching it to 600 and it took off.  Thanks Bures : ]
