### ISSUE TITLE
Update Docker Container / create new Release Version / create Roadmap

### ISSUE THREAD

**Issue by jonathanmmm** [Mailtrain-org/mailtrain#1183]
@bures Could, maybe after a few other pull requests or so, are included, be there a new release / Docker version?

Is there a release roadmap, like V2.x after that is done or so?

Would be maybe good to know. Mailtrain Docker having no updates for 5 months is not a positive sign for people looking at this project. Therefore also coming up this issue: https://github.com/Mailtrain-org/mailtrain/issues/1171

Maybe using this as an example:
https://github.com/Mailtrain-org/mailtrain/issues/1143
https://github.com/Mailtrain-org/mailtrain/issues/410https://github.com/Mailtrain-org/mailtrain/issues/410
https://github.com/Mailtrain-org/mailtrain/issues/505

also
https://github.com/Mailtrain-org/mailtrain/issues/491

Roadmap should be pinned

**Comment by l4b4r4b4b4** [comment]
I can only support this! 
I could not find the beta development branch in the active branches list. Is main branch considered to be the latest stable release now?
@jonathanmmm @bures

**Comment by Ssshafi** [comment]
Hello,
Any news on this ?

Mailtrain looks like a good piece of software but sadly it seems completly abandoned ...

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
