### ISSUE TITLE
Help: GPG Public key is not set

### ISSUE THREAD

**Issue by jonathanmmm** [Mailtrain-org/mailtrain#1184]
Hi,

I put a private key into the settings and created a custom public gpg field into a list (and called the MERGE TAG PGP_CUSTOMER_KEY).
The user can upload a key and even receive encrypted emails and decrypt them.

But when he presses above the public key text to download the public key of the server, he can't, as it comes the error message:
`Public key is not set` under `https://lists.my-domain.com/subscription/publickey`.

I couldn't find where to add the public key of the server. tried to put it below the private key in the settings, but seemed not to work. Where should I put it?

In this commit it was added: https://github.com/Mailtrain-org/mailtrain/commit/9c9af58eb531261a26adb43f0045b875ee164c08 don't know what I could try.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
