### ISSUE TITLE
Throttling not working

### ISSUE THREAD

**Issue by sandoche** [Mailtrain-org/mailtrain#1188]
I have the following settings
![image](https://user-images.githubusercontent.com/3635348/149010117-9bc035d3-23d5-4627-b22f-54890a607dde.png)

But in my campaign 200 mails have been delivered (which is the max per hour of my SMTP)
![image](https://user-images.githubusercontent.com/3635348/149010280-b8a6d0b9-d887-4dc8-b077-632da431d9f1.png)

Is there a setting I am missing or is it a bug?

**Comment by vix-db** [comment]
Same problem here.
Got blacklisted because of this throttling issue...

**Comment by bures** [comment]
The throttling limit is "per sending process". I guess you have 5 sending processes in your system.

**Comment by vix-db** [comment]
How do I tune up the sending process number?
Max connections is not the sending process number?
![Screenshot from 2022-04-07 10-49-14](https://user-images.githubusercontent.com/47904600/162160055-4ac8f171-7df1-4de1-b108-d8b23e295b30.png)

**Comment by anibalpacheco** [comment]
```
$ sudo grep -C2 processes /opt/mailtrain/server/config/production.yaml

queue:
  processes: 5                        <------------------- I believe is here

```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
