### ISSUE TITLE
Some emojis are not displayed when email is sent

### ISSUE THREAD

**Issue by PabloCastellano** [Mailtrain-org/mailtrain#1190]
Hello.

I'm sending a campaign email and have found that some emojis (😡🙂🚀🦠🔌💯🥳) are not correctly displayed. However the emoji ✨ is displayed correctly.

The emojis are displayed correctly while editing the content of the campaign but when I send the test email, a question mark (`?`) is displayed instead.

I have tested it with both Gmail and my own email server which I check using Thunderbird.

I have had a quick look at the source of the email and I'm inclined to think that the root of the issue are the headers used. The email sent using mailtrain uses the following:

```
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

If I compose a new email in Thunderbird and send it to myself, the `Content-Transfer-Encoding` header is different:

```
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit
```

**Comment by PabloCastellano** [comment]
After some more investigation, I have found that you can pass custom options to nodemailer:

https://github.com/Mailtrain-org/mailtrain/blob/7d4c06fd5c59ba70ec326e1741dd1dd49c342c05/server/lib/mailers.js#L190

So I have uncommented the following line in `server/config/default.yaml`:

```
# extra options for nodemailer
nodemailer:
  textEncoding: base64
```

However that didn't seem to take effect. `Content-Transfer-Encoding` is still `quoted-printable`.

I don't know what else to try, so any help to debug is appreciated

**Comment by PabloCastellano** [comment]
According to [nodemailer changelog](https://github.com/nodemailer/nodemailer/blob/master/CHANGELOG.md):

```
6.5.0 2021-02-26

    Pass through textEncoding to subnodes
    Added support for AWS SES v3 SDK
    Fixed tests
```

This might be related. Right now we are using 5.0.0 for server and 6.4.10 inside zone-mta/

**Comment by PabloCastellano** [comment]
Good news! Updating nodemailer to v6 solved this issue.


For the record, there's no need to uncomment `textEncoding`. Updating nodemailer was enough. Emojis are now displayed correctly in spite of `Content-Transfer-Encoding: quoted-printable`.

I'm sending a pull request.

**Comment by bures** [comment]
@PabloCastellano - I have applied the patch (bump of Nodemailer to v6) to my installation. It broke the email delivery. It seems it has some problem with the DKIM signign with the builtin ZoneMTA. Please, could you share what sending setup you use that works for you? I would like to fix the issue with Nodemailer v6, but I need to narrow it down. Thanks.

**Comment by PabloCastellano** [comment]
Hey @bures. Sorry about the delay, I totally missed your comment.

FWIW, I'm using Generic SMTP as sending configuration.

Today I've hit the same bug and after some debugging, the problem seems to come when I hit "test send" from the "Edit Custom Content" page (`https://<host>/campaigns/<id>/content`).

However when I click "test send" from the "Campaign status" page (`https://<host>/campaigns/<id>/status`) the emojis are displayed correctly!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
