### ISSUE TITLE
MailTrain's clicked and opened status not working after being opened by the recipient

### ISSUE THREAD

**Issue by javeriazy** [Mailtrain-org/mailtrain#1192]
![image](https://user-images.githubusercontent.com/97667651/149306019-67cdd3ff-063c-4775-b72d-747c9dc60223.png)
After sending campaign to users, I should see the change in stats but there's no such change.

**Comment by Terminator81** [comment]
the way back is possible ? i mean you have routed it to the internal server?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
