### ISSUE TITLE
Docker image doesn't work on ARM based processors (aarch64)

### ISSUE THREAD

**Issue by beevk** [Mailtrain-org/mailtrain#1193]
I followed official guidelines to run Mailtrain using docker image and ran into this error **"standard_init_linux.go:228: exec user process caused: exec format error".**
My server Config: 
Operating System: Oracle Linux Server 7.9
CPE OS Name: cpe:/o:oracle:linux:7:9:server
Kernel: Linux 5.4.17-2136.302.6.1.el7uek.aarch64
Architecture: arm64

I think the issue is docker image not being compatible with aarch64 (That's my best guess for now). Please help me to fix this issue.

**Comment by Maxxxel** [comment]
:(

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
