### ISSUE TITLE
Minimal set of permissions giving write-only access to a list

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#1194]
I'd like to create a Mailtrain user that is limited to adding new subscribers to a particular list (via the `/api/subscribe/:listCid` API endpoint).

What would a role look like that allowed this and no more?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
