### ISSUE TITLE
One-click unsubscribe link and antivirus

### ISSUE THREAD

**Issue by fxneumann** [Mailtrain-org/mailtrain#1195]
Hi,

today I had an unusual number of unsubscriptions after sending a newsletter, some affected subscribers even complained that they didn't unsubscribe.

I suspect this is caused by some kind of virus scanner that probes all the links in every mail, thus triggering an unsubscribe. (It never happened before. The unsubscriptions concerned all registered addresses of a certain domain, so I guess this has to do with a recent update of the respective mail security strategies.)

I wonder if anyone else runs into this kind of problem – and how to solve it without getting rid of an one-click unsubscribe option.

Best

Felix

**Comment by jonathanmmm** [comment]
@fxneumann The best fix would be, that the you use a "one step with unsubscription form", this way a user after pressing the link has to press on a website something like "Yes, I am sure" (which would also catch misclicks from subscribers).

The problem with one link without a confirmation in any kind is probably not really possible to solve. An antivirus would probably not tell you that it is not a human, so you had to use some kind of captcha system/human recognize system. 

Do you mean about the "unsubscribe" button at the bottom of the standard template or do you mean the one placable in the pre-header/header.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
