### ISSUE TITLE
MailTrain V2 and clicked links

### ISSUE THREAD

**Issue by cervomix** [Mailtrain-org/mailtrain#1196]
Hey, it seems main website [www.mailtrain.org](http://www.mailtrain.org/) is down and I'm looking for documentation and step by step tutorials.

For example in mailtrain V2 i don't have the "link" button on the campaign to see the most clicked links like it is shown on mailtrain V1 screenshots (in the wiki section).
Also, I'm a bit lost, I didn't find any documentation explaining how to set up a campaign, for example I don't really understand what "channels" are made for. Is there guides or tutorials for this ?
Regards,

**Comment by forgeOneHQ** [comment]
@bures can you send me the data from the page? I setup a server today and will grant you access to it too.

Can you change the DNS Records for mailtrain.org?

**Comment by bures** [comment]
I'm afraid I have no data for the webpage. It used to be only the public page of the V1 installation. We never had a proper webpage.

If you send me an IP address, I'll update the DNS.

Thanks.

**Comment by forgeOneHQ** [comment]
Okay, I send it a bit later via slack.

**Comment by cervomix** [comment]
Hey, thanks for trying to put back the official website. However I'm still struggling to get the "clicked links" information in the campaign I sent, I do not have "links" tab in the campaign report. What I am doing wrong ? Thanks !

**Comment by cervomix** [comment]
Up !
Can someone show me a screenshots on the V2 where we can see the summary of "most clicked links" of a campaign... ? :/
Thanks

**Comment by cervomix** [comment]
Thanks to @talheim-it ! If someone else search it, it's not in a tab but on the + icon on the right, in the "clicked" line of campaign statistics page.

**Comment by saschafoerster** [comment]
I am also searching for the information, who clicked on which link for a RSVP-email with conformations and rejections, so I can see, who doesn't want to come to an event.
