### ISSUE TITLE
Global subscriber search

### ISSUE THREAD

**Issue by raneri** [Mailtrain-org/mailtrain#1198]
Hi, I'm looking for a way to search subscriber globally (on the whole Mailtrain installation). The API endpoint `/api/lists/<emailaddress>` basically does this, but I can't find UI command to do the same thing.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
