### ISSUE TITLE
how to integrate mailtrain as Api in nodejs

### ISSUE THREAD

**Issue by rohan2734** [Mailtrain-org/mailtrain#1203]
how to integrate mailtrain as Api in nodejs

**Comment by jonathanmmm** [comment]
Please look at [Wiki API](https://github.com/Mailtrain-org/mailtrain/wiki/Using-API) and then look in the admin webpanel.
Mailtrain can be used via curl, try to find another variant that can mimic this and you can use in nodejs.

**Comment by rohan2734** [comment]
it says we need a API key, isnt mailtrain free?

**Comment by jonathanmmm** [comment]
> it says we need a API key, isnt mailtrain free?

The software Mailtrain is free, no feature is blocked behind a paywall.

The API key is like a password, in each mailtrain account you can create an API Key and even reset it to a new one (look at the Wiki), this API Key is like a password for this account that you can use.

I would propose you create an account in mailtrain and give it permissions to what you want to do via the API (like give it permission - either through roles or sharing like a list - that is needed). Then log in to this account and create an API key and use this one. That way you only give limited access.

**Comment by rohan2734** [comment]
ok , i will check it

**Comment by rohan2734** [comment]
Ok, I will check.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
