### ISSUE TITLE
Saving template does not work 

### ISSUE THREAD

**Issue by HT-Moh** [Mailtrain-org/mailtrain#1207]
I am not able to save the template - it stay on saving, when I refresh template is empty

![image](https://user-images.githubusercontent.com/34759569/154817281-df394cd2-691b-4083-9c34-7b6a843785a3.png)

One more issue there is as well no possibility to use the editors I clicked everywhere but it's not possible to edit.

![image](https://user-images.githubusercontent.com/34759569/154817416-7b0011e3-4b5c-45a2-90b6-b580a4bb4dd1.png)

I am using docker last version

**Comment by forgeOneHQ** [comment]
Have you tried to dig into the logfiles? Usually there are informations.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
