### ISSUE TITLE
periodic CPU load

### ISSUE THREAD

**Issue by Terminator81** [Mailtrain-org/mailtrain#1209]
what exactly does the system keep doing here? 

![grafik](https://user-images.githubusercontent.com/16563785/155675850-e1ea5023-61df-4a0a-ad68-4272b6edd184.png)

**Comment by forgeOneHQ** [comment]
Ahm, have you tried to look into the log files if you can see details there fitting the time stamp?

**Comment by Terminator81** [comment]
which logfiles ? then i will take a look :)

**Comment by Terminator81** [comment]
i found that periodic messages in the messages.log

`Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551751]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551751]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551751]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551751]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551751]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551751]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb setroubleshoot[1686]: failed to retrieve rpm info for /usr/bin/mongod
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551753]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551753]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551753]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551753]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551753]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551753]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb setroubleshoot[1686]: failed to retrieve rpm info for /etc/selinux/targeted
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551754]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551754]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551754]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551754]: error: cannot open Packages database in /var/lib/rpm
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551754]: error: cannot open Packages index using db5 - Permission denied (13)
Apr 17 03:47:15 sv-vwmb org.fedoraproject.Setroubleshootd[551754]: error: cannot open Packages database in /var/lib/rpm`

**Comment by Terminator81** [comment]
after disabling SELinux, it is no longer detectable

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
