### ISSUE TITLE
No emails are being sent out

### ISSUE THREAD

**Issue by azbub** [Mailtrain-org/mailtrain#1212]
Setup mailtrain on docker locally.

Added a list, template, channel and everything.
The list is my personal gmail address and I tried to send a campaign, it says "Sending" forever.

I am using AWS SMTP (not SES), I see no attempt from mailtrain to send or connect to the SMTP server.

Any idea what the issue is ?

**Comment by forgeOneHQ** [comment]
How did you check the smtp connection to AWS SMTP?

**Comment by azbub** [comment]
Issue solved, I changed the SMTP config from STARTTLS to TLS.

Thank you for pointing me to the right direction.
