### ISSUE TITLE
Multiple mailtain instances (multiple SMTP Servers)

### ISSUE THREAD

**Issue by azbub** [Mailtrain-org/mailtrain#1213]
I am currently testing mailtrain with docker-compose, I would like to send multiple campaigns using multiple SMTP servers to avoid loading my primary mailing server.

Would spawning multiple `mailtrain` services in the docker-compose.yml be a solution or sending config are saved on the mysql database ?

**Comment by forgeOneHQ** [comment]
@azbub I am not sure but you can try it. The question is primarly how you route them to like a loadbalancer to each instance. For example when you haproxy or nginx you can do it with roundrobin, but you need to put something in between I think.

Maybe @bures knows more about it.

**Comment by bures** [comment]
I wouldnt do it with multiple mailtrain instances. Better to create multiple send configurations. Each send configuration can be one mail server.

**Comment by azbub** [comment]
> I wouldnt do it with multiple mailtrain instances. Better to create multiple send configurations. Each send configuration can be one mail server.

Is this even possible ? How does one achieve this ?

**Comment by ghost** [comment]
> Is this even possible ? How does one achieve this ?

When creating/modifying a send configuration, in the "Mailer Settings" section.

![A screenshot of the Mail Settings section](https://i.ibb.co/kgW0rhy/Screenshot-2022-03-23-at-14-10-38-Mailtrain.png)

---

**Edit:** if you wanted a single campaign to be sent using multiple SMTP servers, then AFAIK you'd need to provide your own load balancer in-between Mailtrain and your SMTP servers.

**Comment by azbub** [comment]
Thank you, this will do just fine.

**Comment by forgeOneHQ** [comment]
@azbub setup nginx or ha proxy with multiple smtp servers as backend.

If you need help on this let me know.
