### ISSUE TITLE
slowness in sending rate via AWS SES

### ISSUE THREAD

**Issue by Ranjithkumarreddy12** [Mailtrain-org/mailtrain#1214]
Hi @bures,

we are trying to send an email to ~100000 subscribers every time in a single campaign. The issue is it is taking around 7-8hrs to send mail to all the list of subscribers.

We're using mailtrain v2

**Below are the AWS SES configuration:**
Daily sending quota - 1,000,000 emails per 24-hour period
Maximum send rate - 100 emails per second

**Server configuration where we hosted mailtrain, MariaDB, Redis-server and MongoDB**
OS - Debien10
It's an AWS EC2 instance type - t2.lage (2CPUx8gbRAM)
Storage - 30GB (4GB SWAP)

5 mailtrain sender/worker are running.

we tried all the below different changes still no progress.

1. Server configuration from t2.small (1CPUx2gbRAMx0SWAP) to t2.small (1CPUx2gbRAMx4gb SWAP) to t2.large(2CPUx8gbRAMx4gb SWAP).
2. updated mailtrain send configuration Max connections and Max message (1x10000), (20x500), (10x1000) and (2x10000) And Throttling(300000).

@bures Could you Please help us here. how to increase my sending rate. To send ~100000 emails in 1-2hrs. And why there is no difference when I updated mailtrain configuration and server hardware. what is the bottleneck here?

Thanks in advance @bures

**Comment by bures** [comment]
T2.large is pretty small. Considering you need to run DB too and some other things, it leaves you essentially with 1 core. We've run local tests (i.e. replacing AWS SES with a local dummy SMTP server) in which we were able to push out approx. 50k mails in approx. 5 minutes. The configuration was Intel® Core™ i3-7100U CPU @ 2.40GHz × 4 CPU with 10 workers.

**Comment by bures** [comment]
Keep in mind that you are limited in several ways in AWS. For instance T2 instances are burstable and are throttled based on credits. They don't give you full 2 CPU performance all the time. You should switch at least to M-instances to get continuous performance. Another typical pitfall is the EBS IO rate. With the cheapest settings, it's usually fairly low, which will limit the DB performance. So the bottom line, I think your AWS configuration is likely rather suboptimal.
