### ISSUE TITLE
V1 to V2: Migration of templates and images

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#1216]
I successfully imported the MySQL database into a new install on a different server. Now I wonder, how I can transfer all the templates and especially the images and attachments, that I was using before. How did you solve that problem? 
When I look into old campaigns right now, I see all the images broken. Also templates for RSS-emails don't seem to work as before. 
Thank you for your hints!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
