### ISSUE TITLE
V2: How to change the ports from 3000 to a different port 

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#1217]
How can I change the port from 3000 to a different port, when 3000 is already used by another container. I tried to change it in the docker-compose.yml, but then it seemed to me, that I can't connect to the server, as internally it still waits for connections on port 3000. Maybe someone did it successfully already?

**Comment by forgeOneHQ** [comment]
ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"

You just have to change the left ports from which the service will be available from. 
You cannot change the ports inside, that makes also not much sense since it is the basic configuration of mailtrain to listen inside the mailtrain containers on those ports.

    ports:
    - "3020:3000"
    - "3021:3003"
    - "3022:3004"

**Comment by saschafoerster** [comment]
@talheim-it Thank you! That was to easy. Somehow I tried it before and it didn't work, but maybe this was just a misconfiguration of nginx. By the way: I prefer to use 
```
 ports:
- "127.0.0.1:3020:3000"
- "127.0.0.1:33021:3003"
- "127.0.0.1:33022:3004"
```
So the ports are only opened locally. Docker doesn't respect firewalls like ufw, so all the ports would be open to the net.
