### ISSUE TITLE
Please add a way to add multiple blocked emails at once or to unsubscribe them

### ISSUE THREAD

**Issue by nostradam** [Mailtrain-org/mailtrain#1229]
Hello,

At the moment blocked emails can be added only by one and I have thousands to add.
Or else add a way to mass unsubscribe people please, I don't know how I can delete thousands of people at once.

Thanks

**Comment by bures** [comment]
you can mass unsubscribe using import

**Comment by nostradam** [comment]
Oh wow I didn't know ! Thanks ! I have been struggling for a while doing it by hand.
