### ISSUE TITLE
Can't change default password after installation

### ISSUE THREAD

**Issue by gwrx** [Mailtrain-org/mailtrain#123]
There seems to be an issue with some sort of E-Mail-Address checking on the account page? I get this error if I want to change the default admin password:
> Invalid email address "admin@example.com". Address domain not found

**Comment by jachin** [comment]
I think this might be the same issue I was having #133. Restarting mailtrain might be a work around.

**Comment by witzig** [comment]
This has been fixed with #135 thanks to @jachin.
