### ISSUE TITLE
V2 - clear cache

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#1231]
Hi folks, I have an issue with my /server/files/cache/mosaico-images growing over 5G in size. Can I safely delete the contents of this folder (is it just a cache and will the images be regenerated)?

**Comment by GadisDEV** [comment]
bump?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
