### ISSUE TITLE
How to mass update subscribers with a new or updated field ?

### ISSUE THREAD

**Issue by nostradam** [Mailtrain-org/mailtrain#1233]
Hello,

I've seen that countries are present in the stats and I would like to add them in my subscribers and create a new field for that, but I would need to mass update every subscriber with the new field and in the future be able to update the field with the new data. Is it possible to do this ?

Thanks

**Comment by nostradam** [comment]
I would also like to be able to mass mark as bounce some subscribers. I know that I can mass unsubscribe them from the tool but by marking them as bounce would make more sense to me.

I would suggest to be able to update fields in the importer tool from a csv file.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
