### ISSUE TITLE
Issue after mass unsubscribing users by mistake

### ISSUE THREAD

**Issue by nostradam** [Mailtrain-org/mailtrain#1235]
Hello,

I've mass unsubscribe users by mistake and I tried to mass edit their status to subscribed again by re-importing them but it's not working, any workaround ? Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
