### ISSUE TITLE
V2: Migration of existing templates WITH images and files

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#1242]
I successfully migrated the database from V1 to V2. Only images where missing. 
In the V1-docker, the files where saved in a docker-container (not on the local disc of the server). 

Now I am wondering, if there is an easy way to migrate existing templates including their images. Maybe other's have some experiences? I didn't find any description about this process yet.

**Comment by saschafoerster** [comment]
Ah, I found this notice hidden in this subfolder: 
https://github.com/Mailtrain-org/mailtrain/tree/v2/client/static/mosaico/uploads

> This is a directory for images uploaded to Mosaico in Mailtrain ver. 1. Move the content from /public/mosaico/uploads to here (/client/static/mosaico/uploads).

If someone has more details, it would be really helpful! :) How to export from docker? When to copy? How to check if import was successful? Thank you!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
