### ISSUE TITLE
Contact | Security Issues

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#1255]
Dear mailtrain contributors,

I've tried to contact you through the email found here https://github.com/Mailtrain-org but got no response.
Please get back to me at: [vulnerability@whitesourcesoftware.com](mailto:vulnerability@whitesourcesoftware.com) or [miriam.iomin@whitesourcesoftware.com](mailto:miriam.iomin@whitesourcesoftware.com)
It's about security issues found in your project.

Thanks,
Miriam

**Comment by forgeOneHQ** [comment]
@wsmi22 I write @bures

**Comment by bures** [comment]
Indeed. Thank you for the reports. We'll check it and let you know.

**Comment by bures** [comment]
Thanks once again for the report. I've just committed an update that should hopefully fix it.

**Comment by ghost** [comment]
@bures Is there any release coming out soon?

**Comment by ghost** [comment]
@talheim-it can I ask you to contact @bures again? or do you know if there is any release coming out soon? Thanks :)

**Comment by Patrick-Remy** [comment]
Yes, a release would be nice!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
