### ISSUE TITLE
About reported security vulnerability on huntr.dev

### ISSUE THREAD

**Issue by hunter123111** [Mailtrain-org/mailtrain#1260]
@bures I have reported this:- https://huntr.dev/bounties/ad0652fe-c965-42ef-a6f0-3fed82378d16/ vulnerability before 3 months back but got any reply from your side can you please validate the report on huntr.dev?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
