### ISSUE TITLE
Installation without Docker impossible because github.com/mvis/ repos are not available anymore

### ISSUE THREAD

**Issue by vmario89** [Mailtrain-org/mailtrain#1262]
Hi,
i am trying to install mailtrain at the moment but this seems to be impossible due the fact, that github.com/mvis/client.git and other repos from the user mvis are not existent anymore. There have been taken offline or deleted. I did not find a clone/fork repo yet. How to get a proper replacement for this?

regards, Mario

**Comment by vmario89** [comment]
```
/opt/mailtrain# npm install --production mvis/client 
npm WARN config production Use `--omit=dev` instead.
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/mvis/client.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Konnte nicht vom Remote-Repository lesen.
npm ERR! 
npm ERR! Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
npm ERR! und das Repository existiert.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-27T23_15_37_208Z-debug-0.log

```

**Comment by bures** [comment]
Probably my bad. I might have reintroduce it when I did the last update. Just remove the dependency on mvis. It's not used at the moment.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
