### ISSUE TITLE
CSS glitch on mobile view

### ISSUE THREAD

**Issue by vmario89** [Mailtrain-org/mailtrain#1263]
Hi, 
just recognized some CSS glitch, like the following pictures show. The menu buttons on right side are hidden/cut by white space rectangle. guess some padding or z-index is occasionally wrong.

![Screenshot_20220528_113202_org mozilla firefox](https://user-images.githubusercontent.com/5631071/170840725-5fd44663-05ce-4cc6-b874-9dbec3ce7fe2.jpg)

![Screenshot_20220528_113216_org mozilla firefox](https://user-images.githubusercontent.com/5631071/170840727-4e90fd94-9c80-4a69-b1f8-d81b695cc8cc.jpg)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
