### ISSUE TITLE
Importing unsubscribed addresses

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#1264]
A superb Mailtrain feature is the retention of hashed email addresses for those that have unsubscribed; preventing resubscription via import.

When moving existing lists over to Mailtrain from other systems I need to bring along their unsubscribed lists as well. This would require a way to bring lists into Mailtrain such that their addresses are marked unsubscribed and hashed at import time.

AFAIK this isn't currently possible. If anyone knows a reliable way of doing this manually then I'd love to know :)

**Comment by bures** [comment]
I don't see any simple way. The easiest that comes to my mind is to create a new list, import the unsubscribed users to it. Switch ty mysql and update the "status" to 2 (unsubscribed). Then use SQL copy the entries from the "unsubscribed" list to the real one. You should be able to do this by "insert ... select ..." statement (https://dev.mysql.com/doc/refman/8.0/en/insert-select.html).

**Comment by ghost** [comment]
Cheers, @bures! That lead me to something a little simpler: uploading my unsubscribed list as a normal import, then updating the status based on `source_email`.

```sql
update subscription__<list id> set status=2 where source_email=<import id>
```

**Comment by bures** [comment]
Very good idea! I didn't realize we have the "source_email" field. Yes. This is definitely better.

**Comment by bures** [comment]
One more thing. You'll probably have to set the "unsubscribed" field to some date (current or in the past), so that the GDPR cleanup deletes the data (and retains only the hash). This happens here server/services/gdpr-cleanup.js .
