### ISSUE TITLE
Confirm UnSubscription out of control

### ISSUE THREAD

**Issue by selecta-ufuk** [Mailtrain-org/mailtrain#1265]
Unfortunately, our system sends uncontrolled unsubscribe emails.
Not every account is affected, it's just not easy to reproduce. Some accounts receive unsubscribe emails up to 8 times a day without going before to unsubscribe. Any ideas? 
Mailtrain 2
Build 2021-05-25-0915

**Comment by Borian23** [comment]
I've this same problem Additional I can't edit template for unsubscribe page. If this option is available wher can I find it?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
