### ISSUE TITLE
AWS | SMTP configuration set HEADER

### ISSUE THREAD

**Issue by azbub** [Mailtrain-org/mailtrain#1266]
I am looking to use AWS SES Pool of IPs and I need to include a header in the email for my campaign to be executed on the dedicated IP pool instead of default shared IP pool.

I need to add this header to my emails, but I can't figure out how to do on mailtrain Send configuration : 

`X-SES-CONFIGURATION-SET: ConfigSet`

Ref : https://docs.aws.amazon.com/ses/latest/dg/using-configuration-sets-in-email.html

I am unsure if I can force the header in the email content or if it's a good practice.

Appreciate any help.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
