### ISSUE TITLE
Merge Tags no longer working

### ISSUE THREAD

**Issue by mlamboms** [Mailtrain-org/mailtrain#1269]
Tags are no longer working after update. They appear as is when email is sent
Example [LINK_UNSUBSCRIBE] will appear as is in sent email instead of showing the unsubscribe link

**Comment by bures** [comment]
After which update? What have you set as the "Tag language"?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
