### ISSUE TITLE
Issues with GPG integration

### ISSUE THREAD

**Issue by botherder** [Mailtrain-org/mailtrain#127]
We are experiencing some issues with the GPG integration,  with a number of people reporting errors when subscribing with a PGP public key.
Some get 502 in response, others get that the data is truncated, and some others just don't receive the confirmation email:
https://twitter.com/adulau/status/824336282495176713
https://twitter.com/martijn_grooten/status/824347083197022212

None of this is happening for those who registered with no GPG key.

**Comment by andris9** [comment]
Is there anything in the server logs? If the server returned Bad Gateway then this should mean that some kind of an exception was thrown. What version of Node are you running and what is the version of Mailtrain you are running? If you are updating via git then what's the latest commit hash?

**Comment by andris9** [comment]
One possible reason for this is that OpenPGPjs does not like expired keys. One of the keys mentioned in twitter was expired already on 2003

**Comment by botherder** [comment]
I'm using nodejs v6.9.4 and Mailtrain is from git master, latest commit.
