### ISSUE TITLE
Change [FIRST_NAME] [LAST_NAME] variables in TO:, when sending mails

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#1270]
I tried to change the variable-names of the two fields "first name" and "last name". 
I changed them from "FIRST_NAME" and "LAST_NAME" to "VORNAME" and "NACHNAME" in the definition of fields for this certain list. The screenshot shows the old settings: 
<img width="1173" alt="Bildschirmfoto 2022-07-07 um 12 04 58" src="https://user-images.githubusercontent.com/1153741/177748439-79f09881-1d77-4270-a213-bcad8b01cf08.png">

When I send emails, the "TO"-settings where still on "FIRST NAME" "LAST NAME". I didn't find any setting to change the TO: in the emails. Is there a way? 
<img width="293" alt="Bildschirmfoto 2022-07-07 um 12 05 59" src="https://user-images.githubusercontent.com/1153741/177748623-2e3bfaf1-05f5-42a9-8d53-bc82050593d5.png">

**Comment by saschafoerster** [comment]
In Test-E-Mails, I sent to myself, I not get "[MERGE_FIRST_NAME] [MERGE_LAST_NAME]" in the TO:-field
<img width="477" alt="Bildschirmfoto 2022-07-07 um 12 21 39" src="https://user-images.githubusercontent.com/1153741/177751849-520fbb19-61b6-43e3-8892-8e7ca171a381.png">

**Comment by bures** [comment]
I'm not 100% sure I understand, but maybe what you are looking for is in List -> Edit -> Recipients name template

**Comment by saschafoerster** [comment]
@bures Indeed! Thank you so much, I was searching for this and didn't see!

**Comment by saschafoerster** [comment]
@bures By the way: Is there an option to replace to variable with some word, when the field is empty? Something like 
"Dear [FIRST_NAME]"  that get's into "Dear reader", when FIRST_NAME is empty?

**Comment by bures** [comment]
It's the same tag replacement as in campaign. So you can certainly have "Dear [FIRST_NAME]". If I'm not mistaken, it might work to have something like ```[FIRST_NAME|<default>]```. But I would have to check. I might have adopted this from v1.

**Comment by saschafoerster** [comment]
@bures It doesn't work with | in my trials. 

`Liebe*r [VORNAME]` (no name is defined) 
<img width="259" alt="Bildschirmfoto 2022-07-07 um 21 16 58" src="https://user-images.githubusercontent.com/1153741/177854276-ed535b97-51c2-42b3-97f8-8117ef77610b.png">

`Liebe*r [VORNAME|Leser*in]`

<img width="438" alt="Bildschirmfoto 2022-07-07 um 21 17 01" src="https://user-images.githubusercontent.com/1153741/177854281-74edcc4e-ab6d-4da5-8da7-d5a502f3df36.png">

**Comment by saschafoerster** [comment]
I also tried it with default settings for this field, with no success
<img width="646" alt="Bildschirmfoto 2022-07-07 um 21 20 14" src="https://user-images.githubusercontent.com/1153741/177855572-edc6fa72-716f-4f82-a5cc-5488b6cdbeb6.png">

**Comment by bures** [comment]
Try slash '/' instead of pipe '|'

**Comment by saschafoerster** [comment]
<img width="281" alt="Bildschirmfoto 2022-07-07 um 21 52 18" src="https://user-images.githubusercontent.com/1153741/177860271-cbd98052-9cd7-4293-84c5-9c3ef33cd388.png">

It just works! :)

**Comment by bures** [comment]
Perfect.

**Comment by bures** [comment]
If it's inside the campaign/template, you can also switch the tag language to handlebars and then you can have proper if-conditions.
