### ISSUE TITLE
Can't create new user defined subscription form

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#1273]
I try to create a new subscription form. I filled out all the necessary fields and click on "save", then it stays stuck loading. 
<img width="560" alt="Bildschirmfoto 2022-07-08 um 09 05 25" src="https://user-images.githubusercontent.com/1153741/177936434-984c7c48-6669-47b3-9d5a-ea6006ea62bf.png">

Browser console shows this error message: 
```
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (forms-validate, line 0)
[Log] Error in "validateFormState": Error: Request failed with status code 400
```
I don't see any message in the forms, which field creates this problem.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
