### ISSUE TITLE
Can't edit privacy page in custom forms

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#1274]
I try to edit the privacy page in custom forms. 
<img width="997" alt="Bildschirmfoto 2022-07-08 um 09 07 46" src="https://user-images.githubusercontent.com/1153741/177936832-33b827ea-faf2-4979-a844-ef6e720b579c.png">

Clicking on "Save" get's confirmed, but then the field is reloaded with the default text. My new text is overwritten. 

I also don't understand, where or how this privacy-text is shown, as I didn't find any links in any other default form to it.

**Comment by selecta-ufuk** [comment]
> I try to edit the privacy page in custom forms. <img alt="Bildschirmfoto 2022-07-08 um 09 07 46" width="997" src="https://user-images.githubusercontent.com/1153741/177936832-33b827ea-faf2-4979-a844-ef6e720b579c.png">
> 
> Clicking on "Save" get's confirmed, but then the field is reloaded with the default text. My new text is overwritten.
> 
> **I also don't understand, where or how this privacy-text is shown, as I didn't find any links in any other default form to it.**

Does anyone know how to display this privacy field on the subscription page?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
