### ISSUE TITLE
Duplicate Email Adresses

### ISSUE THREAD

**Issue by skeleton55** [Mailtrain-org/mailtrain#1281]
If a customer changes their email via Manage address form, it is possible to add that mail again to a list without any duplicate errors(mail already present). My guess would be that the Manage address form doesn't change the hash_mail, just the email field in the db, which causes this issue?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
