### ISSUE TITLE
noindex

### ISSUE THREAD

**Issue by Vahaggn** [Mailtrain-org/mailtrain#1287]
Hi everyone 
How i can change first page HTML to stop indexing this website by crawlers?

**Comment by jfqd** [comment]
You may add the following line to the head section of the layout-file under`server/views/layout.hbs`

```
<meta name="robots" content="noindex,nofollow,noarchive" />
```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
