### ISSUE TITLE
How can I hide a field from the subscription form? (private fields)

### ISSUE THREAD

**Issue by PabloCastellano** [Mailtrain-org/mailtrain#1296]
Hello! I would like to segment the subscribers in my newsletter depending on whether they are customers or not. This way I could send different emails to them depending on this fact.

I have tried adding a new field, however this solution does not work for me because fields are shown in the subscription form and I don't want subscribers to select if they are customers or not.

I have also tried creating a new segment but adding a new rule for each customer email address doesn't look like the way to go.

Is there any other solution? Thanks!

**Comment by GadisDEV** [comment]
in the field settings you can view the visibility settings of any field:

Subscription form
Select the field before which this field should appear in new subscription form. To exclude the field from the new subscription form, select "Not visible".
Management form
Select the field before which this field should appear in subscription management. To exclude the field from the subscription management form, select "Not visible".

**Comment by PabloCastellano** [comment]
@GadisDEV Oh, I didn't expect to find that option in the Field order section. Thanks a lot!

**Comment by PabloCastellano** [comment]
Oh now I see that the Field order section is not shown when I choose Field Type "Option".

**Comment by GadisDEV** [comment]
so you first create a "Checkboxes (from option fields)" group, set it to not visible, and then create the options inside it by specifying 'Belongs to checkbox / dropdown / radio group'
