### ISSUE TITLE
Make a segment which exclude subscribers of another list ?

### ISSUE THREAD

**Issue by ImaCrea** [Mailtrain-org/mailtrain#1298]
Hi there,

I have two lists, let's say A and B. And there are some subscribers that are subscribed to the two of them.

Now let's say I want to send campaign to these two lists but I wanna make sure people who are in the two list don't receive it twice. What I'd need would be to make a segment in List A for example which says "only sub *not* present in list B". 

Is there a way I can do that at the moment? Can I exclude from List A subs from another list?

Or would you recommend I gather them in a same list and divide them with a custom field?

Thanks for your help,

**Comment by ericuldall** [comment]
If you send to both lists using a single campaign it should already be deduped for you.

**Comment by ImaCrea** [comment]
oh wow, didn't know I could do that. Thanks @ericuldall :)
But that's great if I send the same campaign to both lists. But if I'm sending a slightly different campaign to each list, how should I proceed to avoid sending both to people who happen to be in both lists?

**Comment by ericuldall** [comment]
Currently there is no cross list segmentation that I'm aware of.

**Comment by ImaCrea** [comment]
alright thanks :)
