### ISSUE TITLE
campaign table in reports/#/edit shows wrong created time value

### ISSUE THREAD

**Issue by j-mir-prazak** [Mailtrain-org/mailtrain#1300]
https://github.com/Mailtrain-org/mailtrain/blob/1d05dda88ee3c270ac4b8fe1f1444454770ac0cc/client/src/reports/CUD.js#L236

there is wrong index used on this line of code (created is always 53 years ago): the date is on index 9, changing it fixes the issue. you might be inclined to change the model, but you might also use the model somewhere else: so i rather leave here the issue, than pull request..

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
