### ISSUE TITLE
subscriber click history report

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#1308]
is it possible in mailtrain to view or report which campaigns a subscriber has clicked or has in any way acted upon? 
I would like to see like a user history detail linked to the subscriber, like on date X this subscriber has subscribed, on this date he clicked on this link in this campaign, and on this date he modified his subscription.

is this already possible in some way?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
