### ISSUE TITLE
Message Sent has no content: Template CodeEditor/Mosaico/GrapeJS Not working

### ISSUE THREAD

**Issue by RedWarriorEnt** [Mailtrain-org/mailtrain#1311]
Ubuntu 20.04, Mailtrain v2

Template CodeEditor/Mosaico/GrapeJS Not showing up. Not showing html, or obj oriented editing.

Created tests in multiple ways. Template - Mosaico, GrapeJS, Code Editor. Can't seem to get the template editors to show up. The plain text editor at the bottom of the page shows up but not the editor.

Tested and Reinstalled ImageMagic, Mosaico, and GrapeJS. All are up to date.

Help

Ron

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
