### ISSUE TITLE
Unable to log out of Mailtrain GUI errors with req#logout requires a callback function

### ISSUE THREAD

**Issue by DustyBawls** [Mailtrain-org/mailtrain#1320]
I’ve just run in a new Mailtrain install on Debian 11.5, the installation went well but when I try to log out I get “req#logout requires a callback function”. This is the second time I’ve hit this snag, the first time was on Ubuntu 20.04. 

Installation was on a new, clean install which works fine, with the exception of logging out. My searches for a solution haven’t pulled up anything useful. There is discussion about the use of said function but nothing that relates to Mailtrain.

Do you have any suggestions on how I might fix this, or at least get a more informative error report?

Many thanks for putting Mailtrain together, it’s an impressive server.

kind regards

Nigel.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
