### ISSUE TITLE
Install always hangs @extract:lodash

### ISSUE THREAD

**Issue by v2px** [Mailtrain-org/mailtrain#1323]
Hello,

I tried with a lot of supported systems - CentOS 7, 8 (Alma 8), Ubuntu 18.04 and the install scripts always hang forever in some npm install, like this:

[            ......] / extract:lodash: sill extract lodash@4.17.21 extracted to /opt/mailtrain/shared/node_modules/.staging/lodash-0caaab

This currently makes a fresh installation impossible.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
