### ISSUE TITLE
increase send process on the go

### ISSUE THREAD

**Issue by vikky1992** [Mailtrain-org/mailtrain#1324]
Hi, I have setup the Mailtrain V2 using docker services. Is there a way I can increase the number of processes without restarting the container?
I could see that the in server/config/production.yml queue processes are set to 5 by default. I will have to increase to 10 without restarting the whole docker container.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
