### ISSUE TITLE
`changeemail` API endpoint missing in V2

### ISSUE THREAD

**Issue by Sanqui** [Mailtrain-org/mailtrain#1326]
Hello,

I'm in the process of updating from V1 to V2.  In V1, the following endpoint is present:

![image](https://user-images.githubusercontent.com/289437/210384908-caeb84ca-66ed-4d7b-8b0b-1b960d190b26.png)

This endpoint doesn't appear to be present in V2.  I believe that as a workaround, I can check subscription status for the old email, unsubscribe it, and subscribe under the new one.  Is there a better way to change a subscriber's email address via the API?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
