### ISSUE TITLE
Where is valuable documentation?

### ISSUE THREAD

**Issue by janipeki** [Mailtrain-org/mailtrain#1332]
Hello,

I'm searching for valuable documentation for mailtrain. For example: I'm currently trying to find out how to set the unsubscribe url properly. Where is this documented? Thank you!

Regards,
Jani

**Comment by forgeOneHQ** [comment]
Hello @janipeki,

what are you looking exactly for? I had a bad last year so I didn't make it to work on the website but I plan to do it in the second quarter of this year.

**Comment by janipeki** [comment]
Hi Mathias,

like I said: I am not able to set the unsubscribe URL for a campaign. I did not find a documentation for this and lot of other stuff for mailtrain. Basically where can I find documentation for mailtrain?

**Comment by forgeOneHQ** [comment]
@janipeki sorry for my late response. In communication with @bures I plan to set up a documentation page this year. The server is ready and we just need to look how to automate it with github actions. 

More infos soon :)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
