### ISSUE TITLE
http://localhost:3000/ work but use Host IP Address such as http://10.11.21.26:3000 notwork

### ISSUE THREAD

**Issue by mrtortong** [Mailtrain-org/mailtrain#1333]
Dear All,

            Could you please let me know why I cannot use via http://10.11.21.26:3000 (localhost).
I deployment with Docker and Docker compose.

Best regards,

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
