### ISSUE TITLE
Authenticates two separate LDAP paths

### ISSUE THREAD

**Issue by danachille** [Mailtrain-org/mailtrain#1335]
Hello,  i want two types of users to be able to log in with the LDAP: internal and external.

How do I get :
"OU=Internal,OU=Users,DC=test,DC=example,DC=com" and 
"OU=External,OU=Users,DC=test,DC=example,DC=com"  members to connect to it?

I tried

export LDAP_FILTER (|(&(ou=Internal)(cn={{username}}))(&(ou=External)(cn={{username}}))
export LDAP_BASEDN="OU=Users,DC=test,DC=example,DC=com"
export LDAP_UIDTAG="cn"

And many more, but nothing works.
The scope is set to sub in the code (server/lib/passeport.js) , but when trying with a path above, the recursion doesn't seem to work

Have you encountered the same issue? Do you have an idea to solve this problem?

Thanks

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
