### ISSUE TITLE
add locales issue

### ISSUE THREAD

**Issue by matteocisilino** [Mailtrain-org/mailtrain#1340]
hello , 

i'm running latest git stable , OS debian 11 , everything working .

i've created my personal locale ( it-IT ) creating directory in locales , called common.json

i've changed services/workers/reports/config/default.yaml
adding 

enabledLanguages:
 - it-IT

i've modified lib/translate.js , adding 
loadLanguage('it-IT');

modifed locales/extract.js
and added 
const localeTranslations = ['es-ES/common.json', 'fr-FR/common.json', 'pt-BR/common.json', 'de-DE/common.json', 'ru-RU/common.json', 'it-IT/common.json'];

modified shared/langs.js
and added langCodes 
    'it-IT': {
        getShortLabel: t => 'IT',
        getLabel: t => 'Italiano',
        longCode: 'it-IT'
    },

the locales is selectable in the drop-down , but the languange don't switch , can anyone point me a step by step process to add locales ?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
