### ISSUE TITLE
he.encode option breaks encoding for some email clients

### ISSUE THREAD

**Issue by j-mir-prazak** [Mailtrain-org/mailtrain#1341]
https://github.com/Mailtrain-org/mailtrain/blob/7c6f34ef25dba981de58aec9785af48f3ea3315d/server/lib/tools.js#L175

useNamedReferences: true in gmail messes up the slavic characters encoding, so that the message has literal encoding displayed, even though the preview is fine

if set to useNamedReferences: false the output is fine, as you can see in the screenshots.

is there a reason for useNamedReferences to be true? could it break someplace else?

![Screenshot from 2023-03-19 12-01-12](https://user-images.githubusercontent.com/25672201/226171266-dc6b82f3-6be6-4a57-9795-1e335ed5045b.png)
![Screenshot from 2023-03-19 12-01-30](https://user-images.githubusercontent.com/25672201/226171270-433adff6-aa5b-47f9-8d11-f0273a8bf826.png)
![Screenshot from 2023-03-19 12-01-24](https://user-images.githubusercontent.com/25672201/226171267-1b54f218-51c1-418b-a301-22200725f02f.png)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
