### ISSUE TITLE
Error on user creation

### ISSUE THREAD

**Issue by svaysset** [Mailtrain-org/mailtrain#1345]
Hello,
with the last version, we encounter an error when we wanna to create a new user :
![image](https://user-images.githubusercontent.com/59916035/230557693-0e70c255-f119-4048-a396-1c7f1d655b9c.png)

we are obliged to create it directly in database and it isn't the way we want.
Is there a solution to fix it ?
thx

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
