### ISSUE TITLE
Landing page / Website request

### ISSUE THREAD

**Issue by aha999** [Mailtrain-org/mailtrain#1346]
It would be useful to have this project's landing site / website, so any future news articles can link to it and the website would make a better visual representation of the project that could attract more users, developers and contributors.

A simple and free option is via [Github Pages](https://pages.github.com/), that a lot of github open source projects are using, which Github hosts for any repo on their website.

> Hosted directly from your GitHub repository. Just edit, push, and your changes are live.
> No databases are needed to be set up and no servers to configure

Repositories that use github pages: [Examples](https://github.com/collections/github-pages-examples)

Interesting article: [Link](https://www.toptal.com/github/unlimited-scale-web-hosting-github-pages-cloudflare)

> Consider [Jekyll](https://jekyllrb.com/). You give it [Liquid](https://jekyllrb.com/docs/liquid/) templates and Markdown content
> Free Jekyll templates: https://jekyllthemes.io/free

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
