### ISSUE TITLE
Only sends between 19:00 and 7:00 

### ISSUE THREAD

**Issue by Evcarfan** [Mailtrain-org/mailtrain#1351]
I am trying to figure out why test e-mails and campaigns will only send out between this window.

**Comment by anibalpacheco** [comment]
Hi @Evcarfan, did you solve it? I'm facing something like this and spent **days** (not joke) trying to find, but still no clue, I'm now in the phase of writting log lines in the code and rebuilding (rebuild the server takes a lot if the node_modules are deleted, I'm not a nodejs expert). Using generic smtp on v2 branch, with zone_mta disabled. thank you.

**Comment by anibalpacheco** [comment]
And finally I found a solution!!! @Evcarfan I'll push a MR ASAP

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by Evcarfan** [comment]
This is great!  Looking forward to this :)
