### ISSUE TITLE
Update to a newer version of node-sass

### ISSUE THREAD

**Issue by raboof** [Mailtrain-org/mailtrain#1352]
node-sass@4.14.1, which the client currently depends on, requires python2 in its postinstall script, while python2 is unsupported. It would be nice to update to a newer version of node-sass.

**Comment by forgeOneHQ** [comment]
Hello @raboof ,

I wrote @bures and he responded to me last week.

We plan to upgrade all packages for mailtrain and fix the issues. 

I am behind it and will update about the progress.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
