### ISSUE TITLE
Timezone not working via the subscribe API

### ISSUE THREAD

**Issue by doino-gretchenliev** [Mailtrain-org/mailtrain#1354]
Timezone is not set on the user when the user is created via the API:
```
curl -XPOST \
-H "Content-Type: application/json" \
--data '{"EMAIL":"fake@gmail.com", "TIMEZONE": "EST"}' \
'https://mailtrain.example.com/api/subscribe/QwRkgatmts?access_token=secret' 
```

It's also not working with POST parameters.

**Comment by doino-gretchenliev** [comment]
It works if the timezone is in lowercase, so it might be worth it to add toLowerCase [here](https://github.com/Mailtrain-org/mailtrain/blob/7c6f34ef25dba981de58aec9785af48f3ea3315d/server/routes/api.js#L57).

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
