### ISSUE TITLE
Service can't be started with NodeJS 18

### ISSUE THREAD

**Issue by fxneumann** [Mailtrain-org/mailtrain#1359]
Hi,

I tried to update my NodeJS version from 16 to 18. After doing so, the service couldn't be restarted (supervisorctl threw a "spawn error").

Is Mailtrain compatible with NodeJS 18?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
