### ISSUE TITLE
V2 Translation Localization Open Source project approved on Poeditor - add your language

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#1360]
Hi to all! I am happy to say that the translation project on Poeditor has been approved, removing string limits and so adding new languages will be much easier. 
If you wish to help or add a language, please join the project on 

https://poeditor.com/join/project/U7eqwdyQjl

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
