### ISSUE TITLE
Mailtrain_1 exit code 1 - Docker compose

### ISSUE THREAD

**Issue by PaulMcF1987** [Mailtrain-org/mailtrain#1362]
https://www.awesomescreenshot.com/video/21571665?key=a93cce5bd39ffd999f754aa90aa8dfd3

I have taken the above video to show what is happening. I havent deployed the container via portainer but I tend to use it to get debug info

I cannot access/use mailtrain,  for some reason I am not getting access.

My YML file

    version: '3'

    services:
      mysql:
        image: mariadb:10.4
        environment:
        - MYSQL_ROOT_PASSWORD=XYZ
        - MYSQL_DATABASE=XYZ
        - MYSQL_USER=XYZ
        - MYSQL_PASSWORD=XYZ
        volumes:
        - mysql-data:/var/lib/mysql

      redis:
        image: redis:5
        volumes:
        - redis-data:/data

      mongo:
        image: mongo:4-xenial
        volumes:
        - mongo-data:/data/db

      mailtrain:
        image: mailtrain/mailtrain:latest
        ports:
        - "8100:3000"
        - "8101:3003"
        - "8102:3004"
        volumes:
        - mailtrain-files:/app/server/files

    volumes:
      mysql-data:
      redis-data:
      mongo-data:
      mailtrain-files:

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
