### ISSUE TITLE
Tutorial on how to use transactional API

### ISSUE THREAD

**Issue by patchthecode** [Mailtrain-org/mailtrain#1366]
I see this in the documentation

<img width="885" alt="Screenshot 2023-11-04 at 10 31 35 PM" src="https://github.com/Mailtrain-org/mailtrain/assets/2439146/76010b9a-a8fd-466b-8bed-2508f4d7f10c">

Trying to send this on terminal gives the following error response:

```
{
    "error": "Permission denied",
    "data": []
}
```

What am i missing? Can someone tell me or point me in the direction of everything i need to setup in order to send an email via the API?

**Comment by ddwdwaw111** [comment]
Probably check if the template associated with the :templateId in the URL exists.
