### ISSUE TITLE
List-Unsubscribe-Post

### ISSUE THREAD

**Issue by astroblaster** [Mailtrain-org/mailtrain#1368]
Hello,

Is there support, or plans to support the List-Unsubscribe-Post header and One-click unsubscribe as defined in https://datatracker.ietf.org/doc/html/rfc8058 and required by Google for high volume senders as of February 2024?

https://support.google.com/a/answer/81126?sjid=18111741999076255902-NC&visit_id=638429331185653183-1023441911&rd=1#requirements-5k&zippy=%2Crequirements-for-sending-or-more-messages-per-day

Thanks,

Brian

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
