### ISSUE TITLE
create user/namespaces and send config from api, npm or database

### ISSUE THREAD

**Issue by Jorgepastorr** [Mailtrain-org/mailtrain#1369]
Hello!

I would like to create a script that mailtrain creates users, namespaces and send-configuration.
Is it possible to do it from the API, NPM or database?

I found in /server/routes/api.js, but I don't saw the right route

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
