### ISSUE TITLE
Feature request: add api for retrieving list subscriptions

### ISSUE THREAD

**Issue by nebulade** [Mailtrain-org/mailtrain#137]
Maybe I just can't find it, however if it does not exist, would there be a possibility to add a GET api to retrieve all subscribers of a list?

If that would be accepted, I can work on a pull request for this feature.

**Comment by witzig** [comment]
I'm sure this issue slipped the radar ...

> If that would be accepted, I can work on a pull request for this feature.

That would be great!

**Comment by nebulade** [comment]
Thanks, I will look into that hopefully later this week, currently quite busy here.

**Comment by jdfx** [comment]
#181 Working on these here

**Comment by gkrol-zermelo** [comment]
I've added API support to get all subscribers for a list. See the pull request https://github.com/Mailtrain-org/mailtrain/pull/348 and the branch at https://github.com/zermelo-software/mailtrain/tree/api_extensions
