### ISSUE TITLE
Is this project an abandonware?

### ISSUE THREAD

**Issue by TiagoGouvea** [Mailtrain-org/mailtrain#1370]
The last commit was a long time ago, the issues are most of them without interaction....

Is this code trustworthy? 

Is this project abandonware?

**Comment by GadisDEV** [comment]
We still use it for our organisation. takes some time to setup, but is very good at delivery

**Comment by bures** [comment]
Nono, it's not abandoned. Just waits for someone to find some time to update the packages. I myself use it. The "problem" is that it works, so no updates have been necessary for our setup since the release.

**Comment by forgeOneHQ** [comment]
@bures and I are in contact to find a way but I will involve some people and think about to fund it.

**Comment by TiagoGouvea** [comment]
Got it. 

It seems to have just some version on this repository, as if it is kept in another repo, and, eventually copied a version here.
There are more than a hundred PR open.. with few activities.

Hope it gets active sometime because having an open source JS mail marketing tool would be really great!

**Comment by forgeOneHQ** [comment]
I just wrote @bures again. And help we need to clean up the pull requests too...

a lot of work comes up.^^

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by forgeOneHQ** [comment]
Infos for v3 are collected here: #1372 
Feature Requests: #1373

**Comment by TiagoGouvea** [comment]
@talheim-it I'm in to help validate it, using and giving feedback, for sure.
