### ISSUE TITLE
Delete all resources in namespace

### ISSUE THREAD

**Issue by Jorgepastorr** [Mailtrain-org/mailtrain#1371]
Hello,

How can I delete all the resources from a namespace? 
Right now, I have to do it manually, resource by resource, and show the message error continuously, saying that the resource cannot be deleted because it's associated with another one, and it's very annoying.

Is there a function to delete everything that belongs to a namespace? 
If not, could it be incorporated in the future?

**Comment by bures** [comment]
I'm afraid, there is no easy way to do it at the moment. 
Good idea for the future. Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
