### ISSUE TITLE
One subscriber in multiple lists 

### ISSUE THREAD

**Issue by envas** [Mailtrain-org/mailtrain#1374]
We currently maintain mailing lists on our mail server, but we would like to use an application like Mailtrain. Currently, we are making an evaluation of various mailing systems. 

In our case, we have many mailing lists (currently about 40-50), and there is one mailing list per product. The campaigns then alert customers to important product updates. Naturally, we have customers who are subscribed to many mailing lists. This is where I have a problem understanding the Mailtrain philosophy. If I understand correctly, when we launch a new product and create a new mail list to which I want to add customers manually, I have to edit all their data again, even if they already exist in other mail lists. Other systems like Brevo (formerly Sendinblue) solve this problem easily - there is a list of all recipients, and it is possible to edit the recipient-email list relation, which is 1:n. There are two ways to assign a recipient to a mailing list. The first is the email list view, where I can pick recipients from the all recipients list; the second is a recipient form, where I can assign him all mailing lists he should be active in. 

Is this type of workflow even possible to implement in Mailtrain? Do you have any idea how?

**Comment by forgeOneHQ** [comment]
This is a request for a possible Feature if not already available. Since we focus on v3 we won't make any further changes to v2.
