### ISSUE TITLE
What are the supported / working nodejs versions

### ISSUE THREAD

**Issue by hagenbauer** [Mailtrain-org/mailtrain#1375]
I cannot find a specific version other then 14+ and some issues give me the impression that there are nodejs versions with problems. 

Any clarrification would be appreciated

**Comment by forgeOneHQ** [comment]
Because we are working on a new version and documentation as soon as v3 is ready.

V3 is in progress at the moment to get all libraries and versions updated.

**Comment by forgeOneHQ** [comment]
V3 is in testing.
