### ISSUE TITLE
Can't Send Emails. _senderTimeToNextEnabledDay in mailer.js broken v2 [Temp Fix included]

### ISSUE THREAD

**Issue by markalston** [Mailtrain-org/mailtrain#1376]
I know you are working on v3 but just want to document this for myself and others.
I have been struggling for a week trying to get emails to send changing all sorts of settings.

Finally realized that the function _senderTimeToNextEnabledDay in server/lib/mailers.js would extend the time out a day for any emails sent.   Since I want to send emails immediately I simply added a return 0 statement to the top of the function and now my emails are sending.

If I have time, and assuming this code will be used in v3, I will try to figure out where it is failing but for now I have a working v2 system so I'm not going to get to it too soon.

**Comment by forgeOneHQ** [comment]
@markalston we are focusing on the v3, after that we can work on improvements.
