### ISSUE TITLE
CKEditor 4 is not secure

### ISSUE THREAD

**Issue by Terminator81** [Mailtrain-org/mailtrain#1378]
![grafik](https://github.com/Mailtrain-org/mailtrain/assets/16563785/dbd12f8b-a557-4cb9-82ca-404c555fa60c)

How do I get rid of this message?

**Comment by forgeOneHQ** [comment]
I think not for the moment or @bures ?

Guess this will be fixed with v3?

**Comment by forgeOneHQ** [comment]
CKE is removed in v3 testing at the moment.
