### ISSUE TITLE
Send by email address instead of a mailing list

### ISSUE THREAD

**Issue by HLFH** [Mailtrain-org/mailtrain#138]
Hi,

Let's say we don't care about mailing lists and it takes too much time.
Let's say we have the email addresses or our customers.
And that sometimes we need specific templates for specific purposes for specific customers.
In that case, mailing list/email groups are not efficient, since at each time, we need to re-create one for a small specific list of customers.
Could we select one-by-one at which user/email address we will send the campaign?

Could you add the feature? ?@andris9

Thanks in advance,

**Comment by andris9** [comment]
That would be doable but for now I can't afford to take any extra (unpaid) work outside my already existing pipeline. I'll leave the issue open, maybe someone else implements this and makes a PR.

**Comment by HLFH** [comment]
@andris9 Ok. A PR so.

**Comment by jdfx** [comment]
I am looking into this.

**Comment by elitzer2** [comment]
Resurrecting this, anyone know what it would take to get this into v2? I'm curious in general if anyone has done this and what the architecture looks like for something like this. How does one expose an email address alias to a list? Thanks!

**Comment by forgeOneHQ** [comment]
I close this issue. My workaround was if I send a email in v2 to a specific user again I check it as test user and send it again.
