### ISSUE TITLE
List import from CSV stays on Initialized status

### ISSUE THREAD

**Issue by gregshep** [Mailtrain-org/mailtrain#139]
Strange issue where I import a simple CSV file with just email, first name, and last name.  Mailtrain shows the job as Initialized with 0 added, updated, and failed.  Refreshing the screen does not change the status.  The Mailtrain service is running as is zone-mta.  There are no messages in /var/log/syslog.  This is a fresh AWS instance (Ubuntu 16.04) installed with the auto-script with settings changed.  I did have this working on another AWS instance, and I even started from scratch but I cannot get a list imported.  Any suggestions?  I've read the wiki on importing CSV.  Thanks in advance.

**Comment by davidboliveira** [comment]
Hi,
did you solve this problem?

I get stuck with the same issue.

Thanks

**Comment by gregshep** [comment]
No I never did.  I used the free tier on MailChimp and it told me that 5 lines of my CSV file were wrong.  I fixed these and tried Mailtrain again but it did the same thing.

**Comment by nezam05** [comment]
I found out that if there are fields in the csv that mailtrain can't import, it will get stuck. I removed all other field except mail and name fields and it was working fine.

**Comment by andris9** [comment]
Do you have an example of such CSV that breaks Mailtrain?

**Comment by nezam05** [comment]
@andris9 I have one such mailchimp export file. How can I share the file with you?

**Comment by andris9** [comment]
Could you send it to andris.reinman@gmail.com? I would also need a description of your custom fields (maybe a screenshot of the custom field list?)

**Comment by nezam05** [comment]
@andris9 sent

**Comment by cpresaxXR0MAXx** [comment]
Good afternoon,

After actively checking all the code associated with the shipments, we have determined that the production.toml file configuration has to be as follows:

```

User = "mailtrain"
Group = "mailtrain"
[log]
Level = "error"
[Www]
Port = 80
Secret = "Fi7beech"
[Mysql]
Password = "ohlahPhae3ei"
[Redis]
Enabled = false
[Verp]
Enabled = false
[Queue]
Processes = 5
```


Once you set up the production.toml file (which is located in / opt / mailtrain / config), you will be able to upload lists without problems, and proceed to send mail in a normal way.


Thanks for your time and I would recommend that you adapt the script so that this configuration is applied by default.


Greetings, carlos.presa@outlook.es

**Comment by andris9** [comment]
If you disable Redis then there is no point setting queue processes value more than 1. Without Redis these processes are not able to share state between them.

**Comment by forgeOneHQ** [comment]
Since this is V1 related, I am closing this issue. Please upgrade to V2.
