### ISSUE TITLE
Install error - bash: line 15: apt-add-repository: command not found

### ISSUE THREAD

**Issue by rnarayan** [Mailtrain-org/mailtrain#141]
When I ran the command (on a brand new Linux 16.04 LTS server at Linode)
`curl https://raw.githubusercontent.com/andris9/mailtrain/master/setup/install.sh | sudo bash`

I got the following error
`bash: line 15: apt-add-repository: command not found`

I found the solution at this blog - https://pricklytech.wordpress.com/2014/05/16/ubuntu-server-14-4-trusty-add-apt-repository-command-not-found/

I ran the following command and the problem was solved.
`sudo apt-get install software-properties-common`

Would it be possible to add a check if apt-add-repository exists and if not, install it before running the next command in bash script.

**Comment by forgeOneHQ** [comment]
@rnarayan if you still use it please try v2 which is already stable.
