### ISSUE TITLE
WordPress Mailtrain widget plugin

### ISSUE THREAD

**Issue by HLFH** [Mailtrain-org/mailtrain#152]
Hi,

With a WordPress Mailtrain widget working with [Mailtrain API](https://github.com/andris9/mailtrain/wiki/Using-API), a visitor should be able to add his email address and then the widget plugin will send it to Mailtrain API on the specified mailing list.

**Comment by andris9** [comment]
I don't get it. Do you want to make a Wordpress plugin for Mailtrain?

**Comment by HLFH** [comment]
No, not now. But I just think Mailtrain will greatly benefit from a WordPress plugin. So you can add an _help wanted_ label.

**Comment by andris9** [comment]
good idea, I added the label

**Comment by witzig** [comment]
Already in my pipeline. ETA end of march.

**Comment by witzig** [comment]
https://github.com/Mailtrain-org/mailtrain-wordpress-plugin

**Comment by HLFH** [comment]
@witzig Thank you great and fantastic @witzig!

**Comment by nezam05** [comment]
Thank you very much @witzig, was waiting for this :)

**Comment by GadisDEV** [comment]
is this compatible with V2?
