### ISSUE TITLE
Controlling RSS campaign frequency

### ISSUE THREAD

**Issue by nezam05** [Mailtrain-org/mailtrain#166]
Hi, I am trying to use mailtrain to deliver rss feed from my blog to the reader on daily basis. Default behavior sends mail for every post I publish. Is there any way to control the behavior? It would be great if mailtrain send one mail per day/per week.

TIA

**Comment by andris9** [comment]
Yeah, this has been requested before. For now RSS related stuff is not a priority, so if someone else does not tackle it (Mailtrain is open source after all) then this is not going to happen any time soon

**Comment by healthstatus** [comment]
You can use zapier to create an RSS digest then fire the digest as a feed with one item in it.
