### ISSUE TITLE
Beefree.io Drag and Drop Editor Suggestion

### ISSUE THREAD

**Issue by w3update** [Mailtrain-org/mailtrain#171]
Hi,

You can also include http://beefree.io/ drag and drop editor it is easier, modern and have great features to parse minimal html with maximum compatible across different esp i.e. Gmail, Yahoo, Outlook etc.

thanks

**Comment by bago** [comment]
Beefree is not an opensource project and while having a "free version" it is not Free software (FOSS). Is their client library GPL compatible? If they didn't publish a client library under the GPL license then it is legally not permitted to integrate that editor with Mailtrain.

IANAL, but https://developers.beefree.io/assets/doc/terms-of-service.html doesn't seem to be GPL compatible.

**Comment by w3update** [comment]
Not much aware about license distribution.

I dont think there would be any license issue as the beefree.io is cloud based driven app, it does not share any app source rather offer simple integration which can be integrated free of cost without removing beefree logo check here there plan https://developers.beefree.io/signup.

Here are the sample codes to integrate http://help.beefree.io/hc/en-us/articles/203135882-Sample-code-and-templates

moreover if you look at https://moonmail.io also using the same in free version without any problem here is the demo https://api.moonmail.io/demo-user/login.

I suppose it can be used as an external plugin since every Mailtrain deployment needs to be signed for special api keys from beefree.io unlike your existing drag and drop editors.

Hope it make sense.

**Comment by bago** [comment]
` rather offer simple integration which can be integrated free of cost without removing beefree logo check here there plan https://developers.beefree.io/signup.
`

"free of cost" is a lot different from "GPL-compatible". Try contacting them and ask if they think their plugin is GPL-compatible... Identifying what is part of a "distribution" (in GPL terms) when you integrate 2 javascript libraries, or simply call one javascript library from your html page is not so straightforward, so it is not obvious.

I don't want to be picky, but licenses are important and licensing terms are there for a reason! "guessing" may hurt.

**Comment by witzig** [comment]
Thanks for your suggestion, @w3update.

The licence issue does indeed seem like a deal breaker to get Beefree into the official release.
