### ISSUE TITLE
Postfixbounce can't find email 

### ISSUE THREAD

**Issue by tehsYs** [Mailtrain-org/mailtrain#184]
Hi there,

I tried to setup postfixbounce but my bounced mails never got matched.
I found that mailtrain finds the mails queueId properly but it cannot match it to an actual sent message.

I started to debug the postfix-bounce-server.js and I get an error on line 40.
https://github.com/andris9/mailtrain/blob/f0784156fe914a959ac35e236cb40779cf5ada6f/services/postfix-bounce-server.js#L40

I get the following error:

> Mar 21 10:48:41 mailtrain node[662]: /opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:79
Mar 21 10:48:41 mailtrain node[662]: throw err; // Rethrow non-MySQL errors
Mar 21 10:48:41 mailtrain node[662]: ^
Mar 21 10:48:41 mailtrain node[662]: TypeError: Cannot read property 'stack' of null
Mar 21 10:48:41 mailtrain node[662]: at campaigns.findMailByResponse (/opt/mailtrain/services/postfix-bounce-server.js:42:86)
Mar 21 10:48:41 mailtrain node[662]: at checkNext (/opt/mailtrain/lib/models/campaigns.js:1133:28)
Mar 21 10:48:41 mailtrain node[662]: at Query.connection.query [as _callback] (/opt/mailtrain/lib/models/campaigns.js:1139:32)
Mar 21 10:48:41 mailtrain node[662]: at Query.Sequence.end (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
Mar 21 10:48:41 mailtrain node[662]: at Query._handleFinalResultPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
Mar 21 10:48:41 mailtrain node[662]: at Query.EofPacket (/opt/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
Mar 21 10:48:41 mailtrain node[662]: at Protocol._parsePacket (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:280:23)
Mar 21 10:48:41 mailtrain node[662]: at Parser.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Parser.js:75:12)
Mar 21 10:48:41 mailtrain node[662]: at Protocol.write (/opt/mailtrain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
Mar 21 10:48:41 mailtrain node[662]: at Socket.<anonymous> (/opt/mailtrain/node_modules/mysql/lib/Connection.js:103:28)
Mar 21 10:48:41 mailtrain systemd[1]: mailtrain.service: main process exited, code=exited, status=1/FAILURE

> 

Example log line:
> Mar 21 09:37:05 mail postfix/smtp[29286]: 98E9F2CC07C0: to=<saddsadsadsa@asdasdsaasdasddas.ads>, relay=your-dns-needs-immediate-attention.ads[127.0.53.53]:25, delay=0.22, delays=0.04/0.01/0.16/0, dsn=5.4.6, status=bounced (mail for asdasdsaasdasddas.ads loops back to myself) 
>

**Comment by tehsYs** [comment]
Is there anything else I can help with to fix this problem?

**Comment by andris9** [comment]
Could you try to find out the queue entry from Mailtrain database? It should be in a table campaign__X where X is the ID of your campaign. The queue ID should be in the response_id field. Could you paste the contents of the row that matches your previous queue ID 98E9F2CC07C0? If I could see what is exactly on that database row then I could set up similar situation in my test instance and see what is going on.

**Comment by tehsYs** [comment]
I recreated the issue with a new mail:
>
Mar 24 08:41:43 mail postfix/smtp[16922]: 0E7512CC0CE0: to=<saddsadsadsa@asdasdsaasdasddas.ads>, relay=your-dns-needs-immediate-attention.ads[127.0.53.53]:25, delay=0.32, delays=0.12/0.01/0.19/0, dsn=5.4.6, status=bounced (mail for asdasdsaasdasddas.ads loops back to myself)
>

>
INSERT INTO `campaign__4` (`id`, `list`, `segment`, `subscription`, `status`, `response`, `response_id`, `updated`, `created`) VALUES
(3, 2, 0, 3, 1, '250 2.0.0 Ok: queued as 0E7512CC0CE0', '0E7512CC0CE0', '2017-03-24 07:41:43', '2017-03-24 07:41:42');
>

**Comment by andris9** [comment]
I wasn't really able to replicate that error but just in case, I removed all `err.stack` usage from the code, maybe this helps.

**Comment by tehsYs** [comment]
Thank you for taking the time to look into this, it was probably my mistake.
I managed to fix this after moving the log file to the same computer and not using nc over the network but locally.
