### ISSUE TITLE
Missing Features in 1.23.0

### ISSUE THREAD

**Issue by tobihagemann** [Mailtrain-org/mailtrain#186]
I've most definitely updated to 1.23.0 (I was on 1.21.0 before) and I don't see the new features. The only editor I can use is Summernote (no Mosaico or GrapeJS in sight) and I don't see where I can set up custom forms. Did I miss something obvious?

**Comment by andris9** [comment]
When creating a new template you should see a selection of template editors:

![](https://cldup.com/ncd4GZe0zf.png)

You can access custom forms by opening a list and clicking on the List Actions button

**Comment by witzig** [comment]
Custom Forms are (currently in Master) not in 1.23.0.

**Comment by andris9** [comment]
I tagged the master as v1.23.1 just now

**Comment by tobihagemann** [comment]
Okay cool, custom forms are working now! Thanks for the quick update.

However, I still can't see other template editors than Summernote. Was it bad that I skipped version 1.22.0? How is that list populated, is there any way I can debug this?

**Comment by andris9** [comment]
It is defined in the configuration file. Do you use a modified default.toml config file for your own settings or an environment specific config file (Eg. "production.toml")?

**Comment by tobihagemann** [comment]
That's probably it. Awesome, saw the new configurations in the toml. 👍
