### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by ksthiele** [Mailtrain-org/mailtrain#190]
Hello, 

it would be nice to be able to create a blacklist or at least the possibility to exclude emails listed in another list, like a segment.

**Comment by witzig** [comment]
If you need a solution quickly and your blacklist isn't huge, I'd suggest to add an array to your config file and implement a check here: https://github.com/Mailtrain-org/mailtrain/blob/master/routes/subscription.js#L501

**Comment by larrabee** [comment]
Hello. Blacklist function was implemented by [PR 203](https://github.com/Mailtrain-org/mailtrain/pull/203).

**Comment by witzig** [comment]
Better yet, if you need a solution quickly, ask @larrabee! Props!
