### ISSUE TITLE
Send Campaign to multiple lists

### ISSUE THREAD

**Issue by janus-reith** [Mailtrain-org/mailtrain#191]
I can only send to one list at a time.
Other solutions, like phplist, offer the ability to select multiple lists.

Is someone maybe already working on this?
I consider it a quite essential thing.

**Comment by witzig** [comment]
As far as I'm aware, there's no one working on this.

May I suggest to use use list segments?

**Comment by janus-reith** [comment]
I probably missed something, could you explain further what list segments are?

**Comment by witzig** [comment]
There're some screenshots here: http://mailtrain.org

**Comment by afanjul** [comment]
Yeah, this would be a great feature, because I want to keep my lists separated but be able to send a campaing to more than 1 list.

**Comment by johnmerced** [comment]
This might be a fairly easy implementation - I wonder why is this issue still open? Looking for this as well.

**Comment by forgeOneHQ** [comment]
Should be possible in v2 already. Please install the latest v2 version and try again. If you need any help open a new issue! :)
