### ISSUE TITLE
Can't add html from custom json field

### ISSUE THREAD

**Issue by minusplusminus** [Mailtrain-org/mailtrain#192]
Hi,

according to this link [https://github.com/Mailtrain-org/mailtrain/wiki/JSON-data](https://github.com/Mailtrain-org/mailtrain/wiki/JSON-data)
I can add html template from `Field Type JSON`

But in all the template editors, the JSON gets converted to a string. I'm using the example inside the tutorial
```

{{#each values}}
  <p>{{this.title}}</p>
{{/each}}
```

using `v1.23.2` it doesn't when using `v1.22.0` it does work

Thanks for this awesome project by the way!

**Comment by minusplusminus** [comment]
So, it's allready fixed in the master branch?

**Comment by witzig** [comment]
Unfortunately not, it just references the commit where the change was introduced. Right now I don't see an easy fix other than to [allowUnsafeSymbols](https://github.com/mathiasbynens/he#allowunsafesymbols), which seems out of the question. Perhaps @andris9 could have a look at this as it breaks current behaviour.

Please also consider that those HTML tags will/would be in your plaintext version as well. Perhaps tags should be avoided in the first place.

**Comment by witzig** [comment]
@minusplusminus, the fix is in master now. HTML templates for custom JSON fields render properly again. Thanks.
