### ISSUE TITLE
Template Editor Image Upload Error

### ISSUE THREAD

**Issue by mattmoesen** [Mailtrain-org/mailtrain#193]
hello,

we tried using the newly available template editors, but we cannot upload any images:
- mosaico returns error message "unexpected upload error (Proxy error)"
- grapejs returns an error message just when trying to edit an image placeholder: "No image editor installed"

may anyone has an idea what we are doing wrong or how we can fix this issue?

many thanks in advance!

br,
matthias

**Comment by witzig** [comment]
Can you verify that ImageMagick is installed and Mailtrain has write permission for the upload directories?  (public/mosaico/uploads and public/grapejs/uploads)

**Comment by mattmoesen** [comment]
many thanks. 
got it working, there was a reverse proxy settings problem.

**Comment by HLFH** [comment]
Same issue. I will migrate from `apache2` to `nginx` with some great configuration I have and I will get back to you.
