### ISSUE TITLE
Dockerfile - user local files rather than cloning latest

### ISSUE THREAD

**Issue by programster** [Mailtrain-org/mailtrain#194]
I just downloaded release version 1.23 (which happens to currently be the latest release, but may not be in future). I ran through the documented docker build steps, but then noticed the Dockerfile was just ignoring the version I had downloaded and always fetches the latest code with the step below:

```
git clone git://github.com/Mailtrain-org/mailtrain.git /app
```

Please could we have the dockerfile use the local files instead, so that if a user wishes to deploy a specific release, they can just download that version, and run a docker build from there. A quick hack to get this to work would be to move all the files (except the Dockerfile) into a folder called "app" and replace the command: 

```
git clone git://github.com/Mailtrain-org/mailtrain.git /app
```
with 

```
COPY app /app
```

**Comment by andris9** [comment]
Do you have suggestions how to best handle this so it would not get out of sync? Using some git hook that automatically checks that the version in Dockerfile matches package.json?

**Comment by programster** [comment]
@andris9 I'm a bit confused as to what has to be in-sync. Are you talking about the name/tag of the docker image that get's built when you run a docker build or perhaps libraries that are included at the last minute? My confusion is probably because I'm coming from a PHP background rather than a node one and not sure what that package.json is for but can only assume its like composer.json for including external packages/libs. Ideally (at least from my POV) "releases" are bundled with any/all necessary code with them. E.g. in PHP based applications, the releases would have the "vendor" file included in them, whereas the "master" branch in git would not include vendor and it would be up to the developer to run "composer update". Alternatively, one can use "fixed" version numbers of packages.

**Comment by andris9** [comment]
By keeping things in sync I'm mean that for now releasing a new Mailtrain version means tagging current state in master branch. The Dockerfile was provided by another contributor and sooner or later it is forgotten to update it. So let's say I change the Dockerfile and set the version to use as v1.23.2. Next month the latest version could be already 1.25.0 but the Dockerfile is still at 1.23.2 as no-one remembered to update it.

**Comment by witzig** [comment]
Wouldn't it be possible to fetch the tags here (https://github.com/Mailtrain-org/mailtrain/blob/master/Dockerfile#L4) too, then using build args (https://docs.docker.com/engine/reference/builder/#arg) to checkout a specific version?

**Comment by programster** [comment]
@andris9 If you implement the change I suggested of changing the line in the Dockerfile from:

```
git clone git://github.com/Mailtrain-org/mailtrain.git /app
```
to
```
COPY app /app
```
(after having moved all the files to within a folder called app), then you never have to update the dockerfile and never have to worry about keeping things in sync. The dockerfile will use the local files that the user pulled down rather than pulling from the net. Thus if I pulled version 1.22 the docker file builds 1.22. If I pulled down 1.5 the dockerfile will build version 1.5, _without you changing anything_.

**Comment by andris9** [comment]
Could you make a pull request for this?

**Comment by programster** [comment]
@andris9 already on it :)

**Comment by programster** [comment]
Okay that should be good to go. If you have any problems with it, I can be sure to address them.

**Comment by witzig** [comment]
Moving files around like this may break existing installations during upgrade. Why not just copy current dir to app in the dockerfile instead? No app folder necessary.

> If I pulled down 1.5 the dockerfile in that release will build version 1.5 [...]

There's no dockerfile in 1.5. If you want to run versions prior to v1.23.1 with docker I suggest build args, see comment above.

**Comment by programster** [comment]
@witzig your right. I'll try using `ADD . /app` instead when i get back home to the computer and resubmit if it works.

**Comment by programster** [comment]
I have submitted [another different pull request](https://github.com/Mailtrain-org/mailtrain/pull/199) based on @witzig suggestion. Please accept one or the other. I do think the former actually looks neater, separating the github documenation and licence content out from the app, but can see the latter being easier to merge/accept.
