### ISSUE TITLE
grapeJS Missing Image Editor

### ISSUE THREAD

**Issue by mattmoesen** [Mailtrain-org/mailtrain#195]
Hello,

it seems that it is actualley not possible to edit images in the grapeJS editor by clicking on the pencil icon. Always get the alert "No image editor installed"

Seems to be due to the following code: 
`cmdm.add('tlb-edit', {
        run: function(ed) {
            alert('No image editor installed');
        },
    });`

found in views/grapejs/editor.hbs

Will this be provided/fixed in a future release?

br,
Matthias

**Comment by witzig** [comment]
The pencil icon is a left-over from the GrapeJS Newsletter Demo and I don't think there's currently an image editor available for GrapeJS.

> Will this be provided/fixed in a future release?

Provided as soon an image editor is built into the official GrapeJS release or someone submits a PR.

Until then we should probably remove the icon to avoid further confusion.

**Comment by mattmoesen** [comment]
ok thanks for the info!
