### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by 2silver** [Mailtrain-org/mailtrain#2]
As alternative for MySQL

**Comment by andris9** [comment]
Postgres support is not something I'm going to do myself but there's a guy who offered to help with Postgres support whenever he has time for it (which might mean tomorrow or never, who knows)

**Comment by michaelBenin** [comment]
What about using an orm? Something like bookshelf?

**Comment by andris9** [comment]
I'm not sure how well an ORM would perform in this case – I use a lot of foreign keys, creating and deleting tables (every list and campaign gets its own tables to support large lists and to track individual clicks), adding and removing columns/indexes to tables (needed to support custom fields), transactions (bounced message should also decrement subscribers counter without going out of sync etc.) and so on.

**Comment by michaelBenin** [comment]
From my experience, what you described can be accomplished with Knex and Bookshelf.

**Comment by michaelBenin** [comment]
Also, it would allow flexibility with other supported dbs.

**Comment by forgeOneHQ** [comment]
I am closing this issue again.

**Comment by saper** [comment]
Most of the work needs to be done in the https://github.com/smartarch/ivis-core dependency, which, in turn, uses [Knex](https://www.npmjs.com/package/knex), so it might be possible to build something working on PostgreSQL.
