### ISSUE TITLE
SNS bounce notifications never arrive

### ISSUE THREAD

**Issue by jloh** [Mailtrain-org/mailtrain#200]
I've just setup mailtrain for testing and am using SES for email. I've created a new SNS topic and added the webhook URL (`https://<domain>/webhooks/aws`) as a subscription however bounce notifications never arrive.

Do I have do to any config in SNS to tell it to deliver specific ones for bounce notifications or anything? After adding the subscription I see the initial `POST` arrive that is confirming the subscription but no other entries apart from that.

**Comment by andris9** [comment]
Unfortunately there is no SES setup guide for Mailtrain but you can follow any other guides, like the one from FormGet [here](https://www.formget.com/setup-amazon-ses-account-for-handling-bounces/). If you have already created the SNS topic and subscription then see the SES notification setup starting from Step 9.

**Comment by copyhold** [comment]
what is the endpoint where Mailtrain handles *bounce and spam*

**Comment by marcinkunert** [comment]
@copyhold  /webhooks/aws

Here is a very nice article how to configure it: https://jloh.co/posts/aws-bounce-notifications-for-mailtrain/

**Comment by sweetppro** [comment]
to get this working, you need to also ensure that **Raw message delivery** is **Disabled** for your SNS subscription

**Comment by jloh** [comment]
Thanks @sweetppro! My blog link above has been updated to reflect this.
