### ISSUE TITLE
Mosaico Editor Save

### ISSUE THREAD

**Issue by markalston** [Mailtrain-org/mailtrain#205]
I am getting errors and no saves when clicking "Save" while using the mosaico editor. 

The error log shows:

Apr 13 12:18:07 www node[23937]: info HTTP #033[0mGET /editorapi/img?method=placeholder&params=534%2C200 #033[32m200 #033[0m108.215 ms - -#033[0m
Apr 13 12:18:07 www node[23937]: (node:23937) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): Error: only http(s) protocols are supported
Apr 13 12:18:07 www node[23937]: (node:23937) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): Error: only http(s) protocols are supported
Apr 13 12:18:07 www node[23937]: (node:23937) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 36): Error: only http(s) protocols are supported

**Comment by witzig** [comment]
Is ImageMagick installed?

**Comment by markalston** [comment]
Yes. 

> sudo apt-get install imagemagick
...
imagemagick is already the newest version (8:6.8.9.9-7ubuntu5.6).

**Comment by witzig** [comment]
From within your VPS, can you successfully curl a local image?
`curl https://your-mailtrain-comain.com/mosaico/templates/versafix-1/img/sponsor.gif`

**Comment by witzig** [comment]
> Does saving use a temp directory? Perhaps a permissions problem?
Yes. It uses public/mosaico/uploads

**Comment by markalston** [comment]
Looks like it is something with my custom template.  I can save using the Versafix-1 template.

My custom template works fine with mosaico-php on a seperate install but won't save via mailtrain.

I'm going to try and rebuild it from the versafix-1 template again.
I'll reopen if I still have issues.

**Comment by witzig** [comment]
Make sure to use absolute or root relative URL's for your images.

**Comment by witzig** [comment]
I assume you've resolved the issue by now. Should we update the readme? Or other suggestions?

**Comment by markalston** [comment]
Yeah, I just rebuilt our templates from scratch using the verafix-1 ones again.  Everything seems fine now.  Unfortunately I have no idea what was causing the issue as it still works fine in my mosaico-php backend.
