### ISSUE TITLE
Compromised server with SPAM after install mailtrain

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#209]
Hi there, we have installed mailtrain in a brand new server (with new ip) to use it as a marketing mail server, but sadly the day after we have received an abuse spam report from our ISP, the log shows a lot of connections to send emails from our server to russian mails like these...

`Apr 15 20:58:27 mailtrain zone-mta[2641]: (Sender/default/2641) 15b61a3d6290002550.01f REJECTED[other] from=schoolvestnik@magentonotes.com[schoolvestnik@magentonotes.com] to=ld_mgn@mail.ru mx=mail.ru (queryMx ECONNREFUSED mail.ru)
Apr 15 20:58:27 mailtrain zone-mta[2641]: (Sender/default/2641) 15b61a3d6290002550.03b REJECTED[other] from=schoolvestnik@magentonotes.com[schoolvestnik@magentonotes.com] to=ldc-ad@mail.ru mx=mail.ru (queryMx ECONNREFUSED mail.ru)
Apr 15 20:58:27 mailtrain zone-mta[2605]: (Sender/default/2605) 15b61a3d6290002550.044`

I had to block all outgoings connections to avoid more warnings, and I have 2 questions:

1.- How could somebody send emails from our server?
2.- Wich further actions could we do to avoid sending spam from our server?

thanks in advanced,
Alex

**Comment by andris9** [comment]
Do you have more logs for the id `15b61a3d6290002550`? This should reveal how the message was inserted to the sending queue.

**Comment by andris9** [comment]
And did you use the setup.sh to set up all parts or did you use some custom config?

**Comment by markalston** [comment]
It could also be someone using the subscription form and the emails could simply be the subscribe confirmation email.  Are you sure someone is actually sending their own mail via your server? Stopping the former is hard with any subscription signup form short of using captcha's.

**Comment by afanjul** [comment]
Sorry for the "noise" guys, but after reviewing my config, I could see a test we did to set zone-mta for remote use too (as a usual SMTP server), and maybe that was the "hole" to our spam attack (not verified yet) by some kind of port scanner.

Could somebody tell me if its fine (and a good practice) to change the ports for our whole smtp server? (ie. random high port). I don't know if smtp ports must to be the standard ones for any reason. In case we can do it, is these the only files to change, right?:
-/opt/zone-mta/config/production.json
-/opt/mailtrain/config/default.toml
-change ufw config to allow that ports

thanks in advanced and sorry for the "problem noise",
Alex

**Comment by andris9** [comment]
Yes, you only need to change these files.

The only real port number requirement is port 25 for incoming mail. For everything else you can use any ports you want as long as you yourself know what ports you are using. Standard ports are only needed when you are trying to hook up an email client (eg. Outlook) to the server and it tries to connect to the "well known" ports first but in most cases there are option to provide a different port.

**Comment by afanjul** [comment]
> The only real port number requirement is port 25 for incoming mail.

@andris9 and do I need incoming mail for anything in mailtrain? I mean, we won't use it for anything but standard smtp and marketing mail, but I don't know if incoming is needed for VERP verification or anything else...

**Comment by andris9** [comment]
If you use VERP for detecting bounces then yes, you need to keep the port 25 open for incoming traffic. If Mailtrain's VERP server is listening on port 25 then it should be safe though, Mailtrain never does anything with these messages besides trying to detect if it is a bounce or not. These messages are not stored or forwarded.

**Comment by witzig** [comment]
> -/opt/mailtrain/config/default.toml

You shouldn't change `default.toml`. Please use `/opt/mailtrain/config/production.toml` instead.

**Comment by witzig** [comment]
@andris9, as a precaution, should we change the default Mailtrain password from **test** to something else, since **admin/test** is certainly on of the first combinations the bots will try?

**Comment by andris9** [comment]
Yeah, it wasn't a problem in the beginning when there were only a few Mailtrain installations but now there's a lot more so having fixed credentials is not so great idea anymore. Not sure about the UI though, the user must somehow see the new password. Or maybe keep using the default pass but require changing it before anything else can be done?

**Comment by witzig** [comment]
Hmm, I can only think of complicated solutions and am not even sure how big of a problem fixed credentials are, if the password were a bit stronger and assuming that people are savvy enough to change the password immediately.

An alternate approach might be to not [create a default user](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/sql/mailtrain.sql#L350) at all. Then checking [here](https://github.com/Mailtrain-org/mailtrain/blob/master/routes/users.js#L15) in no user exists and if so, render a form to create a user which will be authorised by providing the DB password, for example.

**Comment by gkrol-zermelo** [comment]
At least, the install.sh script should generate a random password for the admin user.
