### ISSUE TITLE
DKIM when VERP is enabled

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#212]
Hi @andris9, i've just read this sentence from the mailtrain hompage:

> As ZoneMTA uses envelope sender as the default for DKIM addresses, then if using VERP you need to set up DKIM to your bounce domain instead of sender domain and also store the DKIM key as "bouncedomain.selector.pem" in the ZoneMTA key folder.

And now I'm a bit confused, because I had successfully configured my DKIM with my domain (apart from PTR, SPF, DMARC, etc), and now I don't know if I have to change it (after activating VERP).

I'm afraid that deleting my well establish DKIM domain record (mailtrain.myhost.com) and setting a new one to bounce.mailtrain.myhost.com, it starts to malfunction... could you please give me light on this? 
thanks
Alex

**Comment by andris9** [comment]
I think the wording is not so good. You can add additional DKIM for the VERP domain but you do not have to.

**Comment by afanjul** [comment]
OK! thanks for your clarification, in such a case, there is no problem to add another DKIM.

PS: My confusion came from this: "_need to set up DKIM to your bounce domain instead of sender domain_". 

Thanks
