### ISSUE TITLE
Consider use of ORM

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#213]
The DB access is located to modules under lib/models. These files use MySQL directly. There are a few issues that arose over the time:

- There are no unifying higher-level abstractions for DB access. This leads to quite some duplicit code.

- There has been a question (Issue #2 ) asking for another DB. Having some abstraction over the DB would make it easier to switch DB.

Some suggestions were to use Bookshelf with Knox. 

Would it be a good idea to switch to Bookshelf and Knox or are other ORM to consider? 
Would it be technically possible given some advanced use of the DB that is at some places? 
Do we have expectations how it might impact performance? 
How much would it help in making is easier and more unified to develop new and maintain existing entities (campaigns, lists, etc.)?

**Comment by andris9** [comment]
I did not use an ORM mostly because of custom fields and indexing as I needed fine grained access to indexes in order for the segments to work properly. In general I have nothing against ORMs so if you get one working then I don't have any objections.

**Comment by bures** [comment]
Perfect. I was thinking to give it a try (kind of a pilot) when developing the user management. Since there is not much functionality in the users and it's not any performance critical part, it might be a good area to try it out and then decide whether we keep it or drop it.

Any ideas regarding which particular technology to use? Bookshelf and Knox or anything else?

**Comment by forgeOneHQ** [comment]
Close since it is v1 related. Maybe another  feature we can rethink of it in future.
