### ISSUE TITLE
sender.js does not change user to mailtrain

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#214]
It seems that only the main app changes user to mailtrain.mailtrain. The workers sender.js are spawned before the privileges are dropped and thus retain effective root privileges. Is this intended? If not, we should drop the privileges also in sender.js.

**Comment by andris9** [comment]
This is definitely a bug, the sender process does not need root for anything

**Comment by bures** [comment]
Thanks. I'll fix it once we are done with the pull request.

**Comment by bures** [comment]
This should be fixed in the pull request I made yesterday.
