### ISSUE TITLE
MJML support

### ISSUE THREAD

**Issue by HLFH** [Mailtrain-org/mailtrain#215]
Hi,

Could you support MJML in some way with the default code editor provided by Mailtrain?

Thank you,

**Comment by witzig** [comment]
I don't think that's feasible with Summernote. I'm also not aware of any open source MJML WYSIWYG Editor, although [this reddit comment ](https://www.reddit.com/r/web_design/comments/5pwdxp/making_responsive_html_email_coding_easy_with_mjml/dcvqq6p/?context=3) implies there might be some editors in the making, who knows.

Perhaps the best we could offer is this: https://mjml.io/try-it-live/ ... if there's reasonable demand.

**Comment by HLFH** [comment]
> Perhaps the best we could offer is this: https://mjml.io/try-it-live/ ... if there's reasonable demand.

@witzig It would be fantastic.
The [ESP Mailjet is offering MJML feature on its Passport editor](https://www.mailjet.com/blog/news/passport-integrated-mjml-emails-easier/).
It would be fantastic if Mailtrain could support MJML thanks to [this](https://mjml.io/try-it-live/).

**Comment by bures** [comment]
I was also thinking that this would be a good feature. After all, for a technically experienced person, MJML is probably the quickest way of composing regular newsletters.

**Comment by bures** [comment]
I briefly checked the editor. I'm afraid that what they offer is only the desktop version (https://github.com/mjmlio/mjml-app). The online version is not open sourced.

The MJML desktop app is however nothing else than a local React/Redux-based website shown through a local browser. Theoretically, it should be possible to extract relevant parts from it. But in the end, what makes sense for us is only the editor (CodeMirror in their case) and the preview (which I believe is rendered through standard mjml-core). 

In the same way, we could stitch together the ACE Editor (which is already present in Mailtrain when selecting HTML editor option of the Template) with a preview window. Unfortunately, I could not find MJML highlighting package for ACE. (There is no for CodeMirror either.)

Another problem will be that we will need at least some basic file management. It will be necessary to upload image files. I believe we have some upload functionality already in Mailtrain. But I'm not sure how difficult it would be to use it. Also, we would need some way of deleting / renaming the uploaded files. 

@witzig, @andris9 - Any idea how to manage the files?

**Comment by witzig** [comment]
Yeah, the [editor](https://mjml.io/try-it-live/) itself is not the problem. I even started toying with the idea right after we merged #167, yet didn't have a need/time for it. I also think it's a matter of time until there is a proper open source MJML editor available ([perhaps GrapeJS](https://github.com/artf/grapesjs-preset-newsletter/issues/3)), which would render most of our work obsolete. Then there's the MJML desktop app, copy/paste didn't seem to bad.

> In the same way, we could stitch together the ACE Editor (which is already present in Mailtrain when selecting HTML editor option of the Template) with a preview window.

Still have a branch for this ... and guess the MJML implementation would go along without much effort. 

> Another problem will be that we will need at least some basic file management. It will be necessary to upload image files. I believe we have some upload functionality already in Mailtrain. But I'm not sure how difficult it would be to use it. Also, we would need some way of deleting / renaming the uploaded files.

Currently each editor has its own upload directory. Files uploaded to templates are shared across all templates and campaigns of that editor (conflicts #229), uploads to a campaign are only available to that campaign. When saving, the editorapi resizes all images and generates static versions. Files can't be renamed or deleted.

So, what should we do first? What would solve _your_ issue? An MJML mode, whereby the marketing guys would still be challenged? Or should I put some time in [this](https://gist.github.com/witzig/52ac410f157cb3e1e0696a13b8e51000)?

@bures, what do you need?

**Comment by bures** [comment]
> Or should I put some time in this?
Is that MJML component to generate Mosaico templates? That would be awesome. It would make it easy to prepare custom templates which then could be used by layman users. 

As far as I am concerned, the MJML editor can wait a bit. Anyway, as long as we design it primarily for tech savvy users (somewhat like the HTML editor), it should not be a big deal to create it once someone has time and motivation.

> Files uploaded to templates are shared across all templates and campaigns of that editor (conflicts #229), uploads to a campaign are only available to that campaign.
Good catch about #229. Let's see how to address it. Probably we would need to associate the files with a template and restrict listing them only to those having access to the template.

Anyway, it's still rather far. I started prototyping #229 and #223 today, but any working results are still miles away.

**Comment by witzig** [comment]
> Is that MJML component to generate Mosaico templates?

Yep: https://github.com/witzig/mjml-mosaico

They're working for me, but your mileage may vary.

**Comment by ngarnier** [comment]
Hello guys, Nicolas from the MJML team here! Great to hear you're considering supporting MJML 😄 

MJML is transpiling an XML string (or a [JSON object](https://mjml.io/documentation/#using-mjml-in-json) depending on the format of MJML you want to use, the latter being especially useful to build a MJML structure in a drag and drop interface as JSON is easier to manipulate) server-side and returning responsive HTML as a string, so creating an editor is mostly a matter of: 

1. Getting an MJML input from a user
2. Passing it to the [`mjml2html` function](https://github.com/mjmlio/mjml#inside-nodejs) to transpile MJML to responsive HTML
3. Displaying the rendered HTML returned (probably with an iframe)

As @bures mentioned it, you could totally reuse the logic of the [MJML desktop app](https://github.com/mjmlio/mjml-app). The app is using CodeMirror and as MJML is an xml markup, we can simply leverage CodeMirror features for xml (code highlighting, autocomplete, tag collapsing, etc).

Happy to help if you have any question, feel also free to join us on the [community Slack](https://slack.mjml.io/)!

**Comment by bures** [comment]
Excellent! Looks perfect. I'll give it a try. Thanks.
T.

**Comment by witzig** [comment]
@ngarnier, we're already using MJML for the subscription process/custom forms. Works great and saves so much time. Really can't thank you guys enough for your work and open sourcing MJML. 

Thank you!

---

FYI, @artf is [already working](https://github.com/artf/grapesjs-preset-newsletter/issues/3#issuecomment-301593924) on the GrapeJS-MJML-Plugin. Yay!
