### ISSUE TITLE
Subscribing an existing email reinitializes custom fields

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#218]
Steps to reproduce:
1) create a custom field (e.g. "zone")
2) create a custom forms where "zone" is hidden from subscribe/preferences form
3) subscribe a user with email xyz@example.com
4) go to subscribers and change "zone" of the xyz user to "1"
5) go to subscription form of the list and try to subscribe xyz@example.com
6) click on the confirmation link in the confirmation email 

The result is that the "zone" of the xyz user is empty.

This effectively disallows keeping information hidden from subscribers as this information can get lost.

It seems that the problematic part of the code is in lib/models/subscriptions.js:397-400. Generally, I believe it should be OK to move it down to line 456 to know already if the entry exists or not.

However, I don't fully understand the context of the "!!meta.partial" condition in lib/models/subscriptions.js:397. It is set during import and when subscribing through API. I believe it is there to allow partial updates of existing records.

@andris9, @witzig Do you think it would break anything if I moved the code to 456 and replaced the !!meta.partial condition with "existing" ? And consequently removed the use of "partial" from import and API?

I'm not quite sure about all the corner cases, thus I'm asking.

**Comment by witzig** [comment]
Good catch. It's also applies to default forms.

> However, I don't fully understand the context of the "!!meta.partial" condition in lib/models/subscriptions.js:397. It is set during import and when subscribing through API. I believe it is there to allow partial updates of existing records.

Yeah, I'm not fully sure about this either. Whether it's a new subscription or an update, the API `POST /api/subscribe/:listId` always calls `subscriptions.insert` with the partial flag set, which also seems to have a side effect that default values for empty custom fields don't get set.

The subscription form calls `subscriptions.insert` without the partial flag and therefore setting default values for empty custom fields. The manage preferences form calls `subscriptions.update` which seem to behave the same like `subscriptions.insert ` with the partial flag set.

> @andris9, @witzig Do you think it would break anything if I moved the code to 456 and replaced the !!meta.partial condition with "existing" ? And consequently removed the use of "partial" from import and API?

As far as I see, this change shouldn't break anything and would also set default custom field values for API calls correctly.

- - -

A prominent ESP handles the subscription of existing list members the following:
1. Subscribe with an existing email address: `xyz@example.com is already subscribed to list Testliste. Click here to update your profile`.
2. Notice: `For security, we've sent an email to your inbox that contains a link to update your preferences.`
3. Email: `We received a request to change your subscription preferences for Testliste. [...]`

This is probably the way we wan't to handle these cases, too.

**Comment by andris9** [comment]
The partial option indicates that you want to set the values only for selected fields. For example if you import from CSV and it does not have all possible fields included then you wouldn't unset these fields that are not covered by CSV in case the subscriber already exists, so instead the fields should be merged together. At least this is how it is supposed to work.

**Comment by witzig** [comment]
Fixed with #227. An e2e test is in place.
