### ISSUE TITLE
Selectable unsubscription process

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#219]
We plan to use Mailtrain for public newsletters and also for newsletters inside a non-profit organisation. Our subscribers are far from tech savvy and sometimes they forward the newsletters directly from their mailboxes.

All this leads to several issues:
1) If a subscriber forwards the newsletter on his/her own, they forward it together with the unsubscription link, which typically results into someone else unsubscribing them.

2) The internal newsletters inside the organisation should not be subscribable by public (this is already handled by the pull request #207) and they should not allow direct unsubscription. Rather the unsubscription should go through a superior. The reasoning here is that knowing the information contained in the newsletters is part of the responsibilities of the workers in the organisation. 

For these two cases, we would need more flexibility in how the unsubscription process works. Essentially, I see that a list would allow selection of a unsubscription process:
1) One-step unsubscribe - this is the same as it is now
2) Two-step unsubscribe - this would include confirmation email with a link that has to be clicked in order to complete the unsubscription (this addresses the case 1 above).
3) Manual unsubscribe - clicking the unsubscribe link would go to a page with information whom to contact to get removed from the list (this addresses the case 2 above).

If you are OK with this, I already started extending the subscription functionality to include the cases above. I believe this is one of the features needed in Mailtrain to be able to target more enterprise use-cases.

**Comment by witzig** [comment]
That sounds reasonable to me.

**Comment by andris9** [comment]
I don't have strong preference in this issue, as long as there's a way to unsubscribe it's fine by me.

What about adding an option to not auto-unscubscribe but require manual entry for the email field? So if clicked on an unsubscribe link you would end up in an unsubscribe page but it is not pre-filled. Whatever you enter into it gets unsubscribed.

**Comment by witzig** [comment]
The extended subscription/unsubscription functionality is in Master now.

![Extended subscription/unsubscription](https://cloud.githubusercontent.com/assets/4999980/26661227/cbb8f886-467c-11e7-94cb-5265af2ba6f5.png)
