### ISSUE TITLE
Manage address feature of the subscription functionality leaks out membership in a list

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#220]
If someone tries to change an address to another which is in the list, the system reports that the new address is already registered. This is not a bug, it's a feature. However, it would be nice if the system does not give out this information.

I would suggest that it would issue some generic message as: "Further instructions have been sent to the new email." Then it would either send an email with the confirmation link (like it is now) or an email saying that someone tried to register the email, but the email is already registered.

The same (or similar) message about email already registered could be issued when someone tries to subscribe to the list with an email that is already subscribed. This would be part of the approach suggested by Roger in #218.

If OK, I'll implement it. Anyway, I'm currently refactoring a bit the subscription funcionality - removing some duplicities and implementing #219.

**Comment by witzig** [comment]
That seems a very sensible suggestion to me. Not leaking memberships when subscribing #218, managing, or unsubscribing #221 could be an essential requirement for some lists.

**Comment by andris9** [comment]
Sounds reasonable
