### ISSUE TITLE
Anonymous user can unsubscribe pretty much anyone if he/she knows the email address

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#221]
I'm not sure whether this is a bug or a feature. It seems that an anonymous user can unsubscribe pretty much anyone whose email he/she knows. This is because the unsubscribe form allows filling in an email which is not checked against the email of the one who clicked the link.

Steps to reproduce:

1) subscribe to a list
2) click unsubscribe in an email
3) fill in an address of someone else and click unsubscribe

I think we should change this to make it possible to unsubscribe only the user which the unsubscribe link belongs to.

If OK, I will include the change in the extension of the subscription/unsubscription process that I'm currently working on.

**Comment by witzig** [comment]
Since the unsubscribe form is only accessible with a valid `ucid`, that's definitely a bug. Thanks in advance for the patch.

**Comment by andris9** [comment]
It is hard to say if it's a bug or not because I think this is what you can do with other services as well. Usually you don't need special permissions to unsubscribe, just enter an email address and it's gone.

**Comment by witzig** [comment]
Ok, let's not call this a bug per se, yet I'd still argue it shouldn't be possible at the current URL `/:lcid/unsubscribe/:ucid` which is tied to a specific subscription. Perhaps a generic unsubscribe form at  `/:lcid/unsubscribe` would be more suitable. That URL could also safely be published, analog to the URL of the subscription form.

**Comment by andris9** [comment]
Should the address input field on the unsubscribe form be replaced with a static address text then? If you can only unsubscribe yourself then the input field doesn't make much sense anymore. I'd be fine with such a change.

**Comment by bures** [comment]
Yeah. Actually, I already replaced it with static text in my development version. So we are on the same page.
