### ISSUE TITLE
A subscriber address cannot be changed to an address which has been previously unsubscribed

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#222]
I did not test this, but it seems from the code (lib/models/subscriptions.js:1190) that if an address cannot be changed to an unsubscribed one. 

In order to do so, the SQL statement should additionally contain something as "AND status=1".

Please let me know if this I misunderstood anything. Otherwise, I'll fix it as part of the extension of the subscription mechanism.

**Comment by witzig** [comment]
The email address is a unique index of the subscription tables, so I guess we would have to delete the 'old' membership upon confirmation, then change the address of the 'current' membership.

**Comment by andris9** [comment]
Yes, the old subscription needs to be removed in this case or alternatively changed to something else (_user@address_ -> _removed.randomstring.user@address_) to keep the references in old campaigns.

**Comment by bures** [comment]
It's an interesting idea to rename it to something else. So what is the consensus. Myself, I would vote for removing it. The reasoning here is that if someone changes to address to an unsubscribed entry, then it must be the same guy as before and he/she essentially subscribed again. So, the same way we don't keep history of all unsubscriptions/resubscriptions, we would not keep the history here too.

**Comment by andris9** [comment]
Well, yeah, I guess the old entry can be deleted. There's already a [delete method](https://github.com/Mailtrain-org/mailtrain/blob/master/lib/models/subscriptions.js#L818) for it.

**Comment by witzig** [comment]
Fixed with #222. An e2e test has been added with #227.
