### ISSUE TITLE
Embeded images

### ISSUE THREAD

**Issue by afanjul** [Mailtrain-org/mailtrain#225]
Hi @andris9, is there any posibility (or option) to embed images in mails (like inline attachments)?

If there is no option to do it, and it's relatively easy to add it, what files should I have to "touch" to allow this option? It's relative easy to add this function? I'm a newby in conding node js,  so It's hard for me to find the right spots to touch, but I can try it.

**Comment by andris9** [comment]
Currently all data-url images from HTML are converted to embedded attachments. You can see how it is done [here](https://github.com/Mailtrain-org/mailtrain/blob/d555ca44ac51135c35ec4605ea5f66a10aca7df1/services/sender.js#L365-L372).

**Comment by afanjul** [comment]
Oh I see... sorry I was thinking in RSS Campaings... Could I do it for [the new](https://github.com/Mailtrain-org/mailtrain/commit/d555ca44ac51135c35ec4605ea5f66a10aca7df1#diff-a435cbe918c68828edb401e98832005aR55) image tag? Does make sense?

**Comment by brentkearney** [comment]
> Currently all data-url images from HTML are converted to embedded attachments. You can see how it is done [here](https://github.com/Mailtrain-org/mailtrain/blob/d555ca44ac51135c35ec4605ea5f66a10aca7df1/services/sender.js#L365-L372).

Is there an example somewhere of how to display attached images in the template's HTML?

`<img src="attached-file-name.jpg" alt="my attached image" />`

Thanks!
