### ISSUE TITLE
Hierarchical namespaces

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#229]
To target more enterprise use-cases, it would be good if Mailtrain offered some way of scoping the objects (lists, campaigns, etc.) - this is somewhat similar to Mailchimp's "Folders" and Sendy's "Brands". Generally the idea is that each organizational unit has its own namespace(s) of objects. An entity above the organizational units has access to all the objects below.

This brings two benefits:
- provides way of granting a user access to multiple objects (similar to groups) - this is connected to #223.
- provides a way of grouping and restricting view to only objects belonging to a certain unit (thus making it easier to find anything if there are too many lists, campaigns, etc.)

Additionally (though this shall be a separate issue), it makes a nice concept with which one could associate the public archive of campaigns (similar to Mailchimp's Campaign Archive).

I would see this implemented a tree selector somewhere in the top bar (e.g. left of user dropdown). 

Forms for object creation and edit will be extended by selection of the namespace to which it belongs.

Separately we will have a form with editable tree hierarchy of namespaces.

In relation to #223, a namespace can be shared with a user (similar to how a user can be added to a Gitlab group). Upon sharing, the access level will be specified. The user gets the given access to all objects in the namespace, to all namespaces below it and transitively to all objects in the child namespaces.

The namespace selector will also contain the option "Everything", which will disable filtering by namespace. This will be needed to allow sharing individual campaign with someone not having access to the namespace where the campaign is hosted.

**Comment by bures** [comment]
@andris9, @witzig - I would probably start with this and do it together with #223. They are closely related anyway. 

If OK, I would try Knex and Bookshelf for the namespaces table and permissions. As for the tree editor for namespaces, I was thinking about https://github.com/mar10/fancytree/

Or any other better suggestions?

Thanks.

**Comment by bures** [comment]
Thank you. Having some automated tests would be great. Well, we will have to create the tests, but that could be a gradual process.

**Comment by andris9** [comment]
The initial development version of Mailtrain actually used the same "brand" based sectioning as Sendy, so I wanted it from the start. Back then I was more concerned about development speed though, so I dropped it. I had two weeks between jobs, so I was in a real hurry to get a working version out before I start with the new job. I threw out everything that I initially planned but wasn't essential - brands, user management, unit and integration tests etc.

**Comment by bures** [comment]
@andris9, @witzig - One more question. I was thinking about moving the form processing a bit more to the client. I was thinking to use React to implement the forms for the namespaces and possibly for the user management. It should ease a bit the validation. It would also mean that most of the rendering functionality would go from handlebars to React and that most of the GET/POST endpoints would be AJAX-based.

I would try it initially just for the namespace management. We can then evaluate.
I would like to use the namespace management as a test ground also for Knex and async/await. So this we be like a relatively wholesome trial.

What would be your opinion on this. I'm far from pushing it. It just felt it might make things easier especially when we get to more complex UI.

Thanks.

**Comment by andris9** [comment]
I have no objections about doing more stuff on frond-end. I mostly used back-end because I'm not really good with front-end stuff and it was easier to move functionality to back-end than spending time figuring out how front-end works.

**Comment by witzig** [comment]
@bures, I'm all for it. Would definitely make a lot of things much easier.

**Comment by bures** [comment]
Perfect. Thanks for fast reply. I'll give it a try.

**Comment by bures** [comment]
@andris9, @witzig - Any idea what are the following lines in package.json good for? As far as I understand, the pot file is generated by grunt.

```
    "langs:hbs": "jsxgettext -L handlebars -k translate -o langs/hbs.pot views/layout.hbs views/index.hbs",
    "langs:js": "jsxgettext -o languages/js.pot routes/index.js",
    "langs": "npm run langs:hbs && npm run langs:js",
```

If it's some deprecated relict, I would delete it. Thanks.

**Comment by andris9** [comment]
yes, these can be removed

**Comment by bures** [comment]
Thanks.

**Comment by bures** [comment]
@andris9, @witzig, I have a technological demo ready of how the client could be structured and developed. I did implementation of CRUD operations over Namespaces. (At localhost:3000/namespaces or wherever you host it.) You can find it here: https://github.com/bures/mailtrain/tree/access/client

Note that the namespaces have no effect on anything else. The categorization of resources to namespaces and binding to access control will come later. Now, I just would like your feedback on how the client is structured and how Knex is used.

So, here a few points:

- DB is handled by Knex. I didn't use Bookshelf in the end because it didn't seem to simplify things. It just added another layer of complexity. Knex on the other hand looks useful. It eases the burden of correctly composing the SQL statements and making sure everything is properly escaped. 

- I also tried to Knex migrations. An example could be found in https://github.com/bures/mailtrain/tree/access/setup/knex . It is more expressive than the SQL scripts we have so far. It might make sense to switch over to it, but I'm far from pushing. At this moment, I just set it up that the existing migration infrastructure is used till version 29, then Knex migrations take over. 

- Client is in React. I created a few React components for creating forms and some bootstrap components I needed. I would say we have pretty much most of the components we need. What comes to my mind as something TBD is the DataTable and the ACE editor (or some other text editor).

- I embedded React in the existing HBS generated pages. This is to have a gradual upgrade path where we can refactor one menu item after another. If you go to /namespaces, there is a general route and view, which just serves the React content. All the routing inside /namespaces is handled by React router on the client side.

- I tried to systematize the error handling. So I would suggest the following rules:
  - If an error happens on server (we speak only about REST here), the server always fails with an exception.
  - Client receives the exception, interprets it and reports it to the user in whatever way is appropriate.
  - The server does not try to send explanatory text. It rather sends a specialized exception (located in https://github.com/bures/mailtrain/blob/access/shared/interoperable-errors.js - files in /shared are used both by client and server).

- To support the error reporting further, I implemented a hierarchical error handling in the client. If in a React component annotated with `@withErrorHandling` a method is annotated with `@withAsyncErrorHandler`, it is automatically wrapped in a try-catch, which captures the errors and propagates them through the nesting hierarchy of React components (i.e. through those annotated with `@withErrorHandling`). This enables us to combine case-specific error handlers (like https://github.com/bures/mailtrain/blob/access/client/src/namespaces/CUD.js:137,178) with more generic ones (like https://github.com/bures/mailtrain/blob/access/client/src/lib/page.js:190).

- As you see, I opted for some rather new features in JS to make the coding more fun. So don't be surprised if you find there `@xxxx` (decorators) and `::this.XXX` (binding). If you think it's too much, we can drop it. It would work without as well, just some things would need a bit more clumsier syntax. But no big deal.

Last but not least, to compile the client, you have to go to `client` and run `npm install ; npm run build`.
For development, it's better to run `npm run watch` after the build. It will detect changes in the file and do incremental compilation - so much faster than the `npm run build`.

Let me know your feedback. I will continue then. It should be a bit faster then. I needed some time to put in place all this scaffolding.

Thanks.

**Comment by bures** [comment]
Since the React client goes well beyond namespaces, I moved the React client-related stuff to a separate issue #253. The thread here, I would keep again just for namespaces.

**Comment by andris9** [comment]
Knex looks like a great choice (Y)
