### ISSUE TITLE
How do i show a blank page on the root path.

### ISSUE THREAD

**Issue by ubergeekady** [Mailtrain-org/mailtrain#233]
I want users to see some custom text/html at the root of the domain. Not mailtrain homepage.

**Comment by niyyie** [comment]
Same here! I just setup and tried the script today. Awesome. The homepage is my only issue for now.

**Comment by witzig** [comment]
Showing a blank or custom homepage isn't currently possible out of the box, and it might also be a conflict of interest to implement such a feature (once the React client is done). Depends on Andris.

PS. If you feel adventurous, perhaps [this](https://gist.github.com/witzig/3e1e50daf54a1568e971ba129b6739fe) hackish custom script could work for you (too). You'd need to add it in your config file. Disclaimer: It will obviously break once the markup changes. Use at your own risk.

**Comment by quinncomendant** [comment]
Here's a simpler way to change the content of the Mailtrain home page. Just enter some JS into the *Frontpage shout out* field of the Mailtrain settings that does some DOM replacements. It is required to include the jquery script first so it is available when the script executes. Like @witzig's script, it will also stop working when the markup of the home page changes.

    <script src="/javascript/jquery-2.2.1.min.js"></script>
    <script>
    (function ($) {
        $(document).ready(function() {
            $('.jumbotron h1').text('Company Newsletter').after('<a href="/subscription/XXXXXX">Subscribe here</a> for our newsletter blah blah blah.');
            $('.navbar-brand, body:not(.logged-in) .navbar-nav:not(.navbar-right), .jumbotron p, body > .container, footer').remove();
        });
    }(jQuery));
    </script>

You can see how it looks on [our site](http://lists.burb.tv/).

**Comment by triggeroni** [comment]
@quinncomendant that was extremely useful, worked like a charm for us. Thanks!

**Comment by dafky2000** [comment]
Just a small improvement upon @quinncomendant solution using mostly CSS and modifying the text if javascript is enabled. This eliminates the flashing of the original content and optionally restores the homepage once logged in.

```html
<style>
  body:not(.logged-in) .navbar-header { display: none }
  body:not(.logged-in) .navbar-nav:not(.navbar-right) { display: none }
  body:not(.logged-in)>.jumbotron { display: none }
  body:not(.logged-in)>.jumbotron>.container>p { display: none }
  body:not(.logged-in)>.container { display: none }
  body:not(.logged-in) footer { display: none }
</style>

<script src="/javascript/jquery-2.2.1.min.js"></script>
<script>
(function ($) {
    $(document).ready(function() {
        $('body:not(.logged-in)>.jumbotron h1')
          .text('Company Newsletter')
          .after('<a href="/subscription/XXXXXX">Subscribe here</a> for our newsletter blah blah blah.');
        $('body:not(.logged-in)>.jumbotron').show();
    });
}(jQuery));
</script>
```

Currently with above the original homepage is restored once a user is logged in. You can remove `:not(.logged-in)` throughout if you never want to show the root page content.

**Comment by dafky2000** [comment]
Just a small improvement upon @quinncomendant solution using mostly CSS and modifying the text if javascript is enabled. This eliminates the flashing of the original content and optionally restores the homepage once logged in. If you never want to show the original root page, remove `:not(.logged-in)` throughout.

```html
<style>
  body:not(.logged-in) .navbar-header { display: none }
  body:not(.logged-in) .navbar-nav:not(.navbar-right) { display: none }
  body:not(.logged-in)>.jumbotron { display: none }
  body:not(.logged-in)>.jumbotron>.container>p { display: none }
  body:not(.logged-in)>.container { display: none }
  body:not(.logged-in) footer { display: none }
</style>

<script src="/javascript/jquery-2.2.1.min.js"></script>
<script>
(function ($) {
    $(document).ready(function() {
        $('body:not(.logged-in)>.jumbotron h1')
          .text('Company Newsletter')
          .after('<a href="/subscription/XXXXXX">Subscribe here</a> for our newsletter blah blah blah.');
        $('body:not(.logged-in)>.jumbotron').show();
    });
}(jQuery));
</script>
```
