### ISSUE TITLE
Mailtrain automatically logs me out whenever i refresh zmta-webadmin

### ISSUE THREAD

**Issue by adityasingh007** [Mailtrain-org/mailtrain#234]
Any way to patch this ?

**Comment by andris9** [comment]
This should not happen as these are separate systems. They both keep session data in Redis, so maybe your Redis db is full or something like that? Check what happens in the Redis DB when the logout happens.

**Comment by adityasingh007** [comment]
I suspect it has something to do with browser cookies. I am currently running zmta-admin in incognito. It works that way.

**Comment by andris9** [comment]
Are you running both Mailtrain and zmta-webadmin from the same domain?

**Comment by adityasingh007** [comment]
Yes.

**Comment by andris9** [comment]
I guess that explains it, session cookies are in conflict. Use different domains, eg. subdomains, for different applications and this should resolve the issue.
