### ISSUE TITLE
Is it possible to schedule a campaign to run on a specific date and time?

### ISSUE THREAD

**Issue by snowcoda** [Mailtrain-org/mailtrain#235]
Unless I've missed something, it doesn't seem to be possible to schedule a campaign to run on a specific date and time at the moment (only x hours or x minutes from the time the campaign was saved). Have I missed something? If it's not possible to do this at the moment, is it planned as a feature for future development?

Many thanks

Paul

**Comment by andris9** [comment]
I think that the UI only allows you to delay the sending. Effectively it's the same thing though as Mailtrain converts the delay time to a start time when storing it to the database. Once the start time is reached then campaign is sent out.

I dont' think anyone is working on this. If you'd like to tackle this yourself, then you can start [here](https://github.com/Mailtrain-org/mailtrain/blob/408db13fd45442adb3ada69dc6d59e5d34cc77fd/routes/campaigns.js#L753-L769). The /campaign/send route calculates `scheduled` date from the hours and minutes variables. You could get the input for example from a datetime field and then convert the input to a start date and store it as the `scheduled` value yourself.

**Comment by justinh-rahb** [comment]
I don't understand how this isn't a feature already if Mailtrain internally supports setting a start time... it should be just a GUI addition. I'm not terribly great at programming, but I'm going to have to take a crack at this when time permits, having to setup 20 emails to go off at set times over the next 2 days was not fun at all..

**Comment by forgeOneHQ** [comment]
IN v2 you can plan the start for the sending of the campaign.
