### ISSUE TITLE
Error following manual install (Ubuntu)

### ISSUE THREAD

**Issue by webprofusion-chrisc** [Mailtrain-org/mailtrain#237]
Hi, trying the manual install as per the README via an AWS (LightSail) Ubuntu vm (node v7.10.) gives the following errors:

npm install --production
After editing config/production.toml, running:

NODE_ENV=production npm start
**- module 'mailparser' not found**
npm install mailparser
**- Error: unable to load the node-posix extension module**
npm install posix

At that point I'm onto a MySQL connection error, so that's a different issue.

**Comment by andris9** [comment]
@witzig mailparser requirement comes from 6c35046ab2ba3052c1c621b5b88e0ce2eeb967a4. It should probably be moved to dependencies.

I don't know why posix was not installed as it is listed in optionalDependencies and thus should be installed even if using the `--production` flag.

**Comment by witzig** [comment]
Mailparser dependency has been fixed. Sorry about that.

**Comment by webprofusion-chrisc** [comment]
Thanks! For info, I started out trying the install.sh but it failed at connecting to the DB , after that I tried the manual install steps.

**Comment by witzig** [comment]
@webprofusion-chrisc, were you successful in fixing your MySQL issues? Can we close this?

**Comment by webprofusion-chrisc** [comment]
@witzig sorry, I ran out of time and used mailchimp instead (ouch!). If you're happy the current manual procedure works fine then please do close it.
