### ISSUE TITLE
Throttling not working.

### ISSUE THREAD

**Issue by ady007** [Mailtrain-org/mailtrain#243]
I have set max throttling to 20 per hour. And max connections to 1. Also max messages per connections to 1. I have also set number of sending processes to 1 in the config file. Yet the throttling doesn't seem to work. It sends slowly but not 20 per hour. Something like 300+ a hour. My campaign page is refreshing every x minutes and it sends new mails. I have set throttling in my zone-mta config (1 per minute) and that seems to work fine.

UPDATE -  Campaign pause doesn't work. The delivery counter seems to be increasing on every refresh for like 2+ hours after i paused the campaign. In another instance, it still keeps sending messages to the zone-mta process after i have reset the campaign.

**Comment by adityasingh007** [comment]
I sent a mail some hours earlier setting a speed of 20 per hour. Mailtrain sent about 160 in the first hour (as queued in zone-mta). Then i paused the campaign. It kept on sending for about 3 hours and then stopped at exactly 1000 mails. (The list was larger).

**Comment by witzig** [comment]
@adityasingh007, thanks for reporting this. I'm on it and have a fix ready, yet it needs some more testing.

**Comment by witzig** [comment]
@adityasingh007, a fix for throttling and pausing is in master now. Could you give it a try and confirm it's working? Thanks.

**Comment by adityasingh007** [comment]
Thanks updated. Will update this thread when i send the next mail shot.

Also, can you tell me how do prevent "git pull" from overwriting edits i have done to the code locally ? In services/sender.js i have commented out all the unnecessary headers like Sparkpost , Mailgun and Sendgrid.

**Comment by witzig** [comment]
> Also, can you tell me how do prevent "git pull" from overwriting edits i have done to the code locally ?

Check this: [syncing-a-fork](https://help.github.com/articles/syncing-a-fork/).

May I ask why you remove the Sparkpost , Mailgun and Sendgrid header? I reckon they're unnecessary for your use case, but they don't hurt either.

**Comment by adityasingh007** [comment]
Just because they are unnecessary.
