### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by renantatsuo** [Mailtrain-org/mailtrain#244]
i'm trying to use mailtrain API, i've activated the cors and whilelisted my domain but i'm still getting "No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by witzig** [comment]
What is your "requested resource"? I'm afraid, CORS is only implemented for the subscription widget.

**Comment by renantatsuo** [comment]
i've tried widget and got this error, so i made a simple form with xmlhttprequest and got the same

**Comment by witzig** [comment]
Make sure your CORS config matches your origin exactly. Given the example below, `http://www.example.com`, `https://example.com`, etc. wouldn't match. If the origin doesn't match no "Access-Control-Allow-Origin" will be set.

```
[cors]
# Allow subscription widgets to be embedded
origins=['https://www.example.com']
```

Also make sure to restart Mailtrain after you edit your config.

**Comment by renantatsuo** [comment]
Oh, the error occurs on "confirm-subscription-notice".
What about the API, it should work, right?

**Comment by witzig** [comment]
> i've tried widget and got this error, so i made a simple form with xmlhttprequest and got the same

Just tested the Widget. Works fine for me.

> Oh, the error occurs on "confirm-subscription-notice".

Yeah, no CORS on that route. I guess the API is probably better suited for your needs. Also check #177.

**Comment by HLFH** [comment]
@witzig Same issue, when an email address has already subscribed to a mailing list and that this email is entered again on the subscription widget, I am getting Unexpected end of JSON input on confirm-subscription-notice, and it is a CORS issue. Can it be solved?

**Comment by simevidas** [comment]
> Same issue, when an email address has already subscribed to a mailing list and that this email is entered again on the subscription widget, I am getting Unexpected end of JSON input on confirm-subscription-notice, and it is a CORS issue. Can it be solved?

I’m getting this issue as well.

**Comment by snarlynarwhal** [comment]
I am also getting this issue.

**Comment by simevidas** [comment]
@snarlynarwhal I just edited the widget to show “check your email” even when there’s an error. Couldn’t think of anything better.

<img width="1236" alt="screen shot 2018-12-14 at 10 58 10 pm" src="https://user-images.githubusercontent.com/716405/50029679-e17cfa00-fff3-11e8-9123-5cc1a1f53e5b.png">

**Comment by snarlynarwhal** [comment]
I guess that will have to do until the bug gets fixed, thanks you!
