### ISSUE TITLE
schedule to send mail

### ISSUE THREAD

**Issue by kahidna** [Mailtrain-org/mailtrain#245]
can mailtrain create schedule to send mail?   
say set date or time, when the mailtran should send mail or few mails  
because the only automation options in mailtrain that I've tried only have trigger.

**Comment by andris9** [comment]
You can delay sending a campaign by shifting the start in hours and minutes.

**Comment by kahidna** [comment]
where I can find it? because I can't find scheduling except on automation section.   
and on that section only available in 'day' unit, not in hours and minutes   
I'am using version 1.24

**Comment by witzig** [comment]
@kahidna, you can delay sending a campaign by shifting the start in hours and minutes on the campaign page:

![delay-sending](https://cloud.githubusercontent.com/assets/4999980/26670918/e640a3a2-46b3-11e7-8619-fccfd33861f1.png)

**Comment by kahidna** [comment]
oh my bad,
didn't see that part when try test it   
thank you so much for the help.
