### ISSUE TITLE
Datatables error on sorting

### ISSUE THREAD

**Issue by adityasingh007** [Mailtrain-org/mailtrain#246]
In the "Opened info" section (where you see the list of people who opened the mailer", if you try to sort by time "First Open", it throws a datatables error. On inspecting the network logs - 

```
Request URL:http://DOMAIN.com/campaigns/clicked/ajax/21/-1
Request Method:POST
Status Code:200 OK

{"error":"ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`.`created ASC LIMIT 50 OFFSET 0' at line 1","data":[]}

```
![image](https://cloud.githubusercontent.com/assets/1214214/26675914/3f91bee4-46e3-11e7-8c1f-6b8aa24973e7.png)

**Comment by bures** [comment]
This might be on me. I recently refactored this functionality to remove some code duplications.

I'm unable to test it right now. Are you able to put a debug print in table-helpers.js:114 to check what SQL statememt is it creating? 

Something like `console.log(query);` should probably do.

If not, no problem. I can check myself later.

Thanks,
T.

**Comment by adityasingh007** [comment]
`SELECT SQL_CALC_FOUND_ROWS * FROM subscription__7 JOIN campaign_tracker__21 ON campaign_tracker__21.subscriber=subscription__7.id WHERE 1 AND (campaign_tracker__21.list=? AND campaign_tracker__21.link=?) ORDER BY campaign_tracker__21`.`created ASC LIMIT ? OFFSET ?`

**Comment by bures** [comment]
Could you try it now with the latest commit?

**Comment by adityasingh007** [comment]
Works :)
