### ISSUE TITLE
Feature Suggestion - Duplicate Campaign/Template

### ISSUE THREAD

**Issue by ubergeekady** [Mailtrain-org/mailtrain#247]
I think the ability to copy a campaign / duplicate it, is an essential feature in most email campaign management applications. I have used it multiple times in the past with other tools. Say for example, i want to send the same campaign to multiple lists etc.

**Comment by bures** [comment]
Yes. This feature would be nice indeed. The same for a template.

**Comment by shwaydogg** [comment]
It's nice that duplicate template is now a feature in #344 but duplicate a campaign would also be nice... 

Or am I missing a UX step that would allow this?

**Comment by ansgarsmith** [comment]
Same here: copy campaign would be really effective to have :-)

**Comment by ateuber** [comment]
We could also need the possibility to duplicate a campaign.

**Comment by forgeOneHQ** [comment]
It is already implemented in v2. Please install v2.
