### ISSUE TITLE
Subscription with API and Custom Fields requiring confirmation doesn't work properly.

### ISSUE THREAD

**Issue by flapuente-palbin** [Mailtrain-org/mailtrain#249]
I have been trying to subscribe members using the API, filling some of the custom fields data and requiring user's confirmation.
My problem is that when i open the confirmation link, user is created but custom fields data is lost. I have been checking out in the code how confirmations work and checking data stored at confirmations table and compared with data created when using the Web Subscribe Form. Data structure is different when confirmation is created from API.

Data Structure (Web Form):	
```
{"email":"email@example.com","subscriptionData":{"tz":"Europe/Madrid","address":"","sub":"1496652966226","ucid":"","customSourceHyozbotzb":"test"}}
```
Data Structure (API Call)
`{"email":"email@example.com","customSourceHyozbotzb":"test"}`
	
I think that the problem is at api.js line 128, because confirmation is created using 'subscription' object as 'data' param, which is different from 'routes/subscription.js' line 419 where data used contains:
```
const data = {
    email,
    subscriptionData
};

confirmations.addConfirmation(list.id, 'subscribe', req.ip, data, (err, confirmCid) => {
.......
```

I wonder if there is something else that i am missing. Any clues?

Thanks in advance, 
Fran

**Comment by witzig** [comment]
Hey @flapuente-palbin, thanks for pointing this out. Could you submit a PR for this bug?
