### ISSUE TITLE
Upload directory for template editors

### ISSUE THREAD

**Issue by gramakri** [Mailtrain-org/mailtrain#250]
When you try to upload an image in mosaico, it tries to write to `public/mosaico/uploads`. Same goes for grapejs.

On the Cloudron, mailtrain runs on a read-only filesystem. This means that one cannot write to the code directory. I am wondering what is the best strategy to keep the theme editors updated with every mailtrain release and at the same time preserve the files uploaded by the user. Do you recommend simply making the `uploads` directory of each editor writable? Are there other directories that one needs to make writable? I can investigate further as well based on any pointers you give me.

**Comment by witzig** [comment]
Hi @gramakri. For the editors `public/mosaico/uploads` and `public/grapejs/uploads` have to be writable. Also ImageMagick needs to be able to open URLs.

The Reports feature writes to `protected/reports`.

> I am wondering what is the best strategy to keep the theme editors updated with every mailtrain release and at the same time preserve the files uploaded by the user. Do you recommend simply making the uploads directory of each editor writable? 

I don't know how your update process works, but in case you don't want to make these directories writable I guess you create a symlink or mount in its place?

**Comment by gramakri** [comment]
@witzig Yes, symlinks work. Just wanted to double check if that was the preferred approach. Thanks again.
