### ISSUE TITLE
Unsubscribed counter is not working for campagins

### ISSUE THREAD

**Issue by jablkopp** [Mailtrain-org/mailtrain#252]
After selectable unsubscribe feature, counters for unsubscribed emails in campaigns stopped to work.

Details in PR #251 

I'm not a node.js and I can't write a test for this case, but would be nice if someone can do it.

**Comment by witzig** [comment]
@jablkopp, thanks again for fixing this in #251. What a refreshing experience. 👍

We don't have any tests for campaigns yet, just for the subscription process. We'll write those once @bures is done with some client refactoring.
