### ISSUE TITLE
React-based client

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#253]
The purpose of this task is migrate Mailtrains web-UI to React. This should make it easier to introduce new features with a bit more complex UI. Also it should bring more immediate input validation and overall improved user experience.

**Comment by bures** [comment]
Moving in here from #229:

There is a technological demo ready of how the client could be structured and developed. I did implementation of CRUD operations over Namespaces. (At localhost:3000/namespaces or wherever you host it.) You can find it here: https://github.com/bures/mailtrain/tree/access/client

Note that the namespaces have no effect on anything else. The categorization of resources to namespaces and binding to access control will come later. Now, I just would like your feedback on how the client is structured and how Knex is used.

So, here a few points:

DB is handled by Knex. I didn't use Bookshelf in the end because it didn't seem to simplify things. It just added another layer of complexity. Knex on the other hand looks useful. It eases the burden of correctly composing the SQL statements and making sure everything is properly escaped.

I also tried to Knex migrations. An example could be found in https://github.com/bures/mailtrain/tree/access/setup/knex . It is more expressive than the SQL scripts we have so far. It might make sense to switch over to it, but I'm far from pushing. At this moment, I just set it up that the existing migration infrastructure is used till version 29, then Knex migrations take over.

Client is in React. I created a few React components for creating forms and some bootstrap components I needed. I would say we have pretty much most of the components we need. What comes to my mind as something TBD is the DataTable and the ACE editor (or some other text editor).

I embedded React in the existing HBS generated pages. This is to have a gradual upgrade path where we can refactor one menu item after another. If you go to /namespaces, there is a general route and view, which just serves the React content. All the routing inside /namespaces is handled by React router on the client side.

I tried to systematize the error handling. So I would suggest the following rules:

If an error happens on server (we speak only about REST here), the server always fails with an exception.
Client receives the exception, interprets it and reports it to the user in whatever way is appropriate.
The server does not try to send explanatory text. It rather sends a specialized exception (located in https://github.com/bures/mailtrain/blob/access/shared/interoperable-errors.js - files in /shared are used both by client and server).
To support the error reporting further, I implemented a hierarchical error handling in the client. If in a React component annotated with @withErrorHandling a method is annotated with @withAsyncErrorHandler, it is automatically wrapped in a try-catch, which captures the errors and propagates them through the nesting hierarchy of React components (i.e. through those annotated with @withErrorHandling). This enables us to combine case-specific error handlers (like https://github.com/bures/mailtrain/blob/access/client/src/namespaces/CUD.js:137,178) with more generic ones (like https://github.com/bures/mailtrain/blob/access/client/src/lib/page.js:190).

As you see, I opted for some rather new features in JS to make the coding more fun. So don't be surprised if you find there @xxxx (decorators) and ::this.XXX (binding). If you think it's too much, we can drop it. It would work without as well, just some things would need a bit more clumsier syntax. But no big deal.

Last but not least, to compile the client, you have to go to client and run npm install ; npm run build.
For development, it's better to run npm run watch after the build. It will detect changes in the file and do incremental compilation - so much faster than the npm run build.

Let me know your feedback. I will continue then. It should be a bit faster then. I needed some time to put in place all this scaffolding.

Thanks.

**Comment by witzig** [comment]
> Now, I just would like your feedback on how the client is structured and how Knex is used.

I'm with @andris9 on this one:

> Knex looks like a great choice (Y)

As illustrated by the model and route for namespaces, it's quite relieving to see how much 'noise' can be removed with async/await and Knex alone. So much more readable.

The client looks great too, once I wrapped my head around it. :-) Also the error handling proposal, makes sense.

> I created a few React components for creating forms and some bootstrap components I needed.

Regarding bootstrap components, what's the plan for the UI library in the long run? Would it make sense to use [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) in foresight of an easier migration to Bootstrap 4 (and avoiding to reinvent the wheel)? If so, I guess we would have to remove `bootstrap.min.js` for the `reactEntryPoint` then 'polyfill' the JS for just the navbar. The react-bootstrap components benefiting from @withAsyncErrorHandler would also have to be extended, obviously.

In any case, thumbs up from my side. And a great read all around. Thanks.

**Comment by witzig** [comment]
Regarding DataTables, perhaps two articles which might be of interest to you:
- [Advanced Data Tables in React](https://techblog.commercetools.com/advanced-data-tables-in-react-dbe33f8345ab)
- [Integrating React and (jQuery) Datatables](https://medium.com/@zbzzn/integrating-react-and-datatables-not-as-hard-as-advertised-f3364f395dfa)

**Comment by bures** [comment]
Excellent. Thanks. I'll go on then.

As for react-bootstrap, I originally gave it a try first. (Unfortunately it seems I don't have a sample of it to show you.) U was not satisfied. It was a bit limiting in what options and classes it allowed in the markup it created. In the end, I just ended up doing Mailtrain form components (https://github.com/bures/mailtrain/blob/access/client/src/lib/form.js) via another layer of abstraction which was more like standing in the way than helping. 

The only benefit of react-bootstrap is that they reimplemented the bootstrap JS for Bootstrap JS components. That makes sense, however there are not that many Bootstrap JS components that we would benefit from (Alert, Dropdown, Menu, Modal). I already wrapped Alert and Modal. In the end, it's relatively easy to wrap it in a React component (https://github.com/bures/mailtrain/blob/access/client/src/lib/bootstrap-components.js). 

Another concern was that the project does not seem very active to me. They say they are finalizing it, but it's still alpha with a big notice about potential API changes. They announce they look for help. Overall, it does not seem converging.

I had Bootstrap 4 in my mind too. In the end, my reasoning was that if they are lagging so much with Bootstrap 3, they might not be in position to release anything soon once Bootstrap 4 is out. As we just wrap existing Bootstrap implementation, we should be in more ready position to do the move ourselves. As far as I see, there don't seem to be big API changes in Bootstrap 4.

But of course that's just my gamble. However, we are going to hide most of the bootstrap in forms.js and bootstrap-components.js. This should give us a relatively good layer of abstraction would make it easier to move to react-bootstrap anytime later, once it becomes more mature.

What do you think?

The articles about DataTables seem very helpful. Thanks, I'll take a look.

Thanks a lot guys. On to the DataTables and user-management forms then. :-)

**Comment by witzig** [comment]
Convincing points, thanks.

> I had Bootstrap 4 in my mind too. In the end, my reasoning was that if they are lagging so much with Bootstrap 3, they might not be in position to release anything soon once Bootstrap 4 is out.

And by then reactstrap will probably have taken over anyway. Sometimes I really wish for Kendo UI Core to include some more goodies (especially tree and list views) and that they'd have their React version out by now ...

**Comment by bures** [comment]
Another question. Is it a problem if we upgrade from mysql to mysql2 ? 

The reason is that mysql2 supports {rowMode: 'array'} parameter, which allows one to get around this annoying MySQL issue: https://github.com/tgriesser/knex/issues/61

**Comment by witzig** [comment]
> Is it a problem if we upgrade from mysql to mysql2 ?

Don't know, yet.  If you push a version with mysql2 to your branch `access` i'll take care of the testing and fixing.

**Comment by bures** [comment]
I just completed the port of Reports functionality to ReactJS and Knex. It's in my "access" branch (along with the transition to mysql2).

If you would like to have a look and give your feedback, I would be happy. I think this shows already a good sample of what it would mean to migrate to Knex and ReactJS. It should not have things missing with respect to the functinality present in mailtrain master. I also did some smoke testing, but there will certainly be bugs.

Currently, the ReactJS client is used for anything user/account related:
- /users - user management
- /account - own account management, login/logout, forgotten passwords
- /namespaces - namespace management
- /reports - reports and report templates management

Since this is connected with migration to promise-based interface and Knex, I did a few more things:
- created directory /models to keep promise-based models. On one hand, it felt more in line with the standard ExpressJS layout to have models on the same level as /routers. On the other hand, it was handy to have the promise-based models in another directory to allow them to partially co-exist with the callback-based models in /lib/models. If we proceed with Knex, we would gradually port/rewrite models from /lib/models to /models.

- created directory /routers/rest where the REST endpoints for the React client are kept. In the future, directory /routers can keep primarily the endpoints that serve HTML (i.e. index.html, various handlers for downloading files like /reports/download, etc.)

Generally, we can port it to React gradually. The user should not really see much difference in the UI.

Further I tried to create a few reusable UI components for creating the UI. You've already seen the forms.js module that provides the forms elements and binds them to the component state and integrates it with operations on the server. Here we have newly the ACEEditor and Datatables table and selection. 

Worth noticing might be the Datatables-based dropdown-like control that can be used anytime we need to select from lists, subscribers, etc. You can find an example of it if you create a new report. (To check it, create a new report template for subscribers CSV export and then create a new report for it.). It works like a dropdown, but instead of just displaying a list, it shows the datatable. This has two main advantages: (1) it reuses existing REST API for server-side AJAX for getting data to a datatable, which means that once we display an overview of somethings (like the overview of all lists), we get selection of the same in a form for free, and (2) allows for all the operations like sorting, filtering, paging, etc. It means that the same dropdown can be used for selecting from a few elements or for selecting from something which has thousands of elements.

All this is still missing the permissions and access control. That will be my goal now. But first, I wanted to have somewhat more representative sample of the new UI and models which could be used in doing the permissions.

Thanks for all the feedback.

**Comment by witzig** [comment]
Had some troubles logging in, getting an error from [here](https://github.com/bures/mailtrain/blob/access/client/src/lib/form.js#L61): `this.formHandleChangedError is not a function.` It seems `formHandleChangedError` is a function available on the decorated `Login` class, i.e. it's working for me with this change:

```
await this.props.stateOwner.formHandleChangedError(async () => await this.props.onSubmitAsync(evt));
```

However, it seems very strange you didn't catch this as it's obviously throwing an error for every form.

In any case, it looks really great! I'll take a closer look over the weekend trying to find some bugs. :-)

Thanks!

**Comment by bures** [comment]
Good catch Roger. Your fix is right. You got it exactly. It's always a mystery for me how such silly mistakes can make it through. Obviously, I didn't need to login in my last batch of last minute refactoring. :-)

I pushed the fix.

Thanks for giving it a look.
