### ISSUE TITLE
Cannot save grapejs template

### ISSUE THREAD

**Issue by mfechner** [Mailtrain-org/mailtrain#254]
Hi,

I setup mailtrain on a FreeBSD system with node 7.10.0.
I followed the installation:
https://github.com/Mailtrain-org/mailtrain#manual-install-any-os-that-supports-nodejs

I have a nginx running that is acting as proxy.
I have now a template defined which is using GrapeJS.
But if I try to save the template I get on the logs the following:
```
info HTTP GET /mailtrain-header.png 304 0.310 ms - -
info HTTP GET /grapejs/templates/demo/images/grapesjs-logo.png 304 0.512 ms - -
info HTTP GET /grapejs/templates/demo/images/550x250.png 304 1.198 ms - -
info HTTP GET /grapejs/templates/demo/images/150x150.png 304 1.127 ms - -
info HTTP GET /grapejs/templates/demo/images/250x150.png 304 1.457 ms - -
info HTTP GET /grapejs/templates/demo/images/grapesjs-logo.png 304 0.585 ms - -
info HTTP GET /grapejs/templates/demo/images/550x250.png 304 0.755 ms - -
info HTTP GET /grapejs/templates/demo/images/150x150.png 304 0.879 ms - -
info HTTP GET /grapejs/templates/demo/images/250x150.png 304 1.873 ms - -
info HTTP GET /grapejs/dist/fonts/fontawesome-webfont.woff2?v=4.5.0 304 1.479 ms - -
info HTTP GET /grapejs/dist/fonts/main-fonts.woff?v=20 304 1.432 ms - -
info HTTP GET /editorapi/upload?type=template&id=2&editor=grapejs 304 9.917 ms - -
(node:55868) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
info HTTP POST /editorapi/upload?type=template&id=2&editor=grapejs 200 141.954 ms - 103
info HTTP GET /grapejs/uploads/0/3aaabf0a-22c2-43b9-9f93-3db41e4d8414.jpg 200 2.627 ms - 856773
info HTTP GET /grapejs/uploads/0/3aaabf0a-22c2-43b9-9f93-3db41e4d8414.jpg 304 1.415 ms - -
info HTTP GET /grapejs/uploads/0/3aaabf0a-22c2-43b9-9f93-3db41e4d8414.jpg 304 0.700 ms - -
info HTTP GET /grapejs/uploads/0/3aaabf0a-22c2-43b9-9f93-3db41e4d8414.jpg 304 4.601 ms - -
(node:55868) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): FetchError: request to https://news.fechner.net/editorapi/img?src=http%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Fuploads%2F0%2F3aaabf0a-22c2-43b9-9f93-3db41e4d8414.jpg&method=resize&params=215%2C134 failed, reason: socket hang up

==> /usr/home/http/news.fechner.net/logs/error.log <==
2017/06/13 23:46:00 [error] 64013#101048: *3446 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 88.217.181.100, server: news.fechner.net, request: "POST /editorapi/update?type=template&editor=grapejs HTTP/1.1", upstream: "http://127.0.0.1:3000/editorapi/update?type=template&editor=grapejs", host: "news.fechner.net", referrer: "https://news.fechner.net/grapejs/editor?id=2&type=template"
```
It seems that a promise rejection is not handeled correctly which causes here problem (maybe only the error is not reported back to the browser).

What do I have to do, to get the Save function for the template working?
(it seems I have a similar problem if I use the mosaico editor)

**Comment by witzig** [comment]
`(node:55868) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): FetchError: request to https://news.fechner.net/editorapi/img?src=http%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Fuploads%2F0%2F3aaabf0a-22c2-43b9-9f93-3db41e4d8414.jpg&method=resize&params=215%2C134 failed, reason: socket hang up
`

> It seems that a promise rejection is not handeled correctly which causes here problem (maybe only the error is not reported back to the browser).

It's indeed missing a catch. I'm on it.

> What do I have to do, to get the Save function for the template working?

Your request is using ssl: `FetchError: request to https://news.fechner.net/editorapi[...]`, which doesn't seem to work for me: https://news.fechner.net, so I assume this is the culprit for the timeout. Please also make sure that ImageMagick is installed and able to open URLs.

**Comment by mfechner** [comment]
Hi Roger,

the connection should work, maybe you tested it the moment I configured pm2 to automatically start the node app.
I can confirm that the template with Mosaico is working as expected.
Grapejs does not work.

To reproduce it (tested with current master branch 5647dd040), I just open the standard template (of GrapeJS) and clicked on Save.
The logs I get (from node and nginx are):
```
==> /usr/home/http/news.fechner.net/logs/access.log <==
88.217.181.231 - - [19/Jun/2017:19:58:10 +0200] "GET /grapejs/templates/demo/images/grapesjs-logo.png HTTP/1.1" 304 0 "https://news.fechner.net/grapejs/editor?id=2&type=template" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

==> /root/.pm2/logs/mailtrain-error-0.log <==
info
==> /usr/home/http/news.fechner.net/logs/access.log <==
88.217.181.231 - - [19/Jun/2017:19:58:10 +0200] "GET /grapejs/templates/demo/images/550x250.png HTTP/1.1" 304 0 "https://news.fechner.net/grapejs/editor?id=2&type=template" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

==> /root/.pm2/logs/mailtrain-error-0.log <==
HTTP GET /grapejs/templates/demo/images/grapesjs-logo.png 304 0.937 ms - -
info HTTP GET /grapejs/templates/demo/images/550x250.png 304 1.002 ms - -

==> /usr/home/http/news.fechner.net/logs/access.log <==
88.217.181.231 - - [19/Jun/2017:19:58:10 +0200] "GET /grapejs/templates/demo/images/150x150.png HTTP/1.1" 304 0 "https://news.fechner.net/grapejs/editor?id=2&type=template" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

==> /root/.pm2/logs/mailtrain-error-0.log <==
info HTTP GET /grapejs/templates/demo/images/150x150.png 304 0.756 ms - -

==> /usr/home/http/news.fechner.net/logs/access.log <==
88.217.181.231 - - [19/Jun/2017:19:58:10 +0200] "GET /grapejs/templates/demo/images/250x150.png HTTP/1.1" 304 0 "https://news.fechner.net/grapejs/editor?id=2&type=template" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

==> /root/.pm2/logs/mailtrain-error-0.log <==
info HTTP GET /grapejs/templates/demo/images/250x150.png 304 3.110 ms - -
ERR! editorapi request to https://news.fechner.net/editorapi/img?src=https%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Ftemplates%2Fdemo%2Fimages%2F250x150.png&method=resize&params=249%2C149 failed, reason: socket hang up
ERR! editorapi request to https://news.fechner.net/editorapi/img?src=https%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Ftemplates%2Fdemo%2Fimages%2F550x250.png&method=resize&params=520%2C236 failed, reason: socket hang up
ERR! editorapi request to https://news.fechner.net/editorapi/img?src=https%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Ftemplates%2Fdemo%2Fimages%2Fgrapesjs-logo.png&method=resize&params=67%2C67 failed, reason: socket hang up
ERR! editorapi request to https://news.fechner.net/editorapi/img?src=https%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Ftemplates%2Fdemo%2Fimages%2F150x150.png&method=resize&params=156%2C156 failed, reason: socket hang up
info HTTP POST /editorapi/update?type=template&editor=grapejs 200 150.339 ms - 2

==> /usr/home/http/news.fechner.net/logs/access.log <==
88.217.181.231 - - [19/Jun/2017:19:58:11 +0200] "POST /editorapi/update?type=template&editor=grapejs HTTP/1.1" 200 17 "https://news.fechner.net/grapejs/editor?id=2&type=template" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
```

If I try to access the file manually using the link:
https://news.fechner.net/grapejs/templates/demo/images/250x150.png

I get the image. Is it possible that the application is calling something but does not log an error if it fails?

ImageMagick-nox11-6.9.8.9,1 is installed:
```
convert --version
Version: ImageMagick 6.9.8-9 Q16 amd64 2017-06-09 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib fftw fontconfig fpx freetype jbig jng jp2 jpeg lcms lqr ltdl lzma png tiff webp wmf xml zlib
```

The path the binary is stored is:
```
whereis convert
convert: /usr/local/bin/convert /usr/local/man/man1/convert.1.gz
```

If you need any more information to track this problem, please let me know.
I will do my best to help solving that issue.

**Comment by witzig** [comment]
Hi Matthias,

Could you again try with the latest commit? The image handling has been rewritten, so reverse proxy settings or ImageMagick policy restrictions shouldn't be an issue anymore. 

> after clearing the cache I tested it again and it seems to work now fine.

Hmm, https://news.fechner.net still doesn't work for me with a Browser (tried on different Macs/iPhones and on different Networks). Chrome reports a ERR_SPDY_PROTOCOL_ERROR. It's working fine however when I connect with openssl or curl the url.

**Comment by mfechner** [comment]
Hi Roger,

> Could you again try with the latest commit? The image handling has been rewritten, so reverse proxy settings or ImageMagick policy restrictions shouldn't be an issue anymore.

this looks now good, I get a 200 back:
```
==> /root/.pm2/logs/mailtrain-error-0.log <==
info HTTP GET /editorapi/img?src=https%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Ftemplates%2Fdemo%2Fimages%2F250x150.png&method=resize&params=249%2C149 - - ms - -
info HTTP GET /editorapi/img?src=https%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Ftemplates%2Fdemo%2Fimages%2F150x150.png&method=resize&params=156%2C156 - - ms - -
info HTTP GET /editorapi/img?src=https%3A%2F%2Fnews.fechner.net%2Fgrapejs%2Fuploads%2F0%2F3aaabf0a-22c2-43b9-9f93-3db41e4d8414.jpg&method=resize&params=520%2C325 - - ms - -
info HTTP POST /editorapi/update?type=template&editor=grapejs 200 185.753 ms - 2
```

> Chrome reports a ERR_SPDY_PROTOCOL_ERROR

It seems that chrome does not use http2 but tries it with http1.1 which is not supported by the configuration of the load balancer. I enabled http1.1 to fix this problem.

Thanks for your support, I think the problem is fixed now,
I can change templates with both editors and do not get any errors so far, time to dig deeper into this really cool piece of software!

**Comment by witzig** [comment]
Perfect. And to fully test it you might want to send yourself a test mail (see paper plane icon). The email should only contain static images like `domain.com/mosaico/uploads/static/md5hash.jpg`.

> It seems that chrome does not use http2 but tries it with http1.1 which is not supported by the configuration of the load balancer. I enabled http1.1 to fix this problem.

For me, it was not only Chrome which didn't work, but Safari and Firefox too. I can confirm it's working fine now.

PS. If you find some typos in the german translation, please let me know. I don't think it has been reviewed yet, and there's probably lots of Schreibfehler. :)
