### ISSUE TITLE
Sending triggered mails @ particular point of time in the day.

### ISSUE THREAD

**Issue by manishpal** [Mailtrain-org/mailtrain#256]
Currently a trigger can be set only for X no of days. However thats not optimal, one would like to send emails during a particular time of day. e.g after X days & Y hours.

Is there any other way to achieve this ?

**Comment by witzig** [comment]
> Is there any other way to achieve this?

At this moment, no.

The `triggers` table holds the delay in seconds, so I assume it shouldn't be a problem. But as it requires some UI changes, it's probably not going to happen before #253.
