### ISSUE TITLE
bouncetail.service script not working

### ISSUE THREAD

**Issue by kabads** [Mailtrain-org/mailtrain#257]
I've copied the one from the wiki and am getting this error: 

```
Jun 16 17:13:50 tgmg.email systemd[1]: bouncetail.service: Service hold-off time over, scheduling restart.
Jun 16 17:13:50 tgmg.email systemd[1]: Stopped bouncetail.service.
Jun 16 17:13:50 tgmg.email systemd[1]: Started bouncetail.service.
Jun 16 17:13:50 tgmg.email sh[1182]: nc: port number invalid:
```

I've checked the port number according to the config and they are the same. 
```
[postfixbounce]
# Enable to allow writing Postfix bounce log to Mailtrain listener
# If enabled, tail mail.log to Mailtrain with the following command:
#     tail -f -n +0 /var/log/mail.log | nc localhost 5699 -
enabled=true
port=5699
# allow connections from localhost only
host="127.0.0.1"
```
```
Description=Postfix bounce notifier

[Service]
ExecStart=/bin/sh -c '/usr/bin/tail -F /var/log/mail.log | nc localhost 5699 -'
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by witzig** [comment]
Just tested this, I'm not able to reproduce. Can you try manually, i.e.:

`sudo tail -f -n +0 /var/log/mail.log | nc localhost 5699 -`

Same error? If not, could a [newline mismatch](https://stackoverflow.com/questions/34026806/netcatnc-complain-about-invalid-port) be the culprit?

**Comment by kabads** [comment]
When I try and tail from the command line, it just runs continuously. No errors, but no output either.

**Comment by witzig** [comment]
This is the expected behaviour. So, newline mismatch? The issue seems with your bouncetail.service script.

**Comment by kabads** [comment]
OK - that fixed it. Thanks.
