### ISSUE TITLE
Database Structure - Use One Table For Lists

### ISSUE THREAD

**Issue by programster** [Mailtrain-org/mailtrain#260]
I noticed the other day that there is a separate table for each "list". 

![selection_163](https://user-images.githubusercontent.com/5709838/27384070-657e339c-5685-11e7-83a5-26213c3e62ec.png)

May I recommend that there is only one table that has the same structure as the existing lists, except that it has one additional column called "list_id" which should be an index that is used in the queries for fetching the information you need. 

```
+----------------+---------------------+------+-----+-------------------+----------------+
| Field          | Type                | Null | Key | Default           | Extra          |
+----------------+---------------------+------+-----+-------------------+----------------+
| id             | int(11) unsigned    | NO   | PRI | NULL              | auto_increment |
| list_id        | int(11) unsigned    | NO   | UNI | NULL              |                |
| cid            | varchar(255)        | NO   | UNI | NULL              |                |
| email          | varchar(255)        | NO   | UNI |                   |                |
| opt_in_ip      | varchar(100)        | YES  |     | NULL              |                |
| opt_in_country | varchar(2)          | YES  |     | NULL              |                |
| tz             | varchar(100)        | YES  | MUL | NULL              |                |
| imported       | int(11) unsigned    | YES  |     | NULL              |                |
| status         | tinyint(4) unsigned | NO   | MUL | 1                 |                |
| is_test        | tinyint(4) unsigned | NO   | MUL | 0                 |                |
| status_change  | timestamp           | YES  |     | NULL              |                |
| latest_open    | timestamp           | YES  | MUL | NULL              |                |
| latest_click   | timestamp           | YES  | MUL | NULL              |                |
| created        | timestamp           | NO   | MUL | CURRENT_TIMESTAMP |                |
| first_name     | varchar(255)        | YES  | MUL | NULL              |                |
| last_name      | varchar(255)        | YES  | MUL | NULL              |                |
+----------------+---------------------+------+-----+-------------------+----------------+
```

For example, to get the information for a specific list, you would now just do
```
SELECT * FROM subscription WHERE list_id=3
```

This has two main advantages (in order of importance):
* database migrations are **much** easier as there is one known table to change the structure of. With the current situtation, if you need to change the structure, you need to figure out the name of every table and then run the changes on each table and prey that something doesn't happen half-way through.
* It now becomes easier to perform operations across the lists. For example if I wanted to just perform a dump of all the unique email addresses in all of my lists, generate some statistical reports, or just do a dump of all of the lists in one CSV. 

For columns that you need to be unique to a list, just use combined keys, e.g. If you need emails to be unique to a list, then create unique key `(list_id, email)` etc.

People often decide to partition data into separate tables like this for better performance. Indeed you can use this method to spread your tables across multiple disks (using one file per table setting etc). Also, one often thinks that this has a huge bonus in reducing the size of table scans, however I find that creating the correct indexes more than makes up for this and you generally have to have tables with millions of rows before this becomes a problem.

**Comment by witzig** [comment]
If you throw some custom fields in the mix the subscription tables look like this:

![subscription table](https://user-images.githubusercontent.com/4999980/27384237-7793829a-568e-11e7-832c-d53c30473f5c.png)

Migrations are handled [here](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/sql/upgrade-00014.sql#L5-L12).

I assume Andris had good reason to design it that way but in any case, it doesn't seem like an easy change to me. Not sure if it'd be worth the effort.

**Comment by programster** [comment]
Ok, at least you have a way to perform migrations which is the key thing. 

I guess that there are separate tables to be able to handle custom fields. The alternative (if using a singular table), would be to either have a column called extra_fields that was a JSON type (introduced in 5.7), or a separate table that just handled custom fields. Neither of these alternatives force a 1:1 relationship like the current structure.

**Comment by andris9** [comment]
One of the initial goals I had with Mailtrain was to support huge lists. In my tests the separate table approach seemed to perform better when creating segments based on custom fields over large lists. With a single list table such segments would have meant some really crazy JOINs while the current solution always points to a indexed local field.
