### ISSUE TITLE
Enabling https

### ISSUE THREAD

**Issue by tuck1s** [Mailtrain-org/mailtrain#262]
Simple mods to enable https access, taking standard `install.sh` setup as a starting point, to permit secure running on public servers. Ideally for both UI and webhooks receptors.

**Comment by tuck1s** [comment]
There's a simple strawman version in here https://github.com/tuck1s/mailtrain

**Comment by witzig** [comment]
@tuck1s, nice work regarding [your mods for enabling https access](https://github.com/tuck1s/mailtrain/commit/69158f433955a714eabd2dd9e0eb338d6f458bbd).

Generally, I think the SSL stuff is better handled with Nginx or Apache. In case someone's looking for a tutorial, here's a great [guide for Nginx](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04) using Let's Encrypt.

**Comment by christiangenco** [comment]
Is there any progress on enabling SSL for hosted mailtrain instances? I looked through [the guide for adding SSL to nginx](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04) @witzig posted, but I don't think mailtrain is using nginx on my instance (I don't have a `/etc/nginx/` directory)

**Comment by Wooza42** [comment]
It would be great if mailtrain supports https. I did not manage to get it work with apache2 and mod_proxy, it always says: The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

**Comment by MiBaDK** [comment]
And if you are too lazy, like me, to mess around with SSL config then just use CloudFlare and force SSL under crypto.

![image](https://user-images.githubusercontent.com/27769361/41212292-64f74a74-6d6f-11e8-8539-d7c2c75bb3b4.png)

**Comment by projectsfor** [comment]
Installed mailtrain on subdomain, it's working perfectly until https=true.
SSL generated with certbot and after https=true I have not working **http**://subdomain.domain.com and **https**://subdomain.domain.com loading content from https://domain.com
also by **https**://ip:port I'm getting not protected mailtrain content
by **http**://ip:port - site unavailable
conf file: 

> https=true
> # HTTPS certificate file name
> cert="/etc/letsencrypt/live/mailtrain.domain.com/fullchain.pem" (or cert.pem)
> #cert="cert.pem"
> # HTTPS certificate private key file name
> key="/etc/letsencrypt/live/mailtrain.domain.com/privkey.pem"
> #key="privkey.pem"

apache vhost conf:
 

> SSLEngine On
>         #SSLProtocol all -SSLv2
>         #SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5
>         SSLCertificateFile "/etc/letsencrypt/live/mailtrain.domain.com/fullchain.pem"
>         SSLCertificateKeyFile "/etc/letsencrypt/live/mailtrain.domain.com/privkey.pem"
> 
>          ProxyRequests Off
>         ProxyPreserveHost On
>         AllowEncodedSlashes NoDecode
> 
>         <Proxy *>
>                 Order deny,allow
>                 Allow from all
>         </proxy>
> 
>         ServerName mailtrain.domain.com
>         ServerAlias www.mailtrain.domain.com
>         DocumentRoot /home/folder/public_html/mailtrain
> 
>         ProxyPass / http://ip:port/ nocanon
>         ProxyPassReverse / http://mailtrain.domain.com
>         RequestHeader set X-Forwarded-Proto "https"
>         RequestHeader set X-Forwarded-Port "8443"
> 
>         ErrorLog /home/folder/public_html/mailtrain/error_log.log
>         CustomLog /home/folder/public_html/mailtrain/custom_log.log combined
>
What can be wrong?

**Comment by forgeOneHQ** [comment]
I am closing this issue by now. Bash scripts are available and I think about creating an ansible playbook for deployment of v2.
