### ISSUE TITLE
invalid mailer settings error?

### ISSUE THREAD

**Issue by ajmalkhanjamro** [Mailtrain-org/mailtrain#263]
hello i have configured everything in dns setup like mx and all and but when i change the host name of smtp in mail-train advance settings and check for smtp connection it gives error and when i change port 25 and try t  connect to it  dose not work but both things are open and working on server what is the issue and one more big issue is that i cant import big csv files it always gives same shitty internal server error

**Comment by witzig** [comment]
Hello. What is your setup, how did you install Mailtrain? Did you use [install.sh](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/install.sh)?

> when i change port 25 and try t connect to it dose not work but both things are open and working on server

Can you verify it's working, i.e. with `telnet domain.com 25`? Does that work?

**Comment by ajmalkhanjamro** [comment]
yes i have installed it via install.sh and why is this happening i want to connect to smtp of mailtrain from external software but dose not let me change

**Comment by witzig** [comment]
>  i want to connect to smtp of mailtrain from external software

I'm afraid, but this is out of the scope. I suggest to study [install.sh](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/install.sh) to see how zone-mta has been set up. Please also read the [zone-mta](https://github.com/zone-eu/zone-mta) documentation and beware of misconfiguration, e.g. #209.

**Comment by ajmalkhanjamro** [comment]
thanks buddy for the excellent reply i got your point but i can handle the external smtp misbehave and spam from outside i seen the install.sh file and zonemta  smtp feeder sets to localhost in script i dont know which files to configure for replacing to run on external smtps
