### ISSUE TITLE
Make the list ID changeable

### ISSUE THREAD

**Issue by mfechner** [Mailtrain-org/mailtrain#265]
many filter rules that are running on servers (like sieve) using the header field List-ID to sort email into folders.
If I create a new list in mailtrain the system is generating an automatic List-ID which is also included into the mail sent.

It would be really nice if the List-ID could be changed, so the user can decide in which mail-folder the mail should be sorted on the user site.

**Comment by witzig** [comment]
Doesn't the list.name suffice for that? What would you propose?

```
'List-ID': {
  prepared: true,
  value: libmime.encodeWords(list.name) + ' <' + list.cid + '.' + (url.parse(configItems.serviceUrl).hostname || 'localhost') + '>'
}
```

**Comment by mfechner** [comment]
The List-ID in the mailheader look for example like this:
`List-Id: User questions <freebsd-questions.freebsd.org>`
`List-ID: Testlist <SyNJ_naMZ.news.fechner.net>`

Most of the filters will take the first part inside the id so for first example `freebsd-questions` for second example `SyNJ_naMZ`. The first example is real example from a mailinglist.

I see here two possibilities:

- Add a second field to customize the list-id
I do not think it is nice as that would make it impossible to link the list using the list-id (which is maybe used for tracking, unsubscribe and other actions)

- Make the list-id changeable. It is clear that the list-id must be unique, but that should handle the database already for us (id it is a primary key)

That is the reason why I would like the feature to change the list id.

**Comment by witzig** [comment]
Thanks. That's a sensible request.

My first thought was to add an additional field to `lists/create` to set an optional `cid` (List ID), which couldn't be changed afterwards as it's used for tracking, unsubscribe, etc. However, that would conflict the upcoming namespace feature, see #229, or at least leak information from other namespaces.

According to [RFC2919](https://www.ietf.org/rfc/rfc2919.txt):

```
The syntax of the List-Id header follows:

list-id-header = "List-ID:" [phrase] "<" list-id ">" CRLF

where phrase and CRLF are as defined in [DRUMS]. [...]

Examples:

List-Id: List Header Mailing List <list-header.nisto.com>
List-Id: <commonspace-users.list-id.within.com>
List-Id: "Lena's Personal Joke List"
         <lenas-jokes.da39efc25c530ad145d41b86f7420c3b.021999.localhost>
List-Id: "An internal CMU List" <0Jks9449.list-id.cmu.edu>
List-Id: <da39efc25c530ad145d41b86f7420c3b.052000.localhost>
```

What do you think of this:

`List-ID: Testlist <testlist.SyNJ_naMZ.news.fechner.net>`?

**Comment by mfechner** [comment]
I think that should be a good solution:
`List-ID: Testlist <testlist.SyNJ_naMZ.news.fechner.net>`
That would mean `List-ID: list_name <LOWERCASE(list_name).list_id.fqdn>`.

I think that should not break anything and the mail would be sorted into the right mail folder. Even the send has then control to which folder the mail should be sorted.

Great idea!
