### ISSUE TITLE
invalid mailer settings failed mailer verification?

### ISSUE THREAD

**Issue by ajmalkhanjamro** [Mailtrain-org/mailtrain#266]
hello i was enabling it to work with my own domain configured everything in zonemta and restarted and done everything in mail train also but still it giving same error after checking for mailer config

**Comment by witzig** [comment]
If you installed Mailtrain with the official `install.sh` then there's no need to change the SMTP settings. It will work out of the box and the settings will look like this:

![mailer-settings](https://user-images.githubusercontent.com/4999980/27511760-bc51eae8-592c-11e7-8a9a-ce65142110fe.png)

To verify the password see `/opt/zone-mta/config/production/production.json`, section `api`.

**Comment by ajmalkhanjamro** [comment]
@witzig 
i know it will work out of the box but i want change port to 25 and it will work only only in localhost mode it wont work like with my domain like normal smtps liek mail.domain.com smtps to connect that is what iam trying to do trying to connect to smtp from out side its working fine on localhost

**Comment by witzig** [comment]
Port 25 is only required for incoming mail, e.g. the Mailtrain VERP server.

Assuming you installed Mailtrain with the official `install.sh`, and didn't mess with any configuration, here's what you do to make ZoneMTA accept remote connections:

1. In Mailtrain you leave every setting as shown above. 
2. Edit `/opt/zone-mta/config/production.json` and make the `feeder` listen on `"host": "0.0.0.0"`
3. Restart ZoneMTA with ` service zone-mta restart`
4. Open the firewall for port 2525: `ufw allow 2525/tcp`
5. From a different machine test your smtp server with `telnet domain.com 2525`

You now have an unencrypted SMTP server listening on port 2525 which requires authentication. The username is `mailtrain`, the password can be found in `/opt/zone-mta/config/production.json`, section `api`.

Disclaimer: I take no responsibility for any damage resulting from possible misconfiguration. Given #263, #266 and also [this issue](https://github.com/zone-eu/zone-mta/issues/84) you opened at ZoneMTA, I have an uneasy feeling assisting you on your endeavor.
