### ISSUE TITLE
How can we speed up list import ?

### ISSUE THREAD

**Issue by ady007** [Mailtrain-org/mailtrain#270]
I have been trying to import a CSV file of 75 MB containing 1.5mil records. The importing process is extremely slow ~20 per second. I tripled the instance size (~4 cores , 6 GB RAM), still no luck.

**Comment by andris9** [comment]
List importer uses a single process so allocating more cores does not help. Disabling email validation steps (feature introduced by #187) usually helps though.

**Comment by adityasingh007** [comment]
Email validation is a great feature. I didn't know about this. I used some paid tool to validate emails. I think it should be mentioned on the homepage.

**Comment by adityasingh007** [comment]
If i split up my lists and upload them, will it process them in parallel ?

**Comment by adityasingh007** [comment]
The process seems to have failed. 

![image](https://user-images.githubusercontent.com/1214214/27622753-b4b4f678-5bf6-11e7-9eb8-1b0aa8a6f770.png)

**Comment by witzig** [comment]
> If i split up my lists and upload them separately, will it process them in parallel ?

Not really, as Andris mentioned, the list importer uses a single process.

**Comment by Exmoond** [comment]
wrote small work around for importing (this method is just for emails, other fields you need to add to that example ) around 100k records in 1 minute.you need to have shell access on the server.  login to server shell,  upload your file to the temp folder,  modify file for your needs 

> 
LOAD DATA INFILE '/tmp/test.csv' IGNORE 
INTO TABLE subscription__4 
LINES TERMINATED BY '\n' 
(email)
SET cid = concat(
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(LAST_INSERT_ID())*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1),
              substring('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-', rand(@seed:=floor(rand(@seed)*4294967296))*64+1, 1)
             ), status_change = current_timestamp(), imported = 3;
