### ISSUE TITLE
Using external URL as HTML message

### ISSUE THREAD

**Issue by tomzuu** [Mailtrain-org/mailtrain#271]
When I use external php script as HTML message and If that script contains email address, it is replaced with "[email protected]". Why? Any way to disable that?

**Comment by andris9** [comment]
Do you use cloudflare or similar CDN that modifies web pages? I'd say this is probably an issue on your server side.

**Comment by tomzuu** [comment]
Yes, it's Cloudflare. I have to admit I wasn't aware of their "ScrapeShield" feature. Mailtrain obvioulsy is detected as non human :)
