### ISSUE TITLE
Blacklist either not working or we fail to grasp what it does

### ISSUE THREAD

**Issue by finkbg** [Mailtrain-org/mailtrain#272]
First, of all, absolutely nowhere could we find a description of what the blacklist functionality does. Therefore, we assumed it does what we need - a global unsubscribe list (i.e., whoever is added to the blacklist does not get sent any messages from any campaign). Now we think that probably this is not what this blacklist does, because we cannot get the above described functionality working. Any suggestions or clarifications from anyone who is in the know? Thanks.

**Comment by larrabee** [comment]
Hello. Yep, i wrote this function as global Unsubscribe/Bounce/Complain list. You can manage it through API.  [Original PR](https://github.com/Mailtrain-org/mailtrain/pull/203)

**Comment by finkbg** [comment]
Well, that’s great, but it does not work. Is it supposed to be a complete functionality at this pont?

**Comment by larrabee** [comment]
Yes. At this moment it can not automatically add users (and i not planned implement it), but u can add users via API. You can write custom script what load data from mysql and add users to blacklist via API.

**Comment by witzig** [comment]
Just tested the blacklist feature, it's working fine for me.

However, the blacklist does not apply to transactional mails, only to campaign mails.

**Comment by finkbg** [comment]
Ok, will test again and update.

**Comment by rikmendes** [comment]
I fail to understand how to use it, when you say it's available via the API, can I trigger a user removal/blacklist each time someone unsubscribe ?
