### ISSUE TITLE
How to test/debug bounce handling

### ISSUE THREAD

**Issue by mfechner** [Mailtrain-org/mailtrain#277]
Dear all,

I'm not sure if the issue tracker is the right place to ask questions, but I have not found any mailing list or forum I could use, so hopefully this location is ok to also ask questions.

I'm just in the process to evaluate mailtrain and I really like it.
I tried now to test/configure bounce handling.
I have postfix installed as MTA and added into syslog configuration the line:
```
mail.*                                          "|exec nc localhost 5699 -"
```
This should forward all log messages to mailtrain. The syslogd was reloaded to pick up the configuration.

As next step I edited the file config/production.toml:
```
[postfixbounce]
enabled=true
port=5699
# allow connections from localhost only
host="127.0.0.1"
```
A `netstat -an` showed my that something is now LISTEN in the port.

I added now a none existing email from a server that accepts the email and later (some seconds later) creates a bounce email. So that should be a good start to test it.

The bounce message I get back is:
```
Jul  8 13:06:59 anny postfix/smtp[63764]: Verified TLS connection established to mx00.emig.gmx.net[212.227.15.9]:25: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jul  8 13:06:59 anny postfix/smtp[63764]: 31606C43343: to=<thisaddressshouldreallynotexistandshouldbounce@gmx.de>, relay=mx00.emig.gmx.net[212.227.15.9]:25, delay=0.67, delays=0.11/0.03/0.34/0.19, dsn=5.0.0, status=bounced (host mx00.emig.gmx.net[212.227.15.9] said: 550 Requested action not taken: mailbox unavailable (in reply to RCPT TO command))
Jul  8 13:06:59 anny postsrsd[62062]: srs_forward: <""> not rewritten: No at sign in sender address
Jul  8 13:06:59 anny postfix/cleanup[62061]: D9BF3C43346: message-id=<20170708110659.D9BF3C43346@anny.lostinspace.de>
Jul  8 13:06:59 anny postfix/bounce[63765]: 31606C43343: sender non-delivery notification: D9BF3C43346
Jul  8 13:06:59 anny postfix/qmgr[92336]: D9BF3C43346: from=<>, size=19531, nrcpt=1 (queue active)
Jul  8 13:06:59 anny postfix/qmgr[92336]: 31606C43343: removed
Jul  8 13:06:59 anny dovecot: lmtp(63756): Connect from local
Jul  8 13:06:59 anny dovecot: lmtp(idefix@fechner.net): cLbaNdO8YFkM+QAAdX09IA: sieve: msgid=<20170708110659.D9BF3C43346@anny.lostinspace.de>: stored mail into mailbox 'INBOX'
Jul  8 13:06:59 anny postfix/lmtp[62081]: D9BF3C43346: to=<idefix@fechner.net>, orig_to=<news@news.fechner.net>, relay=anny.lostinspace.de[private/dovecot-lmtp], delay=0.05, delays=0.01/0/0/0.03, dsn=2.0.0, status=sent (250 2.0.0 <idefix@fechner.net> cLbaNdO8YFkM+QAAdX09IA Saved)
Jul  8 13:06:59 anny dovecot: lmtp(63756): Disconnect from local: Successful quit
Jul  8 13:06:59 anny postfix/qmgr[92336]: D9BF3C43346: removed
```

But for a reason I do not understand the message is not displayed in mailtrain as bounce, nor is the email unsubscribed.
If I click into the delivered statistics it says:
![image](https://user-images.githubusercontent.com/5580248/27984857-cb4bd96e-63e0-11e7-9e48-b904aa78a8e9.png)

If I click into the bounced statistics I see:
![image](https://user-images.githubusercontent.com/5580248/27984864-e9314c84-63e0-11e7-96cb-e5c0a2a6d85c.png)

Have I understood something wrong with bounce handling or is this a miss-configuration?

**Comment by witzig** [comment]
According to your delivered statistics the message has been queued as `8D1C2C43339`. The line logging `status=bounced` says `31606C43343` and therefore the [bounce handling here](https://github.com/Mailtrain-org/mailtrain/blob/master/services/postfix-bounce-server.js#L31-L40) will not work.

Perhaps pending PR #269 will resolve your issue. Could you give it a try? Otherwise seeing all logs for `8D1C2C43339` would be necessary.

**Comment by mfechner** [comment]
you are right, PR #269 fixes the problem, so I will close this issue.
