### ISSUE TITLE
ERR! Mail Error: Greeting never received

### ISSUE THREAD

**Issue by flapuente-palbin** [Mailtrain-org/mailtrain#278]
After sending a campaign, in the summary it shows that some members were bounced, but when I try to see whose, there's an empty list, when I check the campaign table at DB I see that the same ammount of members that were shown as bounces have a response like "Greeting never received" and in the server log I see this error:
```
ERR! Mail Error: Greeting never received
ERR! Mail     at SMTPConnection._formatError (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:557:19)
ERR! Mail     at SMTPConnection._onError (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:530:20)
ERR! Mail     at Timeout._greetingTimeout.setTimeout (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:471:22)
ERR! Mail     at ontimeout (timers.js:386:14)
ERR! Mail     at tryOnTimeout (timers.js:250:5)
ERR! Mail     at Timer.listOnTimeout (timers.js:214:5)
```
Any clue of why am i getting this error?

**Comment by flapuente-palbin** [comment]
We decreased **max_connections** number to 5  and **max_messages** to 100 and we restarted the server, the next campaign worked, but we do not really know which of the actions was the one that solved the issue.

**Comment by AyeChanPhyo** [comment]
how did you solve this? I have the same error
