### ISSUE TITLE
How to resend for bounced mails?

### ISSUE THREAD

**Issue by Dexus** [Mailtrain-org/mailtrain#279]
Hello is there a way to resend bounced mails?
I have the problem, that we have filtered some mail address with our firewall and now we would like to resend them...

**Comment by witzig** [comment]
I'm afraid, it's currently not possible to resend bounced emails through the UI. And depending on how the bounce has been processed, the email address might also have been unsubscribed.

**Comment by Dexus** [comment]
I have done it myself, looked to the mails and reset both status. Work as expected after that.

Von meinem iPhone gesendet

**Comment by max-weller** [comment]
Hi,
how did you do it? I need to do the same because many mails were bounced because our server was on a blacklist. Now I need to reset the bounce and send again.

It would also be helpful to have this as a UI feature.
Thanks!

**Comment by Dexus** [comment]
@max-weller 
Hmm, so I just can't remember, but I looked in the database... unfortunately I don't know exactly what I did back then. Think, you have to take a look yourself.

**Comment by hoducha** [comment]
For those who have the same issue, here is what I did.

1. Remove the bounced emails (`status = 3`) in the campaign (in my case is `campaign__2`). You may want to specify the `created` or `updated` date also.
```
DELETE FROM campaign__2 WHERE status = 3 AND created = '2018-11-26 06:18:13';
```

2. Update the campaign bounced number to exclude the bounced emails you've deleted.
```
UPDATE campaigns SET bounced = XXX WHERE id = YYY;
```

3. For the regular campaign, you just continue the campaign to resend emails to the bounced emails. For the triggered campaign, you have to remove the bounced emails from the list and add them back again.

Good luck.

**Comment by equilibrium123** [comment]
The best way could be just to download the list from mailtrain , and upload as subscribes in new list name ,  while deleting the entire old list.

**Comment by ray-moncada** [comment]
> For those who have the same issue, here is what I did.
> 
> 1. Remove the bounced emails (`status = 3`) in the campaign (in my case is `campaign__2`). You may want to specify the `created` or `updated` date also.
> 
> ```
> DELETE FROM campaign__2 WHERE status = 3 AND created = '2018-11-26 06:18:13';
> ```
> 
> 1. Update the campaign bounced number to exclude the bounced emails you've deleted.
> 
> ```
> UPDATE campaigns SET bounced = XXX WHERE id = YYY;
> ```
> 
> 1. For the regular campaign, you just continue the campaign to resend emails to the bounced emails. For the triggered campaign, you have to remove the bounced emails from the list and add them back again.
> 
> Good luck.
 
thank you this helped. You also need to adjust the delivered messages

UPDATE campaigns SET delivered = XXX WHERE id = YYY;

Best,
-Ray
