### ISSUE TITLE
Multiple Users & Delivery Servers?

### ISSUE THREAD

**Issue by iadj** [Mailtrain-org/mailtrain#280]
I want to use one Mailtrain installation for multiple projects. Will there be a feature to support multiple user accounts which can manage their own lists and SMTP settings?

**Comment by bures** [comment]
Actually, it's in (slow) progress. See #229 and #223. 

I didn't think about own SMTP settings. Could you be more specific which settings should be customizable on per-project basis?

**Comment by forgeOneHQ** [comment]
all implemented in v2.
