### ISSUE TITLE
Session always only hold for some minutes...

### ISSUE THREAD

**Issue by Dexus** [Mailtrain-org/mailtrain#281]
Is it possible that the session not use the seconds but use the microseconds?

**Comment by witzig** [comment]
I don't really understand this issue. Could you elaborate a bit?

**Comment by Dexus** [comment]
i only get logged-in for some minute, but in the config it say 30 days... with remember me... dont know why... but i think there is a problem with the session expire... cause of i only get session cookies no cookies that hold for 30 days...

**Comment by witzig** [comment]
Have you set up Redis? It's used for the session store. Otherwise the default MemoryStore will be used and perhaps this is your issue, as MemoryStore is [meant for debugging and developing](https://github.com/expressjs/session#sessionoptions) only.

**Comment by Dexus** [comment]
Yes I use redis.

Von meinem iPhone gesendet

**Comment by witzig** [comment]
Just tested, the session cookie is set correctly and valid for 30 days when using "remember me".

Perhaps you have a conflict with another service? See #234.

**Comment by witzig** [comment]
@Dexus, I assume you've solved this problem. Please reopen if necessary.
