### ISSUE TITLE
hope on this ticket some one solve my issue?

### ISSUE THREAD

**Issue by ajmalkhanjamro** [Mailtrain-org/mailtrain#284]
i am not liking to create ticket again and again spam stuff but please can any body tell me why its happening when i add new ip to pool of zonemta and check mailer settings it fails to connect but when i remove everything and set it default it works what iam missing is their any thing else some where i have change stuff i am new to mail train

**Comment by witzig** [comment]
This is a configuration problem with your MTA and unrelated to Mailtrain.
