### ISSUE TITLE
Custom Forms

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#285]
I'm now refactoring the Lists tab for the React-based client. Since I'm refactoring the routes and models too, I was wondering what is your experiment with custom forms.

In particular, they are currently offered per list, which prohibits sharing them across lists. In my view it would make sense to make them independent of a particular list (i.e. to have a list of all custom forms). My rationale here is that the main reason for form customization is translation or branding. That is something which makes sense to share across lists.

My feeling is that the main reason for having the custom form per list is that the custom form edit screen also allows configuring the  visibility and order of fields. This could however be configured per list separately. Anyway the custom form doesn't deal with the fields individually. Typically, it only includes the handlebars partial that renders the fields as per their specified visibility and order.

@andris9 @witzig  Please, what do you think? I could relatively easily make this extension as part of the new client now.

Thanks. T.

**Comment by witzig** [comment]
Yeah, that would be great! I should have done that right away. :)

**Comment by bures** [comment]
Excellent! 
Thanks a lot for a quick reply. I have it right in front of me, so I'll implement it that way.
T.
