### ISSUE TITLE
Visibility field in Custom fields

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#286]
Please, does anyone of you remember what all the field "Visible" in Custom fields influence?

I saw that it determines whether the field shows as a column in the subscribers list. Is there anything else? 

Thanks. T

**Comment by witzig** [comment]
The "Visible" column defines whether a filed is shown to the subscriber when not using custom forms, otherwise the field is only shown to the Mailtrain Admin. The field visible setting in custom forms takes preference.

> Is there anything else?

No, that's all. As far as I'm aware.

**Comment by andris9** [comment]
It's an additional field that can be used for managing subscribers but that the subscriber itself can not see.

**Comment by alpha1** [comment]
It also seems to indicate whether or not the field can have data imported to it via an admin. This seems like an odd behavior.

**Comment by witzig** [comment]
@alpha1, the issue that hidden custom fields weren't available for CSV import has already been reported (#298) and fixed (8e1bc1d).
