### ISSUE TITLE
Showing 502 bad gateway after campaign set up

### ISSUE THREAD

**Issue by saikat108** [Mailtrain-org/mailtrain#290]
Hi,
I am not a techie, so my request might seem naive.
After setting up the campaign in mailtrain I am getting 502 Bad gateway error.  I don't have my tech team with me, so I need your help.
Thank you

**Comment by witzig** [comment]
@saikat108, if you or your "tech team" haven't already solved this problem, please reopen this issue and attach the relevant error logs. We can't help you otherwise.
