### ISSUE TITLE
Is there a merge tag for `subject`?

### ISSUE THREAD

**Issue by pqvst** [Mailtrain-org/mailtrain#291]
It would be convenient to be able to use a merge tag for the campaigns subject inside the template.

**Comment by andris9** [comment]
Currently there is no such tag. You can see the available tags if you click on the "merge tags reference" button in the template editing.

Why would you want to use the subject in message body? In some A/B testing scenario?

**Comment by pqvst** [comment]
@andris9 For templates. If I'm re-using a template for multiple campaigns (with different subjects) then it would be nice to be able to dynamically insert the subject using a merge tag (similar to what mailchimp does with the <title> tag inside templates).

**Comment by njam** [comment]
Related I would be interested in populating the sender address (and name) using merge tags.
