### ISSUE TITLE
Documenting DKIM setup

### ISSUE THREAD

**Issue by killua-eu** [Mailtrain-org/mailtrain#292]
Hi,

While rewriting maitrain's installation script into an an ansible playbook, I got into setting up DKIM properly. The current documentation isn't really helpful so I added some to the readme of https://github.com/Vaizard/mage-mailtrain. Please feel free to cherry pick what you think is relevant, or let me know and i'll just create a PR on mailtrain's readme myself.

thanks for all the work, P.

**Comment by andris9** [comment]
Hey, that's great. Could you make a PR out of it?

**Comment by killua-eu** [comment]
Done.
