### ISSUE TITLE
What are the credentials at https://mailtrain.org?

### ISSUE THREAD

**Issue by Chigari888** [Mailtrain-org/mailtrain#294]
What are the credentials at https://mailtrain.org? May I log it to as a demo user to check it out?

**Comment by andris9** [comment]
There are no public credentials. You can install your own instance of mailtrain and you'd get exactly the same kind of webpage than mailtrain.org is

**Comment by yyolf117** [comment]
There's no installation file for arch linux. How should I know if I even want to spend my time adjusting the install.sh for arch linux?

**Comment by Chigari888** [comment]
there's no installation file for arch linux. how should I know if I even want to spend my time adjusting the install.sh for arch linux?

**Comment by andris9** [comment]
The installation file is something that helps setting up Mailtrain as a service in a fresh Ubuntu box. To get started you only need MySQL and Node.js installed in your machine. Download mailtrain sources, modify database config file (only need to provide authentication info, mailtrain generates MySQL tables itself) and start it with `npm start`

**Comment by andris9** [comment]
See the [docs](https://github.com/Mailtrain-org/mailtrain#manual-install-any-os-that-supports-nodejs) for setting up Mailtrain in your machine
