### ISSUE TITLE
Use-cases for blacklist

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#295]
With my slow tempo, I got to the blacklist feature. I have some difficulties to figure what would be the right way to have it with permissions and namespaces. Please, could you just throw in the main use-cases for the blacklist? Thanks.

**Comment by larrabee** [comment]
Hello. I create it for blacklist bounce and complaint email addresses. Any users should not be able to send emails to this addresses, because it increase bounce rate and Amazon can ban us.

**Comment by witzig** [comment]
Tomas, seems like this issue isn't needed anymore as you have the [blacklist functionality already committed](https://github.com/bures/mailtrain/commit/9203b5cee7268f92681d671dbe2a77b48adbf47e) to your access branch. Looks great!

**Comment by bures** [comment]
Perfect. Thanks Roger.
