### ISSUE TITLE
Bounce issues with default setup and VERP

### ISSUE THREAD

**Issue by sommarnatt** [Mailtrain-org/mailtrain#297]
Hi!

Got Mailtrain set up on ubuntu 16.04 through the installer script a few days ago and it feels like a nice solid way of sending newsletters etc! Great work! 👍 

Getting some bounce issues where zone-MTA says successfully Queued which gets logged as a delivery in Mailtrain. Right after that, zone-MTA sends it off and get's a 450 error, can't find MX for domain.

SPF, DKIM and DMARC gets a pass. Using the same domain for sender as bounces (hostname of the server which also has MX set up to itself).

Any ideas?

```
Aug 22 13:17:17 newsletter zone-mta[12239]: (Sender/default/12239) 15e091ac6130002871.001 DEFERRED[dns] from=SkyQbFDuW.BkPpltD_Z.rkMrRPKu-@newsletter.xxxxx.com[SkyQbFDuW.BkPpltD_Z.rkMrRPKu-@newsletter.xxxxx.com] to=asdasd23erasd@casfcasc.com mx=casfcasc.com (450 Can't find an MX server for casfcasc.com)
Aug 22 13:17:17 newsletter zone-mta[12239]: (Sender/default/12239) 15e091ac5f30002871.001 DEFERRED[dns] from=SkyQbFDuW.BkPpltD_Z.r1dVAwYuZ@newsletter.xxxxx.com[SkyQbFDuW.BkPpltD_Z.r1dVAwYuZ@newsletter.xxxxx.com] to=adsasd@csdf8afdasd.sae mx=csdf8afdasd.sae (450 Can't find an MX server for csdf8afdasd.sae)
Aug 22 13:33:01 newsletter zone-mta[12208]: (SMTP/feeder/12208) Connection from [127.0.0.1]:47468
Aug 22 13:33:01 newsletter zone-mta[12208]: (SMTP/feeder/12208) Authenticated "mailtrain" from [127.0.0.1][127.0.0.1] using PLAIN
Aug 22 13:33:01 newsletter zone-mta[12208]: (Queue/12208) 15e09b79c630002871 QUEUED (message-id=<c5adfb11-95ed-3807-1c3a-190493ff5ed2@newsletter.xxxxx.com> from=SkyQbFDuW.BkPpltD_Z.Sk6PL5tdW@newsletter.xxxxx.com to=asdf23tsdf@sdfv34tedgf.com source=127.0.0.1 subject="Newsletter test" body=51946 md5=c77f9ac921eb)
Aug 22 13:33:03 newsletter zone-mta[12234]: (Sender/default/12234) 15e09b79c630002871.001 DEFERRED[dns] from=SkyQbFDuW.BkPpltD_Z.Sk6PL5tdW@newsletter.xxxxx.com[SkyQbFDuW.BkPpltD_Z.Sk6PL5tdW@newsletter.xxxxx.com] to=asdf23tsdf@sdfv34tedgf.com mx=sdfv34tedgf.com (450 Can't find an MX server for sdfv34tedgf.com)
```

**Comment by sommarnatt** [comment]
VERP seems to work though, tested it with a SMTP errors uknown user and it gets bounced however it gets logged with SMTP response: `250 Message queued as 15e09c4b6f40002871`

**Comment by andris9** [comment]
There's been a lot of changes in ZoneMTA lately and the install script is not upgraded. I think you'd be better off with another provider, for example Amazon SES or SparkPost.

If you want to continue using ZoneMTA then the errors indicate that the MX DNS is not resolving for whatever reason. Try to resolve it manually from the same server and see if you can do it from command line

    dig mx casfcasc.com

**Comment by andris9** [comment]
Oh, I probably misunderstood your question. If you get a successful delivery in Mailtrain but not in ZoneMTA then it is normal. This happens with any provider, it only means that your message is accepted by the next hop (in your case from Mailtrain to Zonemta). Once ZoneMTA finaly fails to deliver the message (which happens probably in two days) it sends back a bounce to Mailtrain which marks the delivery as bounced.

VERP server is supposed to respond with a success message, otherwise it would mean that the bounce message was not delivered.
