### ISSUE TITLE
'From' header is missing.

### ISSUE THREAD

**Issue by PinGwynn** [Mailtrain-org/mailtrain#299]
Hello,

I've created test campaign with emails in gmail and hotmail. Mailtrain set up for sending emails over my own smtp server, but emails not delivering with this errors:

> Our system has detected that this message is
> 5.7.1 not RFC 5322 compliant:
> 5.7.1 'From' header is missing.
> 5.7.1 To reduce the amount of spam sent to Gmail, this message has been
> 5.7.1 blocked. Please visit
> 5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant
> 5.7.1 and review RFC 5322 specifications for more information.

As I see, I've got emails without From header in BODY. All fields are filled with properly data.

Could you help please.

**Comment by sommarnatt** [comment]
Hi!

I've got From: headers in all my testing emails from mailtrain. Did you set up your campaign with a `Email "from" address` ?
Is your SMTP servers stripping headers for some reason?

**Comment by andris9** [comment]
Missing From: is not normal, try to identify the cause and report back if you detected what is causing it

**Comment by PinGwynn** [comment]
@sommarnatt sure my campaign filled with all this fields.

@andris9 could you advice, how can I catch email body and headers which should be send to smtp from mailtrain before it will be sent ?

**Comment by sommarnatt** [comment]
@PinGwynn Would it be possible for you to try some other SMTP? Or could you perhaps check the body/headers at your own SMTP server? You could for instance try and send to an address that doesn't exist, which should put the whole email in your SMTPs spool for retrying later.

**Comment by PinGwynn** [comment]
I've made research. It looks like issue on my MTA. I've sent several emails to another MTA, and it looks fine. Thank you. Sorry for inconvenience
