### ISSUE TITLE
DKIM Verification Fails

### ISSUE THREAD

**Issue by fridlutz** [Mailtrain-org/mailtrain#302]
Hi,
not sure if this is the right place to ask, please let me know in case it should go somewhere else ...

I am currently testing mailtrain for our internal mailing campaigns and face some issues with respect to DKIM signatures. Can you please point me to the some resources to figure out how to fix it?

A. I am running the docker image of mailtrain -> working
B. I use our own postfix server to send emails -> working, DKIM signature process is handled by postfix
C. Sending emails directly via a client or through applications such as SuperMailer signs the messages correctly - working
D. Sending emails from mailtrain works, **but DKIM signature does not verify** (Google says "FAIL with domain null", appmaildev says "DKIM-Result: fail (bad signature)"
E. Records are correct, and it seems to relate to the way mailtrain interacts with postfix.

Any hints?

Thanks,
Wilfrid

**Comment by sommarnatt** [comment]
D: Can you check the headers of a failed dkim check email and check how the signature looks there? Compare it to when you send it just by postfix.
E: It could be that you're doing something to the headers both at postfix and mailtrain. If there's a dkim signature already from mailtrain then you should skip adding it in your postfix. At least just add it once.

**Comment by theyough** [comment]
@fridlutz 
try to add this in your opendkim.conf file

```
SignHeaders		From, To, Subject, Date, From
RemoveOldSignatures	yes
```

**Comment by witzig** [comment]
@fridlutz, could this be a [mapping problem](https://serverfault.com/a/848091)? Unless you're using VERP, Mailtrain will not add the sender header.

And to clarify, Mailtrain does not DKIM sign any messages. The DKIM section under settings configures only a webhook for ZoneMTA to fetch the keys.

**Comment by witzig** [comment]
Closing for lack of feedback, please reopen if necessary.

**Comment by alen12345** [comment]
I am experiencing the same behaviour by sending emails through my docker-mailserver; DKIM is working via Thunderbird for example but not with Mailtrain.

How can I help you to clarify this issue?

AN

**Comment by stutteringp0et** [comment]
> @fridlutz
> try to add this in your opendkim.conf file
> 
> ```
> SignHeaders		From, To, Subject, Date, From
> RemoveOldSignatures	yes
> ```

These settings fixed the issue in my implementation.  I just added them to the bottom of my opendkim.conf file.
