### ISSUE TITLE
"eeeeee" on the Mailtrain newsletter subscribe form

### ISSUE THREAD

**Issue by quinncomendant** [Mailtrain-org/mailtrain#303]
What is "eeeee"?

![screen shot 2017-09-02 at 17 19 42](https://user-images.githubusercontent.com/6884276/29995256-040bcbbc-9003-11e7-9f14-cf32f554251a.png)

**Comment by sommarnatt** [comment]
Sounds like you've added a custom field to your List named eeee.

**Comment by andris9** [comment]
@quinncomendant Oh, that was a test in Mailtrain newsletter list. Forgot to remov it.
