### ISSUE TITLE
Error reading from bouncetail service: Cannot read property '1' of null

### ISSUE THREAD

**Issue by quinncomendant** [Mailtrain-org/mailtrain#309]
I've setup the postfix "bouncetail" service according to [these](https://github.com/Mailtrain-org/mailtrain/wiki/Processing-bounces-with-Postfix) instructions. It runs fine until mailtrain received a line of log content it cannot process. Mailtrain exits, which in turn causes the bouncetail service to exit.

Here's the full mailtrain logs showing the error with context:

    Sep 13 17:52:49 lists postfix/anvil[2391]: statistics: max connection rate 1/60s for (smtp:208.123.79.59) at Sep 13 17:49:22
    Sep 13 17:52:49 lists postfix/anvil[2391]: statistics: max connection count 1 for (smtp:208.123.79.59) at Sep 13 17:49:22
    Sep 13 17:52:49 lists postfix/anvil[2391]: statistics: max cache size 1 at Sep 13 17:49:22
    Sep 13 17:52:49 lists sh[2420]: /usr/bin/tail: write error: Broken pipe
    Sep 13 17:52:49 lists sh[2420]: /usr/bin/tail: write error
    Sep 13 17:52:49 lists systemd[1]: bouncetail.service: Main process exited, code=exited, status=1/FAILURE
    Sep 13 17:52:49 lists systemd[1]: bouncetail.service: Unit entered failed state.
    Sep 13 17:52:49 lists systemd[1]: bouncetail.service: Failed with result 'exit-code'.
    Sep 13 17:52:59 lists systemd[1]: bouncetail.service: Service hold-off time over, scheduling restart.
    Sep 13 17:52:59 lists systemd[1]: Stopped bouncetail.service.
    Sep 13 17:52:59 lists systemd[1]: Started bouncetail.service.
    Sep 13 17:52:59 lists node[2426]: /opt/mailtrain/services/postfix-bounce-server.js:51
    Sep 13 17:52:59 lists node[2426]:                         queued_as = queued_as[1];
    Sep 13 17:52:59 lists node[2426]:                                              ^
    Sep 13 17:52:59 lists node[2426]: TypeError: Cannot read property '1' of null
    Sep 13 17:52:59 lists node[2426]:     at checkNextLine (/opt/mailtrain/services/postfix-bounce-server.js:51:46)
    Sep 13 17:52:59 lists node[2426]:     at checkNextLine (/opt/mailtrain/services/postfix-bounce-server.js:88:24)
    Sep 13 17:52:59 lists node[2426]: message repeated 3 times: [     at checkNextLine (/opt/mailtrain/services/postfix-bounce-server.js:88:24)]
    Sep 13 17:52:59 lists node[2426]:     at readNextChunk (/opt/mailtrain/services/postfix-bounce-server.js:92:9)
    Sep 13 17:52:59 lists node[2426]:     at Socket.socket.on (/opt/mailtrain/services/postfix-bounce-server.js:100:9)
    Sep 13 17:52:59 lists node[2426]:     at emitNone (events.js:86:13)
    Sep 13 17:52:59 lists node[2426]:     at Socket.emit (events.js:188:7)
    Sep 13 17:52:59 lists node[2426]:     at emitReadable_ (_stream_readable.js:434:10)
    Sep 13 17:52:59 lists sh[2449]: nc: getaddrinfo: Servname not supported for ai_socktype
    Sep 13 17:52:59 lists systemd[1]: mailtrain.service: Main process exited, code=exited, status=1/FAILURE
    Sep 13 17:52:59 lists systemd[1]: mailtrain.service: Unit entered failed state.
    Sep 13 17:52:59 lists systemd[1]: mailtrain.service: Failed with result 'exit-code'.
    Sep 13 17:53:04 lists systemd[1]: mailtrain.service: Service hold-off time over, scheduling restart.
    Sep 13 17:53:04 lists systemd[1]: Stopped Mailtrain server.
    Sep 13 17:53:04 lists systemd[1]: Started Mailtrain server.
    Sep 13 17:53:07 lists node[2455]: info Using local auth
    Sep 13 17:53:08 lists node[2455]: Warning: connect.session() MemoryStore is not
    Sep 13 17:53:08 lists node[2455]: designed for a production environment, as it will leak
    Sep 13 17:53:08 lists node[2455]: memory, and will not scale past a single process.

And here are the postfix log entries during that time:

    Sep 13 17:52:49 lists postfix/anvil[2391]: statistics: max connection rate 1/60s for (smtp:208.123.79.59) at Sep 13 17:49:22
    Sep 13 17:52:49 lists postfix/anvil[2391]: statistics: max connection count 1 for (smtp:208.123.79.59) at Sep 13 17:49:22
    Sep 13 17:52:49 lists postfix/anvil[2391]: statistics: max cache size 1 at Sep 13 17:49:22

Of course the problem can be solved by filtering the lines sent to mailtrain using `grep status=bounced`, but mailtrain should handle input lines more carefully in any case.

Thanks.

**Comment by andris9** [comment]
Are you using the latest version of Mailtrain? I think that issue was already fixed by #305

**Comment by andris9** [comment]
And by "latest version" I mean the version in the master branch.

**Comment by quinncomendant** [comment]
I installed Mailtrain a couple weeks ago using the `install.sh` script. If I run `git show` it say's I'm using commit da6aa7f6b50803ba2cb3949bb580b9969a28f102. How can I see the version number?

BTW, what is the best way to update? Just run `cd /opt/mailtrain && git pull && service mailtrain restart`?

**Comment by quinncomendant** [comment]
BTW, a question: I notice bounce processing happens even before setting up postfix, perhaps via zone-mta. I see one bounce was processed that corresponds to this log entry:

    Sep 13 17:49:05 lists zone-mta[2122]: (Sender/default/2122) 15e7c5bcb1b000a529.001 REJECTED[recipient] from=admin@lists.burb.tv[admin@lists.burb.tv] to=fwkhjef98h4go39geubsrl@gmail.com mx=gmail-smtp-in.l.google.com (550-5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser j23si14063319edh.180 - gsmtp)

How does zone-mta communicate back to mailtrain that the delivery failed? Does it send to tcp port 5699 like the bouncetail service?

**Comment by andris9** [comment]
yes, `git pull && service mailtrain restart` should do it.

Zone-mta pushes bounce info back to Mailtrain through an http api call.

**Comment by andris9** [comment]
Oh, in addition, also run `npm install --production` in the Mailtrain folder as the dependencies might have changed in between

**Comment by quinncomendant** [comment]
Great, thanks.

BTW, it required doing `git pull origin master`.

**Comment by quinncomendant** [comment]
Oh, wait – the `status=bounced` will only occur if I'm using postfix to send mail. I'm using zone-mta. Is postfix bounce processing only useful if I'm sending mail using postfix as the outgoing smtp server?

I was under the (incorrect) assumption that I would setup postfix to receive mail on port 25 and let mailtrain watch the logs when *receiving* the bounce messages (whether or not I had enabled VERP). But if zone-mta is sending the mail, then zone-mta is aware when a message bounces and notifies mailtrain.

There is no reason to setup postfix to receive on port 25 unless I have enabled VERP, right? Or does mailtrain itself listen on port 25 to receive the VERP bounces? The instructions only say, *Mailtrain (v1.1+) is able to use VERP-based bounce handling* but doesn't say if postfix is involved.

**Comment by andris9** [comment]
Don't use both Postfix and ZoneMTA. Mailtrain has a built-in VERP server that you can configure to listen on port 25 to detect external bounces. See [here for config](https://github.com/Mailtrain-org/mailtrain/blob/6aec53d88285f1f0e60ef4957a3498912051322c/config/default.toml#L99-L104). Enabling VERP from the settings (use port 25, not 2525 as the default), gives you additional config options in the web settings page.

**Comment by quinncomendant** [comment]
Thanks, that clears everything up (just copy-paste what you wrote into the read me will surely help others).
