### ISSUE TITLE
How to use the form description in custom form templates?

### ISSUE THREAD

**Issue by quinncomendant** [Mailtrain-org/mailtrain#310]
I've entered text for the description of a Custom Form of a list. How do I use that description in the form templates? I would expect to use`{{description}}` but that doesn't work:

![screen shot 2017-09-14 at 13 38 38](https://user-images.githubusercontent.com/6884276/30419021-9b8465aa-9952-11e7-8398-beda31982421.png)

**Comment by andris9** [comment]
The description field is for own usage only, it is not shown anywhere.
