### ISSUE TITLE
Possibility to make custom field a requirement for subscription

### ISSUE THREAD

**Issue by msbt** [Mailtrain-org/mailtrain#312]
Hi there!
I can't find the option to make (custom) fields a requirement. The only required field on a form is the email address, but I would like people to add at least a first name or a custom field. Is there a way to achieve that or does that not exist yet?

Best regards, M

**Comment by witzig** [comment]
Yes, that would be nice to have but it doesn't exist yet.

**Comment by PabloCastellano** [comment]
I'm interested in implementing it however I'm not familiar with the source code. Can anyone guide me?

**Comment by Addy90** [comment]
This is a "quick and dirty" fix that enables required fields on the fly.
You need to add a form and set it the default form of the list.
Then in that form, add to the "Layout" template the following piece of code at the end before the closing mj-container but after the last mj-raw that imports "subscription_footer_scripts":
```
<mj-raw>
    {{#if isWeb}}
        <script type="text/javascript">
            var mainForm = document.querySelector('form');

            // Override each input field with the required tag, that is needed
            mainForm.querySelector('input[name=first-name]').required = true;
            mainForm.querySelector('input[name=last-name]').required = true;

            document.querySelectorAll('a[href="#submit"]').forEach(function(a) {
                a.onclick = function() {
                    var form = document.getElementById('main-form');
                    if(!form.checkValidity()) {
                        form.reportValidity();
                    } else {
                        form.submit();
                    }
                    return false;
                };
            });
        </script>
    {{/if}}
</mj-raw>
```

The trick is that the required tags are added and that the default form submit behavior is overwritten to include HTML5 element validation. Without JavaScript, the form does not work at all, so it is not a real problem to enable this by script. Of course, somebody could overwrite this behavoir as it is script-side only, but for the moment, this is the best thing I have.

For the widget form, you need the following after the last script-import of the widget.js:
```
<script type="text/javascript">
function ready() {
    var widgetForm = document.querySelector('.mailtrain-subscription-widget form');
    if(widgetForm == undefined) {
        window.requestAnimationFrame(ready);
    } else {
        // Again set the required fields here
        widgetForm.querySelector('input[name=first-name]').required = true;
        widgetForm.querySelector('input[name=last-name]').required = true;
    }
}
ready();
</script>
```

Additional custom fields can be addressed like this:
`widgetForm.querySelector('input[name*=gdpr]').required = true;`
Just add the lines that you need.

**Comment by axelolympe** [comment]
Many thanks @Addy90 You rock

**Comment by GadisDEV** [comment]
this is like #793
for v2 it has to change to 
`
<mj-raw>
    {{#if isWeb}}
        <script type="text/javascript">
            // Needed for IE only, but all browsers accept it
            var forEach = function (array, callback, scope) {
                for (var i = 0; i < array.length; i++) {
                    callback.call(scope, i, array[i]);
                }
            };

            var mainForm = document.querySelector('form');

            // Override each input field with the required tag, that is needed
            mainForm.querySelector('input[name=MERGE_FIRST_NAME]').required = false;
            mainForm.querySelector('input[name=MERGE_LAST_NAME]').required = false;
            mainForm.querySelector('input[name=MERGE_PRIVACY_GDPR]').required = true;

            forEach(document.querySelectorAll('a[href="#submit"]'), function(i, a) {
                a.onclick = function() {
                    var form = document.getElementById('main-form');
                    if(!form.checkValidity()) {
                        // IE does not support the reportValidity method, all other browsers do
                        if(form.reportValidity != undefined) {
                            form.reportValidity();
                        } else {
                            alert('Please fill out all necessary fields.');
                        }
                    } else {
                        form.submit();
                    }
                    return false;
                };
            });
        </script>
    {{/if}}
</mj-raw>
`
