### ISSUE TITLE
Cannot install MJML npm package on Ubuntu 16.04 !

### ISSUE THREAD

**Issue by dmitrirussu** [Mailtrain-org/mailtrain#315]
Vesion of MAIL train 1.24, but that error I get also doing on last version from Master

Cannot install mjml library I get always same error

npm install mjml
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! path /home/dumitru/Documents/www/mailtrain/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/dumitru/Documents/www/mailtrain/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-18T13_30_43_683Z-debug.log

**Comment by dmitrirussu** [comment]
Also when I try to install dependency of mjml -> jsBeautify also fail

npm install js-beautify
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! path /home/dumitru/Documents/www/mailtrain/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/dumitru/Documents/www/mailtrain/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-18T13_35_14_073Z-debug.log

**Comment by witzig** [comment]
Try `npm install js-beautify@1.6.14`. See [here](https://github.com/beautify-web/js-beautify/issues/1247) for more info.

**Comment by dmitrirussu** [comment]
yes installing js-beautify@1.6.14 I have installer MJML, thanks
