### ISSUE TITLE
How to generate a ZoneMTA DKIM API Key

### ISSUE THREAD

**Issue by bbbart** [Mailtrain-org/mailtrain#316]
Hi,

I recently switched from an external SMTP server to using ZoneMTA for my Mailtrain campaigns, in order to get control over the DKIM signing.

ZoneMTA seems to work fine, and I also managed to get zmta-webadmin working, hoping to find a way to create or find the ZoneMTA DKIM API Key Mailtrain is to requiring. I searched the code as well, but couldn't find anything pointing me towards what I need to do to get DKIM working with Mailtrain/ZoneMTA.

I know this is not a 'forum', but I was hoping to find an answer here.

Thank you so much!

**Comment by witzig** [comment]
ZoneMTA uses the plugin `core/http-config` to fetch the DKIM settings from Mailtrain. See [here](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/install.sh#L179-L182) for ZoneMTA config example. And [here's](https://github.com/Mailtrain-org/mailtrain/blob/master/routes/webhooks.js#L290-L330) the corresponding webhook in Mailtrain.

Just generate your own Key, save it under Settings in Mailtrain and in the the ZoneMTA config, then it should work as expected.

**Comment by bbbart** [comment]
Hm... Two questions

1/ I'm having .toml config files, no .js config files. So, I created `config/plugins/http-config.toml` with

    ["core/http-config"]
    enabled=["main", "receiver"]
    url="http://localhost/webhooks/zone-mta/sender-config?api_token=veirengohWoana6yohngi"

Does this make sense?

2/ What is `localhost` supposed to mean in this config file? I tried in my browser with the URLs for mailtrain and zmta-webadmin, but no luck.

Thanks for your help!

**Comment by witzig** [comment]
> 1/ I'm having .toml config files, no .js config files.

Ah yes, there's a different application configuration scheme in ZoneMTA 1.1. Assuming that ZoneMTA and Mailtrain are on the same host, and Mailtrain is listening on port 80, then your config looks good to me.

> 2/ What is localhost supposed to mean in this config file? I tried in my browser with the URLs for mailtrain and zmta-webadmin, but no luck.

The URL is getting POSTed to by ZoneMTA. On your server, try:

```
curl -X POST http://localhost/webhooks/zone-mta/sender-config?api_token=veirengohWoana6yohngi
```

**Comment by bbbart** [comment]
I tried `curl -X POST http://localhost:8083/webhooks/zone-mta/sender-config?api_token=veirengohWoana6yohngi`, since Mailtrain is listening on port 8083 on the server.

The reply was simply `Access denied` and now also sending a Mailtrain campaign fails: `zone-mta[29554]: (Plugins) "HTTP Sender Config" for "smtp:mail_from" failed with: Invalid status code 401`.

Seems like we're making progress, but I'm not sure what the next step is supposed to be...

**Comment by witzig** [comment]
> I tried curl -X POST http://localhost:8083/webhooks/zone-mta/sender-config?api_token=veirengohWoana6yohngi, since Mailtrain is listening on port 8083 on the server. The reply was simply Access denied [...]

Hmm. Is Mailtrain itself really [listening on port 8083](https://github.com/Mailtrain-org/mailtrain/blob/master/config/default.toml#L61)? If so, then surely `curl http://localhost:8083` will yield the homepage, right?

**Comment by bbbart** [comment]
Ah, damnit, you're right! ZoneMTA is listening on port 8083. Sorry it got confusing after a while. :-)

Mailtrain is listening on port 14361 and `curl -X POST http://localhost:14361/webhooks/zone-mta/sender-config?api_token=veirengohWoana6yohngi` returns some JSON with my configured DKIM information.

So far so good. I just sent out a test campaign to two mail addresses, and they are collected by ZoneMTA but at first glance seem to be stuck there in the default queue. It's been three minutes now, whereas before mails were successfully sent immediately.

Anyway, this is a separate issue, not related to Mailtrain, I suppose.

Thanks again for the superb support!

**Comment by witzig** [comment]
Great, and no problem. :) Two things:

1) If `veirengohWoana6yohngi` is your actual DKIM API Key, please change it. We wouldn't want someone to get a hold of your DKIM Private Key. 

2) You might want to configure the ZoneMTA plugin `core/http-bounce` if you haven't already done so. See [here](https://github.com/Mailtrain-org/mailtrain/blob/master/setup/install.sh#L166-L169) for config example.

**Comment by bbbart** [comment]
1. It wasn't the real API key, but thanks! :-)

1. I added http-bounce to the configuration, but to no apparent change now

I'm also singling out the error I'm getting in ZoneMTA (it's related to DKIM), but I'm opening a separate ticket at the appropriate place for that.
