### ISSUE TITLE
install heroku

### ISSUE THREAD

**Issue by GlauberF** [Mailtrain-org/mailtrain#318]
Hello,
I want to install in heroku, can someone explain to me, what steps to perform the installation there in heroku?

**Comment by witzig** [comment]
Heroku has a read-only filesystem if I'm not mistaken. Which means the upload functionality in Mosaico and GrapesJS as well as the Reports feature won't work. If these features don't matter to you, see [this](https://github.com/Mailtrain-org/mailtrain/issues/71#issuecomment-233365835) comment for config example.

**Comment by andris9** [comment]
I’m not sure how easy it would be to get MySQL running in Heroku as they are a Postgres provider

**Comment by witzig** [comment]
Yes, good point. @GlauberF, if you give it a try, choose a MySQL Add-on. See [JawsDB](https://elements.heroku.com/addons/jawsdb) or [ClearDB](https://elements.heroku.com/addons/cleardb).

**Comment by GlauberF** [comment]
do you have any step-by-step instructions on how to install Mailtrain? @andris9 , @witzig

**Comment by witzig** [comment]
1. Clone the repo `git clone git://github.com/Mailtrain-org/mailtrain.git` then `cd mailtrain`
2. Create a file `config/production.js` with the following content and commit it to master.

``` javascript
const url = require('url');
const mysqlParts = url.parse(process.env.CLEARDB_DATABASE_URL);

module.exports = {
    editors: [
        ['summernote', 'Summernote'],
        ['codeeditor', 'Code Editor']
    ],
    log: {
        level: 'error'
    },
    www: {
        port: process.env.PORT || 5000,
        secret: process.env.WWW_SECRET || 'a cat'
    },
    mysql: {
        // MySQL config must be an Object because of https://git.io/vdv4p
        host: mysqlParts.hostname,
        user: mysqlParts.auth.split(':')[0],
        password: mysqlParts.auth.split(':')[1],
        database: mysqlParts.pathname.substr(1),
        port: mysqlParts.port,
        connectionLimit: 10
    },
    redis: {
        enabled: true,
        url: process.env.REDIS_URL,
        db: 0
    }
}
```

3. In the Mailtrain folder, run:

```
heroku create
heroku addons:create heroku-redis:hobby-dev
heroku addons:create cleardb:ignite
heroku addons:create papertrail:choklad
git push heroku master
heroku open
```

4. Log in as `admin` with password `test` (and change the password).

Good luck. :-)

**Comment by liberaltech** [comment]
@witzig  Thanks for the tip 👍  Make sure to also remove the line containing `config/production.*` from the `.gitignore` file or the `production.js` file won't be committed to the master.
