### ISSUE TITLE
Sub-campaigns should honour settings from parent campaign

### ISSUE THREAD

**Issue by anselmh** [Mailtrain-org/mailtrain#319]
### Currently situation:

When using e.g. RSS-Campaigns, I set "Do not track openings" and "Do not track links" in the main campaign. However, when the new sub-campaign of an RSS-entry is created automatically by Mailtrain, these settings don’t get applied to the new campaign.

### Expected situation:

The tracking settings of the parent campaign are respected as otherwise it’s impossible to modify this setting for subsequent campaigns.

**Comment by witzig** [comment]
Thanks for reporting this issue. The tracking settings of the parent campaign are now copied when the sub-campaign is created.

**Comment by anselmh** [comment]
❤️
