### ISSUE TITLE
Wrong - form URL

### ISSUE THREAD

**Issue by codingyannick** [Mailtrain-org/mailtrain#320]
when I embed the Widget I get the wrong URL to my Subscriptio. ist says:

`.../settings/subscription/***/subscribe`

I tested IT ist must be - 

`.../subscription/***/subscribe`

**Comment by witzig** [comment]
Hello @codingyannick, I assume you're talking about the [form action URL](https://github.com/Mailtrain-org/mailtrain/blob/60907c0d860811649fd00856b16d52c87dd739a2/views/subscription/widget-subscribe.hbs#L10) of the rendered subscription widget? If so, please make sure your `serviceUrl` under settings is configured correctly.

**Comment by codingyannick** [comment]
Sorry was my fault 😑 thx for the advise☺️

-- 



YANNICK LANGER

SCHLAGZEUGER · PERCUSSIONIST · COACH · PRODUZENT
Phone: +49 151 40152865 · Web: yannicklanger.de 

lerneschlagzeugspielen.de · buttonbefactory.com · franziskaseidler.com
