### ISSUE TITLE
Confirmation url in text email does not work if ended with "-"

### ISSUE THREAD

**Issue by graabein** [Mailtrain-org/mailtrain#321]
Hello

If the subscriber has text only view in his/her email client, the confirmation url sent to the subscriber will not work if the last sign is "-". This work well in HTML view, but not in text view
Like this:
Yes, subscribe me to this list: https://website.tld/subscription/subscribe/B1H3G-fs- (this ends with "-")

In a text view only email reader it will look like this:
[https://website.tld/subscription/subscribe/B1H3G-fs](https://website.tld/subscription/subscribe/B1H3G-fs)-
The ending "-" will not be part of the hyperlink, the confirmation will fail, and the subscriber will not understand why, get pissed, and walk away from the website :-)

I use Thunderbird email reader in Ubuntu, maybe it will work in other installations?

**Comment by witzig** [comment]
Hello @graabein, thanks for reporting this issue.

@andris9, shall we replace [shortid](https://github.com/dylang/shortid) with [nanoid](https://github.com/ai/nanoid)? See [here ](https://github.com/ai/nanoid/issues/8)for comparison.

**Comment by andris9** [comment]
@witzig I don't mind changing it. I didn't put too much though into it when I originally chose to go with shortid.

**Comment by witzig** [comment]
There's another downside to shortid as the generated ID's may be predictable according to [this comment](https://github.com/dylang/shortid/issues/70), which could prove problematic especially regarding imported lists.

To address this issue and the trailing `-` for the subscription ID's, we could extend the shortid afterwards with some alphanumeric random chars, or perhaps switch to nanoid whereby the character set and key length is up for discussion.

Assuming `A-Za-z0-9` for the character set (to avoid any issues with trailing special chars) and an ID length of 14 (max length of a shortid), the approximated odds of a collision for a list with 100 million existing subscribers are 1 in 2.5 billion, in theory, and if the [formula](https://en.wikipedia.org/wiki/Birthday_problem#Cast_as_a_collision_problem) checks out:

[`d = 62^14; n = 1e+8; 1-((d-1)/d)^(n*(n-1)/2)`](http://www.wolframalpha.com/input/?i=d+%3D+62%5E14;+n+%3D+1e%2B8;+1-((d-1)%2Fd)%5E(n*(n-1)%2F2))

Increase ID length? We could certainly handle the collisions in the code too ...

@andris9, @bures, what do you think?
