### ISSUE TITLE
Can list import be made to preserve unsubscribed status?

### ISSUE THREAD

**Issue by deisner** [Mailtrain-org/mailtrain#325]
We're considering Mailtrain for a newsletter that will have periodic additions to the recipient list via CSV import. I've installed Mailtrain, and it looks like the CSV import clobbers the unsubscribed status field. Is there a way to prevent this, or workaround it somehow?

My concern is that a user who unsubscribes herself may accidentally be added back at a later date.

And by the way, thanks for Mailtrain -- it really looks promising.

**Comment by witzig** [comment]
Yeah, that's a reasonable concern. We can add an additional option to the import screen.

Categorize the imported subscribers as:

- Subscribed – Regular subscriber addresses
- Subscribed (Force) – Regular subscriber addresses, resubscribe users that have unsubscribed
- Unsubscribed – Suppressed emails that will be unsubscribed from your list

**Comment by deisner** [comment]
That was fast. I pulled your commit and it seems to work as expected -- nothing "funny". :^) Danke.

**Comment by witzig** [comment]
Ha! Gern geschehen. :)
