### ISSUE TITLE
Problems with Special characters when when using URL instead of template

### ISSUE THREAD

**Issue by Wolfwood07** [Mailtrain-org/mailtrain#328]
Hi, i'm having problems when using an URL to generate the HTML instead of regular template.
The feature seems working except that special characters like accents (á, é, í ...) are shown as � (both preview and in tha mail).
It does not look like a display browser issue as IE, edge, chrome all the same and inspecting the code shows also �.
I first suspected that origin URL was the problem because of missing encoding, but after making sure to place it in every possible way i could find still does the same. Merge Tag "POST" don't look like the problem as regular text field works fine with special characters. So i suppose now that the problem might be in the "read" function.
While i'm not a proper developer i usually try to find and fix these things by myself and provide the solution, but i'm having trouble finding where in the code is the function/functions for this feature.

**Comment by witzig** [comment]
Looks like an encoding problem on your end. You're using charset utf-8, right?

`Content-Type: text/html; charset=utf-8`

`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`

Start [here](https://github.com/Mailtrain-org/mailtrain/blob/master/services/sender.js#L441-L452) if you want to digg into the code.

**Comment by Wolfwood07** [comment]
I did have the proper meta / Content type defined. But a wrong config in the file editor was the issue.
Thanks.
