### ISSUE TITLE
Can a merge tag only be used once per template?

### ISSUE THREAD

**Issue by anselmh** [Mailtrain-org/mailtrain#329]
Hi, 

I’m using `[RSS_ENTRY_LINK]` 2 times now in my template. The first occurrence is working fine and as expected, however, the 2nd one is not getting converted to the link but stays the merge tag.

Markup is this: `<a href="[RSS_ENTRY_LINK]">Read this letter online.</a>`

**Comment by witzig** [comment]
Hi, and thanks (again) for reporting an issue. All `RSS_ENTRY_*` merge tags are now replaced globally. So this should be fixed.

**Comment by anselmh** [comment]
Thank you for fixing this so fast (again)!
