### ISSUE TITLE
CSV Import is synchronous? Why

### ISSUE THREAD

**Issue by codeforgeek** [Mailtrain-org/mailtrain#331]
So as far as I observer, CSV import process is synchronous? I mean if you upload two Csv files in seperate list, say 3000 records each. It first complete list A import then list B. 

Is there any way we can scale it?

**Comment by andris9** [comment]
Yes, you're right. CSV files are processed one by one. If you want to get the fastest result possible then consider skipping CSV and write directly to MySQL.

**Comment by codeforgeek** [comment]
Well, I guess that won't be scalable either. How about if we use external queues such as RabbitMQ where we can push all CSV data in each message and attach multiple listeners to perform the email validation and database insertion/update?

Any thoughts on same?

**Comment by andris9** [comment]
You could post the contact data coming from a Rabbit queue to the Mailtrain API. You can only post a single contact but you could use a lot of workers that push data in parallel.

**Comment by codeforgeek** [comment]
I am thinking more related to CSV upload and background job. Extending it to become a parallel process. You think queues would help?

I am thinking this way.

1: User uploads CSV and stored in disk and entry to DB is made.
2: Background process run like its running now in every 5000 ms and get the unfinished job.
3: Read all records from CSV using stream and push those messages to the Queue.
4: Put multiple listeners say 4 and prefetch 100 messages at a time, use the same subscription insert() function to add/update in the database.

What do you think?
