### ISSUE TITLE
Import group values in CSV

### ISSUE THREAD

**Issue by davidwindell** [Mailtrain-org/mailtrain#332]
Is it possible (or as a feature request) so allow importing comma separated values into group options.

For example, in the CSV we might have a column called **interests** which has the value for a contact as `option 1,option2`.

We'd then like this to select the relevant group values of our `Interests` checkboxes custom field in Mailtrain.

**Comment by deisner** [comment]
I agree, this would be a nice feature to have.

**Comment by deisner** [comment]
By the way, a workaround is to setup a separate column in your CSV file for each option value, with "Yes" if the option is on for that row, and no value if the option is off. When you import the CSV file in Mailtrain, you then associate each column with the corresponding group option, and it seems to work.
