### ISSUE TITLE
Can't de-select Custom Field checkbox

### ISSUE THREAD

**Issue by vseager** [Mailtrain-org/mailtrain#333]
If a custom field checkbox is selected for a subscriber, you cannot de-select it.

**To reproduce**
* Create checkbox custom field in a list
* Create a subscriber and check the field
* Save subscriber
* Edit subscriber
* Unselect the checkbox
* Save Subscriber

**Expected result**
Subscriber should no longer have checkbox selected.

**Actual result**
Subscriber still has checkbox selected.

**Comment by witzig** [comment]
That's a good catch, thanks a lot for reporting this issue. It should be fixed with the latest commit.
