### ISSUE TITLE
Renaming a custom field makes it impossible to change subscriptions

### ISSUE THREAD

**Issue by killua-eu** [Mailtrain-org/mailtrain#335]
How to reproduce:

- Create some custom checkboxes (/fields/{id})
- Select some /lists/subscription/{id}/edit/{id} for a subscriber
- Edit the checkbox names (/fields/{id})
- Try to unselect selected checkboxes and select unselected ones (/lists/subscription/{id}/edit/{id}) for a subscriber (and fail)

BTW since I had to manually edit the database to work around this, I noticed that the database schema used for custom fields is based on adding columns for every custom filed, i.e. `custom_my_checkbox_no_1_b1yv0wasq`. I didn't do any debugging, but I'd suspect that the problem might to do with these schema changes - while they are technically possible, I'm not sure I'd use such an approach for any of my projects. My JS is weak, so I don't dare to delve into the code and send a PR, but I'd at least like to offer two different approaches from the top of my head that might be relatively simple to implement and maybe open a discussion on the schema?

- either use only unique ids, not the whole optional field name (`b1yv0wasq` instead of `custom_my_checkbox_no_1_b1yv0wasq`)
- or use a single column with a json document instead of multiple per (support for that is available in mysql for some time, but still recent versions are required).

Thanks for all the work, I really enjoy mailtrain.

**Comment by witzig** [comment]
This seems related to #333 and should be fixed. Can you try with the latest commit?

**Comment by killua-eu** [comment]
Oh, by the time I finished submitting this, I guess this became a duplicate of #333

**Comment by killua-eu** [comment]
Yep, will do
