### ISSUE TITLE
Fature request: Custom fields description and reordering

### ISSUE THREAD

**Issue by killua-eu** [Mailtrain-org/mailtrain#336]
I wanted to add different subscription options (custom checkboxes in the subscription form) to create segments. I also needed to describe what each option means, so I added a custom checkbox with a fieldname "SOME OPTION (description of what this selects)". I noticed later, then the whole fieldname gets displayed in the list view, making the whole quite hard to read, so I tried to rename the fields (removed the descriptions) and (hit #335) and hoped to somehow force the description into the form template (and failed). The most reasonable thing seems to me to have an optional description field that gets displayed along with the form element (this is what my request is about). Optionally, being able to reorder the form fields would be great as well.

(If this is possible to achieve otherwise, could you please give me a short explanation or point me to the docs?)

**Comment by witzig** [comment]
> The most reasonable thing seems to me to have an optional description field that gets displayed along with the form element (this is what my request is about).

This seems reasonable to me too. I suggest we add this with the react client (#253).

> Optionally, being able to reorder the form fields would be great as well.

This can currenty only be done with custom forms. In the future this will be easier as @burers has the ordering already improved in the react client.

**Comment by afilp** [comment]
@witzig Hi Roger, where can we review and contribute to (if possible) the React client? Thanks!

**Comment by witzig** [comment]
@afilp, the React Client can be found here: https://github.com/bures/mailtrain/tree/access 

I'm sure Tomas would be more than happy to welcome contributions. It's also still on my to do list … :)
