### ISSUE TITLE
Adding multiple addresses to blacklist at once

### ISSUE THREAD

**Issue by deisner** [Mailtrain-org/mailtrain#339]
It would be nice if I could add multiple addresses to the blacklist at once. I don't think that's possible right now through the web interface (but correct me if I'm wrong).

Can I just add them directly to the 'blacklist' mysql table? Or would it be better to repeatedly use the /api/blacklist/add API method?

Thanks.

**Comment by witzig** [comment]
> It would be nice if I could add multiple addresses to the blacklist at once.

We might implement this feature after merging the React Client (#253).

> Can I just add them directly to the 'blacklist' mysql table?

Sure, that's how it's done. See [here](https://github.com/Mailtrain-org/mailtrain/blob/c9136f8abd1c4c1eb08615fcbd47ea6d1d9c51fb/lib/models/blacklist.js#L31-L47).

**Comment by deisner** [comment]
Thanks. That's what I'll do for now, then.
