### ISSUE TITLE
CustomFields

### ISSUE THREAD

**Issue by jonathangilpin** [Mailtrain-org/mailtrain#346]
hi Forgive me if this is the wrong place.. this may not be a bug but more of a lack of understanding on my part..

I wish to use segmentation for a list of 120,000 email addresses.
Each of these email addresses owns a number of planes.

I have 514 unique models and 65 unique 'makes'(brands)
Each Brand has a number of models. e.g. there are 30 Boeing Models.

1. Is there a way I can sub-segment the models under each brand? 
2. Using Custom Field options adding a model checkbox adds a new column to the subscriber table, would have 600 columns be a problem for the functionality of the software?

The goal here is to be able to sent an email to people owning a particular model and also a particular make. This means I need to be able to select boeing or a subcatagory of boeing e.g. 747.

Can anyone point me in the right direction or tell me where to send this request for advice?

Jonathan

**Comment by gkrol-zermelo** [comment]
You can probably use a text field, and add all makes/models. Like "Boeing 777-300ER,Airbus A380-900" (comma separated). When you want to send mail, create a segment using the % wildcard search options. Like "%Boeing%" for everyone having a Boeing plane, "%Boeing 777%" for Boeing 777 owners, and finally "%Boeing 777-300ER%" for people with that specific model.

I haven't yet used this in practice, but I expect it to work fine.

**Comment by jonathangilpin** [comment]
Thanks a lot for the feedback, I will give this a try
