### ISSUE TITLE
GDPR Compliant?

### ISSUE THREAD

**Issue by Jab2870** [Mailtrain-org/mailtrain#347]
As anyone living inside the EU should know, GDPR is a set of new Privacy Laws that are coming into force in May next year. Read about it here: http://www.eugdpr.org/

Is Mailtrain compliant?

**Comment by andris9** [comment]
In general, GDPR affects companies not software. You can either use Mailtrain in a GDPR compliant way or not. For example users can unsubscribe but can not delete their data. They can though make a request to you as the site owner to delete their data and the site admin can delete subscribers. Mailtrain stores all user data in a single MySQL database, you would have to do manual data export in case an user requests it, there is no built in feature for this. You own and control the database, so you can do whatever you want with it even if Mailtrain does not directly provide the features needed for GDPR compliancy.

**Comment by Jab2870** [comment]
Thanks for your quick response, I think you have answered most of my concerns but I am still interested in the issue of pseudonymisation / anonymization.  Does mailtrain do this out of the box?

**Comment by andris9** [comment]
Mailtrain allows to disable usage tracking per campaign, so if a subscriber opens a message or clicks on links then these actions are not stored by Mailtrain. Nothing special is done with user data, whatever the subscribers enter to the signup form is stored to the database. Subscribers can later edit though their profile information (including email address) and previous versions of that data is not stored
