### ISSUE TITLE
To enable merge tags in Email "from name" Email "from" address

### ISSUE THREAD

**Issue by mailfromabox** [Mailtrain-org/mailtrain#350]
Hi,

How can I enable merge tags in the Email "from name" Email "from" address field.

I would really need that feature because I need to send the campaign to each subscriber from a specific address, so I have my mail server setup with one smtp user who can send (relay) as other users. (so I would like to upload the from name and from email as custom fields.

Anybody has an idea, or some code?

Thank you

**Comment by robertdebret** [comment]
I changed the input type from email to text to disable client side form validation, I was really hoping the merging function was also enabled on the email from fields, I am very new t node.js, I have not been able to find where the merging happens in the code.

Anybody has any suggestion?
