### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gramakri** [Mailtrain-org/mailtrain#353]
It seems it's been a while since a new release was tagged. Just checking if there any plans to do so and if we should consider using master since there seem to be a lot of fixes since the last release.

Thanks!

**Comment by njam** [comment]
@bures it would be great to have a new release available, to make use of some recent improvements. The last release 1.24.0 is more than a year old.
What do you think about creating a new tag 1.25.0? Or is there something blocking a new release?

**Comment by bures** [comment]
No problem on my side. Just I'm completely focus on Mailtrain 2 and didn't 
have time to properly test the recent improvements. If you tested it and 
can stand behind it, I'll be happy to tag any commit you tell me.

Thanks. T.

**Comment by gramakri** [comment]
@bures Thanks!

Cloudron's current app package is based off eb8a5878dda1b2573fde3e8ee033747266058670. We do have automated tests for package updates, so I am currently running them with the latest master to check if things will update fine. If it does, maybe we can tag the current master.

I didn't know about mailtrain 2, awesome! Is there any more information about it?

**Comment by gramakri** [comment]
It looks like LDAP auth broke in master, investigating.

**Comment by gramakri** [comment]
@bures OK, that was caused by https://github.com/Mailtrain-org/mailtrain/pull/444. I was able to update to latest master from the previous release. Can we tag dcf83309294eee6cdaefd312b8b8c1c92d7ab71f as a new release with the release note that the LDAP configuration has changed (there is a single url parameter now instead of host/post like before)?

**Comment by bures** [comment]
Done. See https://github.com/Mailtrain-org/mailtrain/releases/tag/v1.24.1

**Comment by bures** [comment]
And thanks for testing it.
