### ISSUE TITLE
Instance freezes immediately after install script completes.

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#359]
I installed mailtrian via the install script three times today on a t2.micro instance on AWS, as root, and each install reaches the 'success!' message, before the instance immediately crashes. 

I saw an 'out of memory' error in the terminal the second time, but generally things freeze up almost straight away, so there's little time to see what's running. 

After that i can't ssh into the instance with another session, and I end up having to terminate the instance.

Example:

```
Success! Open http://ec2-34-230-71-207.compute-1.amazonaws.com/ and log in as admin:test
root@ip-172-30-0-113:/home/ubuntu# ^C
root@ip-172-30-0-113:/home/ubuntu# ls
root@ip-172-30-0-113:/home/ubuntu# lsdf
ps -aux
free -m
blah
```

**Comment by bradzo** [comment]
+1

I can't ssh into the EC2 t2.micro instance after installing Mailtrain, and after stopping and starting the instance.

I stopped it, upgraded the instance to t2.small, and all is good!

So before you run the install script, ensure you're running a t2.small instance if on AWS.
