### ISSUE TITLE
grapeJS MJML editor self-closing tags bug

### ISSUE THREAD

**Issue by mattmoesen** [Mailtrain-org/mailtrain#360]
Hello,

is there workaround for the known bug with self-closing tags in the grapeJS MJML editor?
This is most of the time a problem with the mj-image tag and other elements (mj-text, mj-button) following in the same mj-column.

The problem was explained in detail in this issues:
https://github.com/Mailtrain-org/mailtrain/issues/334
https://github.com/artf/grapesjs-mjml/issues/10#issuecomment-330652563

For sure I can change all tags and use e.g. <mj-image src="..."></mj-image> instead of <mj-image src="..." /> but this has to be done directly in the code and is changed back after import. 
So this is really no acceptable solution for people who are not familiar with editing code and only want to/can use the visual drag&drop editor.

Can't the tool be modified so that it already inserts/uses <mj-image src="..."></mj-image> instead of <mj-image src="..." />?

Many thanks in advance for your solutions/hints!

br,
Matthias

**Comment by NorthstarTech** [comment]
any update on this? @mattmoesen

**Comment by mattmoesen** [comment]
@NorthstarTech no sorry. I am also still waiting for a response.
At the moment for it is not possible to use the MJML Version of GrapeJS, only HTML Version.

But with the HTML anyone an idea, how to handle the responsive Layout for smaller (mobile) devices? With the MJML for example three columns automatically switched to one column on small devices.

br,
Matthias

**Comment by kickbk** [comment]
Same issue here. Would really appreciate a solution. Totally ok to use regular closing tags, but as soon as you do editor.getHtml, it removes the closing tags. Very frustrating. This is the only major issues we are facing right now.
How do we go about keeping regular closing tags? Is there a way to getHtml but keep the </mj-image> and other self closing tags?

**Comment by AlessandroMagri** [comment]
Same issue here.
Any news?
