### ISSUE TITLE
Feature Suggestion: Add "No need email confirmation" when creating list

### ISSUE THREAD

**Issue by roycwc** [Mailtrain-org/mailtrain#362]
I have created a List with a subscription form. New subscribers need to check email and verify email after filling out the subscription form, which can be annoying for them to join some kind of campaign.

It would be great to have an option "No need email confirmation" when creating a list.

**Comment by thetuyo** [comment]
+1

**Comment by rbicelli** [comment]
Is this possible in mailtrain V2?

**Comment by bures** [comment]
Well, it won't be too much a problem to add it to V2, however it would allow anyone to subscribe any email (i.e. not necessarily theirs). In the end, the one hosting the Mailtrain instance would easily end up delivering unsolicited emails.

**Comment by rbicelli** [comment]
Is there a fast workaround to skip confirmation in v1 or to gather unconfirmed addresses?

**Comment by harunurhan** [comment]
In our use-case, users do really want to subscribe if they are entering their email, so it is ver unlikely that somebody will provide wrong emails on purpose and we rarely get spams. That's why it would be nice to remove this extra conformation step especially that it usually ends up in "Junk", and have only "You are subscribed" email which doesn't require extra action.

**Comment by taoeffect** [comment]
Please note: it appears there are attacks on email servers and newsletters where emails will be automatically added by bot networks to newsletters.

Implementing this feature would almost certainly kill your email server and result it in being blacklisted.

**Comment by laurentlourenco** [comment]
cc @taoeffect 

This option is well known as "simple opt-in" to compare with actual "double opt-in".
Where it's recommended to use "double opt-in" to avoid spam and attack of any kind, it's very helpful to use "simple opt-in" in some marketing use cases.

**Use case 1 example**, in a B2B environement, when you're in touch by phone with a potential client and he agree to receive emails from you, especially an onboarding on. It's not the client but yourself who is going to add him in the list and with the trigger he will receive automatically an welcome email. In this case "double opt-in" is a non sens and the customer will not understand.

**Use case 2 example**, a customer is already into a list and your backoffice team would like to add it into another list (e.g. special member or anything else). In this case again "double opt-in" is a non sens.

NOTA: In both case you keep the unsubscription tag active and the user can unsuscribe if wanted.

So until these feature become available, I need to develop a subscription form dedicated to my backoffice team on another server and to to call the API to avoid to send the confirmation email. :-(

**Comment by taoeffect** [comment]
@laurentlourenco Those sound like features to be added to some admin interface, not the user-facing subscription form.

Also, these attacks on newsletters have, in my experience, been pretty severe. Even with double-opt in, your mail server will end up sending hundreds/thousands of confirmation emails to various emails, possibly triggering a block. I feel like newsletters and signup forms in general should start to move toward proof-of-work and/or LN-micropayments.
