### ISSUE TITLE
Any plan to upgrade zone-mta version?

### ISSUE THREAD

**Issue by adamxxx** [Mailtrain-org/mailtrain#363]
Hi, I found that mailtrain still using the zone-mta **v0.1.0-alpha.144** version. Any plan to upgrade it?
https://github.com/Mailtrain-org/mailtrain/blob/master/setup/install.sh#L133

**Comment by killua-eu** [comment]
Hey @andris9 , while you still maintained mailtrain, do you remember any reason why an old zone-mta was used in the install script? Is there something that might break really bad and be hard to track down when using current zone-mta? Thanks, Pavel
