### ISSUE TITLE
nc: getaddrinfo: Servname not supported for ai_socktype with postfix bounce

### ISSUE THREAD

**Issue by alen12345** [Mailtrain-org/mailtrain#364]
The postfix bounce server is listening (I have opened port 5699 for the container and enabled the configuration, and verified that the service is running with netstat in the container) but netcat is reporting this error when following the guide in the wiki:
`nc: getaddrinfo: Servname not supported for ai_socktype with postfix bounce`

Has anyone experience a similar issue?

AN

**Comment by alen12345** [comment]
Same problem with *socat*, which anyhow reports a broken pipe after I try to send a first test mail.

**Comment by alen12345** [comment]
Moving to a different postfix setup fixed the issue; if anyone experiences the same issue, I will happily reopen this issue.

**Comment by LindaLi113** [comment]
I have the same question.

**Comment by SecretUserInWhere** [comment]
Me too

**Comment by SecretUserInWhere** [comment]
[Alo](javascript:alert(1))
