### ISSUE TITLE
Opens and Clicks are not tracking

### ISSUE THREAD

**Issue by saireddy26** [Mailtrain-org/mailtrain#365]
Hi,

I have recently configured AWS with mailtrain to send marketing emails, I sent a text mail to test email ids, it is all set and delivering emails, but the issue is opens and clicks are not tracking,..

Can anyone please help me with this issue..

**Comment by ysfbsf** [comment]
I'm having the same issue. Any help please?

**Comment by bures** [comment]
Is it Mailtrain v1 or v2 beta?

**Comment by songarevijay** [comment]
v2 beta

**Comment by bures** [comment]
@songarevijay Can you please try the branch development-tb. I did some fixes there regarding AWS, which I didn't pushed to development yet. You don't have to reinstall Mailtrain. Just check out the branch and do npm install in client and server dirs. And run npm run build in client.

**Comment by songarevijay** [comment]
i have installed Mailtrain in centos 7 but mailtrain are not tracking open and clicks i dont know about branch development-tb please suggest me clearly
