### ISSUE TITLE
Mailtrain future

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#373]
As @andris9 handed over the project, we should decide on a couple of points. To start with:

- What to do with mailtrain.org domain (expires in April)?

- How to organize accepting PRs? Here we would need some core group of developers. For instance, I remember @witzig was quite active in reviewing PRs and merging them. Any volunteers very welcome here.

Thanks.

**Comment by HLFH** [comment]
> How to organize accepting PRs?

You can add me in the core team. I'm volunteer. Thanks.

**Comment by killua-eu** [comment]
As per #372, I can offer to maintain Ansible deployment roles, either as a supplement to the installer, or as a basis for a hosted model.

**Comment by janek37** [comment]
Currently mailtrain.org is permanent redirect to this github project (HTTP 301). This is very bad. It means that after it's changed some clients will still remember the redirect.

**Comment by bures** [comment]
@andris9 I can pay for the domain, so that we have more time to figure out how to use it. Where is it hosted? Would it be possible to transfer it to me?

**Comment by mailanetworks** [comment]
Hi, I can host the project.
Please let me know how to help.

Thanks,

**Comment by bures** [comment]
@HLFH @killua-eu @mailanetworks thanks for volunteering. Let's see if we have some more people onboard.

An important decision we should also take is whether we should try to provide support or only address the PRs. There are quite a few issues since November that no one had time to address. What do you think?

**Comment by bures** [comment]
@mailanetworks I think it would be good to host at least the public page of the installation as it was till now. It gave at least a rough idea what Mailtrain looks like and what its features are. We can ask @andris9 to redirect the domain there and then in the meantime, we can figure out what next with the domain.

Later on, once we have the permissions which should allow us to regulate what a user can do, it would be good if we could host a test installation where one would be able to look inside.

**Comment by killua-eu** [comment]
@bures, PRs are a nobrainer. As for support - I guess I wouldn't mind supporting that what I understand. I guess most of us might feel the same? So the support might be as for now on a case-by-case basis - depending on our time and skill distribution. To inform about issues that should get, but wont get support, a NEEDHELP tag might work just fine.

**Comment by HLFH** [comment]
@bures After some cleaning, we may also do a summary of the worthy issues into https://github.com/Mailtrain-org/mailtrain/projects

**Comment by bures** [comment]
@killua-eu Perfect. Let's do the support case-by-case whoever has capacity. 

@HLFH Good idea with the projects. I can setup a project and necessary columns. Any idea about the "worthy issues"

**Comment by mailfromabox** [comment]
He left in such a hurry, thats weird, hope his account did not get hacked

**Comment by andris9** [comment]
@bures i could send you the EPP code needed for domain transfer, just let me know where to send it

@mailfromabox my account was not hacked. Just some newyears cleanup, I haven’t really worked with the project for some time by now

**Comment by bures** [comment]
@andris9 Thank you. If you could please send it to bures@d3s.mff.cuni.cz I'll send you a separate email, just that you have this address in the mailbox. Thanks.

**Comment by gsiou** [comment]
Since a project on my company requires mailtrain, I am willing to spend some time to help with PRs and issues.

**Comment by ratancs** [comment]
https://github.com/Mailtrain-org/mailtrain/issues/118 can this be considered now?

**Comment by bures** [comment]
@ratancs I'm afraid this is still rather out of question. Even with the port to Knex, which I'm working on, we are still pretty tied to SQL databases. I don't really see a way how this could be done.

**Comment by killua-eu** [comment]
@ratancs, is there a specific reason for this? Its been almost 2 years that Mysql supports storing and querying json documents. If we ever decide to rewrite some of the messy sql parts, we still shouldn't have any valid need for switching to Mongo.

**Comment by brentdur** [comment]
I'm happy to help review PR's. Mailtrain has been very useful for a number of non-profits I've worked with.

**Comment by kolaente** [comment]
I would propose to use labels and milestones to plan the following release. Maybe taking a look at [the Gitea project](https://github.com/go-gitea/gitea/issues) is a good idea.

**Comment by torcolato** [comment]
what about setting up google groups or similar for user questions?

**Comment by bures** [comment]
Personally, I'm glad that I have some time for Mailtrain a few days every couple of weeks. I won't be able to moderate the google groups or answer questions there. However, it's a good idea. If you want to go for it, please feel free.

**Comment by jg4smile** [comment]
May I be added as a contributor/member? I'm a pretty good "old school" developer w/extensive PM experience (language agnostic), and wouldn't mind giving a few hours a week towards development.

**Comment by restyler** [comment]
We are considering using mailtrain as an alternative to too-resource-hungry mautic, but I noticed the number of commits to mailtrain in 2019 is very small (according to github insights) and issues are piling up. Is mailtrain still being actively developed? Is v2 version stable and performant enough for usage in production for 1m contacts project? Thanks!
