### ISSUE TITLE
Hosting mailtrain.org website

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#375]
I'm now in charge of the mailtrain.org domain. I was thinking that before we decide what to put to mailtrain.org domain, we could at least setup something similar which was there before. If I understand right, it was a (potentially empty) mailtrain instance, which was there pretty much to show the public page that has some screenshots of what mailtrain is. 

@mailanetworks, do I understand right, you offered to host this on your servers for the time being? Alternatively, I can put it ours. That's no problem, I was just hoping that this could relieve me of some maintenance effort. But no problem in either option.

Thanks.

**Comment by mailfromabox** [comment]
@bures you will need a test version to test new releases, you could use that domain for that

**Comment by mailanetworks** [comment]
Hi,
Yes, count on me for the hosting if needed it.

Thanks,

**Comment by torcolato** [comment]
if i can support with hosting, sysadmin work or similar let me know.

**Comment by bures** [comment]
@mailanetworks - Perfect. In that case, I would kindly ask you to setup an mailtrain instance on some server. We just need it for the homepage. Let me know the IP then, I'll setup the DNS entry.
Thanks a lot.

@torcolato - thanks for offer. I would leave it to @mailanetworks to ask if he needs help.

**Comment by mailanetworks** [comment]
Hi Tom, 

Will do it. 
Do you have a preference for the OS to host it? 

Thanks, 



De: "Tomas Bures" <notifications@github.com> 
Para: "Mailtrain-org" <mailtrain@noreply.github.com> 
Cc: "jfranco" <jfranco@maila.com.br>, "Mention" <mention@noreply.github.com> 
Enviadas: Domingo, 18 de fevereiro de 2018 15:56:31 
Assunto: Re: [Mailtrain-org/mailtrain] Hosting mailtrain.org website (#375) 



[ https://github.com/mailanetworks | @mailanetworks ] - Perfect. In that case, I would kindly ask you to setup an mailtrain instance on some server. We just need it for the homepage. Let me know the IP then, I'll setup the DNS entry. 
Thanks a lot. 

[ https://github.com/torcolato | @torcolato ] - thanks for offer. I would leave it to [ https://github.com/mailanetworks | @mailanetworks ] to ask if he needs help.

**Comment by bures** [comment]
Perfect. As for preferences - not really. I would normally go for some Linux-based system. Whether it is CentOS, Fedora or Ubuntu, I don't really care.

Thanks.

**Comment by mailanetworks** [comment]
Hi @bures 
This is the IP, 138.118.35.116
I would need you to point the domain to proceed with the SSL certificate.

Thanks,

**Comment by bures** [comment]
@mailanetworks 
Excellent. I just added the records to DNS. Please try it out.
Thanks.

**Comment by mailanetworks** [comment]
@bures 
All working! Thank you.
But docs.mailtrain.org stopped working. I believe it pointed to https://github.com/Mailtrain-org/mailtrain/tree/master/docs

Thanks,

**Comment by bures** [comment]
If you can setup a redirect on your server from docs.mailtrain.org, I can create the A record and point it there. What do you think? Thanks.

**Comment by mailanetworks** [comment]
Sure thing, just point to the same IP and I´ll redirect.

Thanks,

**Comment by bures** [comment]
It is there. Thanks.
