### ISSUE TITLE
Problems when registering multibyte characters in field names of custom fields.

### ISSUE THREAD

**Issue by cold00water** [Mailtrain-org/mailtrain#376]
I found a problem when registering multibyte characters in the field name of the custom field.

1. input field name

Field Name : [multibyte charcter]

2. Edit subscriber

3. View mysql table

select * from custom_fields \G;

*************************** 2. row ***************************
(snip)
        column: custom__sy6tjuilm

custom__sy6tjuilm  should normally be custom_[multibyte charcter]_sy6tjuilm .
However, it seems strange that multi-byte characters are included in the MySQL field.

I want to register a value different from the field name in column, but are there any good ideas?

**Comment by bures** [comment]
I don't think we ever intended to use other than basic identifier characters (A-Za-z0-9) for field identifiers. The problem is that they are used as part of DB column names. Any particular use-case you want to achieve with it?

**Comment by cold00water** [comment]
I am Japanese. For users who can not read English, I'd like to create a custom field for Japanese.

I found a workaround. Once created a custom field in ASCII, it is a way to change the name of the field to a multi-byte character. Since the name of the DB column is not changed from ASCII, only items on the WEB interface can be multibyte.

However, it will take some time

**Comment by bures** [comment]
Makes sense. In the version currently under development, I already split the field name and the field identifier. That should address your case. If for the time being you can go with your workaround, I would close the issue. OK? Thanks.

**Comment by cold00water** [comment]
thanks!
