### ISSUE TITLE
Automated Selenium Tests

### ISSUE THREAD

**Issue by programster** [Mailtrain-org/mailtrain#382]
Hello all,
I think it's a major blow to Mailtrain that @andris9 is leaving the project and worry that the project would just "fade away" as it's just too darn useful.

I was thinking that one of the major things that Mailtrain could do with is automated selenium tests. This would allow:
* releases to be pushed far more frequently with a greater degree of confidence, especially when merging other contributors code.
* me to contribute to the project more even though I am not a professional Node developer.
* others who are thinking about using/switching to mailtrain to have more confidence in the tool and its stability.

I've made a [short video demonstrating what I mean. Please watch the video](https://www.youtube.com/watch?v=guySIZrOuoU&feature=youtu.be).

### Getting Feedback
I would be keen to get feedback from the main contributors / maintainers / owners on what key things they would want from automated testing. I believe this is @bures  and perhaps some others?

* Is there just no point in taking this further as this is written in PHP and that is a different language to the main project? 
    * If someone could set up a little framework/test-suite like in my video for writing selenium tests quickly in Javascript/Node/Typescript, I could probably contribute by writing some tests, but at the moment I don't know how to run Selenium tests that way (but keen to learn).

If we were to proceed:
* Would it need to be hooked up to a build server and automatically executed whenever master branch is updated?
     * I could do this, but it would require quite a bit more effort than just running the tests as shown in the video and its probably more important to get more tests written first. 
     * This would probably require testing to be docker based so the server can just build and run the container. I don't yet know how to hook the results up to github, but I could probably figure out how to do this with some info from others. (E.g a webhook/API request to an endpoint).  
     * For better testing, the build/test server would need xserver installed as I believe using cli based browser testing can miss things as it wont spot when elements are not visible or clickable.

* Could you provide descriptions of the top 30 tests that need to be written in order of priority. E.g.
     * Create list and a template. Send a campaign based on that template to the list and checked that email is recieved by one of the users.
     * Create list that contains an invalid email address, and a template. Send a campaign based on that template to the list and check that mailtrain sees that the email was not recieved/bounced.
     * yadda yadda yadda.

**Comment by bures** [comment]
I'm slowly working on a next version of Mailtrain (now in branch development). The tests are excellent idea. However a bit of problem will be that with the new version pretty much all the tests will have to be rewritten. The new version uses React.js for UI and also introduces improvements/modifications at a lot of places. 

I hope to have a beta of the new version by the end of the summer. Selfishly, I would happier if someone did the tests for the new version. It would help to test the functionality that is already in (list management, subscription, API, reports) and would make sure it gets not broken as the other features (templates, campaigns, triggers) are being rewritten.

BTW, @witzig already did some basis for selenium testing. It sits in the folder 'test' and can be executed by targets in package.json. It's currently used to test some basic subscription scenarios and some API calls (please note that the API tests are not yet ported to the development version).

**Comment by programster** [comment]
@bures 

> ...with the new version pretty much all the tests will have to be rewritten. ... Selfishly, I would happier if someone did the tests for the new version.

That's fine, if you keep pushing the branch, I could work the tests against that with pull requests.

> BTW, @witzig already did some basis for selenium testing. It sits in the folder 'test' and can be executed by targets in package.json. It's currently used to test some basic subscription scenarios and some API calls (please note that the API tests are not yet ported to the development version).

After taking another look at the testing folder I can see that it is indeed selenium test. I will try to learn how that works and get them running. It's always good to pick up new skills.

**Comment by forgeOneHQ** [comment]
I am closing this issue right know. We can rethink of it in v2 again. :)
