### ISSUE TITLE
Node-posix issue on install

### ISSUE THREAD

**Issue by rodti** [Mailtrain-org/mailtrain#387]
I'm trying to install manually on Debian 9.3 from git.

I've followed the manual install instructions as far as _NODE_ENV=production npm start_

I then receive the following error:

`> mailtrain@1.23.2 start /home/user/mailtrain
> node index.js

info Using local auth 
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
/home/user/mailtrain/node_modules/posix/lib/posix/index.js:25
    throw new Error("unable to load the node-posix extension module");
    ^

Error: unable to load the node-posix extension module
    at load_extension (/home/user/mailtrain/node_modules/posix/lib/posix/index.js:25:11)
    at Object.<anonymous> (/home/user/mailtrain/node_modules/posix/lib/posix/index.js:28:13)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at tryRequire (/home/user/mailtrain/node_modules/try-require/index.js:18:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailtrain@1.23.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mailtrain@1.23.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-25T12_26_16_157Z-debug.log` 

I've tried installing the posix module manually using npm which doesn't seem to make any difference.

Any ideas?

**Comment by rodti** [comment]
I should have said, this is on Node v9.6.1 and NPM 5.7.1

**Comment by rodti** [comment]
Fixed this myself, I'd installed the posix module with the -g option.  Oops!

**Comment by rodti** [comment]
Hmm, posix issues continue, I've clearly not sorted this yet.

I managed to get Mailtrain running.  Restarting now using systemctl I have more posix issues in the logs:

`Feb 25 17:13:12 bakery systemd[1]: Started Mailtrain server.
Feb 25 17:13:13 bakery node[42117]: info Using local auth
Feb 25 17:13:13 bakery node[42117]: /opt/mailtrain/node_modules/posix/lib/posix/index.js:21
Feb 25 17:13:13 bakery node[42117]:                 throw error;
Feb 25 17:13:13 bakery node[42117]:                 ^
Feb 25 17:13:13 bakery node[42117]: Error: Module version mismatch. Expected 48, got 59.
Feb 25 17:13:13 bakery node[42117]:     at Error (native)
Feb 25 17:13:13 bakery node[42117]:     at Object.Module._extensions..node (module.js:604:18)
Feb 25 17:13:13 bakery node[42117]:     at Module.load (module.js:494:32)
Feb 25 17:13:13 bakery node[42117]:     at tryModuleLoad (module.js:453:12)
Feb 25 17:13:13 bakery node[42117]:     at Function.Module._load (module.js:445:3)
Feb 25 17:13:13 bakery node[42117]:     at Module.require (module.js:504:17)
Feb 25 17:13:13 bakery node[42117]:     at require (internal/module.js:20:19)
Feb 25 17:13:13 bakery node[42117]:     at load_extension (/opt/mailtrain/node_modules/posix/lib/posix/index.js:16:20)
Feb 25 17:13:13 bakery node[42117]:     at Object.<anonymous> (/opt/mailtrain/node_modules/posix/lib/posix/index.js:28:13)
Feb 25 17:13:13 bakery node[42117]:     at Module._compile (module.js:577:32)
Feb 25 17:13:13 bakery systemd[1]: mailtrain.service: Main process exited, code=exited, status=1/FAILURE
Feb 25 17:13:13 bakery systemd[1]: mailtrain.service: Unit entered failed state.
Feb 25 17:13:13 bakery systemd[1]: mailtrain.service: Failed with result 'exit-code'.
`

**Comment by alexanderrieder** [comment]
I have the same problem, how did you fix this?

**Comment by rodti** [comment]
Try [this](https://github.com/Mailtrain-org/mailtrain/issues/388)

**Comment by belqit** [comment]
"rm -rf node_modules" solved my problem
