### ISSUE TITLE
No Administration menu item

### ISSUE THREAD

**Issue by buttle** [Mailtrain-org/mailtrain#389]
Hi,

I've recently (manually) installed Mailtrain. (thanks for keeping this project going).

I'm missing the Administration option in the top menu.
I noticed when I went to create a second user account (something I can't do).

Any ideas?

Thanks.

**Comment by ezzra** [comment]
It looks for me like there is no multiuser possibility because there is no registration page, is that right? I just created a second user directly in the database and it works.

**Comment by bures** [comment]
It this version 1 or version 2?

**Comment by ezzra** [comment]
I use Version 1

**Comment by bures** [comment]
There are no real multiple users in v1. You can create another in database which will allow you to have another user with different login and password. However you have no way of restricting permissions. If you are looking for true multi-user functionality (including granular permissions), you have to go for v2 (currently beta).
