### ISSUE TITLE
bounce handling postfix

### ISSUE THREAD

**Issue by johniemj** [Mailtrain-org/mailtrain#390]
I have created the bounce handling service that is in the wiki.
It's getting started and when i'm doing a service status i;m getting this output

`Redirecting to /bin/systemctl status bouncetail.service
● bouncetail.service
   Loaded: loaded (/etc/systemd/system/bouncetail.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-03-01 14:51:03 CET; 5s ago
 Main PID: 16999 (sh)
   CGroup: /system.slice/bouncetail.service
           ├─16999 /bin/sh -c /usr/bin/tail -F /var/log/maillog | nc localhost 5699 -
           └─17000 /usr/bin/tail -F /var/log/maillog

Mar 01 14:51:03 mydomain.com systemd[1]: Started bouncetail.service.
Mar 01 14:51:03 mydomain.com systemd[1]: Starting bouncetail.service...
Mar 01 14:51:03 mydomain.com sh[16999]: Ncat: Got more than one port specification: 5699 -. QUITTING.`

is this correct?
What's the last line mean?

**Comment by kusaasira** [comment]
Ialso got stuck here and Mailtrain aint capturing my bounces at all!
