### ISSUE TITLE
Track clicks but not by user

### ISSUE THREAD

**Issue by gerbsen** [Mailtrain-org/mailtrain#394]
Hello,
I was wondering if it is possible to track the clicks from the email but not by user but just by count. As the association where I work in, does not want to know that. 

Cheers and thanks for this wonderful program,
Daniel

**Comment by err0r3o3** [comment]
Hello,
It would be great to have a config parameter to enable anonymous click statistics.

Best Regards 
Michael

**Comment by selecta-ufuk** [comment]
Looking forward for feature like that.
I would like to have the percentage evaluation of the click statistics but which user clicked what is unimportant from our point of view.

**Comment by saschafoerster** [comment]
We have customers, that want to send RSVP emails with confirmation or rejection to an invitation. It would be nice if at least I could create a custom report with this information. Maybe someone can help?
