### ISSUE TITLE
Suggestion: Connection to MariaDB/MySQL on the host via socket instead of separate docker containers for MySQL and redis

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#395]
I tried half a day to get a connection between Mailtrain in Docker and the exisiting MySQL-databases on the host. I found this article, but it wasn't helpful for me. I didn't find the correct IP-adresses and I don't like the idea of opening the server for everyone (even though there is a firewall).
https://blog.programster.org/deploy-mailtrain-with-docker
I would be really happy, if there was a documented way to use mysql-socket on the host. Some for Redis which is now also running twice. Thanks!

**Comment by forgeOneHQ** [comment]
@saschafoerster I guess this is v1 related, please try with v2 and open a new issue if you still having issues with the deployment.
