### ISSUE TITLE
Mailtrain fails to spawn child processes and throws after update

### ISSUE THREAD

**Issue by alikuru** [Mailtrain-org/mailtrain#405]
Tried updating my old setup today but failed. After the update, Mailtrain started to throw with this looping message:

```
info
Using local auth
info
sql
 Database check completed
info
Express
 WWW server listening on port 2996
info
PrivilegeHelpers
 Changed group to "www-data" (33)
info
PrivilegeHelpers
 Changed user to "www-data" (33)
verb
UTC
 Updating timezone offsets
Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at exports.fork (child_process.js:103:10)
    at spawnSender (/var/www/sub.domain.tld/http/index.js:93:21)
    at spawnSenders (/var/www/sub.domain.tld/http/index.js:109:5)
    at Immediate.triggers [as _onImmediate] (/var/www/sub.domain.tld/http/index.js:127:29)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

I was on [a commit](https://github.com/Mailtrain-org/mailtrain/commit/3afb37e1692f712e93b5727929b2dfb74d8c954d) made back in December, 2016, which puts my setup somewhere between releases v1.20.0 and v1.21.0. So, I was at least 7 releases and probably hundred commits behind.

Searched a bit and found that this `Error: spawn EACCES` issue is a quite common and usually related to missing executable bit of a file. However, playing with the permissions of the files shown in the log above didn't help.

Then checked the `install.sh` to inspect whether a new element has been added to the setup process and found that the script creates a read only MySQL account for the Mailtrain for the workers and saves it to `workers/reports/config/production.toml`. Since this wasn't mentioned on the manual setup steps, I did what script does and created a separate user with SELECT privileges only and saved at the same spot copying the template from `default.toml`. That didn't help either.

I'm using Nodejs v8.9.3 with NVM on Debian 9.4 and I run Mailtrain with PM2 v2.8.0. My Redis version is 4.0.1. Below is my `config/production.toml`.

```
title="mailtrain"

user="www-data"
group="www-data"

[log]
level="verbose"

[www]
port=2996
host="0.0.0.0"
secret="secret phrase"
remember=2592000
log="dev"
proxy=true
postsize="10MB"

[mysql]
host="localhost"
user="db_name"
password="db_pass"
database="db_user"
port=3306
charset="utf8mb4_general_ci"
timezone="local"

[redis]
enabled=true
host="localhost"
port=6379
db=5
password="redis_pass"

[verp]
enabled=false
port=25
host="0.0.0.0"

[testserver]
enabled=false
port=5587
host="0.0.0.0"
username="testuser"
password="testpass"
logger=false

[ldap]
enabled=false
host="localhost"
port=3002
baseDN="ou=users,dc=company"
filter="(|(username={{username}})(mail={{username}}))"
passwordresetlink=""

[postfixbounce]
enabled=false
port=5699
host="127.0.0.1"

[queue]
processes=2
```

Any ideas on how to solve this issue?

**Comment by alikuru** [comment]
Still couldn't figure this out, appreciate any help.

**Comment by forgeOneHQ** [comment]
@alikuru  please use v2 since v1 is EOL.
