### ISSUE TITLE
Mailtrain lambda

### ISSUE THREAD

**Issue by M0dM** [Mailtrain-org/mailtrain#411]
Hi,

I would be very interested to have you opinion on the possibility to run mailrun on AWS lambda using :
- Claudia (https://claudiajs.com/, https://github.com/claudiajs/claudia)
- Up (https://up.docs.apex.sh/, https://github.com/apex/up)

or any other "servelessify" deployment tool.

Does anyone have done this before ?
Would you be interested to make some tests and documentation about it ?

I think it could be a real asset for mailtrain to become serverlessly deployable.

Regards, M0dM

**Comment by bures** [comment]
I'm afraid this is never going to easily work. Mailtrain needs persistent file storage to save attachments. This is not provided by Lambda (at least as far as I know). We would have to implement support for working with files on S3. Not sure if this is worth the effort.

**Comment by M0dM** [comment]
It doesn't seems easy but I think it could be worth it.

Seems there is some projects which could help :
- https://www.npmjs.com/package/s3fs
- https://www.npmjs.com/package/s3
and https://github.com/jamhall/s3rver for test purpose.

Anyway, thanks for the answer.
