### ISSUE TITLE
Saving impossible "Path must be a string. Received null"

### ISSUE THREAD

**Issue by kolaente** [Mailtrain-org/mailtrain#418]
I duplicated an old template yesterday and did some modifications. When I wanted to continue working on the template today, I couldn't save anymore. I haven't changed anything compared to yesterday.

I've updated to the latest version today (after the error occured), didn't help. Still does not work.
I'm using the official docker image.

Full trace:

```
mailtrain_1  | path.js:28
mailtrain_1  |     throw new TypeError('Path must be a string. Received ' + inspect(path));
mailtrain_1  |     ^
mailtrain_1  | 
mailtrain_1  | TypeError: Path must be a string. Received null
mailtrain_1  |     at assertPath (path.js:28:11)
mailtrain_1  |     at Object.join (path.js:1253:7)
mailtrain_1  |     at resizedImage (/app/routes/editorapi.js:108:27)
mailtrain_1  |     at getProcessedImage (/app/routes/editorapi.js:182:9)
mailtrain_1  |     at fs.readdir (/app/routes/editorapi.js:208:13)
mailtrain_1  |     at FSReqWrap.oncomplete (fs.js:136:15)

```

**Comment by kolaente** [comment]
After some more digging, the error seems to occur only when the template contains an image tag without a path. (Using GrapeJS here)

**Comment by forgeOneHQ** [comment]
@kolaente I guess this is v1 related? If yes, please try again v2 and let us know if you still have the same issues with all infos like config, how you deployed it, log files.
