### ISSUE TITLE
Official docker images

### ISSUE THREAD

**Issue by marceloboeira** [Mailtrain-org/mailtrain#419]
Can we start building images from this repo on a CI and pushing them to docker-hub ?

I believe the image should be an stand-alone version of mail-train rather than the whole package, mainly because it makes it easier for anyone running this on an cluster-environment. e.g.: I will have to do this myself so I can run on my company's k8s cluster...

**Comment by Avalarion** [comment]
@marceloboeira did you already set this up and running?

**Comment by marceloboeira** [comment]
@Avalarion I did, I'm using this very simple one https://github.com/hey-car/mailtrain
