### ISSUE TITLE
Allow to disable "List-Unsubscribe" header

### ISSUE THREAD

**Issue by njam** [Mailtrain-org/mailtrain#422]
I'm using Mailtrain for sending promotional campaigns to my website's users. Now my website has its own *unsubscribe* feature, and I would like to manage the list there primarily. I'm importing a field `unsubscribe_link` with the list, which I include in the email. But Mailtrain still includes its own unsubscribe link the the `List-Unsubscribe` header.

Basically I would like my users to never interact with the Mailtrain website directly.
What do you think about allowing to disable the `List-Unsubscribe` header?

The header is added in `services/sender.js :: formatMessage()`.

(another solution could be to make the header configurable through a merge tag from the list, but I guess that would be quite complicated.)

**Comment by njam** [comment]
Would this get accepted if I would introduce a global configuration option to disable `List-Unsubscribe` headers?

**Comment by bures** [comment]
I would be fine with making this configurable on the list level (i.e. lists table in DB) or via the global conf. option.

Just note that ain't won't likely keep the global conf option in the next major version of Mailtrain (which won't be around for at least several months). I'll likely reflect it on the list level.

**Comment by njam** [comment]
@bures if the right place is on the *list level*, then I will add it there. So you prefer if I add a column `disable_listunsubscribe` to the `lists` table, right?

**Comment by bures** [comment]
Yes. That would be great. Thanks.

**Comment by njam** [comment]
This is implemented and merged.

@bures What would be the procedure to get this change added to the next release? Is there any new release planned?
