### ISSUE TITLE
Custom Form Layout Varibles

### ISSUE THREAD

**Issue by fluiddmotion** [Mailtrain-org/mailtrain#425]
Hello,

All good in the world of getting MailTrain deployed and operational, but I have hit a roadblock.

When editing the layout template for the Webforms, I cannot for the life of me find the variable to display the description of a list.. Name is easy {{title}} but is there a list of variables that are available to to be used in MJML anywhere?

Kind Regards

Lee

**Comment by balping** [comment]
You can see in this function what variables are passed to rendering

https://github.com/Mailtrain-org/mailtrain/blob/dcf83309294eee6cdaefd312b8b8c1c92d7ab71f/routes/subscription.js#L172
