### ISSUE TITLE
Double OptIn

### ISSUE THREAD

**Issue by fluiddmotion** [Mailtrain-org/mailtrain#428]
Is there any easy way to disable double optin?

**Comment by bures** [comment]
What exactly do you mean by disabling double opt-in?

**Comment by gnunicorn** [comment]
@fluiddmotion when you create a list you can choose (on the bottom) which opt-in-strategy is being applied for that list. You can choose to not double-optin.

![screenshot-20190214144505-2408x876](https://user-images.githubusercontent.com/40496/52790686-72f60000-3067-11e9-81b5-1c956775e81b.png)

**Comment by laurentlourenco** [comment]
The one-step option is not working as expected because we receive also a opt-in confirmation email. 
So I've the same request how to disable double-opt in ?

**Comment by forgeOneHQ** [comment]
@fluiddmotion @jacksparrowid  I don't think that not to have double opt-in is not copliant with GDPR.

**Comment by ericuldall** [comment]
Why was this closed with no proposed resolution? Seems perfectly reasonable to let the end user decide if they want the confirmation email sent.

Not all email lists require GDPR compliance (not even sure double opt in is a hard requirement) as you can confirm consent in more than one way.

The api allows subscription with no confirmation as well, so the UI is inconsistent with the API.
