### ISSUE TITLE
how to speed up mailtrain send rate

### ISSUE THREAD

**Issue by scalaview** [Mailtrain-org/mailtrain#430]
i use Amazon ses to send email, my account rate is 200 emails/second, i try to send emails to 113504 subscribers, but the rate of mailtrain can't reach 200 emails/second

The Amazon ses setting:
Sending Quota: send 2500000 emails per 24 hour period
Quota Used:  0% as of 2018-04-25 17:33 UTC+8
Max Send Rate:200 emails/second
Last updated:  2018-04-25 17:33 UTC+8

here are the mailtrain setting:
Max connections: 10
Max messages: 1000
Throttling: 0

also i try some option in production.toml

[queue]
processes=10
or
[queue]
processes=25
or
[queue]
processes=35

my server hardware:
4 Intel CPU
16G Mem

i try 3 time, calculate from table campaign__x , the rate of processes=10, processes=25, processes=35 are 55 emails/second, 61 emails/second and 65 emails/second.
would you like to help me to find out what's the problem? how can mailtrain reach the Amazon ses send rate, about 200 emails/second ?

**Comment by Zetanova** [comment]
Could you find the issue?
