### ISSUE TITLE
Unsubscribe link in email template

### ISSUE THREAD

**Issue by nikollou** [Mailtrain-org/mailtrain#431]
Hi guys, sorry to post here for what is rather not an issue as much as a request for some help. For the life of me I cannot figure how to embed a link in a template that will allow the receiver to unsubscribe from the mailing list. 

I have been searching all over the place with no luck, the only place with info on unsubscribing is the API section but I just want a link in the email that will direct people to the unsubscribe page where they can follow the process.

Sorry and thanks in advance for any advice.
Nik

**Comment by lordtangent** [comment]
I have the same challenge. 

You know what would go a long way to helping this? Including a GrapesJS template that was more than just the default than GrapesJS that demonstrated the use of some of the merge tags.

Please help!

**Comment by pablo75rus** [comment]
Look for "Merge tags" button for all possible links including [LINK_UNSUBSCRIBE]

**Comment by forgeOneHQ** [comment]
I close this issue. In the standard templates it is available. If you still have this issue in v2 you are welcome to open a new issue.
