### ISSUE TITLE
Mosaico template upload images not working

### ISSUE THREAD

**Issue by mycoola** [Mailtrain-org/mailtrain#435]
when trying to upload an image in mosaico template the image not uploading and appear in the template.

**Comment by krzyzaq** [comment]
I have the same issue. The console output below:
info HTTP GET /mosaico/dist/vendor/skins/gray-flat/content.inline.min.css 304 0.741 ms - -
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailtrain@1.24.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mailtrain@1.24.0 start script.

**Comment by fwolfst** [comment]
https://github.com/Mailtrain-org/mailtrain/issues/374 might provide the solution: In the settings, change the Service Address (URL) to the actual IP/domain name instead of localhost, if that is set.
