### ISSUE TITLE
Simple Remote Installation 

### ISSUE THREAD

**Issue by LanceHaverkamp** [Mailtrain-org/mailtrain#439]
At first glance, MailTrain looks to be what I need!
Where are the instructions for installation on, for example, a shared hosting (like cPanel) account, by a subscriber, typically someone who can't use root commands, or a command line? 

Thanks!
Lance

**Comment by JWDT** [comment]
Mailtrain is built on NodeJS. I'm not aware of any shared hosting that supports that.

I set it up using the docker files included, which worked fairly easily, and you can get quite cheap systems that will run docker for you.

**Comment by tammohaannl** [comment]
If u want it on a shared host maybe checkout fastcomet. I run it on there as well. Check there plans[here](https://affiliate.fastcomet.com/scripts/click.php?a_aid=5afbf79a62e00&a_bid=651a85ea&desturl=https%3A%2F%2Fwww.fastcomet.com%2Fwhy-fastcomet)

**Comment by simevidas** [comment]
FWIW, I’m trying to set Mailtrain v1 up on FastComet shared hosting as we speak. I’m facing the following issue, but I’m not sure if it’s caused my Mailtrain.

```
App 616742 output: Trace: You required the Node Cluster module, which is incompatible with Passenger, a non-functional shim was returned and your app may still work. However, please remove the related code as soon as possible.
App 616742 output:     at Module.require (/opt/passenger-5.3.7-13.el6.cloudlinux/src/helper-scripts/node-loader.js:63:12)
App 616742 output:     at require (internal/modules/cjs/helpers.js:25:18)
App 616742 output:     at Object.<anonymous> (/home/mailtrai/nodevenv/wwwroot/10/lib/node_modules/shortid/lib/util/cluster-worker-id.js:3:15)
App 616742 output:     at Module._compile (internal/modules/cjs/loader.js:778:30)
App 616742 output:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
App 616742 output:     at Module.load (internal/modules/cjs/loader.js:653:32)
App 616742 output:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
App 616742 output:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
App 616742 output:     at Module.require (internal/modules/cjs/loader.js:692:17)
App 616742 output:     at Module.require (/opt/passenger-5.3.7-13.el6.cloudlinux/src/helper-scripts/node-loader.js:80:25)
```

**Comment by simevidas** [comment]
I successfully set up Mailtrain v1 on FastComet’s shared hosting (the cheapest tier). I had to preform a change to the Mailtrain’s code. See this for more info:

https://github.com/Mailtrain-org/mailtrain/pull/938
