### ISSUE TITLE
Multiple email addresses and migrating database

### ISSUE THREAD

**Issue by nwaxiomatic** [Mailtrain-org/mailtrain#440]
Hi, I apologize for my severe ignorance with the project.

I am primarily looking to use mailtrain as a customizable newsletter app but I am not familiar with the stack here.

The docs don't seem to have info regarding customization of the models...

What is the general way to add migrations to the database?

Specifically I'd like to be able to have multiple email addresses per Subscription, but adding new fields in the UI does not allow for this CC functionality.

Thanks for any pointers in the right direction!

**Comment by nwaxiomatic** [comment]
After reviewing examples:
https://github.com/Mailtrain-org/mailtrain/blob/master/setup/sql/upgrade-00014.sql#L5-L12
https://github.com/Mailtrain-org/mailtrain/pull/434/files

still confused if there is a way to automatically create these files

**Comment by bures** [comment]
Not sure which files you want to create. If you mean migrations, just take some SQL file as an example, copy it in your own file and change it to suit you.
