### ISSUE TITLE
Unable to debug the action of sending email

### ISSUE THREAD

**Issue by rjrodriguezalvarez97** [Mailtrain-org/mailtrain#441]
Hi, I've been trying to debug Mailtrain but I'm unable to do it. The child Sender process is unable to start while debugging but it starts properly during running. This is the output from running:

> info Using local auth 
> Warning: connect.session() MemoryStore is not
> designed for a production environment, as it will leak
> memory, and will not scale past a single process.
> info sql Database check completed
> info Express WWW server listening on port 3000
> verb UTC Updating timezone offsets
> info POSTFIXBOUNCE Server listening on port 5699
> info Service All services started

And this is the output from debugging:

> /usr/bin/node --inspect-brk=42835 /home/ricardo/mailtrain/index.js
> Debugger listening on ws://127.0.0.1:42835/ecaafed2-45de-4622-bcd3-c4f8d8a7bc93
> For help see https://nodejs.org/en/docs/inspector
> Debugger attached.
> info Using local auth 
> Warning: connect.session() MemoryStore is not
> designed for a production environment, as it will leak
> memory, and will not scale past a single process.
> info sql Database check completed
> info Express WWW server listening on port 3000
> verb UTC Updating timezone offsets
> info POSTFIXBOUNCE Server listening on port 5699
> Starting inspector on 127.0.0.1:42835 failed: address already in use
> info Service All services started
> ERR! Child Sender process 8979 exited with 12

I think it might be caused because of `child_process.fork()` as explained here
[https://github.com/nodejs/node/issues/8495#issuecomment-246600965](https://github.com/nodejs/node/issues/8495#issuecomment-246600965)

Any ideas or workaround? 
Thanks.

**Comment by bures** [comment]
Honestly, I thing it's close to impossible to debug a multi-process app with concurrently running co-routines. Just use log messages via console.out.

**Comment by forgeOneHQ** [comment]
Close this issue. You are welcome to reopen a new issue on v2 if still required and you are welcome to participate on this.
