### ISSUE TITLE
Separate styles for email and web forms

### ISSUE THREAD

**Issue by cornerman** [Mailtrain-org/mailtrain#448]
Currently using Mailtrain and I want to style my web forms differently than my email.

At first, I tried to update the "Form Input Style" css file. But this will have an effect on emails as well as the website. Is there a way to have different css files for mail and website? Otherwise, an idea would be to inline styles with `mj-raw` above all web/email pages. But this is tedious to maintain. Any ideas?

**Comment by cornerman** [comment]
As a workaround, I have added styles into the main layout in combination with an `if isWeb` statement:
```html
<mj-raw>
  {{#if isWeb}}
    <style>       
    ...
   </style>
  {{/if}}
</mj-raw>
```

**Comment by forgeOneHQ** [comment]
I think this is still v1 related. Checkout v2 and let us know if you any issues :)
