### ISSUE TITLE
mailtrain image not exist or may require 'docker login'

### ISSUE THREAD

**Issue by YuraKril** [Mailtrain-org/mailtrain#454]
Can not start mailtrain in docker docker-compose up -d  or docker-compose pull  not work.

Pulling mailtrain (mailtrain:latest)...
ERROR: pull access denied for mailtrain, repository does not exist or may require 'docker login'

**Comment by thibwa** [comment]
Any news about this issue ?

**Comment by sfdb** [comment]
I had the same problem as I skipped step 2 "Copy the file docker-compose.override.yml.tmpl to docker-compose.override.yml and modify it if you need to."
Following that resolved the issue for me.

**Comment by anandbaskaran** [comment]
The solution from @sfdb works. I think the team can close this issue.
