### ISSUE TITLE
Mail limit per day ?

### ISSUE THREAD

**Issue by d4op** [Mailtrain-org/mailtrain#455]
I have a list with 50.000 subs in 1 List.

now i want to send my campain splitted. every day 300 mails. next day the next 300.
is this possible ????
only found delay sending ?!

**Comment by greench** [comment]
You can use Throttling under Advanced Mailer settings. If you enter 12, your MTA will send 12 messages per hour, 288~300 messages per day.

**Comment by forgeOneHQ** [comment]
Closing the issue. You can check out in V2 and reopen the issue if still necessary. :)
