### ISSUE TITLE
Is 1GB Ram really needed for a really small list? (less than 500)

### ISSUE THREAD

**Issue by precogtyrant** [Mailtrain-org/mailtrain#456]
Hello,
I saw that the recommended requirements state 1GB of RAM. Is that really necessary for a small list?
Can I host it on a VPS with 1GB of RAM alongside another site ?

**Comment by sommarnatt** [comment]
I'd say it would run on less, but RAM isn't that expensive, perhaps you could afford another GB of RAM since you're not paying for mailtrain? ;)

**Comment by precogtyrant** [comment]
@sommarnatt thanks. I am just thinking of getting a single box with higher RAM and hosting my other app on it as well, along with mailtrain. I just wanted to make sure it doesn't bog down my main application by taking up a lot of RAM for a small list :)

**Comment by ilyacherevkov** [comment]
I run postal mail server + mailtrain  + actual app on 2gb machine, and im able to send 10k emails without a problem.

Although, postal claims to need 6 gb & mailtrain 1 gb

**Comment by forgeOneHQ** [comment]
@precogtyrant  Depends on. A VPS with 1 GB needs to run the Operating System + Application. I usually run my servers with min 2GB for OS and 2GB for App. Depends on the prices you can get cheap servers also with 2CPUs and 4-8GB RAM.
