### ISSUE TITLE
Custom fields are not searchable

### ISSUE THREAD

**Issue by foleac** [Mailtrain-org/mailtrain#460]
Currently custom fields are not searchable. I am not sure if this is the intended behavior.

I run a list where names and email address can change so it would be nice to be able to search the custom fields that identify the recipient permanently.

**Comment by bures** [comment]
Not sure what you mean by "searchable"? Could you be a bit more specific?

**Comment by foleac** [comment]
Sure. What I mean by "searchable" is that you cannot search for contents of the fields using the search box in the top right.
Example: I create a list and add the custom field "comment". Then I add the following subscriber: ( {Address:"test@example.com", FirstName: "John", LastName: "Dow", Comment: "nocomment"}. Now when I enter "nocomment" into the search box I get no results. Yet when I enter "John" the subscriber is listed as he should be. I think the same should be true for the contents of the custom fields.

**Comment by foleac** [comment]
Does this make it any clearer? Do you need screenshots?

**Comment by bures** [comment]
Yep. You are right. I have this implemented in Mailtrain v2. I assume I might have an alpha pre-release ready  in about 1-2 month. However, it may take a few more months to become sufficiently stable.

**Comment by foleac** [comment]
This is good news. Keep up the good work!

**Comment by forgeOneHQ** [comment]
@foleac I am closing this issue since v2 is already stable :)

You are welcome to help testing and improving it!
