### ISSUE TITLE
Users automation

### ISSUE THREAD

**Issue by killua-eu** [Mailtrain-org/mailtrain#461]
Hi, I'd like to add user management to the ansible role we use to install mailtrain (https://github.com/vaizard/mage-mailtrain). I guess that per https://github.com/Mailtrain-org/mailtrain/blob/master/lib/models/users.js, mailtrain uses bcrypt password hashes. I tried to pregenerate passwords from shell/python with `python -c 'from passlib.hash import bcrypt; print bcrypt.hash("test")'` but the generated hashes didn't match against the tests within mailtrain. Any pointers what I might be missing?

Thanks in advance, Pavel

**Comment by bures** [comment]
I gave it a quick try. It seems that the bcrypt we use in mailtrain uses some older version of the algorithm. Try: `from passlib.hash import bcrypt; print(bcrypt.using(ident="2a").hash("test"))`

**Comment by eagleamon** [comment]
Hi, just tried this on python 3.7.3 with passlib 1.7.1 but the hash is still different:

`>>> from passlib.hash import bcrypt; print(bcrypt.using(ident="2a").hash("test"))
$2a$12$yiiPEazOvv8K2VJUXwjYKO2cGLHGBXfL20KNaUOfWCiUuuxpRmXka`

whereas in db:
`$2a$10$mzKU71G62evnGB2PvQA4k..Wf9jASk.c7a8zRMHh6qQVjYJ2r/g/K`

also tried 2,2y,2b.
