### ISSUE TITLE
Widget displays JSON parse error when email address already on the list 

### ISSUE THREAD

**Issue by jesseskinner** [Mailtrain-org/mailtrain#462]
When an email address is entered into the subscribe widget, and already exists on the list, then it displays this below the form: `JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

I see it makes a POST to /subscription/xxx-XXXXX/subscribe and that responds with a 302 status code and an empty body. Trying to JSON.parse the empty body causes the error above.

Thanks for such a great product, and apologies in advance if this error turns out to be caused by a misconfiguration on my end.

**Comment by wdarking** [comment]
Same problem here, did you manage to solve it @jesseskinner ?

**Comment by jesseskinner** [comment]
@wdarking nope, I still have the problem.

**Comment by forgeOneHQ** [comment]
@jesseskinner I guess this is v1 related, can you try again with v2 and look if the issues persists? You are welcome to test and open a new issue. :)
