### ISSUE TITLE
Emails are missing character set.

### ISSUE THREAD

**Issue by phol** [Mailtrain-org/mailtrain#464]
First of all, let me start by saying I really like this piece of software, as far as I have now been able to test it out.

I am currently testing Mailtrain for use in a small club.
We use the following software:
- Ubuntu 18.04
- Postfix 3.3.0
- Rspamd 1.7.9 with standard rules

I noticed while checking the logs that, at least when using Mosaico, Rspamd reports that the character set is missing in the message:
R_MISSING_CHARSET(2.5)
This causes the message spam score to increase by 2.5 points in Rspamd.
A missing character set might also be bad for spam scores when using other spamfilters.

I then checked the messages sent by mailtrain.
This is the current situation:
```
Content-Type: text/html"

and

Content-Type: text/plain
```
I think it should be this:
```
Content-Type: text/html; charset="UTF-8"

Content-Type: text/plain; charset="UTF-8"
```

**Comment by bures** [comment]
Thanks for reporting it. I'll have a look.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
