### ISSUE TITLE
Mosaico - image adding problems

### ISSUE THREAD

**Issue by krzyzaq** [Mailtrain-org/mailtrain#469]
Hello, I'm fresh with Mailtrain, but I have almost all configured. When I try to manage template and add photos/images error occures that stops the mailtrain service and blocks adding the images to server. GrapeJS is working fime. I've also copied uploaded gallery from grapejs upload folder to mosaico, but those appear as white rect's.
infoHTTPGET /mosaico/dist/vendor/skins/gray-flat/content.inline.min.css 304 1.600 ms - -
events.js:183
throw er; // Unhandled 'error' event
^

Error: spawn convert ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:362:16)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickDomainCallback (internal/process/next_tick.js:219:9)
npmERR!codeELIFECYCLE
npmERR!errno1
npmERR!mailtrain@1.24.0 start: `node index.js`
npmERR!Exit status 1
npmERR!
npmERR!Failed at the mailtrain@1.24.0 start script.
npmERR!This is probably not a problem with npm. There is likely additional logging output above.

npmERR!A complete log of this run can be found in:

what is the issue and is there a solution?

**Comment by GabrielStetco** [comment]
+1

**Comment by bago** [comment]
Do you have ImageMagick's convert command installed and in path?
E.g: running "convert" on the command line should give you imagemagick help.
