### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by M4tZeSS** [Mailtrain-org/mailtrain#473]
Hello all,

I would like an Dutch translation for Mailtrain. Can this happen?

Thanks in advance,
-Mathis

**Comment by devMCpro** [comment]
You can write a translation using eg. poeditor.

**Comment by M4tZeSS** [comment]
> You can write a translation using eg. poeditor.

I know, but I don't exactly have the time to write it myself, and there's probably someone out there with the paid version of PoEditor to translate it automatically.

**Comment by M4tZeSS** [comment]
Can someone help here?

**Comment by forgeOneHQ** [comment]
@M4tZeSS I guess this was for v1, you are welcome to to participate on this project.

I am closing this issue right now, to get a better overview on the latest issues.
