### ISSUE TITLE
PHP API library -Testers needed

### ISSUE THREAD

**Issue by giorgioma** [Mailtrain-org/mailtrain#475]
Hi there,

I have published a PSR-4 [PHP Mailtrain API Library](https://github.com/giorgioma/MailtrainApiPhp)
if there are any PHP developers here any feedback and contribution is welcome :)

**Comment by Avalarion** [comment]
Hey @giorgioma we are currently planning to use mailtrain and other systems more often and use PHP as base for most of our applications so I will come back to this test. Thanks for your work!

**Comment by giorgioma** [comment]
FYI I developed this to integrate some features for a client with mailtrain v1 not v2
