### ISSUE TITLE
Cannot get widget to work

### ISSUE THREAD

**Issue by frankdilo** [Mailtrain-org/mailtrain#481]
Hello, thanks for this amazing project.

I am running my own installation of Mailtrain and I cannot get the widget to work because of a CORS problem.

I added all the domains that should be able to embed the widget in the configuration file (`config/docker-production.toml.tmpl`), but still can't access all the widget-related urls and can't see the CORS headers set by inspecting the headers? I restarted the Docker containers and destroyed/recreated them multiple times (that doesn't seem to be the problem).

Am I missing something? Documentation isn't very clear on the widget, I would love to contribute back to it once I get this fixed.

**Comment by sweetppro** [comment]
same problem :(

**Comment by frankdilo** [comment]
Not really. 

The way I ended up solving this is by creating my own backend, with an endpoint allowing CORS requests, that made it easy to subscribe from any webpage. My backend knows the Mailtrain secret and can subscribe anyone with just a POST request.

**Comment by snarlynarwhal** [comment]
Thanks for the info, I appreciate it very much.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
