### ISSUE TITLE
Mailtrain do not actually use the Throttling setting with my SES

### ISSUE THREAD

**Issue by mygitaccount2** [Mailtrain-org/mailtrain#485]
Hi 

i have configured all correctly in settings but mailtrain decide to send everything in one block
instead of the 30 email per hours i had configured, 
how to fix this ?

**Comment by tmikaeld** [comment]
See the **Additional settings** at the bottom here:

https://github.com/Mailtrain-org/mailtrain/wiki/Using-SES

Make sure you take all into account.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
