### ISSUE TITLE
Mailtrain v2 - What would you like to see in campaign stats?

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#490]
As we are getting closer to beta release of Mailtrain v2, I would like to ask for proposals what statistics and graphs you would like to see in the campaign status (i.e. opens, clicks/links, etc.) If you make a suggestion, please assign also a priority to it (like CRITICAL, IMPORTANT, NICE TO HAVE).

Thanks.

**Comment by hoducha** [comment]
Cool, glad to hear the beta release is coming soon. Thanks @bures for your time and effort put into this project. This is my proposal for the statistics and graphs. I think the graph is important for tracking the performance of a campaign.

![campaign-stats](https://user-images.githubusercontent.com/3087444/50371102-bba0b800-05e6-11e9-9dfe-5c2811c59824.png)

**Comment by bures** [comment]
Looks good. At this point, I implements some basic overview (pie chart and a map) as it was in Mailtrain v1. My intention is to integrate IVIS (https://gitlab.d3s.mff.cuni.cz/evif/ivis-core) with Mailtrain. That should give us the possibility of relatively advanced and user-definable graphing.

**Comment by hoducha** [comment]
The idea of user-definable graphing is very interesting. I look forward to seeing IVIS version of Mailtrain.

**Comment by forgeOneHQ** [comment]
I am closing this issue, v2 is already out.
