### ISSUE TITLE
mailtrain not working from script install

### ISSUE THREAD

**Issue by ajmalkhanjamro** [Mailtrain-org/mailtrain#493]
hello it used to work with script install in Ubuntu every time i used it quite alot of time it install on port 80 which is basically apache port so i remove apache it always works but today i got intresting nothing was working not even on centos 7 i tried it same error what could be issue

[EDIT]

so i found the issue in script which causing it here are the lines which cause it 

`MYSQL_ROOT_PASSWORD=`pwgen 12 -1`

debconf-set-selections <<< 'mariadb-server-5.5 mysql-server/root_password password $MYSQL_ROOT_PASSWORD'
debconf-set-selections <<< 'mariadb-server-5.5 mysql-server/root_password_again password $MYSQL_ROOT_PASSWORD'`

so this caused issue i dont know how i can fix it

**Comment by vitetj** [comment]
In my case before run the script  i did 

yum update   

yum install pwgen 


That fix this issue
