### ISSUE TITLE
Delivered Campaign Statistic stuck

### ISSUE THREAD

**Issue by jessebrightman** [Mailtrain-org/mailtrain#497]
Hello all,

Thank you to all contributors.  I have been using this program for months without fail, but recently have migrated to a new server and now the delivered statistic is stuck.  Out of a mailing list of 13991, 'Delivered' is stuck at 73.  I have confirmed with my mailserver that all emails were indeed sent out and 'Opened' shows 237 so far and is updating as expected.  Anyone else have this happen or know of a fix?  Much appreciated.

**Comment by ajmalkhanjamro** [comment]
> Hello all,
> 
> Thank you to all contributors. I have been using this program for months without fail, but recently have migrated to a new server and now the delivered statistic is stuck. Out of a mailing list of 13991, 'Delivered' is stuck at 73. I have confirmed with my mailserver that all emails were indeed sent out and 'Opened' shows 237 so far and is updating as expected. Anyone else have this happen or know of a fix? Much appreciated.

same issue with me on centos7 server and ubuntu dose not even work

**Comment by jessebrightman** [comment]
Yes, I am using Centos6, which was the same as the old server and was working perfectly before I migrated to the new server.  I will take some time to check out the code and see what I can find.

**Comment by jessebrightman** [comment]
For some reason all the statistics are working correctly now.  I will now close this issue.

**Comment by ajmalkhanjamro** [comment]
if any stumble upon here the issue was the redis server which dose not turn on by default you have to daemonise it to run it background then restart mailtrain it will start working
