### ISSUE TITLE
[[ QUESTIONS ]] how to modify "return to website url" and change "email address" field to just "email"

### ISSUE THREAD

**Issue by babatundebusari** [Mailtrain-org/mailtrain#499]
I will like to do 2 things

#1. change the `return to ur website` url to custom per list i have.
This is needed if i have multiple brands, so 1 list per 1 brand and want the url to be for each brand 

#2. the `email address` field is required but how can i change it to just `email`?

**Comment by babatundebusari** [comment]
finally figured 1 out but seems number 2 is not possible but manageable

**Comment by yashsaxena** [comment]
@babatundebusari you should share what you did for other to figure out what you did. It might be helpful.

**Comment by babatundebusari** [comment]
i figured out that i needed to create custom form and modify the custom form to show what website i wanted as return url...the email address field, am unable to change to just email..i think that one is permanent field that comes with mailtrain..so no way to modify that
