### ISSUE TITLE
Piwik plugin

### ISSUE THREAD

**Issue by HLFH** [Mailtrain-org/mailtrain#50]
Hi,

Would it be interesting to integrate Mailtrain in [Piwik as a plugin](http://piwik.org/integrate/)?
I don't have enough argumentation right now, but I'm really curious to see your point of view.

Thanks,
HLFH

**Comment by andris9** [comment]
It probably would make sense. I don't have time for this for now but if anyone wants to work on it, then it's free to take

**Comment by forgeOneHQ** [comment]
@HLFH if still interested in you can add participate and help developing it as @andris9 wrote. :)
