### ISSUE TITLE
Subscription Widget - Email gets sent, but subscription notice fails due to CORS

### ISSUE THREAD

**Issue by snarlynarwhal** [Mailtrain-org/mailtrain#500]
I enabled CORS for my sites and the subscription itself works. It fails when trying to show the subscription notice. Any ideas?

`Access to XMLHttpRequest at 'https://mail.halfhumangames.com/subscription/rJfit7pAM/confirm-subscription-notice' (redirected from 'https://mail.halfhumangames.com/subscription/rJfit7pAM/subscribe') from origin 'https://dwerve.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

After investigating further, I've found that it only seems to happen when attempting to subscribe with an email that has already been subscribed.

**Comment by elitzer2** [comment]
This is fixed in v2 (development branch) by this PR https://github.com/Mailtrain-org/mailtrain/pull/948
