### ISSUE TITLE
Can't edit grapes template

### ISSUE THREAD

**Issue by Vartkat** [Mailtrain-org/mailtrain#504]
node v8.14.0
npm 6.5.0
running behind Apache proxy on Ubuntu 16.04

After saving a template made with Grapejs if I get back for editing I get a weird page 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/1696899/50389399-24447d80-072a-11e9-80cd-2697f982f3af.png">

As you can see Safari says syntax error and it also fires an error for file not found for grapes.min.js.map. I searched, there's no such file in Mailtrain.

On Firefox the errors is
SyntaxError: "" literal not terminated before end of script .................editor:253:68691

I dug a bit and perhaps found something that could help 
https://stackoverflow.com/questions/227552/common-sources-of-unterminated-string-literal

especially the comment saying 
' I changed "</script>" to "</scr"+"ipt>" and that fixed it'

**Comment by forgeOneHQ** [comment]
@Vartkat please try again with v2 if you still have the same situation and open a new ticket if you run into issues.

Since this issue is v1 related I close it.
