### ISSUE TITLE
Mailtrain v2 Beta - manual install on single domain with 3 separate ports

### ISSUE THREAD

**Issue by sweetppro** [Mailtrain-org/mailtrain#506]
I am currently running MailTrain v1 on a **Centos 7 Plesk subdomain**, with a **LetsEncrypt wildcard ssl certificate installed** on the primary domain. I would like to manually install v2 into the subdomain using separate ports for the various components of the app. This would enable me to utilise the already installed ssl certificate, and keep everything packaged up nicely for Plesk's admin interface:
[Plesk Admin Panel.jpg](https://postimg.cc/qgz3PQKV)

any pointers on a manual install for this configuration would be appreciated.

**Comment by bures** [comment]
I had a quick look at Plesk. As far as I understand, you can configure HTTPS proxy through Plesk, isn't it? Something like this: https://stackoverflow.com/questions/37248699/sub-domain-with-different-ports-in-plesk ?

If so, then it should be enough to:
1) do local install of Mailtrain (there are the *-local.sh scripts in setup directory)
2) Update base urls in server/config/production.yml
3) Configure NGINX or HTTPD in Plesk to provide the HTTPS proxy. An example for multi-domain HTTPS proxy conf for Apache is in setup/mailtrain-apache-sample.conf

Just let me know if you need help with Mailtrain config or the Apache config file.

Unfortunately, I'm not familiar with Plesk, so I can't help much there. Anyway, if you figure out, a corresponding section on installation in Plesk in the README.md would be very appreciated.

Thanks.

**Comment by sweetppro** [comment]
im totally in over my head here... server setups are not my strong point.
ill have another go at this tomorrow

**Comment by bures** [comment]
No problem. If you can't figure out and unless someone else can help, just send me screenshots of the UI (either here or directly to bures@d3s.mff.cuni.cz). I can take a look and hopefully figure it out how to set it up.

**Comment by sweetppro** [comment]
its difficult to configure, as the structure is different to a normal nodejs app.  Plesk needs the Application Root/Document Root/Startup File locations. the application root seems to be the `shared` directory, but the Document Root seems to be the `client/static` directory. This is a problem for Plesk as the Document Root is not a direct child of the Application Root.

Ive tried adding symlink for the `static` directory into the `shared` folder. I also tried setting the Application Root as the `mailtrain` folder, and adding hardlinks to the `app.js` and 'package.json` files.

Im also trying to NPM install via Plesk.... which probably isn't going to work anyway...
is there anything else I could perhaps try?

**Comment by bures** [comment]
I had some quick look at Plesk. It seems that it does not support more complex web apps that require more ports to function. I think it's better to use the Docker container. 

I could create the option to strip down Mailtrain to run only on one port, but I would like to see that there is some interest in this before investing time to it. 

Please note that if that runs on one port, it is suitable only for deployments where users that create templates and custom forms are admins.

Please vote whether single port deployment is a critical functionality for you.

Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
