### ISSUE TITLE
Mailtrain V2 Beta npm ERR! Invalid Tag Name bounce-handler@7.3.2-fork.3

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#507]
I'm getting
npm ERR! invalid tag name bounce-handler@7.3.2-fork.3 Tags may not have any characters that encodeURIComponent encodes
then it crashes out and won't allow me to finish the install

if I delete the mysql database and users and start the script again it runs to the same place and crashes out.

I'm running the Ubuntu 18.04 in virtualbox

Thanks

**Comment by bures** [comment]
My bad. Please try it now.

**Comment by mantisae** [comment]
That fixed that problem however now I'm getting Mailtrain is starting try again after a few seconds
and then a white screen with this in the console

> root.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
> (index):36 Uncaught ReferenceError: MailtrainReactBody is not defined
>     at HTMLDocument.<anonymous> ((index):36)

Thanks for your time and effort

**Comment by bures** [comment]
My guess is that your www.trustedUrlBase, www.sandboxUrlBase and www.publicUrlBase in the server config do not correspond to the URL you use to access Mailtrain. 

Could you please send me the URL that you use to open the page and also the source of of the page that shows only as the white screen. I'll check it if it is indeed the misconfiguration of the url bases.

In any case, I'll add some diagnostics in the page to give a warning if the url bases are misconfigured as this is likely to be a common pitfall.

**Comment by bures** [comment]
Excellent. I assume that it works for you now. I'm thus closing this issue.
