### ISSUE TITLE
Mailtrain V2 Beta created: in 5 hours

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#509]
When creating anything the main listing pages Created column is showing "in 5 hours" when I create it. 
 My timezone is America/New_York suggesting that it's using UTC time instead of adjusting for local time. I see no option in the interface to set the timezone, I also checked the default and production config files as well and my system time is set correctly.

**Comment by bures** [comment]
I just pushed a commit that should hopefully fix it. Please try it out.

Please note that this contains also commits related to migration to Bootstrap 4 and React 16. Also the DB driver was changed, so you will have to reinstall all modules and build the client again. The easiest is if you execute the following from the root mailtrain directory:

```
for idx in client shared server zone-mta; do
(cd $idx && npm install)
done
    
(cd client && npm run build)
```

**Comment by mantisae** [comment]
Yep that fixed it it's now telling me a few seconds ago

**Comment by bures** [comment]
Excellent. Thanks a lot for quick response. I'll thus close this issue. Thanks a lot for help with testing.
