### ISSUE TITLE
Mailtrain Beta V2 merge tag errors

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#510]
- [MERGE_FIRST_NAME][MERGE_LAST_NAME] fields do not exist when list is created

- merge tags for custom fields do not show up in the merge tag reference (they do show correctly in sent emails)

- [TO_NAME] & [CAMPAIGN_ID] tags do not change when email is sent

**Comment by mantisae** [comment]
ad 1) Working

ad 2) I apparently don't read help text very well

ad 3) Fixed

the [CAMPAIGN_ID] works when you're in a campaign that's another one on me I was sending from the GrapesJS template designer without being in a campaign

**Comment by equilibrium123** [comment]
Hello Guys, Am also trying to test the mailtrain 2 and the placeholder for FIRST_NAME does not show the real name on the list in the email sent. I use Hello  [MERGE_FIRST_NAME],  use [FIRST_NAME ] and even [FIRST]. It shows exactly what is put in there.

Please how can I fix this?
Thanks

**Comment by equilibrium123** [comment]
It worked when I use placeholders for handlebars template viz:   {{MERGE_NAME}}
This [MERGE_NAME] does not work

**Comment by anuskasthapit98** [comment]
Hi i am using the GrapeJs template and i don't know where to put the merge tag [LINK_BROWSER] in my html code.
