### ISSUE TITLE
Mailtrain Beta V2 Segment Rules Values will not accept input

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#511]
I attempted to create a new segment and set the email to an SQL Like for %@domain.com and it would not let me type anything in the value field

I then attempted with a custom number field same result however I switched the input back to the email and the value field then showed an unremovable or unchangeable 8

**Comment by bures** [comment]
This should be fixed now. Thanks for reporting it. Please try it out.

**Comment by mantisae** [comment]
Fixed however the save after creating rules is up in the top right and I missed it the first time after hitting ok on the rule creation.  It might be a good idea to put a second save button under the rules creation section.

**Comment by bures** [comment]
Good point. I moved the "Save" button below the rules. Thanks. I'll close this issue. If there are any more points, please reopen it. Thanks.
