### ISSUE TITLE
Mailtrain V2 Beta EACCES: permission denied, mkdir '/opt/mailtrain/server/files/imports'

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#512]
When attempting to upload a csv to create an import on a list after hitting save and edit it redirects me to the homepage with "EACCES: permission denied, mkdir '/opt/mailtrain/server/files/imports'"

After going and changing the permissions on the files directory from root:root to mailtrain:mailtrain it continued properly however I had created 9 fields and it ran them off the page and wouldn't let me scroll (in chrome) I tried firefox and it scrolled fine

The chrome console error was
`/rest/imports/2:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
webpack://MailtrainReactBody/./src/lib/page.js?:396 Error: Request failed with status code 500
    at createError (webpack://MailtrainReactBody/./node_modules/axios/lib/core/createError.js?:16)
    at settle (webpack://MailtrainReactBody/./node_modules/axios/lib/core/settle.js?:18)
    at XMLHttpRequest.handleLoad (webpack://MailtrainReactBody/./node_modules/axios/lib/adapters/xhr.js?:77)`

Once I got that working I was able to import my demo data

**Comment by bures** [comment]
The permission problem should have been fixed by cfdcaf65d8adf1cbaf0fe5875a214229bb74431c (about 5 days ago). Please, could you try it out again with the newest version?

I'm not sure if I understand the problem with 9 fields. I tried to replicate what I understood in my settings (in Chrome), but all looks OK. 

Thanks.

**Comment by mantisae** [comment]
Last night when I tried to create an import the 9 fields pushed the submit buttons off the page and I couldn't scroll in chrome.  I then went and opened firefox and it scrolled fine.  When I came back this morning and tried again in chrome it scrolled just fine.  Probably a glitch in my browser.
