### ISSUE TITLE
Mailtrain v2 Beta Mosaico thumbnail and saving of template

### ISSUE THREAD

**Issue by devlarjay** [Mailtrain-org/mailtrain#516]
Hi @bures it's me again though I am having new issues on hand. Apologies for bring another one but I think it might be helpful as well for the community. Anyway, my problem is I can't see the thumbs properly. No luck in dragging the images as well from gallery to the block. Can you help me please?

![image](https://user-images.githubusercontent.com/46402579/50734927-a54b4c80-11e1-11e9-9bbd-c1b66f85949c.png)

**Comment by bures** [comment]
You're right. There seems to be some problem with generating the image placeholder on the server side. I'll check it.

**Comment by devlarjay** [comment]
Any news on this? @bures :)

**Comment by bures** [comment]
I pushed it to the development branch. Please try it out and reopen the issue if needed.
