### ISSUE TITLE
Abnormal behavior of delivered, opened and link clicks analytics.

### ISSUE THREAD

**Issue by engineerdeep** [Mailtrain-org/mailtrain#517]
Hi. Sorry for a mix of questions in a single post, didn't think it was necessary to create separate issues for them.  So I have a few questions,

1. I recently sent a mail to about 250+ recipients, the delivered count showed 170 and opened count showed 200+, which means the mail was sent to more than 170 users. I'm unable to understand why the delivered count would get stuck at 170? 

2. I had to disable link clicks analytics because if that is enabled, every link that is sent, the link is converted to {myurl}/links/{campaignid}/{listid}/{subscriptionid}. Which obviously does not open the url properly. I understand it needs the following parameters to understand who clicked the link, but how would I let people open the link correctly AND also get analytics?

3. I don't know what this issue is, I've tried sending about 50 mails and faced a weird behavior. Let's say my Service URL in settings is : **http://localhost:3000/abc/def/** (localhost just for example sake, it's an internet exposed url otherwise so I get analytics correctly.)

When the mail is sent, sometimes the pixel src url that is sent is **http://localhost:3000/abc/def/links/{campaignid}/{listid}/{subscriptionid}**, in which case I receive the analytics. 
Some mails the pixel src url is
**http://localhost:3000/links/{campaignid}/{listid}/{subscriptionid}**, in which case the opened analytics don't work obviously. I can't understand how it truncates "/abc/def/" sometimes. 

4. If a mail is forwarded, the opened count gets increased by 3 always. Why & How could I make it to 1?

Answers to any of the above would be greatly appreciated.

Thanks

**Comment by brentkearney** [comment]
>  {myurl}/links/{campaignid}/{listid}/{subscriptionid}. Which obviously does not open the url properly

Why would it not open the url properly? It works for me. That is, it forwards to the original URL after updating the counter.

I have only tested with a list membership of 2. The analytics showed 2 deliveries, but clicking the + to expand had only a list of 1 member. The missing member also clicked the unsubscribe link, so maybe that has something to do with its being missing from the delivered to list? Even after re-subscribing that email to the list, it does not appear.

**Comment by bures** [comment]
Is this Mailtrain v1 or v2?

**Comment by Developer-Deep** [comment]
It was Mailtrain v2. The issue of the url not opening correctly was because of my third issue. After the counter is incremented, the url that gets sent is the truncated one hence it wouldn't open. Till the end I couldn't figure out why sometimes the url would be truncated and sometimes it wouldn't, Never got to fix that.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
