### ISSUE TITLE
Ansible role to setup Mailtrain 2 (mage-mailtrain)

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#518]
Had a brief look on the setup directory as I'd like to update https://github.com/vaizard/mage-mailtrain/ an ansible playbook automating mailtrain deployment to support v2 as well. I notice that the development branch 

- drops the setup/sql directory. is this by intention or by mistake? when/where/how does the database scheme get installed and updated?
- adds a mongodb dependency. again, is this intentional? both mysql and maria have a mature support for json documents stored inside sql tables, all with querying, indexing and stuff.

thanks for the clarification.

_Originally posted by @killua-eu in https://github.com/Mailtrain-org/mailtrain/issues/505#issuecomment-453868853_

**Comment by bures** [comment]
ad 1) It's located in server/setup/sql. However, Mailtrain 2 combines the original approach to migration with Knex.js. It first runs the original migration mechanism to get the DB to a latest state in Mailtrain v1 and then uses Knex migrations (located in server/setup/knex/migrations) to bring it up to date with Mailtrain v2. 

The original mechanism is also used to bootstrap the DB. The bootstrap sql file is located in server/setup/sql/mailtrain.sql. It contains a snapshot of a DB fully updated to Mailtrain v2.


ad) The mongodb dependency is because of builtin ZoneMTA. Mailtrain itself does not use mongodb, however ZoneMTA does. Mailtrain provides the ability (enabled by default) to run an instance of ZoneMTA. This significantly simplifies the setup because a mailer does not have to be installed manually. Mailtrain also integrates better with this builtin ZoneMTA, so different DKIM keys can be entered in Mailtrain and they are dynamicaly selected and used by the builtin ZoneMTA. 

If you like to deactive the builtin ZoneMTA, you can do so via server config. Look for builtinZoneMta/enabled. Once deactivated, the mongodb dependency is no longer needed. Note however that also another DB bootstrap file will likely be needed, because mailtrain.sql introduces a send-configuration that relies on the builtin ZoneMTA. This configuration won't be able to deliver emails unless changed (via the web UI) to another sending mechanism.

**Comment by killua-eu** [comment]
Thanks for the explanation! ZoneMTA inclusion makes sense, the role for mailtrain v1 pulls it always to have a default mailer. The role also supports mailgun, which I've been using in production, so once i've updated it to support v2, I'll let you know if all works well.
I assume the easiest upgrade path between version 1 and version 2 is to:

- keep mysql data as they are
- delete /opt/mailtrain (or whichever path mailtrain v1 is installed to)
- install mailtrain 2 over it.

right?

**Comment by bures** [comment]
Yes. Pretty much. Just backup the DB because the migration from v1 to v2 is not properly tested. At least at this points, it's a bit "fingers-crossed" process.

**Comment by killua-eu** [comment]
Cool. I'll get to work on this in the next few days. BTW I noticed that v2 exists by running into a deployment error. Installing master complained about missing ajv@^5.0.0 dependency and dependencies needing fixing. Do you still support v1 or focus on v2? Should I report the v1 install errors?

**Comment by bures** [comment]
Thanks for giving it a try. It's good if you report the v1 error. Hopefully someone will take care of it. As my capacity is limited, I would like to keep focus on v2 only. The sooner we bring it to production readiness, the better. I think that already now it works decently well to be a viable option for new deployments.

**Comment by bures** [comment]
One more thing, I'll be happy if you give it a try with the Mailgun. I could not test it. I only took and refactored the Mailgun-related code from v1. So very likely it's not gonna work. But if you let me know, I'll guide you in debugging and will fix it. Thanks.

**Comment by bures** [comment]
Is there any new development on this or shall I close the issue?

**Comment by killua-eu** [comment]
My bad :-/ I got really busy. Lets keep this open please, I should get some breathing time once I wrap up an other big infra project.

**Comment by bures** [comment]
No problem. I got myself tied up with many things at work too. So the progress on my side is much slower than I would wish.

**Comment by golmanosocks** [comment]
Any updates on this and the mailgun integration? 
Webhooks are still not working see #561

**Comment by nicksellen** [comment]
I created an ansible role for installing mailtrain 2 (development branch) to a server, it's probably a bit specific to our setup to be generally usable, but maybe some ideas in there https://github.com/trustroots/trustroots-ansible. No ZoneMTA either. It's made mostly from reading the contents of `setup/functions`.
