### ISSUE TITLE
Reply to address not possible with triggered campaign

### ISSUE THREAD

**Issue by ansgarsmith** [Mailtrain-org/mailtrain#519]
When creating a normal campaign it is possible to specify a reply-to address. But when I create a triggered campaign this is not possible. Is there a different way of specifying a reply-to address for a triggered campaign?

**Comment by bures** [comment]
If I understand your question correctly, you should be able to do that in Mailtrain v2 beta.

**Comment by ansgarsmith** [comment]
Thanks Bures, is the beta version stable enough for daily use? Any expectations when it is ready to be a stable release?
