### ISSUE TITLE
Mailtrain v2 Beta show view code button in GrapesJS MJML

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#520]
V1 had a view code button in GrapesJS is there a chance we could get that back in V2?  I recorded a slow-mo video of the page loading and it looks like it's just being hidden but I can't find it in the code inspector on the page after it finishes loading.

**Comment by bures** [comment]
Good point. I'll check it.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
