### ISSUE TITLE
help nedded Guide: How to create new route/page

### ISSUE THREAD

**Issue by Arkango** [Mailtrain-org/mailtrain#522]
Hi, I added a route correctly called, the files of that added in root.js of client/src.
There is a list of route enabled ? How i can add them to show the content.
React is undebuggable. Now i can see only a page with toolbar. Someone can help me?.
![screenshot_2019-01-19_20-24-23](https://user-images.githubusercontent.com/23188987/51431383-3c73c380-1c28-11e9-8aff-f34b566d796c.png)

**Comment by bures** [comment]
Is this still a problem or can I close the issue? I'm afraid, I don't have the capacity to help with general React issues. If there is a problem with Mailtrain v2, I'll be happy to help.

**Comment by Arkango** [comment]
There is a simple schema how to add a react page in this application. Only
if it is possible please.

Il giorno dom 17 feb 2019, 13:59 Tomas Bures <notifications@github.com> ha
scritto:

**Comment by bures** [comment]
Just follow the example of client/src/Home.js. The page has to be registered in client/src/root.js. And then don't forget to recompile the client (best done with `npm run watch` in `client` directory).

**Comment by Arkango** [comment]
Thanks a lot

Il giorno dom 17 feb 2019, 14:18 Tomas Bures <notifications@github.com> ha
scritto:
