### ISSUE TITLE
Ivis-core submodule reference pointing to private repo

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#524]
I'm trying to install v2 and when trying to init the submodules, `ivis-core` tries to connect to a private Gitlab repo and asks for authentication. Maybe I'm wrong or missing something, but shouldn't the submodule reference point to the [Github repository](https://github.com/gerobit/ivis-core)?

The commit hash the subdmoule is pointing to (currently `a9ad4ba`) is found on the Github repo, too, so I'm guessing the Gitlab one is a mirror and I'm just cloning the Github one under my `mvis/ivis-core`.

**Comment by bures** [comment]
Thanks for reporting. It should be fixed now. Mailtrain does not use the project yet (it's gonna be there for analytics), but it's good to have it correctly in place.
