### ISSUE TITLE
Create campaign API

### ISSUE THREAD

**Issue by ilyacherevkov** [Mailtrain-org/mailtrain#525]
Can I create campaign via API? I need to generate custom emails for different user segments on the fly.

User opts-in for particular categories of information, and I need to limit information included into the email according to user preferences.

**Comment by bures** [comment]
I'm afraid there is none. I'll be happy to accept a PR on this to Mailtrain v2. Alternatively please describe your particular requirements and use-case and I'll be happy to consider it to implement it myself to Mailtrain v2.

**Comment by ilyacherevkov** [comment]
Hello, @bures 

Thank you for your response. I found the option to fetch message source from URL. This way I don't need API, i ll gust pull dynamic content at the time sending

**Comment by bures** [comment]
Perfect. Thanks.

**Comment by ericuldall** [comment]
Hi @ilyacherevkov or @bures,

Where can I find the "option to fetch message source from URL" ? I'm not seeing that in the V2 template or campaign settings...

**Comment by ericuldall** [comment]
> Hello, @bures
> 
> Thank you for your response. I found the option to fetch message source from URL. This way I don't need API, i ll just pull dynamic content at the time of sending.
> 
> As I understood, mailtrain will post parameters to that URL, and I'll generate relevant HTML. Im interested in how to handle plaintext template in this case though.

Also wondering about plain text here... Any update?

**Comment by ericuldall** [comment]
@ilyacherevkov I've been digging through the code for dynamic content and found that in this case the message text is just set to an empty string. I'm going to submit a PR that will allow for the endpoint called to return a json response like the following:

```
{
   "html": "html template here",
   "text": "text template here"
}
```

This is a pretty simple fix and I'll make sure that we can stay reverse compatible with people that are simply returning html.

**Comment by ericuldall** [comment]
I've created PR https://github.com/Mailtrain-org/mailtrain/pull/751 to address the missing text issue

**Comment by ericuldall** [comment]
Sorry, I reviewed some more and it seems the original code will attempt to make the text version from the provided html. As this could result in a less than desirable output, I think my PR could still be warranted just to give the end user full control over their text output. Please let me know if you guys think I'm missing anything else.
