### ISSUE TITLE
Mailtrain V2 Beta ZoneMTA passing localhost as helo

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#529]
I'm trying to get mailtrain set up with the built in ZoneMTA and DKIM but sending it to mail-tester.com is complaining that it's using localhost as the helo. It's set to zoneMTA Built-In ZoneMTA mydomain.com mailtrain and the private key I generated. DNS is set up and seems to be working, the DKIM SPF and DMARC additions are responding properly.  What am I missing?  I also tried the "dynamic configuration of DKIM keys via the mailtrain plugin" option with a domain of lists.mydomain.com.

**Comment by bures** [comment]
Just a guess. What is the hostname of you computer? Meaning what appears when you type `hostname`?

**Comment by mantisae** [comment]
that fixed it. However note I had to set lists.mydomain.com in the /etc/hostname file instead of just lists which would be the actual name of the machine.

**Comment by bures** [comment]
What about to set hostname as a fully qualified name? This is what I normally use on my Linux boxes.

**Comment by mantisae** [comment]
Once I did that it's working properly.

**Comment by bures** [comment]
perfect. thanks.
