### ISSUE TITLE
mailtrain v2 api !

### ISSUE THREAD

**Issue by shahzaibcb** [Mailtrain-org/mailtrain#530]
Hi,

First of all please allow me to appreciate the mailtrain development, its a great application. Now comming to the issue.
Calls via api for admin user working, however if we generate access_token for some other user such as username "test" with privilege of "compaign admin". API call generates "permission denied" error. 

`curl -XGET 'http://localhost.com:3000/api/lists/user@domain.com?access_token=d996d3a996493b643265ec93e1769a25b52638a3'
{"error":"Permission denied","data":[]}`

This access token was generated for test user under its own dashboard but it gives error.

**Comment by bures** [comment]
Could you double check it? I just tried, but it works for me.

```
[root@mailtrain ~]# curl -XGET 'http://localhost:3000/api/lists/xxx@example.com?access_token=bfbe4f67ac244feced3c06995b0f5688d484ba63'

{"data":[{"id":2,"name":"Test"}]} 
```

Have you setup any namespaces? If so, make sure the campaigns admin user has permissions to the list. Campaigns admin may by default access only lists that reside in the same namespaces as the user or in some namespace below.

If it still does not work, I would need to see you list settings and the user settings.

**Comment by shahzaibcb** [comment]
Hi,

I've deleted user, template, list, and namespace. Created it again under a new namespace and its not showing error now. I'll update further. 

Thanks for the response :)

**Comment by bures** [comment]
Perfect. In that case, I'm closing this issue. If anything does not work, please reopen it or create a new one. Thanks.
