### ISSUE TITLE
Send configurations, SMTP settings not properly hidden

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#533]
In the "Send configurations" page, in the "Mailer settings" section, there are 3 options: SMTP, Zone MTA and Amazon SES. Selecting SMTP displays the STMP-related fields, whereas Zone MTA hides it, but only when the "Built-in ZoneMTA" suboption is selected. When chosing any of the other 3 Zone MTA suboptions, the SMTP parameters are still shown (in my case, they are not empty because I tried them before).

**Comment by bures** [comment]
I double checked, but I think this is OK. If one wants to use a non Built-in ZoneMTA, one needs to say where it runs and on which port. Only if ZoneMTA is built-in, Mailtrain automatically configures the host/port, so there is no need to enter it. Or am I missing anything? Thanks.

**Comment by priethor** [comment]
Sorry for the invonvenience, as probably I am the one missing something. What confuses me the most is that settings for non built-in MTA and SMTP are the same, including the checkbox "Enable SMTP authentication". If external zone-MTA works like a normal SMTP, why do we need to differenciate it from SMTP?

I'm also confused by the 2 first zone MTA options, what's the difference between them:

> - Built-in Zone MTA
> - Dynamic configuration of DKIM keys via Zone MTA's Mailtrain plugin **(use this option for builtin MTA)**

Anyway, thanks for your help!

**Comment by bures** [comment]
It's there because ZoneMTA can load DKIM keys dynamically. It's true that when you select "Zone MTA" and "No dynamic configuration of DKIM keys" then it's the same as generic SMTP.

Regarding the "(use this option for builtin MTA)", that's a forgotten remnant from before built-in Zone MTA. I have already removed it from the help text. 

Thanks for help.
