### ISSUE TITLE
Migrated text based segment rules don't contain the "type" setting

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#535]
Following #532, where text-based rules crashed the migration script, the migration now finishes without errors but text-based rules are not migrated properly.

In v1, the rules where simpler to the extend they had only a rule (field) and a value, but now we can also define directly a type such as "equals to", "match", etc. The migrated text rules don't contain any type, only the column and the value.

**Comment by priethor** [comment]
As in v1 the value could contain wildcards such as %, I guess the default type added in migrations should be `Match (with SQL LIKE)`, right?

**Comment by bures** [comment]
Yes. I guess so. Thanks.
