### ISSUE TITLE
v2 - No "parent namespace" can be selected when creating/updating namespaces

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#536]
As the title says, when you open the page for creating/updating namespaces, the `Parent Namespace` dropdown is empty and nothing can be selected.

No traces are left in the logfiles or browser console.

**Comment by bures** [comment]
Indeed. I must have broken it by some update. I'll fix it now. Thanks for reporting it.

**Comment by bures** [comment]
Should be fixed now. Please try it out. Thanks.
