### ISSUE TITLE
embed external images within email

### ISSUE THREAD

**Issue by preexo** [Mailtrain-org/mailtrain#54]
phpList has just released version 3.2.5 and with it the possibility to embed external referenced images within the email automatically while sending out the email. 

I wouldn't necessarily say this is always a good idea, but it might make sense sometimes and is definitely a great feature, maybe mailtrain wants to put this on the list as well.

**Comment by andris9** [comment]
I guess there should be an option to turn this on or off (in case you really want the images to be linked, for example to use custom tracking etc.). I wonder though, should the embedding be turned on or off by default?

**Comment by forgeOneHQ** [comment]
I close this issue since it is more a feature request and v1 related.
