### ISSUE TITLE
Feature request - Confirmation modal when launching campaign

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#542]
In v1, there was a javascript alert that prompted for confirmation when launching a campaign. It certainly wasn't the most good looking popup, but it did save us from accidentally launching big campaigns by mistake a couple of times.

Although I'm no React developer, it shouldn't be hard to add a modal similar to the existing ones, but I would like to ask the community: am I the only one who misses this feature? What's the community's opinion?

**Comment by bures** [comment]
I believe it's a good feature. I'll put it on my todo list.

**Comment by priethor** [comment]
Fixed in #564
