### ISSUE TITLE
Feature request for v2 - Show confirmation when user want to leave a page with unsaved changes

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#544]
It would be good to present a modal when someone wants to close a tab (or navigate back) from a page where there are unsaved changes. Now when no such confirmation is shown, it's pretty easy to loose any changes one does when editing a template or similar.

**Comment by priethor** [comment]
I agree, in fact it's one of many similar UX pain points I've noticed. A similar one is when you edit and save a campaign/template tab and the browser goes back to te campaign/template list, which means you need to search again for that campaign/template if you want to keep editing it. This can be quite annoying as long as there is no namespace filtering as discussed in #543 or any table filtering other than the search by name (no status or type filters, mainly).

Should we make a full list of these *smaller* pain points in just one issue to have a better scope?

**Comment by bures** [comment]
Yes. The thing with going back to the list is also a thing I noticed. Maybe we can always have buttons "Save" and "Save and go back" or similar.

A list of such smaller pains would be good. At least it does not get forgotten and hopefully someone will fix it before we get so much used to the pain that we stop realizing it.

**Comment by bures** [comment]
I just refactored all the form to offer whether to save and stay or save and leave. This should make the UI much easier to use because one does not have to look for an entity that has just been created.
See commit 4a6aed4cf74e5ebf33d425b0e7a47797d825fefe

**Comment by priethor** [comment]
Great @bures! I have just tested it and seems to work fine for Lists, Templates and Campaigns, will let you know if I see anything strange.

**Comment by forgeOneHQ** [comment]
I am closing the issue. The fix is in the latest v2 version.
