### ISSUE TITLE
Mailtrain V2 Unsubscribe button in subscriber lists erasing data

### ISSUE THREAD

**Issue by mantisae** [Mailtrain-org/mailtrain#545]
When I routed our campaign through our SMTP mailserver it wasn't forwarding bounces back to mailtrain so I went and manually clicked the unsubscribe button in my list for all the bounce emails I received.  After doing so all the subscribers that I unsubscribed now say [ERASED] in the email column and all my other fields are empty.  I need to make sure that when I import new data they don't get re added.
![screen shot 2019-02-20 at 11 32 10 am](https://user-images.githubusercontent.com/1761267/53107561-3c0a6900-3503-11e9-86b1-38b1254ff78f.png)

**Comment by mantisae** [comment]
I just ran a couple more and they're still showing just saying unsubscribed like I would expect.

**Comment by priethor** [comment]
What is your GDPR setup in the `production.yaml` configuration file? It probably has to do with the mailtrain GDPR mechanism that, when unsubscribing, deletes all fields except the email hash so that the subscriber isn't added again during an import.

**Comment by mantisae** [comment]
I just went and dug into the database and sure enough you were right there is just a hash there.  My problem still stands though I ran some the other day and they deleted the data leaving the hash but running no updates the ones I just did yesterday still have the emails there.

**Comment by priethor** [comment]
Take into account there is a delay after the user is unsubscribed until:
- All the data except the hash is deleted (defaults to 1 day)
- The hash is also deleted (defaults to 30 days)

If you want to disable the hash to be deleted disable `deleteSubscriptionAfterUnsubscribe` in the following `production.yaml` section:

> GDPR related settings (https://en.wikipedia.org/wiki/General_Data_Protection_Regulation)
> gdpr:
>   If enabled, after a user unsubscribes or complains, his/her data are removed from the subscription.
>   Only hashed email remains to prevent resubscription via import
>   
> `deleteDataAfterUnsubscribe:`
>     `enabled: true`
>     `secondsAfterUnsubscribe: 86400 # 1 day`
> 
>   If enabled, after the time below, an entry of a subscriber that unsubscribed or complained
>   is completely removed from the subscribers list (including the hashed email)
>   `deleteSubscriptionAfterUnsubscribe:`
>     `enabled: true`
> `secondsAfterUnsubscribe: 2592000 # 30 days`

**Comment by mantisae** [comment]
```
gdpr:
  deleteDataAfterUnsubscribe:
  enabled: false

  deleteSubscriptionAfterUnsubscribe:
  enabled: false
```

which production.yaml file?
server/config/production.yaml
mvis/server/config/production.yaml

I've tried both and each separately and mailtrain refuses to start with it in there.

**Comment by bures** [comment]
that's because you have wrong indenting there. 

```
gdpr:
  deleteDataAfterUnsubscribe:
    enabled: true

  deleteSubscriptionAfterUnsubscribe:
    enabled: true
```

**Comment by mantisae** [comment]
that worked.
