### ISSUE TITLE
Mailtrain v2: Help needed with testing with different mail servers

### ISSUE THREAD

**Issue by bures** [Mailtrain-org/mailtrain#548]
I would need help with testing on different mailserver. In particular, I'm not sure how exactly they respond to sending out an email. I'm looking for people who use Mailtrain with AWS SES, Sparkpost, Sendgrid, and Mailgun. If you want to help, please drop a line here. I'll instruct you how to get the diagnostics I need. 

Thanks.

**Comment by adamramadhan** [comment]
im using mailgun here, cannot make it work using smtp connection, seems "done sending" but nothing goes at the email, how to diagnostic in v2? in v1 works just fine

**Comment by bures** [comment]
@adamramadhan - How do you deliver vial Mailgun. Through SMTP? I would need the logs that it generates - use `journalctl -u mailtrain`. Thanks.

**Comment by informdev** [comment]
If you still need help, I'm a new Mailtrain user but I'll be using SES.

**Comment by bures** [comment]
Perfect. I did some testing of SES already, but it would be good to confirm that it works for others too. Let me know if you have any issues or if it works for you. Thanks.

**Comment by chovy** [comment]
I have mailgun but I need instructions on how to configure docker-compose.yml to work with mailgun (v2 of mailtrain)

**Comment by nicksellen** [comment]
I just started using mailtrain with sparkpost via SMTP and so far so good! ~6000 sent out.

The bounce webhook also appears to be working, entries from my list are getting marked with "Bounced" status. The only anomaly I can see is campaign statistics page is showing 0 bounced (the opened and clicked counts are incrementing fine).

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
