### ISSUE TITLE
install error beta v2

### ISSUE THREAD

**Issue by pokernet** [Mailtrain-org/mailtrain#550]
i install on centos 7 mailtrain v2 beta
git, and run the install script for local

after all the script end like this :
added 87 packages from 106 contributors and audited 168 packages in 1.701s
found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Reinstalling modules in mvis/ivis-core/client
/opt/mailtrain/setup/functions: line 222: cd: mvis/ivis-core/client: No such file or directory

and stop running

h mailtrain not working

**Comment by pokernet** [comment]
Any help ?

**Comment by bures** [comment]
ivis-core is a git submodule and currently it is not in use.
Either skip the steps that relate to ivis-core or pull the git submodule in mvis/ivis-core

**Comment by pokernet** [comment]
thanks for the replay , 

i make git pull on ivis-core
and i get :
[root@localhost ivis-core]# git pull
Already up-to-date.

how can i skipe this ?

**Comment by pokernet** [comment]
after running the git submoduled in /opt/mailtrain
and run install again after deleting the database and the user from sql :)
i get this again :
Reinstalling modules in mvis/ivis-core/client
/opt/mailtrain/setup/functions: line 222: cd: mvis/ivis-core/client: No such file or directory
[root@localhost mailtrain]#

**Comment by pokernet** [comment]
Ok I delete the ivis from the function and all look ok now


May be you need to delete it from the script until it's work
