### ISSUE TITLE
v2 - Unsubscription with confirmation email fails

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#554]
Steps to reproduce:
- Create a list with 2-step unsubscription.
- Try to unsubscribe a user from that list with the unsubscribe link.
- Click on the "Confirm unsubscription" button recieved by email.
- An `Invalid campaign` message appears.

**Comment by bures** [comment]
That's strange. How do you get the email with the unsubscription link?

**Comment by priethor** [comment]
What do you mean exactly by how do I get it?

We are having lots of issues related to the unsubscription, like some lists loading forever not being able to send confirmation emails for subscription/unsubscription because they keep trying to read the "send configurations" forever, but it is a bit hard to track down a way to reproduce them; the only thing we have confirmed is that by having everything related in the Root namespace, nothing wrong happens.

**Comment by bures** [comment]
I'll check it. I had a campaign in the root namespace and everything worked 
normally. I'll try something in another namespace.

**Comment by priethor** [comment]
Closed as the issue didn't reproduce anymore.
