### ISSUE TITLE
v2: How to add pugin to grapesjs [help wanted]

### ISSUE THREAD

**Issue by C00Lzero** [Mailtrain-org/mailtrain#559]
Hello, 

i'm trying to get the plugin [grapesjs-blocks-basic](https://github.com/artf/grapesjs-blocks-basic) to work. 
Unfortionately i'm a bit lost here :/
what do I have to do, to get this working? 

As for now I've added it to my plugins and also tried to load via "sandboxed-grapesjs-root.js" - which is probably wrong, when i read the peerDependencies info at the plugin. 

Any help would be appreciated. 
Thanks

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
