### ISSUE TITLE
git update

### ISSUE THREAD

**Issue by pokernet** [Mailtrain-org/mailtrain#560]
i install last beta v2

how i get last updates from git
if i make git pull again it say error ?

**Comment by bures** [comment]
Sorry, but unless you describe exactly what you do and what error you get, no one will be able to help you.

**Comment by pokernet** [comment]
Ohh I don't have error
I just want to know how to keep last beta version update from git ?

**Comment by Avalarion** [comment]
After `git pull` you need to redo steps `2` and `4` of the documentation ( https://github.com/Mailtrain-org/mailtrain#requirements-1 )  in order to update npm packages and than start mailtrain again.

**Comment by forgeOneHQ** [comment]
Usually it shouldn't be a big problem.

Option to is to backup the old folder and completely clone the repository again, copy the configuration and run the reinstall-modules.sh
