### ISSUE TITLE
v2 Webhooks for SendGrid

### ISSUE THREAD

**Issue by chadgough** [Mailtrain-org/mailtrain#561]
Are Webhooks for v2 working?  I just installed latest v2 from dev branch, and can't seem to get Sendgrid to recognize the endpoint, it just times out on their end

I set up with bash setup/install-ubuntu1804-https.sh mailer01.mydomain.com sandbox.mailer01.mydomain.com lists.mydomain.com me@mydomain.com

and used https://mailer01.mydomain.com/webhooks/sendgrid as the URL in SendGrid for the endpoint.  all DNS entities and LetsEncrypt certs are working

**Comment by brentkearney** [comment]
I can see that the webhooks code is still there in v2, under `server/routes/webhooks.js`.

I'm setting Mailgun as a Send Configuration, and they have a "Test Webhook" button that outputs what their script receives from the webhooks API. I get:

```
<script>
        if (!window.location.href.startsWith('')) {
            console.warn('Warning: Misconfigured urlBases. If the website does not work, check the settings of www.trustedUrlBase, www.sandboxUrlBase and www.publicUrlBase in server config file.');
        }
 </script>
```

I am using the docker image, and passing the trustedUrlBase in as an environment variable. The web interface works from my browser. However, the docker container is running behind nginx-proxy, so its external URL might look different from its internal (docker-assigned) IP address.

**Comment by moerazem** [comment]
Sendgrid webhook didn't work for me either on V2.

**Comment by bures** [comment]
I ported the webhooks that were present in v1. However, I had no way of testing them because they rely on various paid providers. I tested only the AWS hooks. I would appreciate if you could fix whatever problem you encounter and create a PR. Alternatively, if you give me access to the respective service, I can do some testing myself.

**Comment by moerazem** [comment]
@bures SendGrid has a free account. https://sendgrid.com/pricing/

**Comment by fthobe** [comment]
@bures Is that offer still open? I have an instance of mailtrain and would like to use sendgrid for bounces.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
