### ISSUE TITLE
About namespaces and send configurations

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#562]
Right now, send configurations are assigned aty two different levels, per List, in order to send the forms notification/confirmation emails, and per Campaign, to actually send the campaign. However, this seems a little confusing from the namespace perspective.

For example, what happens when a user with full privileges creates a List `A` in namespace `A` and send configuration `A` , and assigns it to a campaign with namespace `B` and send configuration `B`? And if the campaign is also in nampesace `A` but the SC is in `B`?

Probably this will both result in permission errors, which at first glance indicates it should not be possible to assign things to element out of its scope. For example, assigning a list to a campaign which isn't able to "see" the list because of the namespaces they belong to.

There is a second doubt which comes to mind, which is why do we need send configurations actually in the campaign level. Wouldn't it be easier to just use the SC assigned to the list(s)? At least as a default option when no specific SC is chosen.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
