### ISSUE TITLE
Unable to locate package redis

### ISSUE THREAD

**Issue by kdaffef** [Mailtrain-org/mailtrain#566]
Hi, i'm trying to install mailtrain v2 on vultr vps, but the process was stoped with this error  : 

- E: Unable to locate package redis

I tried to install it separately with "sudo apt install redis-server", and relaunched the install abain but exited with same error.

Second question, i'm wondering if it installed along side on same vps with Postal mail server, will encounter issue with https certificate ? - i make install on 2 different subdomains ...

Any fix for this ? - thank you for you fantastic application,

**Comment by bures** [comment]
Which distribution do you use? At this point, the other install scripts supporting only Centos7 and Ubuntu 18.04.

Installing it with other services should not be an issue, however you may need to configure the certificate and https proxy manually.

**Comment by kdaffef** [comment]
Hi there,
I'm using ubuntu 18.04 on vultr vps, but restartd install agan, and was
fine,

as im' not expert, could you help to succeed to install mailtrain v2 at
mailtrain.mydomain.com and Postal at postal.mydomain.com ? any help to get
that working ?
any help link plz ?

very impressed with v2, great app!!

**Comment by bures** [comment]
Thanks. I'm afraid, I have no experience with Postal. I'm also not sure how it is installed. I assume you will have a single HTTPS proxy (apache or nginx) which will route requests to mailtrain or postal based on server name. I would suggest you use apache and then the https version of the install scripts. It will add a config to apache for mailtrain. If Postal is also setup with apache, it might work together. But no promises, most likely something will need some manual tweaking.
