### ISSUE TITLE
Mailtrain crashes when uploading images in template editor

### ISSUE THREAD

**Issue by ScottCrumpler** [Mailtrain-org/mailtrain#567]
Anyone else having a problem uploading images in the template editors (Mosaico and Grape)?  I've just installed 1.24.1 on my webserver with node 11.12.0 and npm 6.7.0 and everything works well except when I try to upload images in the template editors, it crashes with this in the cli:
`
> info HTTP GET /editorapi/img?method=placeholder&params=258%2C150 200 61.994 ms - -
> fs.js:141
>     throw new ERR_INVALID_CALLBACK();
>     ^
> 
> TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
>     at makeCallback (fs.js:141:11)
>     at Object.unlink (fs.js:959:14)
>     at ReadStream.<anonymous> (/[PATH TO]/mailtrain/node_modules/jquery-file-upload-middleware/lib/uploadhandler.js:149:48)
>     at ReadStream.emit (events.js:202:15)
>     at ReadStream.EventEmitter.emit (domain.js:481:20)
>     at endReadableNT (_stream_readable.js:1132:12)
>     at processTicksAndRejections (internal/process/next_tick.js:76:17)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mailtrain@1.24.0 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mailtrain@1.24.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/brightwork/.npm/_logs/2019-03-25T21_21_25_997Z-debug.log
`

I see mailtrain 1.24.0 referenced in the above errors (instead of 1.24.1 -- does that have anything to do with it?

**Comment by Geartwo** [comment]
Check if you have installed imagemagick with the command "convert" in the commandline. That was my problem.
