### ISSUE TITLE
Manual install instructions for v2 on LAMP WHM stack?

### ISSUE THREAD

**Issue by ScottCrumpler** [Mailtrain-org/mailtrain#570]
Can I install v2 similarly to the manual instructions for v1?  For v1, I installed nodejs on my LAMP WHM webserver and then ran the manual install instructions for mailtrain v 1.24.1, which gave me access to mailtrain from the web on port 3000.  To install v2, if I create the subdomains myself for the separate endpoints first, what are the manual steps to install and arrange the files?

**Comment by ScottCrumpler** [comment]
In other words, is there an install script available for v2 that works with subdomains already setup and accessible to the web via SSL/443?  (I run autossl so all subdomains automatically have ssl certs configured for them.)

**Comment by bures** [comment]
Just use the local install script and then edit server/config/production.yaml and update the trustedUrlBase, sandboxUrlBase and publicUrlBase to urls that you would like to use from outside.

**Comment by ScottCrumpler** [comment]
Thanks @bures - I'll give it a shot!

**Comment by kdaffef** [comment]
Hi, i'm too will try manual install this way!!

Second, is it possible to switch to Nginx Instead apache2 ? if yes, any help for not-expert ?

I'm playing with Mailtrain v1 on ubuntu 16.04, tried to confirm email opens from different devices with same email, all html email opens are not reported in statics!!!. Could you confirm that all email opens are reported ? - how to optimise to get that working at 100% ?
Thank you+++

**Comment by kdaffef** [comment]
> In other words, is there an install script available for v2 that works with subdomains already setup and accessible to the web via SSL/443? (I run autossl so all subdomains automatically have ssl certs configured for them.)

Hi, same issue here, want to get ssl for multiple subdomains on same vps, how to get autossl for all subdomains ? any tuto plz ?. Thank you

**Comment by ScottCrumpler** [comment]
@bures On install from the local script I'm getting this error:
`ERROR` 1396 (HY000) at line 1: Operation CREATE USER failed for 'mailtrain'@'localhost'
Which looks like it's trying to create a db user, but on my server setup, I'm going to have to do the db creation and user manually.  Is there anything the install script is going to do after that crash point?  Or can I just edit the config with the correct db details?

**Comment by bures** [comment]
Just comment the DB stuff out in the script and then setup your mailtrain config manually.
The script only creates a database and a user. It does not setup any tables. Those are setup automatically upon the first start of Mailtrain. So empty DB + user is enough.

**Comment by kdaffef** [comment]
Sorry @bures,
didn't find complete script  invoked by @ScottCrumpler, in my vps/opt/mailtrain/setup there is only few lines in script  "install-ubuntu1804-local.sh" for manual install,  where is full script in which had to comment db stuff plz ? thank you from newbie!!

**Comment by kdaffef** [comment]
got it, commented db code with db users and  same pswd, and edited /server/config/production.yaml like 
  host: mydomain.com
  proxy: false
  secret: "peiF7tei"
  trustedUrlBase: mailtrain.mydomain.com
  sandboxUrlBase: sbox.mydomain.com
  publicUrlBase:  lists.mydomain.com

then enabled and started mailtrain service.
But, can not access to cloud vps under : trustedUrlBase, i'm having "This site can’t be reached" error ?
missunderstood surely something, any help ?

vps : ubuntu 18.04 vultr

**Comment by bures** [comment]
Did you setup the HTTPs proxy server to proxy requests from xxx.mydomain.com to localhost (ports 3000, 3003, 3004)?

**Comment by bures** [comment]
With the local install, mailtrain does not setup the HTTPs proxy itself. You have to configure Apache or nginx yourself.

**Comment by kdaffef** [comment]
thank you, will make a recheck!! ++ 
would be fantastic if it will work as local install...

**Comment by kdaffef** [comment]
Im blocked here, no way i'm not expert enough ... not able to tweak alone
and no mailtrain nginx template. I'm sorry
Thank you for help and time

**Comment by bures** [comment]
Then why don't you use the httpd installer that setups Apache based proxy automatically? Why do you go for nginx?

**Comment by kdaffef** [comment]
no reason, will try httpd and feed back, not easy!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
