### ISSUE TITLE
Get Option value rather than name from Group Option Merge Tag

### ISSUE THREAD

**Issue by sven-weber** [Mailtrain-org/mailtrain#572]
Hi, 

I have the following fields configured for my list: 

![image](https://user-images.githubusercontent.com/39764491/55278155-f8c4c680-5308-11e9-8125-835d015b479d.png)

A Dropdown-List provides two values the user can select from regarding their gender.

I want to use this selection to provide the correct salutation for the emails. 

When using the merge tag for the Group Option ([MERGE_ANREDE]) it delivers the Name of the Option that was selected by the user. E.g. "Herr" in this case.

I would rather have the default Merge Tag value of the selected option because then I can set the correct salutation inside the option. 

**What I already tried**

I already tried to encapsulate the merge tags to have something like this

```
[MERGE_[MERGE_ANREDE]]
```
But it seems the process replacing the merge tags is only running once so the result is 

```
[MERGE_Herr]
```
rather than "geehrter Herr". 

Another Idea was to set the Default-Merge-Tag-Value of the regarding group to something like 

```
[MERGE_value]
```
But I don't think its possible to use the selected value inside the group like this.

Is it in any way possible to get the default merge tag value from the select option by the group merge tag? 

I think issue #39 could be referenced to my problem.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
