### ISSUE TITLE
Windows Docker: Not starting

### ISSUE THREAD

**Issue by anandbhaskaran** [Mailtrain-org/mailtrain#574]
I am trying to install Mailtran in docker way in windows OS by following https://github.com/Mailtrain-org/mailtrain. After `docker-compose start` the system attempts to start all the three services.  But, the mailtrain_mailtrain_1 always keeps restarting.
![image](https://user-images.githubusercontent.com/6847984/55334863-62280f00-549a-11e9-8d5d-9710680ad38b.png)

I am using `Windows 10`, `Docker version 18.03.0-ce, build 0520e24302` and `docker-compose version 1.20.1, build 5d8c71b2`

**Comment by Avalarion** [comment]
@anandbaskaran what does `docker-compose logs mailtrain` show you?

**Comment by fleverest** [comment]
@Avalarion I'm having the same issue, and the logs show the following, repeating each time the container attempts to restart:

`: invalid optionapp/docker-entrypoint.sh: line 2: set: -
mailtrain_1  | set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
mailtrain_1  | /app/docker-entrypoint.sh: line 3: $'\r': command not found
mailtrain_1  | /app/docker-entrypoint.sh: line 19: syntax error: unexpected end of file`

**Comment by 4n70w4** [comment]
+1

**Comment by Teedious** [comment]
+1

**Comment by michaltalaga** [comment]
anyone got this working?

**Comment by anandbhaskaran** [comment]
I solved it by moving to Linux instead. It would be really great if someone from @mailtrain can fix this :)

**Comment by redips** [comment]
+

**Comment by umairrazzaq** [comment]
+1

**Comment by JoseDinis1** [comment]
this is related to https://stackoverflow.com/questions/51581809/r-command-not-found-with-docker-compose
before clone mailtrain, running this:

`git config --global core.autocrlf input`

solved for me

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
