### ISSUE TITLE
Changing default language

### ISSUE THREAD

**Issue by mmomasters** [Mailtrain-org/mailtrain#577]
I tried to add:

language="fr_FR"
language="fr"

in file : config/production.toml

then: docker-compose build; docker-compose up

And still in English, any ideas?

**Comment by carl-chenet** [comment]
Hi maintainers,

Same issue trying to activate french here:
using : 

`# Default language to use
language="fr"`

in config/production.toml after restarting it does not seem to show the content of fr_FR.po in the web interface.

**Comment by carl-chenet** [comment]
is it a feature of the v2 beta? maybe useful to mention it somewhere if it's the case.

**Comment by jonathanmmm** [comment]
This pull request https://github.com/Mailtrain-org/mailtrain/pull/1175 will create an ENV variable for docker usage.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
