### ISSUE TITLE
[Question] Can mailtrain DB huge load of data (estimated arround 100million/day)?

### ISSUE THREAD

**Issue by chakas** [Mailtrain-org/mailtrain#581]
We are planning to use mailtrain to send 100million-mails/day.So just wondering MySQL(MariaDB) that used as backend can scale to that level.

**Comment by chints-emailguy** [comment]
@chakas - Did you use mailtrain to send 100 millions a day. How was your experience?

**Comment by misterioss** [comment]
@chints-emailguy - Did you use mailtrain to send 100 millions a day. How was your experience?
