### ISSUE TITLE
Unable to stop compaign v2!

### ISSUE THREAD

**Issue by shahzaibcb** [Mailtrain-org/mailtrain#582]
Hi,

I am using Mailtrain v2. The problem is if we want to stop compaign that is being sent out, it triggers 500 error with response `Cannot stop campaign until it is in SCHEDULED state` . Please find the picture below :

http://prntscr.com/naz0i4

**Comment by shahzaibcb** [comment]
We're in really a big problem, we've triggered a compaign but mistakenly sent wrong template, now we're trying to stop compaign but all in vain. 

http://prntscr.com/ndluz8

**Comment by bures** [comment]
I'll take a look at it.

**Comment by bures** [comment]
Can you send me a screenshot of the campaign Status page?

**Comment by bures** [comment]
Is it a regular campaign or a triggered one?
Can you send me the output of the server? If you used the install script, you can get the server log using `journalctl -u mailtrain`

**Comment by shahzaibcb** [comment]
> Is it a regular campaign or a triggered one?
> Can you send me the output of the server? If you used the install script, you can get the server log using `journalctl -u mailtrain`

Hi, it's a regular campaign. I did setup mailtrain v2 using manual steps. Following is output of mailtain

`https://pastebin.com/hhvzrc5g`

To stop compaign, i manually changed campaign status to finished in database.

**Comment by bures** [comment]
Stopping the campaign by changing the status in DB was the right move.

It seems that your send configuration wasn't properly configured. Is that possible? It seems like we have a bug that the sending of campaign never finishes if the mail server configured in the send configuration cannot be reached.
