### ISSUE TITLE
Error starting index.js (mailtrain v2)

### ISSUE THREAD

**Issue by ansgarsmith** [Mailtrain-org/mailtrain#584]
I have done a manual installation of Mailtrain v2. I had to install node10 on my Centos 7 VPS. after that I succesfully executed a "npm install" in de /server directory. Then I executed "node index.js" and I am getting the following error:

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'owasp-password-strength-test'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/var/www/vhosts/-host-/httpdocs/mailtrain-beta/shared/password-validator.js:4:35)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/var/www/vhosts/-host-/httpdocs/mailtrain-beta/server/models/users.js:8:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

How should I go around troubleshooting this?

**Comment by bures** [comment]
Execute npm install also in `shared` directory.

Also, don't forget to do npm install and npm build in `client.

**Comment by ansgarsmith** [comment]
Thanks @bures . 

I just did your suggestions with npm install in shared and client directory. That went well (except for a couple of found vulnerabilities (1 low, 5 high))
1. Do I need to fix those?
2. Also  "npm build" in client directory results in error: 
-sh-4.2$ npm build
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?

I am trying to install mailtrain v2 on a Plesk/Centos 7 VPS, and it's a bit tricky getting the environment in good shape, after manually installing NodeJS v10. So my first step is to get it running from the command line.

**Comment by ansgarsmith** [comment]
Alright got it running now. Plesk does not come with NodeJS 10 yet, so this needs to be installed manually. I used the following instructions to get it done:

https://stackoverflow.com/questions/44131956/how-to-add-a-new-node-js-version-for-the-node-js-manager-on-plesk

Don't forget to set the PATH=$PATH:/opt/plesk/node/10/bin to reflect the location of the new nodejs

I installed the git repository automatically with plesk, within one of the domains; so all user rights are in good state.

(not sure if this is needed) I created a .npmrc file in the server directory with the following content:
scripts-prepend-node-path=true

I edited the config file default.yaml with the correct mysql database credentials, ip numbers, and domainnames to respond to  (instead of localhost). Important: I disabled zone-mta since it seems to require a mongodb , which is not default on my VPS and I do not need zone-mta yet.

Thanks to @bures I ran "npm install" in directories ./server ./static and ./client. Also I ran "npm run build" in the ./client directory.

During the installs I ran in all kinds of vulnerability warnings, and I used "npm audit fix" to fix most of them

Within Plesk I opened the firewall for the port 3000, 3003 and 3004

And within the server directory i just entered "node index.js" to start the server from the command line.

Now I am still not finished, but at least I can log in and start system testing to see the stability of the v2 development build. I noticed lot's of good improvements already!!! I hope the API is backwards compatible with the v1.8

Next steps I need to figure out:
- start mailtrain within the Plesk interface
- automatic of services i.c.w. Plesk

I hop these instructions might help someone else in the future

**Comment by bures** [comment]
Perfect. Thanks a lot for instructions. It may be even helpful to add a note to README.md with at least a pointer to this issue. I'll be happy to accept the PR.

A small note, the directories to do `npm install` are client, server, shared - not static.

**Comment by ansgarsmith** [comment]
Thanks @bures  I edited my previous post to reflect the shared directory. If I get it working I intend to document this. I will share when I nail it :-)

**Comment by bures** [comment]
Excellent. Thanks a lot. If you encounter any other problem, let me know. I'll be happy to help - at least in my capacity of having zero experience with Plesk. :-)
