### ISSUE TITLE
MTv2: Error on creating template based on existing template

### ISSUE THREAD

**Issue by ansgarsmith** [Mailtrain-org/mailtrain#588]
When creating a new template and ticking the checkbox "Clone from an existing template; then selecting a previously created template based (Mosaico), I get the following error:

`Cannot create property 'model' on string '{"mosaicoTemplate":1,"metadata":"{\"template\":\"[SANDBOX_URL_BASE]/mosaico/templates/1/index.html\",\"name\":\"No name\",\"created\":1555619487461,\"editorversion\":\"0.16.0\",\"templateversion\":\"1.0.6\"}","model":"{\"type\":\"template\",\"customStyle\":false,\"preheaderVisible\":true,\"titleText\":\"TITLE\",\"preheaderBlock\":{\"type\":\"preheaderBlock\",\"customStyle\":false,\"id\":\"ko_preheaderBlock_1\",\"backgroundColor\":null,\"preheaderText\":\"\",\"linkStyle\":{\"type\":\"linkStyle\",\"face\":null,\"color\":null,\"size\":null,\"decoration\":null},\"preheaderLinkOption\":\"[LINK_PREFERENCES]\",\"longTextStyle\":{\"type\":\"longTextStyle\",\"face\":null,\"color\":null,\"size\":null,\"linksColor\":null},\"unsubscribeText\":\"Preferences\",\"webversionText\":\"View in your browser\"},\"sponsor\":{\"type\":\"sponsor\",\"visible\":false},\"footerBlock\":{\"type\":\"footerBlock\",\"customStyle\":false,\"longTextStyle\":{\"type\":\"longTextStyle\",\"face\":null,\"color\":null,\"size\":null,\"linksColor\":null},\"id\":\"ko_footerBlock_2\",\"backgroundColor\":null,\"linkStyle\":{\"type\":\"linkStyle\",\"face\":null,\"color\":null,\"size\":null,\"decoration\":null},\"longText\":\"<p>Email sent to <a href=\\\"mailto:[EMAIL]\\\">[EMAIL]</a></p>\",\"disiscrivitiText\":\"Unsubscribe\"},\"mainBlocks\":{\"type\":\"blocks\",\"blocks\":[{\"type\":\"singleArticleBlock\",\"customStyle\":false,\"backgroundColor\":null,\"titleVisible\":true,\"buttonVisible\":true,\"imageVisible\":true,\"titleTextStyle\":{\"type\":\"textStyle\",\"face\":null,\"color\":null,\"size\":null},\"longTextStyle\":{\"type\":\"longTextStyle\",\"face\":null,\"color\":null,\"size\":null,\"linksColor\":null},\"buttonStyle\":{\"type\":\"buttonStyle\",\"face\":null,\"color\":null,\"size\":null,\"buttonColor\":null,\"radius\":null},\"image\":{\"type\":\"image\",\"src\":\"\",\"url\":\"\",\"alt\":\"\"},\"longText\":\"\\n <p>Far far away, behind the word mountains, far from the countries <a href=\\\"\\\">Vokalia and Consonantia</a>, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>\\n \",\"buttonLink\":{\"type\":\"link\",\"text\":\"BUTTON\",\"url\":\"\"},\"id\":\"ko_singleArticleBlock_3\",\"externalBackgroundColor\":null,\"text\":\"\\n Section Title\\n \"},{\"type\":\"tripleArticleBlock\",\"customStyle\":false,\"backgroundColor\":null,\"titleVisible\":true,\"buttonVisible\":true,\"imageVisible\":true,\"titleTextStyle\":{\"type\":\"textStyle\",\"face\":null,\"color\":null,\"size\":null},\"longTextStyle\":{\"type\":\"longTextStyle\",\"face\":null,\"color\":null,\"size\":null,\"linksColor\":null},\"buttonStyle\":{\"type\":\"buttonStyle\",\"face\":null,\"color\":null,\"size\":null,\"buttonColor\":null,\"radius\":null},\"leftImage\":{\"type\":\"image\",\"src\":\"\",\"url\":\"\",\"alt\":\"\"},\"leftLongText\":\"\\n <p>Far far away, behind the word mountains, far from the countries <a href=\\\"\\\">Vokalia and Consonantia</a>, there live the blind texts. </p>\\n \",\"leftButtonLink\":{\"type\":\"buttonLink\",\"text\":\"BUTTON\",\"url\":\"\"},\"middleImage\":{\"type\":\"image\",\"src\":\"\",\"url\":null,\"alt\":\"\"},\"middleLongText\":\"\\n <p>Far far away, behind the word mountains, far from the countries <a href=\\\"\\\">Vokalia and Consonantia</a>, there live the blind texts. </p>\\n \",\"middleButtonLink\":{\"type\":\"buttonLink\",\"text\":\"BUTTON\",\"url\":\"\"},\"rightImage\":{\"type\":\"image\",\"src\":\"\",\"url\":null,\"alt\":\"\"},\"rightLongText\":\"\\n <p>Far far away, behind the word mountains, far from the countries <a href=\\\"\\\">Vokalia and Consonantia</a>, there live the blind texts. </p>\\n \",\"rightButtonLink\":{\"type\":\"buttonLink\",\"text\":\"BUTTON\",\"url\":\"\"},\"id\":\"ko_tripleArticleBlock_4\",\"externalBackgroundColor\":null,\"imageHeight\":\"90\",\"leftTitleText\":\"Title\\n \",\"middleTitleText\":\"\\n Title\\n \",\"rightTitleText\":\"\\n Title\\n \"}]},\"theme\":{\"type\":\"theme\",\"frameTheme\":{\"type\":\"frameTheme\",\"backgroundColor\":\"#3f3f3f\",\"longTextStyle\":{\"type\":\"longTextStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#919191\",\"size\":\"13\",\"linksColor\":\"#cccccc\"},\"linkStyle\":{\"type\":\"linkStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#ffffff\",\"size\":\"13\",\"decoration\":\"underline\"}},\"contentTheme\":{\"type\":\"contentTheme\",\"longTextStyle\":{\"type\":\"longTextStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#3f3f3f\",\"size\":\"13\",\"linksColor\":\"#3f3f3f\"},\"externalBackgroundColor\":\"#bfbfbf\",\"externalTextStyle\":{\"type\":\"textStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#f3f3f3\",\"size\":\"18\"},\"backgroundColor\":\"#ffffff\",\"titleTextStyle\":{\"type\":\"textStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#3f3f3f\",\"size\":\"18\"},\"buttonStyle\":{\"type\":\"buttonStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#3f3f3f\",\"size\":\"13\",\"buttonColor\":\"#bfbfbf\",\"radius\":\"4\"},\"bigTitleStyle\":{\"type\":\"bigTitleStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#3f3f3f\",\"size\":\"22\",\"align\":\"center\"},\"hrStyle\":{\"type\":\"hrStyle\",\"color\":\"#3f3f3f\",\"hrWidth\":\"100\",\"hrHeight\":\"1\"},\"bigButtonStyle\":{\"type\":\"buttonStyle\",\"face\":\"Arial, Helvetica, sans-serif\",\"color\":\"#3f3f3f\",\"size\":\"22\",\"buttonColor\":\"#bfbfbf\",\"radius\":\"4\"}}}}"}'`

Any thoughts on this? Thanx, Ansgar

**Comment by ansgarsmith** [comment]
I installed Mailtrain v2 on a second server, and noticed the same problem, which is specific to the Mosaica templates. When creating a bare html template without any content, it was nog problem making a copy.  Anybody else experiencing this problem as well?

**Comment by forgeOneHQ** [comment]
@ansgarsmith please try the latest version of v2 and if you still struggle you are welcome to open a new issue with providing all issues including the deployment (docker/container or directly on centos or ubuntu), log files and configuration.
