### ISSUE TITLE
Triggered Campaigns not sending

### ISSUE THREAD

**Issue by rkalsky** [Mailtrain-org/mailtrain#589]
We have created 4 campaigns using the latest pull from the development branch.

Test Triggered Campaign Email 0 |  Trigger - 0 Days After | Triggered | Active | 3 days ago 
Test Triggered Campaign Email 1 |  Trigger - 1 Days After | Triggered | Active | 3 days ago
Test Triggered Campaign Email 2 |  Trigger - 2 Days After | Triggered | Active | 3 days ago 
Test Triggered Campaign Email 3 |  Trigger - 3 Days After | Triggered | Active | 23 minutes ago

Email 0 was created manually, and will send an email as soon as a contact is added the the Test List
Email 1 was created from a template of Email 0. It has a trigger of 1 day.  It will not send.
Email 2 was created from a template of Email 0. It has a trigger of 2 days.  It will not send.
Email 3 was created manually.  It has a trigger of 3 days. It will not send.

I've waiting 3 days for the first two campaigns to send but nothing.  I cannot wait days to see if an email will be sent, so to speed up testing, I've modified the records in the database.

MariaDB [mailtrain]> select id,name,enabled,entity,event,seconds,campaign,count from triggers;
| id | name                                     | enabled | entity       | event   | seconds | campaign | count |
|  1 | Trigger - 0 Days After                   |       1 | subscription | created |       0 |        2 |     4 |
|  2 | Trigger - 1 Days After (86400s to 150s)  |       1 | subscription | created |     150 |        3 |     0 |
|  3 | Trigger - 2 Days After (172800s to 300s) |       1 | subscription | created |     300 |        4 |     0 |
|  4 | Trigger - 3 Days After (259200s to 450s) |       1 | subscription | created |     450 |        5 |     0 |

What can I send to help troubleshoot why it's not sending emails for any triggered campaigns?

A copy of the output from`journalctl -u mailtrain` from the last start was posted here: https://pastebin.com/1fAm6666

**Comment by rkalsky** [comment]
After review it seems the lower values do not work as I assumed, and I would get all 4 at once.

What I'm looking to do is:
Once a subscriber (john@doe.com) is added to a list, send day 0 email.
1 day later from initial add to the list, send the Day 1 email to john@doe.com
2 days later from initial add to the list, send the Day 2 email to john@doe.com
...
14 days later from initial add to the list, send the Day 14 email to john@doe.com
3 weeks later (21 days) from initial add to the list, send the Week 3 email to john@doe.com
4 weeks later (28 days) from initial add to the list, send the Week 4 email to john@doe.com

Each day we add 1-N contacts to 1 list and want that campaign to be able to send day 1 to john@doe.com on day 1, AND since jane@doe.com was added to the list 10 days ago, so she is  getting the Day 10 email.

**Comment by adilix** [comment]
Hi,

I'm facing this same problem, did you find a solution ?

**Comment by rkalsky** [comment]
Hi,

 

  No.  I ended up doing a complete reinstall, and created a new campaign and list.  Sorry

 

 




Rich Kalsky
Director of Operations
Pinogy Corporation

Office  877-360-7381 x1310
Email  rich.kalsky@pinogy.com <mailto:rich.kalsky@pinogy.com> 
Software Support 877-360-7381
www.pinogy.com <http://www.pinogy.com/> 

	

This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Pinogy Corporation, and all its subsidiaries. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.

**Comment by ericuldall** [comment]
I had a trigger campaign set for 0 days on created, just to immediately shoot out a welcome email when a user subscribes. It was working for a bit then all of the sudden stopped sending. Anyone else having a similar issue?

**Comment by bures** [comment]
I don't use triggered campaigns, so they are not really tested from my side.

**Comment by ericuldall** [comment]
Okay.. I'll let you know what we find.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
