### ISSUE TITLE
v2 LDAP Support

### ISSUE THREAD

**Issue by bbraganca** [Mailtrain-org/mailtrain#590]
Hi all, does anyone have a step-by-step to configure AD/LDAP authentication on the v2?

Thanks in advance.

**Comment by Charlo270398** [comment]
In my case I did this for LDAP: 

1. Install Apache Directory Studio.
2. Install ldapauth/ldapjs packages if you don't have installed yet (go to mailtrain main folder and execute **npm install ldapauth**/ **npm install ldapjs**)
3. Start Apache Directory Studio service (**service apacheds start**)
4. Configure LDAP in _default.yaml_ file. My current config is this: 

![imagen](https://user-images.githubusercontent.com/32102276/63247572-a52a2980-c265-11e9-9d17-e8a45348a508.png)

5. Restart Mailtrain service
6. Open a new connection in Apache Directory Studio (use parameters used in _default.yaml_) In my config BindDN/user is **uid=admin, ou=system** (introduce this literally in authentication step) and bindPassword is **secret**. 
7. Then you can create domains and users into the root folder. In my case my 
folders structure is: 

![imagen](https://user-images.githubusercontent.com/32102276/63248278-3bab1a80-c267-11e9-828e-3965ce721561.png)

Users use **inetOrgPerson** class and domains use **domain(structural)** class. 
In my case, users are identified by **uid** field. I added a password for each user adding a **userPassword** field. Users must accomplish filter requirements.
8. Try to login. 

Note that right now if you try to login an user that doesn't exists in the BD you won't login, so add this user before using LDAP. I'm trying to solve this issue.

**Comment by rbicelli** [comment]
Are multiple LDAP Domains supported?

**Comment by forgeOneHQ** [comment]
@rbicelli I don't think multi ldap is supported yet. 

I need to digg into the code and look. But I look for testing and document ldap in v2.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
