### ISSUE TITLE
Receiving error "connect ECONNREFUSED 127.0.0.1:3306" after sending email.

### ISSUE THREAD

**Issue by sokulski** [Mailtrain-org/mailtrain#599]
Hello,

I've got a Mailtrain installation running in a Digital Ocean droplet, and when I send a message to one of my larger lists (1k+) I get this message for a few seconds up to a minute when trying to load the UI.

> connect ECONNREFUSED 127.0.0.1:3306

What is the most likely cause of this? An underpowered VPS?

Thank you for your assistance.

**Comment by forgeOneHQ** [comment]
@sokulski V1 or V2, you can also try the latest version.

Please write us if you tested the latest v2 version and send us the hardware you have and OS version, config and log files.

I am closing it here, you are welcome to open a new issue with the latest v2.
