### ISSUE TITLE
Performance Feedback

### ISSUE THREAD

**Issue by radleta** [Mailtrain-org/mailtrain#60]
I'm working to figure out the best way to increase my send rate. 

I started with t2.micro MySql and t2.nano EC2. I found that I could send about 7-8k per hour until my CPU credit was used up on both then it dropped to half that and stayed steady. The interesting part was the CPU of the EC2 instance never really went much above 10%. It appears I probably need more MySql capacity to improve send rate.

The latest improvement to the code definitely helped a lot in improving my send rate. Prior to the update the above numbers were far worse. Seeing 4k max send until it ran into the degraded issue. I've included the below.

**Send rate prior to fix.**

I tried to increase the send rate by increasing the DB and EC2 capacity on 5/23 23:00 and you can see it picked up.

``` CSV
'2016-05-21 11','3318'
'2016-05-21 12','4127'
'2016-05-21 13','3997'
'2016-05-21 14','3934'
'2016-05-21 15','3832'
'2016-05-21 16','1052'
'2016-05-21 17','604'
'2016-05-21 18','600'
'2016-05-21 19','598'
'2016-05-21 20','595'
'2016-05-21 21','591'
'2016-05-21 22','587'
'2016-05-21 23','583'
'2016-05-22 00','580'
'2016-05-22 01','577'
'2016-05-22 02','575'
'2016-05-22 03','572'
'2016-05-22 04','568'
'2016-05-22 05','567'
'2016-05-22 06','564'
'2016-05-22 07','561'
'2016-05-22 08','558'
'2016-05-22 09','554'
'2016-05-22 10','552'
'2016-05-22 11','547'
'2016-05-22 12','546'
'2016-05-22 13','544'
'2016-05-22 14','541'
'2016-05-22 15','539'
'2016-05-22 16','537'
'2016-05-22 17','531'
'2016-05-22 18','534'
'2016-05-22 19','530'
'2016-05-22 20','528'
'2016-05-22 21','526'
'2016-05-22 22','523'
'2016-05-22 23','523'
'2016-05-23 00','520'
'2016-05-23 01','518'
'2016-05-23 02','516'
'2016-05-23 03','515'
'2016-05-23 04','513'
'2016-05-23 05','499'
'2016-05-23 06','509'
'2016-05-23 07','507'
'2016-05-23 08','504'
'2016-05-23 09','503'
'2016-05-23 10','500'
'2016-05-23 11','486'
'2016-05-23 12','495'
'2016-05-23 13','493'
'2016-05-23 14','490'
'2016-05-23 15','488'
'2016-05-23 16','497'
'2016-05-23 17','478'
'2016-05-23 18','486'
'2016-05-23 19','491'
'2016-05-23 20','480'
'2016-05-23 21','480'
'2016-05-23 22','481'
'2016-05-23 23','1499'
'2016-05-24 00','2872'
'2016-05-24 01','3435'
'2016-05-24 02','3757'
'2016-05-24 03','3720'
'2016-05-24 04','3678'
'2016-05-24 05','3641'
'2016-05-24 06','3602'
'2016-05-24 07','3575'
'2016-05-24 08','3525'
'2016-05-24 09','3512'
'2016-05-24 10','3465'
'2016-05-24 11','3424'
'2016-05-24 12','3367'
'2016-05-24 13','882'
```

**The below is the send rate after the fix.** 

No modifications were made to the EC2 or DB.

``` CSV
'2016-06-04 10','7882'
'2016-06-04 11','8048'
'2016-06-04 12','8043'
'2016-06-04 13','7983'
'2016-06-04 14','7998'
'2016-06-04 15','7824'
'2016-06-04 16','7892'
'2016-06-04 17','7973'
'2016-06-04 18','7845'
'2016-06-04 19','7863'
'2016-06-04 20','4569'
'2016-06-04 21','3126'
'2016-06-04 22','3098'
'2016-06-04 23','3151'
'2016-06-05 00','3102'
'2016-06-05 01','3088'
'2016-06-05 02','3061'
'2016-06-05 03','67'
```

I'm planning on increasing my DB capacity the next run to see what affect it will have on the send rate. If you have any suggestions, please let me know. Thanks.

**Comment by andris9** [comment]
Great to see that things are much better after such a simple change in Mailtrain!

7k/h is still very slow though. Send optimization is something that I want to address next once I have the initial automation support ready. Currently the bottleneck is mostly MySQL and not because MySQL is bad but because Mailtrain uses it in a not optimal way. I want to move queue processing out from MySQL to Redis which should improve the situation a lot.

The other issue is with processes as Mailtrain uses the same single process for everything. So if you'd upgrade to multi-core server there would be no use of it since Mailtrain still uses just a single core.

**Comment by forgeOneHQ** [comment]
Closing the issue, please try again with v2 and let us know :)
