### ISSUE TITLE
hungarian translation

### ISSUE THREAD

**Issue by gkisdaroczi** [Mailtrain-org/mailtrain#601]
Hello!

I really like this project's 2.0 version and I working on the Hungarian translation on local.
I created a "hungarian-translation" branch.

Let me know if you interested in and tell me, how can we handle this. :)

Best regards, Gabor

ps: I use the docker version

**Comment by bures** [comment]
Hello Gabor. Thank you. I'm definitely interested in Hungarian translation. 

Please use the version which is now in `development-tb`. I regenerated there some translation strings, etc. I'll later merge it in `development`, but I first want to do some testing.

If you have any questions on how to do the translation, let me know. In any case - this PR may help https://github.com/Mailtrain-org/mailtrain/pull/595.

Thanks.

**Comment by gkisdaroczi** [comment]
Thank you!
I use my translation on local so I know, how to do that. :P

I rebase my branch. So I am ready to push when you are ready. ;)

**Comment by bures** [comment]
Perfect. Can you create a pull request against the `development-tb` branch? That way I can easily merge it in. Thanks.

**Comment by gkisdaroczi** [comment]
Ok. I will. Not now, but soon. :)
No, thank you!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
