### ISSUE TITLE
Campaign not sending

### ISSUE THREAD

**Issue by adrianogoncalves** [Mailtrain-org/mailtrain#602]
Hi,
I'm using Mailtrain as Docker container. I've configured everything, and set and tested the SMTP in the settings page. But when I try to send the campaign, the progress screen stays "sending" forever, but nothing is done. My list have just 3 people, for now. Is there any log file I can look for any information about what is happening? I couldn't find anyone.

Thank you very much for the attention,

Adriano Gonçalves

**Comment by ganeshkrishnan1** [comment]
I have the same issue. Regular campaigns are stuck in sending phase. No emails, no output, no results.

**Comment by bures** [comment]
Is this mailtrain v1 or v2? If it is v2, can you send me the output of the server?

**Comment by ganeshkrishnan1** [comment]
It's version 1. I left it on "sending" and weirdly it went out after 4-5 hours. There was nothing in the logs (except access of the js files) and that's why I couldn't debug it either.
