### ISSUE TITLE
v1 Recommended way for handling backup & restore?

### ISSUE THREAD

**Issue by Ziinc** [Mailtrain-org/mailtrain#603]
What is the recommended way for handling backups when running mailtrain with docker?

One alternative i can think of is to have a cron backup job running to extract data using the api, but is that the only way to do it?

**Comment by ateuber** [comment]
Hi,

I'm running the following cronjob:

`docker exec mailtrain_mysql_1 bash -c "mysqldump --defaults-file=/var/lib/mysql/.mycnf mailtrain" | gzip -c > /var/backups/docker/mailtrain_db_dump_$(date +%Y-%m-%d-%H.%M).sql.gz
`

together with another cronjob to delete old backups:
`find /var/backups/docker -mtime +10 -type f -delete`

The database dumps are included in the system backup for which I use https://github.com/borgbackup/borg. Therefore there is no need for more complex methods to preserve and rotate backups for Mailtrain itself.

**Comment by Ziinc** [comment]
I see, so the mysql backups are stored on your host, for which you then backup with borg, is that it?
