### ISSUE TITLE
[V2] [URL_BASE] is not substituted when sent using transactional API

### ISSUE THREAD

**Issue by goooseman** [Mailtrain-org/mailtrain#606]
### Steps to reproduce

1. Create a Mosaico template
2. Upload image in Files section
3. Try to use public link (`https://mailtrain-public.***/files/mosaicoTemplate/file/5/a8080f5ade6176614306bba7e6a6dad8`) in the `mj-image`

![Screenshot from 2019-06-06 19-19-20](https://user-images.githubusercontent.com/3503252/59049378-82a48900-8890-11e9-84dc-83b4ffdc25f7.png)

### Expected

Get an email with an image

### Actual

Get an email with `<img src="" />`

**Comment by goooseman** [comment]
Maybe I just use the url in a wrong way?

**Comment by bures** [comment]
Not sure. This should work. Just tested it myself. I uploaded the file the Mosaico template (Files section). And referenced it like this:

```
    <mj-section mj-class="header-section">
      <mj-column>
        <mj-image src="https://lists.sathyasai.org/files/mosaicoTemplate/file/8/5d1f7df42e1dbd8873fe48388c14a882" />
        <mj-text align="left"><a href="https://lists.example.org/subscription/[LIST_ID]?locale=en-US">Subscribe</a></mj-text>
      </mj-column>
      <mj-column>
        <mj-image src="[URL_BASE]/files/mosaicoTemplate/file/8/5d1f7df42e1dbd8873fe48388c14a882" />
        <mj-text align="right"><a href="[LINK_BROWSER]">View&nbsp;in&nbsp;browser</a></mj-text>
      </mj-column>
    </mj-section>
```

The option with `[URL_BASE]` is better because it is portable, but both should work. See below:

![image](https://user-images.githubusercontent.com/1729239/59050583-f774c480-888a-11e9-8a06-5dfb7020bdce.png)

**Comment by goooseman** [comment]
I'm trying, but it does not render nor in Gmail, not in Apple Mail.app

Here is the code:
![Screenshot from 2019-06-07 00-24-22](https://user-images.githubusercontent.com/3503252/59067581-b09ec300-88ba-11e9-9b3e-5a4cc6b9c901.png)

Here is the template (inside Mosaico editor):
![Screenshot from 2019-06-07 00-24-15](https://user-images.githubusercontent.com/3503252/59067609-c14f3900-88ba-11e9-8d4a-6a456dd81809.png)

Here is in the mail:
![Screenshot from 2019-06-07 00-23-59](https://user-images.githubusercontent.com/3503252/59067621-ca400a80-88ba-11e9-8dfc-56d9563a62c3.png)

**Comment by goooseman** [comment]
Now it is becoming even more weird.

I've changed back to full public url:
<img width="939" alt="Screen Shot 2019-06-07 at 0 34 01" src="https://user-images.githubusercontent.com/3503252/59068121-032caf00-88bc-11e9-8812-fb5852fc30fb.png">

Resaved the template to update it.

And then sent to Apple Mail and looked raw:
```
<img src=3D"[URL_BASE]/files/mosaicoTemplate/file/5/b7120a8c745a2bd12=
7937eed063d7c16" style=3D"line-height: 100%; -ms-interpolation-mode: =
bicubic; border: 0; display: block; outline: none; text-decoration: none; =
height: auto; width: 100%;" width=3D"100" height=3D"auto">
```
3D are ok. But whats URL_BASE is doing here? A revert replace?

**Comment by goooseman** [comment]
Ok, I've found the problem. When the email is sent using transactional email API `https://mailtrain.cluster-staging.trucknet.io/api/templates/10/send`, the `URL_BASE` parameter is not substituted at all. Not for images, nor for links.
I've renamed the issue.

Will try to further investigate.

**Comment by goooseman** [comment]
So I've bypassed the problem for now by sending `variables:='{"URL_BASE": "https://mailtrain-public.cluster-staging.trucknet.io"}'`

And it works.

But can I write the code to get URL_BASE automatically, if it was not specified?

Where it originally comes from, when the campaign is being sent?

**Comment by bures** [comment]
This is where the URL bases get setup: https://github.com/Mailtrain-org/mailtrain/blob/development/server/models/fields.js#L728

And this is where it is used in campaign sender: https://github.com/Mailtrain-org/mailtrain/blob/development/server/lib/campaign-sender.js#L42

**Comment by goooseman** [comment]
I've create a [PR](https://github.com/Mailtrain-org/mailtrain/pull/609)

**Comment by bures** [comment]
Great. I just merged it.

**Comment by bures** [comment]
@goooseman - I'm now cleaning up and fixing some issues in the template-sender. Please, could you send an example how you invoke the API. In particular, I don't understand what you pass in in the `DATA` argument. Thanks.

**Comment by goooseman** [comment]
This is how i test it: with [httpie](https://httpie.org/):

```
http POST https://mailtrain.cluster-staging.***.io/api/templates/10/send\?access_token\=*** email=alex@***.io data:='{"notifications": [{"title": "Test title", "description": "Test description 1", "link": "goooseman.ru"}, {"title": "Test title", "description": "Test description 1", "link": "goooseman.ru"}], "test": "foo"}' variables:='{"URL_BASE": "https://mailtrain-public.cluster-staging.***.io"}'
```
But variables are not needed after the PR is merged, I've put them here just as an example.

In data I put variables to be substituted by handlebars (it works even with arrays).
In variables I can send variables which are substituted from `[VAR]`.

**Comment by bures** [comment]
Could you also send an example what your template looks like? Thanks.

**Comment by goooseman** [comment]
Mosaico template:

```
<mjml>
  <mj-body background-color="#f6f6f6">
    <mj-mosaico-container>
      <mj-mosaico-block block-id="notifications" label="Notifications">
        
        <mj-section background-color="#fff">
          <mj-raw>{{#each notifications}}</mj-raw>
          <mj-column>
            <mj-text padding="5px 25px">{{title}} ff</mj-text>
            <mj-text padding="5px 25px">{{description}}</mj-text>
          </mj-column>
          <mj-column>
            <mj-button href="https://{{link}}" font-family="Helvetica" background-color="#23cf5f" color="white">
              Go to Trucknet
            </mj-button>
          </mj-column>
          <mj-raw>{{/each}}</mj-raw>
        </mj-section>
        
      </mj-mosaico-block>
      <mj-mosaico-block block-id="footer_trucknet" label="Trucknet Footer">
        <mj-section>
          <mj-column>
            <mj-image src="[URL_BASE]/files/mosaicoTemplate/file/5/b7120a8c745a2bd127937eed063d7c16" width="100px" />
          </mj-column>
        </mj-section>
      </mj-mosaico-block>
      <mj-mosaico-block block-id="footer_busnet" label="Busnet Footer">
        <mj-section>
          <mj-column>
            <mj-image src="[URL_BASE]/files/mosaicoTemplate/file/5/a8080f5ade6176614306bba7e6a6dad8" width="100px" />
          </mj-column>
        </mj-section>
      </mj-mosaico-block>
    </mj-mosaico-container>
  </mj-body>
</mjml>
```

And then I've create a template with just one `notifications` block.

**Comment by bures** [comment]
I see. I suspected that you mixed in HBS in the standard templates. This is quite a hack because the templates for transactional email have different semantics than for campaigns. That pretty much means you will require the HBS templates feature described in https://github.com/Mailtrain-org/mailtrain/issues/611#issuecomment-502345227 . 

I'm now refactoring the transactional email API so that it doesn't contain security issues and hacks like this one. I'll connect it also to the HBS templates feature so that you don't loose the functionality. Anyway, once it is implemented, you will have to update your templates to change `[URL_BASE]` to `{{urlBase}}`. I don't want to mix two different styles of tags within one template.

**Comment by goooseman** [comment]
Got you. Agree. And `{{urlBase}}` will be substituted to the template automatically?

**Comment by bures** [comment]
Yes. There won't be difference between data and variables.

**Comment by bures** [comment]
I reworked the way templates are sent. I added the HBS templates which allow more expressiveness in scripting. Please try it out and let me know if there are any problems.
