### ISSUE TITLE
V2: "Custom unsubscribe URL" ignored for [LINK_UNSUBSCRIBE]

### ISSUE THREAD

**Issue by brentkearney** [Mailtrain-org/mailtrain#608]
This for version 2 beta.

I would like to add a custom unsubscribe url in the body of an email template that is the unsubscribe url for a different list. I put in the "Custom unsubscribe URL" field, "https://lists.mydomain.com/subscription/[other-list-id]/unsubscribe/[MERGE_ID]"

In the email that was delivered, the custom URL appeared in the List-Unsubscribe: header, but not in the message body. In the template, I have: 

> To unsubscribe, click this link: [LINK_UNSUBSCRIBE]

It still had the default unsubscribe link for the list that the campaign was sent to. So I have two questions:

1. In the "Custom unsubscribe URL" field, where I put "[MERGE_ID]", what should I actually put to have the subscriber's id substituted? i.e. it would look something like: "CPCNaQ-gF?c=423xC7WGu"

2. Should I use something other than "[LINK_UNSUBSCRIBE]" in the template, to substitute for the custom unsubscribe url?

Thank you!

**Comment by brentkearney** [comment]
Also: is there an authoratative list of the available merge tags, like "[LINK_UNSUBSCRIBE]"?

**Comment by bures** [comment]
Yes. Click the "Merge tag reference" button in template edit.

**Comment by toanvn** [comment]
> erge tag reference" button in template edit.

have you solve your problem? I have the same your problem
