### ISSUE TITLE
Unable to install Mailtrain v2 Beta on Both ubuntu and Docker 

### ISSUE THREAD

**Issue by amitprince** [Mailtrain-org/mailtrain#612]
![Untitled](https://user-images.githubusercontent.com/42072278/59426004-b33a7480-8df4-11e9-9361-8cb05d44b262.png)

Need Help in Installing the Mailtrain V2 Beta version , i tried installed it through Ubuntu and Docker but it won't work ,the above image was showing when i installed it through Docker Compose command .....and below is the output in the terminal 

mailtrain_1 | info HTTP GET / 500 0.608 ms - - mailtrain_1 | info HTTP GET /client/mailtrain.css 500 0.719 ms - - mailtrain_1 | info HTTP GET /static-npm/jquery.min.js 500 0.443 ms - - mailtrain_1 | info HTTP GET /static-npm/popper.min.js 500 0.510 ms - - mailtrain_1 | info HTTP GET /static-npm/bootstrap.min.js 500 0.607 ms - - mailtrain_1 | info HTTP GET /static-npm/coreui.min.js 500 0.509 ms - - mailtrain_1 | info HTTP GET /static/favicon.ico 500 0.610 ms - - mailtrain_1 | info HTTP GET /static/favicon.ico 500 0.628 ms - -

Need Help please ....

**Comment by bures** [comment]
Can you paste the output of the command line where you run the docker-compose?

**Comment by amitprince** [comment]
https://pastebin.com/EaTSk2Cq

Hii @bures  above is the Output i got after running sudo docker-compose up -d.

**Comment by amitprince** [comment]
![Untitled 1](https://user-images.githubusercontent.com/42072278/59431189-e0415400-8e01-11e9-8f30-5138d2076470.png)
 @bures  its only loading

**Comment by amitprince** [comment]
![Untitled 2](https://user-images.githubusercontent.com/42072278/59433839-f3572280-8e07-11e9-942e-86e6f507064e.png)
 @bures  now its displaying same thing ..
 need help please ......

**Comment by brentkearney** [comment]
Try starting it like this:

```
export MAILTRAIN_SETTINGS="--trustedUrlBase https://yourdomain.com --sandboxUrlBase https://sbox.yourdomain.com --publicUrlBase https://lists.yourdomain" 
docker-compose up -d
```

If its running behind a proxy service, add the `--withProxy` argument. This is described in Step 2. of the [Docker instructions](https://github.com/Mailtrain-org/mailtrain/tree/development#deployment-with-docker-and-docker-compose).

**Comment by amitprince** [comment]
Hii @brentkearney ..
Thanks for the Reply but after hitting the above command i received this output https://pastebin.com/iHjmwVLB and its showing the same response ...

Need Help

**Comment by bures** [comment]
And how did you set the MAILTRAIN_SETTINGS?

**Comment by bures** [comment]
How much memory do you give it. The log you included indicates that Mailtrain has not fully started, but does not report any error. Can you check whether you didn't run out of memory and your system started swapping?

**Comment by amitprince** [comment]
Hiii @bures  ,Currently i am trying with a 30 GB memory space ,should i try with a High level instance with more Memory and ram  ,will it work ? yes You are right it stopped after some time .....

**Comment by bures** [comment]
Nope. 30 GB should be more than enough. I normally run it with 8GB.

**Comment by bures** [comment]
Can you send me output of `top`.

**Comment by amitprince** [comment]
Hi @bures 
i am trying but its showing this below error ...please help me out .

GET http://localhost:3000/client/mailtrain.css net::ERR_CONNECTION_REFUSED
(index):19 GET http://localhost:3000/static-npm/jquery.min.js net::ERR_CONNECTION_REFUSED
(index):20 GET http://localhost:3000/static-npm/popper.min.js net::ERR_CONNECTION_REFUSED
(index):21 GET http://localhost:3000/static-npm/bootstrap.min.js net::ERR_CONNECTION_REFUSED
(index):26 Warning: Misconfigured urlBases. If the website does not work, check the settings of www.trustedUrlBase, www.sandboxUrlBase and www.publicUrlBase in server config file.
(anonymous) @ (index):26
(index):22 GET http://localhost:3000/static-npm/coreui.min.js net::ERR_CONNECTION_REFUSED
(index):42 Uncaught ReferenceError: MailtrainReactBody is not defined
    at HTMLDocument.<anonymous> ((index):42)
(anonymous) @ (index):42
(index):35 GET http://localhost:3000/client/root.js net::ERR_CONNECTION_REFUSED
2localhost:3000/static/favicon.ico:1 GET http://localhost:3000/static/favicon.ico net::ERR_CONNECTION_REFUSED

**Comment by bures** [comment]
You are seeing this because you didn't set the MAILTRAIN_SETTINGS as @brentkearney instructed you. The log you just pasted even tells that you didn't configure the URL bases. Just follow the installation instructions.

**Comment by amitprince** [comment]
Hii @bures  

i have configured the URL bases ... 

![image](https://user-images.githubusercontent.com/42072278/59556398-99a95080-8fdf-11e9-8ba6-59c10fb27b26.png)

![image](https://user-images.githubusercontent.com/42072278/59556485-b3976300-8fe0-11e9-9f11-39485c96f75b.png)

**Comment by martijnmichel** [comment]
how to set these URL bases is very unclear to me, even from the docs.
