### ISSUE TITLE
V2: Allow adding attachments to sendTemplateEmail API

### ISSUE THREAD

**Issue by heroic** [Mailtrain-org/mailtrain#615]
Transactions emails will often require to send PDFs, etc as attachments(invoices, bills), etc. We could accept attachments as base64 encoded, and as urls, since multipart-encoding is not supported for API

**Comment by bures** [comment]
I reworked the sending mechanism. In that course, I incorporated the attachments. Could you please try that the API works with the current version (in development)? I didn't test it. Thanks.
