### ISSUE TITLE
Cannot clone from an existing template

### ISSUE THREAD

**Issue by trantienthanh** [Mailtrain-org/mailtrain#619]
I'm using Mailtrain v2. When creating a template with "Clone from an existing template" option selected (from a Mosaico with predefined templates), I'm getting "There are errors in the form. Please fix them and submit again." The form is validated with all green tick and there's no error from the web console.

**Comment by bures** [comment]
It should be fixed  now. Please test it. Thanks.

**Comment by trantienthanh** [comment]
Hi Tomas, thanks for fixing this bug. Templates can now be cloned successfully.
One small thing I notice with the cloned templates is that all the images won't be displayed.
All files do get copied correctly to the new template, however the id of the template in the hyperlink to the image files is wrong.
If the id of the template is 10, the id in the hyperlink becomes 100.
If the id of the template is 11, the id in the hyperlink becomes 111.
If the id of the template is 12, the id in the hyperlink becomes 122.
If the id of the template is 13, the id in the hyperlink becomes 133.

Example link:
https://example.com/mosaico/img?src=https://lists.example.com/files/template/file/**133**/dea2ed471d1cb84ccdc5b6bfbfd70ca4&method=resize&params=166,null

The correct link should be:
https://example.com/mosaico/img?src=https://lists.example.com/files/template/file/**13**/dea2ed471d1cb84ccdc5b6bfbfd70ca4&method=resize&params=166,null

**Comment by trantienthanh** [comment]
Data is populated incorrectly in the template table.
\"src\":\"[URL_BASE]/files/template/file/**133**/dea2ed471d1cb84ccdc5b6bfbfd70ca4\",

**Comment by trantienthanh** [comment]
Tomas, can you please shed some light on the part that handles SQL queries? Thanks.

**Comment by forgeOneHQ** [comment]
@trantienthanh please try again with the latest v2 version.
