### ISSUE TITLE
Subscription Form mjml.mjml2html is not a function

### ISSUE THREAD

**Issue by maxsarlija** [Mailtrain-org/mailtrain#620]
hello a while ago I have the error mjml.mjml2html is not a function when I want to access the subcription form to configure it on the web page, I really can not find the error, in some post I saw that I had to modify part of the code, but where I find the code that exports the form to html?
Mailtraing version 1
Thank you so much

**Comment by bures** [comment]
Do you jsem Mailtrain v1 or v2?

**Comment by maxsarlija** [comment]
> Do you jsem Mailtrain v1 or v2?

V1

**Comment by bures** [comment]
I'm afraid v1 is not very actively developed any more. You can try different versions of mjml npm package. At some point, they changed a bit the interface which causes this error. Alternatively, you can try v2 beta, which still has some glitches, but is actively developed.

**Comment by maxsarlija** [comment]
> I'm afraid v1 is not very actively developed any more. You can try different versions of mjml npm package. At some point, they changed a bit the interface which causes this error. Alternatively, you can try v2 beta, which still has some glitches, but is actively developed.

Well, I can not change this version since it is active, but for the next ones we start with v2, how can I install different versions of mjml npm package in ubuntu?
Thank you

**Comment by bures** [comment]
try npm install or update inside the mailtrain directory

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
