### ISSUE TITLE
Cors issue with login page DOCKER beta v2

### ISSUE THREAD

**Issue by DaveClissold** [Mailtrain-org/mailtrain#621]
I've just installed v2 and am getting a CORS error on the login screen, when trying to login for the first time using admin:test

`16:11:56.212 xhr.js:178 OPTIONS https://mailtrain.audiovitamins.com/rest/login 404
16:11:56.212 xhr.js:178 OPTIONS https://mailtrain.audiovitamins.com/rest/login 404
16:11:56.213 login?next=%2F:1 Access to XMLHttpRequest at 'https://mailtrain.audiovitamins.com/rest/login' from origin 'https://lists.audiovitamins.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
16:11:56.214 page.js:545 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)`

It's not listed in the docs as to how to enable CORS? Any advice would be welcome.

**Comment by bures** [comment]
That's strange. Can you send me the content of `trustedUrlBase`, `sandboxUrlBase`, `publicUrlBase` in your mailtrain installation. If you used the installer, it should be located in `server/config/production.yaml`. If you used the docker image, it should be the `MAILTRAIN_SETTINGS` env variable. Also, please send me your hostname ... `hostname -f`.

**Comment by DaveClissold** [comment]
I used the follow for install 

`export MAILTRAIN_SETTINGS="--trustedUrlBase https://mailtrain.audiovitamins.com --sandboxUrlBase https://sbox.mailtrain.audiovitamins.com --publicUrlBase https://lists.audiovitamins.com --withProxy" ` 

hostname -f output:
localhost.localdomain

I am running this on a server which runs plesk and proxying the docker containers though nginx, if that makes any difference

**Comment by bures** [comment]
Hard to say. It looks OK to me. Can you also send me the nginx configuration to see how the proxy is configured?

**Comment by DaveClissold** [comment]
This is for lists.audiovitamins.com, for the others the port changes respectively.  i forgot to mention that I have routed the port 3000 to 3002 as there is already another ruby app running on that port.

```

server {
	listen 77.68.20.225:443 ssl http2;

	server_name lists.audiovitamins.com;
	server_name www.lists.audiovitamins.com;
	server_name ipv4.lists.audiovitamins.com;

	ssl_certificate             /usr/local/psa/var/certificates/scfoIwiyP;
	ssl_certificate_key         /usr/local/psa/var/certificates/scfoIwiyP;
	ssl_client_certificate      /usr/local/psa/var/certificates/scfsaII7E;

	client_max_body_size 128m;

	root "/var/www/vhosts/audiovitamins.com/lists.audiovitamins.com";
	access_log "/var/www/vhosts/system/lists.audiovitamins.com/logs/proxy_access_ssl_log";
	error_log "/var/www/vhosts/system/lists.audiovitamins.com/logs/proxy_error_log";

	#extension docker begin
	location ~ ^/.* {
		proxy_pass http://0.0.0.0:3002;
		proxy_set_header Host              $host;
		proxy_set_header X-Real-IP         $remote_addr;
		proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	#extension docker end

	#extension letsencrypt begin
	location ^~ /.well-known/acme-challenge/ {
		root /var/www/vhosts/default/htdocs;

		types { }
		default_type text/plain;

		satisfy any;
		auth_basic off;
		allow all;

		location ~ ^/\.well-known/acme-challenge.*/\. {
			deny all;
		}
	}
	#extension letsencrypt end

	#extension kolab begin
	# Plesk Premium Mail is not enabled for this domain.
	#extension kolab end

	location / {
		proxy_pass https://77.68.20.225:7081;
		proxy_set_header Host             $host;
		proxy_set_header X-Real-IP        $remote_addr;
		proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header X-Accel-Internal /internal-nginx-static-location;
		access_log off;

	}

	location /internal-nginx-static-location/ {
		alias /var/www/vhosts/audiovitamins.com/lists.audiovitamins.com/;
		internal;
	}

	location ~ ^/(plesk-stat|awstats-icon|webstat|webstat-ssl|ftpstat|anon_ftpstat) {
		proxy_pass https://77.68.20.225:7081;
		proxy_set_header Host             $host;
		proxy_set_header X-Real-IP        $remote_addr;
		proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header X-Accel-Internal /internal-nginx-static-location;
		access_log off;

	}

	add_header X-Powered-By PleskLin;

}

server {
	listen 77.68.20.225:80;

	server_name lists.audiovitamins.com;
	server_name www.lists.audiovitamins.com;
	server_name ipv4.lists.audiovitamins.com;

	client_max_body_size 128m;

	return 301 https://$host$request_uri;
}
```

**Comment by bures** [comment]
That might be the source of the problem. You have to setup the proxy as follows:
- https://mailtrain.audiovitamins.com -> http://localhost:3000
- https://sbox.mailtrain.audiovitamins.com -> http://localhost:3003
- https://lists.audiovitamins.com -> http://localhost:3004

**Comment by DaveClissold** [comment]
Ahhh I got the mailtrain and lists round the wrong, way. I miss read the docs then. Sorry about that and thanks for the help

**Comment by bures** [comment]
No worries. That was good input. I extended a bit the README.md to be a bit more straightforward on this. Thanks.
