### ISSUE TITLE
Bounced emails with AWS SES

### ISSUE THREAD

**Issue by DaveClissold** [Mailtrain-org/mailtrain#622]
So this is a bit of a weird one.  I can send emails to gmail accounts when using a SMTP, but cannot when using AWS SES.  The ses console does not report any rejects or bounces, but mailtrain says they have bounced.  There is not output from # journalctl -f -u mailtrain

`-- Logs begin at Wed 2019-05-29 16:21:03 UTC. --`

Is all I get. I've setup the webhooks to be returned to https://mailtrain.doman.com/webhooks.aws

But nothing more than an indication that it's bounced comes back, but then i get the same bounced email if I turn of the SNS service to the webhook.  

Any ideas on where to start digging about to debug this?

**Comment by halixness** [comment]
Make sure you have successfully configured the SNS Topic. In order of setup:
1. Add and verify a new e-mail address (sender) into the SES Console
2. Create a new SNS topic and insert the Mailtrain Webhook in order to verify it
3. Go back to the sender e-mail address, click and choose the created SNS Topic for bounces, complains...as you wish.
4. Test a new sending. Of course I assume you've already inserted your AWS SES credentials in settings page and ticked the "Using AWS" checkbox.

It works like a charm to me. Be careful: sending rates are not as accurate as you may think. I started from very low numbers in order not to get bounces. Regular bounces from Amazon return an HEX string, if you check the Bounces page under your current campaign, otherwise you may see something like "Message rate reached" error!

**Comment by equilibrium123** [comment]
The guy here made the whole thing of bounce handling using amazon SES look so easy!
https://jloh.co/posts/aws-bounce-notifications-for-mailtrain/

Will just paste the wording here and someone will find useful. It helped me! 
====
Setting up AWS SNS/SES bounce notifications for Mailtrain

Mailtrain is a NodeJS based self hosted Newsletter app built upon Nodemailer. I’ve been having a play around with it and Amazon SES (Simple Email Service) whilst toying with the idea of setting up a weekly newsletter. The issue with not using a local MTA (such as Postfix) is that bounce receipts get lost.

Mailtrain already has webhooks available that Amazon can POST to, but documentation around the setup for it is sadly lacking. So after some trial and error I’ve got it all working with the following.

Create a SNS Topic
First things first, you need to create a SNS topic that will send POSTs to Mailtrain. Go to your Amazon console and go to SNS. Then create a new topic:

New SNS Topic

It doesn’t have to be called mailtrain-bounces but it should be named something you can easily identify/remember later.

Create a SNS Subscription
This is where half the magic happens. You need to tell SNS that it should send notifications to this topic on to Mailtrain. Select your topic you just created and click Create Subscription. Whether you select HTTP or HTTPS as the Protocol is up to you, but if you aren’t using HTTPS you really should be!

The endpoint is just http[s]://<your_mailtrain_domain>/webhooks/aws.

New SNS Subscription

Initially the endpoint status will likely be Pending but if you give it a refresh you’ll see a Subscription ID appear in the first box in the table once SNS confirms the endpoint works.

When creating the Subscription ensure that Raw message delivery is Disabled.

Setup SES Notifications
Finally, we need to edit your SES configuration so it sends bounce notifications for this domain/email to Mailtrain. This step will be slightly different depending on whether you’ve setup the whole domain or just a single email in SES. Either way the changes are mostly the same, just a different left hand menu.

If you have a domain setup in SES you’ll need to edit it via the Domains menu, if its just a single email address you’ll need to edit it via the Email Addresses menu.

Note: I would recommend setting up the specific email/s you’re sending your newsletters from. This way you can just send bounce notifications for these specific emails to Mailtrain as opposed to all bounces that go through SES for that domain.

Once you’ve selected either your domain or email address you’re using in Mailtrain click on the Notifications drop down and edit the configuration. Enter the SNS topic into Bounces and Complaints and boom! You’re all done.

SES Notification Setup

You can try and send a test campaign to an email address that doesn’t work (like this_email_wont_work@geeeeeeeeeeeemail.com) and you should see POST requests from Amazon SNS to your Mailtrain instance reporting the bounce.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
