### ISSUE TITLE
Add easily multiple Emails

### ISSUE THREAD

**Issue by ezzra** [Mailtrain-org/mailtrain#624]
I am missing the possibility to easily add multiple email addresses to a list. Currently there is the option to add a single mail or to import a file. In Mailman you have the opportunity to just enter several emails within a textfield:

![Screenshot_2019-06-28_10-39-07](https://user-images.githubusercontent.com/37742522/60329620-01bd4680-9991-11e9-9818-24f2500ff2dd.png)

I would love to have an easy option like this.

**Comment by forgeOneHQ** [comment]
And what is the issue to make a simple csv file? 

We can think about this feature again.
