### ISSUE TITLE
string not translatable

### ISSUE THREAD

**Issue by ezzra** [Mailtrain-org/mailtrain#626]
The msgid

```
"The custom form used for this list. You can create a form <a href=\"/forms/"
"{{id}}/create\">here</a>."
``` 
will not be translated/replaced in html output. I guess it has something to do with the link and ID there.

**Comment by ezzra** [comment]
and there is also 

`<dt>List subscribers</dt>`

in `./views/campaigns/view.hbs:46` not set up for translations

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
