### ISSUE TITLE
[SOLVED]Working scenario

### ISSUE THREAD

**Issue by doug3d** [Mailtrain-org/mailtrain#627]
I have a small server running some my own websites.

Machine 1 - Centos webpanel with Fixed IP.   Running apache and nginx.

Now I've installed Mailtrain on a new server (called Machine 2) and it's working fine but just throught localhost:3000

How is the right way to run the application on a different machine from my main server and use the same FIXED IP poiting to port 3000 on the server where mailtrain is installed?

Im very lost here because i want to have access to mailtrain externally using a domain hosted on server one.

Thank you guys

**Comment by bures** [comment]
Setup a reverse proxy on Machine 1 that proxies to the ports on Machine 2 as described in https://github.com/Mailtrain-org/mailtrain/blob/development/README.md#deployment-with-docker-and-docker-compose

Remember that you have to configure the url bases in `server/config/production.yaml`. They have to be configured contain to the domain that points to Machine 1 - i.e. the domain you want to use externally to access Mailtrain.

**Comment by doug3d** [comment]
@bures thanks man. is working :)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
