### ISSUE TITLE
mailtrain v2 not starting correctly with last docker image

### ISSUE THREAD

**Issue by PhilippeAccorsi** [Mailtrain-org/mailtrain#635]
## At present

Server1:  
- Debian Jessie 8.10 
- Docker 17.05.0-ce
- Docker-compose  1.7.1
Server2:
- Debian Stretch 9.9
- Docker 18.09.6
- Docker-compose 1.24.0

I have installed Mailtrain with docker in April (I think) to test Mailtrain v2 on server1. In same time on server2 I have installed Mailtrain v1 with docker.

Yesterday I have pull the last v2 docker image (server1) and starting again Mailtrain v2. We have understand at this time why the last time v2 not really working on server1 (missing nginx config about sandbox) so new v2 working good.

I have tried to import database from v1 to v2 (to import list off all email) like this:
- In server2 (Mailtrain v1):
docker exec -it {container_id_mysql} /bin/bash
cd /var/lib/mysql
mysqldump --user=mailtrain --password=mailtrain --databases mailtrain > dump.mailtrain.sql

- In server1 (Mailtrain v2):
docker exec -it {container_id_mysql} /bin/bash
cd /var/lib/mysql
mysql --user=mailtrain --password=mailtrain mailtrain < dump.mailtrain.sql

And after that I have restart all Mailtrain container on server1. But I think its not good idea to import old database to new one because after that I have broken Mailtrain. Nothing work.

So I have deleted all docker volume about Mailtrain v2 and trying to start again Mailtrain (from scratch).
At this time Mailtrain don't want to start because an error appear about missing privileges to connect to Mariadb:
~~~
mailtrain_1  | ERR!    'Error: ER_HOST_NOT_PRIVILEGED: Host \'172.18.0.2\' is not allowed to connect to this MariaDB server\n    at Handshake.Sequence._packetToError (/app/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)\n    at Handshake.ErrorPacket (/app/server/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)\n    at Protocol._parsePacket (/app/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)\n    at Parser._parsePacket (/app/server/node_modules/mysql/lib/protocol/Parser.js:433:10)\n    at Parser.write (/app/server/node_modules/mysql/lib/protocol/Parser.js:43:10)\n    at Protocol.write (/app/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/app/server/node_modules/mysql/lib/Connection.js:525:10)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)\n    --------------------\n    at Protocol._enqueue (/app/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)\n    at Protocol.handshake (/app/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)\n    at PoolConnection.connect (/app/server/node_modules/mysql/lib/Connection.js:119:18)\n    at Pool.getConnection (/app/server/node_modules/mysql/lib/Pool.js:48:16)\n    at listTables (/app/server/lib/dbcheck.js:24:8)\n    at runUpdates (/app/server/lib/dbcheck.js:164:5)\n    at tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at ret (eval at makeNodePromisifiedEval (/app/server/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)\n    at dbcheck (/app/server/lib/dbcheck.js:226:11)\n    at init (/app/server/index.js:83:11)\n    at Object.<anonymous> (/app/server/index.js:129:1)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:282:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)',
mailtrain_1  | ERR!   code: 'ER_HOST_NOT_PRIVILEGED',
mailtrain_1  | ERR!   errno: 1130,
mailtrain_1  | ERR!   sqlMessage:
mailtrain_1  | ERR!    'Host \'172.18.0.2\' is not allowed to connect to this MariaDB server',
mailtrain_1  | ERR!   sqlState: undefined,
mailtrain_1  | ERR!   fatal: true }
~~~

I have tried many things without good result.

I have seen in my server1 that I have docker image when I have tested Mailtrain v2 at the first time (near April) and I try this version:
delete mailtrain_mysql volume and start again Mailtrain but with this specific image.

=> Mailtrain is starting correctly without privileges error.

So I think something is missing or different between April image and latest image.

**Comment by bures** [comment]
Does the docker image start correctly with empty DB? If so, could you check the latest version (the docker image should be available in about 10 minutes). I did some updates in the import from v1. It might work now.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
