### ISSUE TITLE
Mailtrain v2 : imported Subscribers csv file lost some information

### ISSUE THREAD

**Issue by PhilippeAccorsi** [Mailtrain-org/mailtrain#638]
## At present

My Subscribers list use custom fields with "Drop Down (from option fields)".
I have exported list of Subscribers with some value selected in this kind of custom fields.

When I import this list again, all selection in custom field are lost. In export csv I can see value at "1" for each selection but after import I can't see value. If I export again, value is at "0".

I know this is a beta version so I think its a bug in this version.

## Expected

- [ ] Exported csv file and imported this file set all value like visible in exported file.

**Comment by bures** [comment]
Can you paste a line from the CSV here?

**Comment by PhilippeAccorsi** [comment]
Yes of course :)

This is command what I used to export data from mailtrain v1 db:
~~~
SELECT * FROM subscription__5 INTO OUTFILE '/var/lib/mysql-files/prospects4.csv' FIELDS TERMINATED BY ',' ENCLOSED BY '"'  LINES TERMINATED BY '\r\n';
~~~

After that we add column name in csv file to import in mailtrain v2:
~~~
id,cid,email,opt_in_ip,opt_in_contry,tz,imported,status,is test,status changed,latest open,latest click,created,first name,last name,telephone,entreprise ou organisation,post rôle,pro,distributeur,intégrateur,association,enseignement,particulier,site web,jdll,reseau,bouche a oreille,autre,remarque,collectivité
"1","z-054S48h","xxxx.xxxx@xxxx.info",\N,\N,"utc",\N,"1","0","2019-07-15 09:10:16",\N,\N,"2019-07-15 09:10:15","xxxx","xxxx","xxxx","Association Défis","","0","0","0","1","0","0","1","0","0","0","0","Download tracim.fr\
2018-11-15 11:52:04\
Mail envoyé par Damien le 29/11/2018","0"
~~~

To import correctly data we have created all custom fields first in mailtrain v2. All custom field value is not set correctly when import csv, so we have tried to set manually and export csv. We have file like this:
~~~
cid,status,HASH_EMAIL,EMAIL,MERGE_FIRST_NAME,MERGE_LAST_NAME,MERGE_TELEPHONE,MERGE_ENTREPRISE_ORGANISATION,MERGE_POSTE_ROLE,MERGE_REMARQUES,MERGE_PROFESSIONNEL,MERGE_DISTRIBUTEUR,MERGE_ASSOCIATIF,MERGE_ENSEIGNEMENT,MERGE_PARTICULIER,MERGE_COLLECTIVITE,MERGE_SITE_WEB,MERGE_JDLL_2019,MERGE_RESEAUX_SOCIAUX,MERGE_BOUCHE_A_OREILLE,MERGE_AUTRE,MERGE_INTEGRATEUR
dgTmL80r5,subscribed,i3evvAAcZMgxKpVqb9n1oIySwgb21LkGuBG74nRLsR2pXqbpz3Ym7aG5MrkFkUDBtyUta1mls9iIbteJk30iwg==,xxxx.xxxx@xxxx.info,xxxx,xxxx,xxxx,Association Défis,,"Download tracim.fr\
2018-11-15 11:52:04\
Mail envoyé par Damien le 29/11/2018",0,0,1,0,0,0,1,0,0,0,0,0
~~~

After that if I import this file and export again we have this:
~~~
cid,status,HASH_EMAIL,EMAIL,MERGE_FIRST_NAME,MERGE_LAST_NAME,MERGE_TELEPHONE,MERGE_ENTREPRISE_ORGANISATION,MERGE_POSTE_ROLE,MERGE_REMARQUES,MERGE_PROFESSIONNEL,MERGE_DISTRIBUTEUR,MERGE_ASSOCIATIF,MERGE_ENSEIGNEMENT,MERGE_PARTICULIER,MERGE_COLLECTIVITE,MERGE_SITE_WEB,MERGE_JDLL_2019,MERGE_RESEAUX_SOCIAUX,MERGE_BOUCHE_A_OREILLE,MERGE_AUTRE,MERGE_INTEGRATEUR
1HT0puzmJ,subscribed,i3evvAAcZMgxKpVqb9n1oIySwgb21LkGuBG74nRLsR2pXqbpz3Ym7aG5MrkFkUDBtyUta1mls9iIbteJk30iwg==,xxxx.xxxx@xxxx.info,xxxx,xxxx,xxxx,Association Défis,,"Download tracim.fr\
2018-11-15 11:52:04\
Mail envoyé par Damien le 29/11/2018",0,0,0,0,0,0,0,0,0,0,0,0
~~~

We can see value at one is lost in second import.

**Comment by chrisHRD** [comment]
I can report the same issue with my instance of Mailtrain v2. All "options" fields loose their "1" values. Has anyone figured out a workaround to import information?

**Comment by gutobenn** [comment]
Happening here too. It seems option values aren't saved. Tried with different values like `1`, `Yes` and `yes` with no success.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
