### ISSUE TITLE
New feature: Matomo tracking

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#640]
Appart from having Google Analytics tracking, it would be very helpful to support Matomo tracking, both in the application and in campaigns

@bures, does the Google Analytics support campaign tracking with pixel beacons or does it only track platform usage?

**Comment by bures** [comment]
The google analytics tracks only platform usage. I adopted it from Mailtrain v1, so to be completely honest, I'm not sure now what exactly it tracks from the platform. What exactly would you like to track?

**Comment by priethor** [comment]
To be honest, as in my team we run the platform inhouse without granting external members access, platform tracking is not important at all. However, we use intensively Matomo for campaign analytics and currently we are adding manually a tracking pixel to every campaign sent, so that we can double cross the data with Mailtrain's own statistics and even send Matomo the subscriber ID.

First, the plan is to have a look at the current Analytics implementation (to check which events or page views are being tracked) and probably implement the possibility of tracking the same in Matomo. On a second, even more interesting phase IMHO, we are going to study the possibility of automatically adding that tracking pixel to the campaigns, although I'm not very possitive about this since it would need to be introduced in the email HTML.

**Comment by bures** [comment]
The tracking pixel is already in every campaign (unless explicitly forbidden).
BTW, I already started some event reporting infrastructure in the code. It's in server/lib/activity-log.js. You can look for statements like log*Activity. The aim is to add it to all relevant places in code and them implement various event consumers (e.g. Grafana, but maybe also for Matomo ?).

**Comment by priethor** [comment]
Yes, that would be the best option in order to "subscribe" to events happening in Mailtrain. That way we can also send email/slack notifications when campaigns are sent, when they finish or when imports are run (it's a feature PHPList has that was really helpful when managing campaigns with more people).

You are right, Mailtrain already adds its own tracking pixel for its statistics. Then I guess we could add another one next to it if Matomo tracking is enabled!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
