### ISSUE TITLE
I keep getting a High bounce rate with gmail SMTP settings

### ISSUE THREAD

**Issue by lazarusvc** [Mailtrain-org/mailtrain#642]
![screencapture-newsletter-budgeat-co-2019-07-24-10_58_35](https://user-images.githubusercontent.com/4788358/61804782-83728980-ae02-11e9-9a33-569979469495.jpg)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
