### ISSUE TITLE
Sending campaigns concurrently

### ISSUE THREAD

**Issue by ilyacherevkov** [Mailtrain-org/mailtrain#645]
Is it possible to send multiple campaigns concurrently? 

I've configured production.toml to use 2 sender processes and I have Redis installed and configured. 

However in case I start sending 2 campaigs, only one seems to be sent, in two processes.

Can I use each process to send each campaign separately?

**Comment by bures** [comment]
Not sure about Mailtrain v1. You should be able to do that in Mailtrain v2 (currently beta).

**Comment by ilyacherevkov** [comment]
All right, thank you
