### ISSUE TITLE
Delay in sending emails

### ISSUE THREAD

**Issue by metrangia** [Mailtrain-org/mailtrain#646]
We send several thousand emails in one campaign.  Each email is being sent separately, and the entire process takes a few days to complete.  Is it possible to multithread this?  Can you point us to the code that handles the sending of the emails?  Thanks.

**Comment by bures** [comment]
Is that Mailtrain v1 or v2 beta?

**Comment by metrangia** [comment]
It's mailtrain v1.  I'm still getting the details but I am told it took over 24 hours to send 4,000 emails.  That would be less than 3 per minute.  Something seems wrong here.  Could it bog down as the number of recipients increases?

**Comment by bures** [comment]
Not sure about v1. With v2, we are delivering at rate of approx. 6-8 mails per second. But that very much depends on the server and Mailtrain configuration. I believe, we should easily be able to deliver 4000 emails in about 10 minutes.

**Comment by metrangia** [comment]
Thanks Tomas.  Can you point me to the place in the v1 code that sends the emails?  I'd like to take a look and see what's going on.

**Comment by bures** [comment]
Start from services/sender.js

**Comment by forgeOneHQ** [comment]
@metrangia can you please upgrade to v2 if still needed and try again? You are welcome to open a new issue on this and we can help with the investigation if you provide us all infos like configuration, log files and how mailtrain v2 was deployed.
