### ISSUE TITLE
Unable to display images on Masaic

### ISSUE THREAD

**Issue by hernandez949** [Mailtrain-org/mailtrain#648]
Hello. I am using  Ubuntu 18.04.2LT and I installed Mailtrain with Docker. Everything is working fine except I am unable to see the images I upload on Masaico and Grapejs. What can I do to troubleshoot?

**Comment by bures** [comment]
Is that Mailtrain v1 or v2 beta?

**Comment by hernandez949** [comment]
Mailtrain v2 beta

**Comment by bures** [comment]
Did you do it via docker compose up or some other way? Can you send Mailtrain logs produced around inserting the image?

**Comment by hernandez949** [comment]
I am sorry I don't know where to find them. Do you know which command I can
use to pull that up for you?

**Comment by hernandez949** [comment]
Hello I hope these help I think these are the right logs. I really want to get this resolved. 

Thank you so much. 
![logs1](https://user-images.githubusercontent.com/43512431/62339776-0db98e00-b492-11e9-8eb7-8b746ef406a1.png)
![logs2](https://user-images.githubusercontent.com/43512431/62339780-114d1500-b492-11e9-9779-e0060f3aa45d.png)
![logs3](https://user-images.githubusercontent.com/43512431/62339784-14e09c00-b492-11e9-9319-70d5d934b104.png)

**Comment by bures** [comment]
This looks fine. Does the webbrowser say anything. Open the developer view and look at the console and at the network view.

**Comment by bures** [comment]
BTW, this looks like output from Mailtrain v1, not v2 beta. You can send me a screenshot of you think otherwise.

**Comment by hernandez949** [comment]
No you are correct I just double checked it's v1

**Comment by hernandez949** [comment]
![Browser Console](https://user-images.githubusercontent.com/43512431/62349290-2b97ea80-b4b4-11e9-8f98-f03ec11ab83c.png)
![DelopersNetwork](https://user-images.githubusercontent.com/43512431/62349291-2b97ea80-b4b4-11e9-8b37-2367d93d3cff.png)

**Comment by hernandez949** [comment]
that is what I see

**Comment by bures** [comment]
Well. I'm afraid, I won't help you with v1.  You can try v2 beta. If anything doesn't work there, I'll be happy to help.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
