### ISSUE TITLE
V2: Campaigns can't set subject anymore (or most likely wrong upgrade?)

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#652]
After upgrading to the latest development version as of today 5th August, all the knex migrations have applied, removing the "subject" column from the `send_configurations` table. However, the "Subject" text input field still appears in the send configurations screen, and campaigns settings can't override it. At the moment I'm not sure if this is actually a bug or my upgrade isn't successful, since I'm not seeing other fixes that have been done in the last months that I do see when run under a fresh development environment.

Am I missing something in the upgrade process? I deleted my `package-lock.json` files, pulled the latest `origin/development` and run a modules reinstall with the help of the `reinstall-modules.sh` script.

On the other hand, while the knex migrations have applied properly according to both the knex_migrations table and by checking the database structure changes, the migrations from the server/setup/sql folder haven't (there is even no `db_schema_version` row in the `settings` table.

Any suggestion?

**Comment by bures** [comment]
Have you recompiled the client? `npm run build` in client folder. `db_schema_version` is used only for Mailtrain v1 style migrations. Knex has its own tables for this.

**Comment by priethor** [comment]
OMG Tomas, you're a life saver! Such a rookie mistake!

I'm testing now some of the most recent features, such as handlebars tag styles (such a cool feature!). Should I open separate issues for each feature in order to report feedback? For example, as soon as I select HBS in the new campaign "Tag language" dropdown, my client crashes in CUD.js line 150 `this.templateTypes[newValue].afterTagLanguageChange(mutStateData, isEdit);`, as `this.templateTypes` contains `ckeditor4`, `mosaico`, `codeeditor`,  `mosaicoWithFsTemplate`, `grapesjs` but the value of `newValue` is `hbs`.

**Comment by bures** [comment]
Great. Yes, please open the issues. If they are related, you can aggregate them in one issue. Thanks.
