### ISSUE TITLE
V2: Send configurations not working when VERP enabled

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#653]
Affected version: 2019-08-01-0745

When a send configuration has VERP enabled, campaigns can't be sent with that send configuration (test emails do work), failing with the following message:

> Aug 06 09:51:40 mailing.swiss4ward.com node[7957]: ERR! Senders Sending message to 13:1 failed with error: sendConfiguration is not defined.

@Charlo270398 already found the issue and will soon provide a PR.

**Comment by bures** [comment]
Thanks for the PR. I did some additional updates to it. Can you please test it now?

**Comment by priethor** [comment]
Working as expected, thanks!
