### ISSUE TITLE
V2: Can't select HBS tag format during campaign creation

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#655]
Steps to reproduce:
- Create a new campaign.
- Select the HBS tag format instead of simple in the appropriate dropdown.
- The client will crash in line 150 of CUD.js (`this.templateTypes[newValue].afterTagLanguageChange(mutStateData, isEdit);`, as `this.templateTypes` contains `ckeditor4`, mosaico, `codeeditor`, `mosaicoWithFsTemplate`, `grapesjs` but the value of `newValue` is `hbs`.)

@Charlo270398 already found the issue and will soon provide a PR.

**Comment by bures** [comment]
PR merged. Should be fine now. Thanks.
