### ISSUE TITLE
V2: updating

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#657]
Hello from Italy,
I have a working install that I would like to upgrade. I cannot find any reference as to how I should update and retain current lists, templates, campaigns.. 

could anyone point me in the right direction?

**Comment by GadisDEV** [comment]
forgot to mention that i have done a local install using the installa script on a centos7 VM, not using docker.

**Comment by bures** [comment]
It should be enough to follow these steps:

- Backup your Mailtrain DB (!)
- Do `git pull` in the root Mailtrain dir (typically /opt/mailtrain). If git complains about changes in package-lock.json, just revert the files and do the pull.
- Execute `sh setup/reinstall-modules.sh` in root Mailtrain dir
- Execute `npm run build` in `client` directory
- Restart Mailtrain with `systemctl restart mailtrain`

**Comment by GadisDEV** [comment]
worked like a charm. thanks so much!
to "revert", I did 
`git checkout server/package-lock.json` 
anc also for the other package locks. 
thank you so much!
