### ISSUE TITLE
Mailtrain crashes on subscription

### ISSUE THREAD

**Issue by lightonflux** [Mailtrain-org/mailtrain#658]
I am using the current master branch at commit 62e63fbb805ac0364cde02cd3c00705990a82d44.

Everytime i click a subscriber confirmation link MT crashes here:  

`node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:268`
handlebars@4.1.2

Full log:
```node[11871]: info HTTP POST /subscription/GTDO4IInz/subscribe 302 75.761 ms - 146
node[11871]: info HTTP GET /subscription/GTDO4IInz/confirm-subscription-notice 200 55.732 ms - -
node[11871]: /srv/mailtrain/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:268
systemd[1]: mailtrain.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: mailtrain.service: Unit entered failed state.
systemd[1]: mailtrain.service: Failed with result 'exit-code'.
systemd[1]: mailtrain.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped Mailtrain server.
systemd[1]: Started Mailtrain server.

```

Any idea where i can start debugging?

**Comment by bures** [comment]
Honestly, I would suggest that you try Mailtrain v2 beta. I believe v2 beta starts to work better than than v1 which is no longer maintained. Just make sure you backup your database, before migrating to v2. The migration process from v1 to v2 is a bit tricky and prone to errors. Or if you don't have any important existing data, try a fresh install.

**Comment by lightonflux** [comment]
Thanks for the recommendation. Can you recommend me some steps for the migration? Or does v2 setups scripts automatically recognise a v1 DB and update it?

**Comment by bures** [comment]
The easiest is to backup the DB and potential images that you have uploaded to Mailtrain. Make a fresh install of v2 and then delete the DB (just drop the whole DB) and restore it from the v1 backup. Once you start v2, it will recognize v1 DB and will perform migration.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
