### ISSUE TITLE
How to use RSS merge tags?

### ISSUE THREAD

**Issue by radoslav-stefanov** [Mailtrain-org/mailtrain#660]
Hello,

How exactly are RSS merge tags being used?

I tried adding for example [RSS_ENTRY_CONTENT] to the template content, but whenever I send a test email it just prints [RSS_ENTRY_CONTENT] instead of the actual content.

Using development branch.

Thanks!

**Comment by bures** [comment]
Good point. I don't think we have implemented support for RSS in "Test send" so far. To test it at this point, I'm afraid you have to setup and enable the campaign and have it delivered the usual way. 

I'll check whether we can include the RSS entries in "Test send".

**Comment by radoslav-stefanov** [comment]
I see. Well that explains it at least. I was pulling my hair out thinking I am doing something wrong...

I will keep an eye on next commits in case you decide to implement it.

Thanks!

**Comment by bures** [comment]
You can check it now. I added functionality that pulls the feed and substitutes its data to RSS_ENTRY_XXX

**Comment by radoslav-stefanov** [comment]
Thanks, I will review it soon. On vacation still.

**Comment by radoslav-stefanov** [comment]
Confirming this one as well - it is working. Thanks!
