### ISSUE TITLE
Problem with images in outlook

### ISSUE THREAD

**Issue by FlorianDev** [Mailtrain-org/mailtrain#667]
hi,

Hi,

we have the problem that pictures cannot be displayed in Outlook for Windows and cannot be downloaded (see screenshot). 
In Outlook for MacOS and OWA or Thunderbird it works without problems.
What can we do?
We are using Mailtrain V2

Thank you,
Florian

![SharedScreenshot](https://user-images.githubusercontent.com/8836305/62951073-9537c300-bde9-11e9-8a35-a96cd49cb034.jpg)

**Comment by bures** [comment]
Did you try the other clients for the same recipient for whom the Outlook doesn't work?

**Comment by FlorianDev** [comment]
Yes, we did.
Same recipient on Thunderbird, Outlook for Windows and OWA.

**Comment by bures** [comment]
Can you send me the message source from the Outlook?

**Comment by FlorianDev** [comment]
[email_mailtrain.txt](https://github.com/Mailtrain-org/mailtrain/files/3497684/email_mailtrain.txt)

**Comment by bures** [comment]
My 2c is that it is caused by missing file suffix, which Mailtrain does not provide. Can you try the following? Locate the respective row in files_template_file table and change the filename (not the originalname) to the same with `.png` suffix. Locate the file on disk (in server/files/template/file/11) and rename it the same way (i.e. add the suffix). Edit the template such that the file is included with the suffix. Then try to send it again.

**Comment by FlorianDev** [comment]
We did the suggest things. Unfortunately with the same result in Outlook. Do you want to see the message source as well?

**Comment by bures** [comment]
Yes. Please send it to me, I'll double check it.

**Comment by FlorianDev** [comment]
Here you go.
[email_mailtrain2.txt](https://github.com/Mailtrain-org/mailtrain/files/3498039/email_mailtrain2.txt)
Btw. thank you for your help

**Comment by bures** [comment]
Yup. It looks ok. Then sorry. I have no idea. Have you made sure you don't have some antivirus that could be "protecting" the Outlook?

**Comment by FlorianDev** [comment]
I am only using Windows defender.
Is there a possibility, that we switch the way the pictures are sent to something where it is possible to download the images inside outlook like here:
![download](https://user-images.githubusercontent.com/8836305/62961733-9ffc5300-bdfd-11e9-80ad-5f63ad808b66.jpg)

**Comment by bures** [comment]
Not sure what you have in mind. The images are linked in a usual way. Not sure what should be different. If you manage to manually change in Mailtrain. At this point I don't know what the email should look like.

**Comment by mottomoetai** [comment]
3.5 years later, this is still relevant
any solutions?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
