### ISSUE TITLE
Issue while duplicating templates

### ISSUE THREAD

**Issue by sorbanbela** [Mailtrain-org/mailtrain#672]
Hey. I'm new with mailtrain, i'm sorry if this question is not relevant or the issue is caused by me, i just need some help to fix it.

So everything works well, including sending emails, settings .. anything **except duplication of the templates.**
The whole app crashes/stops with the following issue when i'm trying to duplicate a template:

```
Aug 14 13:46:13 kampany npm[28437]: /datastore/mailtrain/node_modules/mysql/lib/protocol/Parser.js:437
Aug 14 13:46:13 kampany npm[28437]:       throw err; // Rethrow non-MySQL errors
Aug 14 13:46:13 kampany npm[28437]:       ^
Aug 14 13:46:13 kampany npm[28437]: TypeError: Cannot read property 'trim' of null
Aug 14 13:46:13 kampany npm[28437]:     at /datastore/mailtrain/lib/models/templates.js:69:23
Aug 14 13:46:13 kampany npm[28437]:     at Array.forEach (<anonymous>)
Aug 14 13:46:13 kampany npm[28437]:     at Object.module.exports.create (/datastore/mailtrain/lib/models/templates.js:63:27)
Aug 14 13:46:13 kampany npm[28437]:     at /datastore/mailtrain/lib/models/templates.js:150:27
Aug 14 13:46:13 kampany npm[28437]:     at Query.<anonymous> (/datastore/mailtrain/lib/models/templates.js:45:20)
Aug 14 13:46:13 kampany npm[28437]:     at Query.<anonymous> (/datastore/mailtrain/node_modules/mysql/lib/Connection.js:525:10)
Aug 14 13:46:13 kampany npm[28437]:     at Query._callback (/datastore/mailtrain/node_modules/mysql/lib/Connection.js:491:16)
Aug 14 13:46:13 kampany npm[28437]:     at Query.Sequence.end (/datastore/mailtrain/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
Aug 14 13:46:13 kampany npm[28437]:     at Query._handleFinalResultPacket (/datastore/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
Aug 14 13:46:13 kampany npm[28437]:     at Query.EofPacket (/datastore/mailtrain/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
```

Can someone had issues like this before?

UPDATE:
Using Ubuntu 18.04 with the first version of Mailtrain (I think that is the stable version at this moment). node v12.8.0, npm  v6.10.2. Running proxied under nginx and SSL.

**Comment by gmaster0o0** [comment]
Somethime the value variable will be null, and the app crashing.

```javascript
    Object.keys(template).forEach(key => {
        let value = template[key];
        key = tools.toDbKey(key);
        if (!allowedKeys.includes(key)) {
            return;
        }
        value = value.trim();
        if (key === 'description') {
            value = tools.purifyHTML(value);
        }
        keys.push(key);
        values.push(value);
    });
```

**Comment by bures** [comment]
My suggestion would be to go for Mailtrain v2 beta (in development branch). Mailtrain v1 is no longer maintained.

**Comment by Raideerke** [comment]
Thank you Gmaster for your work.
@bures I saw there was an update in the master branch a month ago, and because the v2 is beta I was'nt expecting  that it would be stable.

Do you think that the v2 is ready for production use (even with small bugs that may appear)?

**Comment by bures** [comment]
I believe v2 is mostly ready for production. We have been already running it with real subscribers. Of course there are still issues here and there, so make sure that you:
1) Backup the DB and files before every update (ideally back them up every day)
2) Do a small test after every update to make sure that your emails are still being delivered (and accounted for) correctly.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
