### ISSUE TITLE
v2: enabledLanguages not having effect

### ISSUE THREAD

**Issue by mhulet** [Mailtrain-org/mailtrain#678]
I have this in my `production.yaml` file:

```
# Enabled languages
enabledLanguages:
- en-US
```

But I still have all default languages (EN, ES, PT, FK) shown on the language switcher.

* I have installed Mailtrain via Docker
* I have set `enabledLanguages` prior running `MAILTRAIN_SETTINGS=... docker-compose up`

**Comment by bures** [comment]
Works for me. Can you check the config of the live container? The config is regenerated every time to start the container. It's likely that your changes have been overwritten.

**Comment by jonathanmmm** [comment]
@mhulet 

This pull request https://github.com/Mailtrain-org/mailtrain/pull/1185 should close your issue (either doing it yourself, by replacing docker-entrypoint.sh or waiting for a new docker build). If not, please tell.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
