### ISSUE TITLE
If i change the code it's not reflected in application how can i resolve this issues.

### ISSUE THREAD

**Issue by saiprasadMolagavalli143** [Mailtrain-org/mailtrain#682]
Hi Good Morning ..

1)I want to create a signup page for the mail-train application. so i want to made some changes in root .js of client .. (client/src/root.js and client/src/login/root.js) .
But once i run the app, it's not reflected the changes in my application.

2)And i didn't get the routes for login in (server/routes ) 

Please help me on this.. 
Thanks

**Comment by bures** [comment]
The chances are you didn't recompile the client.

**Comment by saiprasadMolagavalli143** [comment]
i entered to the server folder and i did npm install and npm start . the application is open in localhost:3000 . 

but you are saying recompile the client . How can i resolve this issue can you please explain me here

**Comment by saiprasadMolagavalli143** [comment]
@bures  can you please tell exactly what you meant by .. it's very urgent for me ..

**Comment by bures** [comment]
`npm run build` in client directory

**Comment by saiprasadMolagavalli143** [comment]
Thank you it's resolved.

**Comment by saiprasadMolagavalli143** [comment]
But for each change we have to build the app in client . is there any dynamic way to do this.

**Comment by saiprasadMolagavalli143** [comment]
@bures  

Hi i'm creating new tables in mailtrain.sql but when i rebuild the npm and i start the server means it's not created to database . 
can you please let me know here. we have to run any other scripts for this . 
eg :  I'm creating table called master i write the query in mailtrain.sql and i rebuild the npm using npm rebuild and i run the server using npm start database check it build but it's not showing if i add this query to last . if i add this query at first it says something

> mailtrain@2.0.0 start /home/comx/projects/mailtrain/server
> node index.js

info Using local auth 
info sql SQL not set up, initializing
info sql Loading tables from mailtrain.sql
ERR! Error: Settings table not found from database
ERR!     at listTables (/home/comx/projects/mailtrain/server/lib/dbcheck.js:171:33)
ERR!     at Query.connection.query (/home/comx/projects/mailtrain/server/lib/dbcheck.js:61:20)
ERR!     at Query.<anonymous> (/home/comx/projects/mailtrain/server/node_modules/mysql/lib/Connection.js:525:10)
ERR!     at Query._callback (/home/comx/projects/mailtrain/server/node_mod
![Uploading Screenshot from 2019-08-20 13-03-25.png…]


please give me an idea how can we resolve the issue ..
