### ISSUE TITLE
Bug: statistics not tracked when the user is not a test user

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#685]
## Steps to reproduce:
- Create a new list and add a few subscribers, some of them test users and some of them not.
- Create a new campaign and send it that list, with open/click tracking enabled.
- Open the mails recieved in the subscriber mailboxes. Only the subscribers marked as "test users" have their statisctics tracked.

## Stacktrace
Although I can't confirm this happens every single time a user clicks on a link and doesn't get tracked, it is very likely that their related:
> Aug 21 09:23:39 x.y.z node[5495]: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 21 09:23:39 x.y.z node[5495]:     at ServerResponse.setHeader (_http_outgoing.js:470:11)
Aug 21 09:23:39 x.y.z node[5495]:     at ServerResponse.header (/opt/mailtrain/server/node_modules/express/lib/response.js:771:10)
Aug 21 09:23:39 x.y.z node[5495]:     at ServerResponse.send (/opt/mailtrain/server/node_modules/express/lib/response.js:170:12)
Aug 21 09:23:39 x.y.z node[5495]:     at done (/opt/mailtrain/server/node_modules/express/lib/response.js:1008:10)
Aug 21 09:23:39 x.y.z node[5495]:     at /opt/mailtrain/server/node_modules/hbs/lib/hbs.js:93:9
Aug 21 09:23:39 x.y.z node[5495]:     at Object.done (/opt/mailtrain/server/node_modules/hbs/lib/async.js:74:20)
Aug 21 09:23:39 x.y.z node[5495]:     at /opt/mailtrain/server/node_modules/hbs/lib/hbs.js:88:18
Aug 21 09:23:39 x.y.z node[5495]:     at render_file (/opt/mailtrain/server/node_modules/hbs/lib/hbs.js:49:14)
Aug 21 09:23:39 x.y.z node[5495]:     at render_with_layout (/opt/mailtrain/server/node_modules/hbs/lib/hbs.js:80:5)
Aug 21 09:23:39 x.y.z node[5495]:     at Instance.middleware (/opt/mailtrain/server/node_modules/hbs/lib/hbs.js:140:12)
Aug 21 09:23:39 x.y.z node[5495]:     at View.render (/opt/mailtrain/server/node_modules/express/lib/view.js:135:8)
Aug 21 09:23:39 x.y.z node[5495]:     at tryRender (/opt/mailtrain/server/node_modules/express/lib/application.js:640:10)
Aug 21 09:23:39 x.y.z node[5495]:     at Function.render (/opt/mailtrain/server/node_modules/express/lib/application.js:592:3)
Aug 21 09:23:39 x.y.z node[5495]:     at ServerResponse.render (/opt/mailtrain/server/node_modules/express/lib/response.js:1012:7)
Aug 21 09:23:39 x.y.z node[5495]:     at app.use (/opt/mailtrain/server/app-builder.js:362:21)
Aug 21 09:23:39 x.y.z node[5495]:     at Layer.handle_error (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:71:5)
Aug 21 09:23:39 x.y.z node[5495]:     at trim_prefix (/opt/mailtrain/server/node_modules/express/lib/router/index.js:315:13)
Aug 21 09:23:39 x.y.z node[5495]:     at /opt/mailtrain/server/node_modules/express/lib/router/index.js:284:7
Aug 21 09:23:39 x.y.z node[5495]:     at Function.process_params (/opt/mailtrain/server/node_modules/express/lib/router/index.js:335:12)
Aug 21 09:23:39 x.y.z node[5495]:     at next (/opt/mailtrain/server/node_modules/express/lib/router/index.js:275:10)
Aug 21 09:23:39 x.y.z node[5495]:     at Layer.handle_error (/opt/mailtrain/server/node_modules/express/lib/router/layer.js:67:12)
Aug 21 09:23:39 x.y.z node[5495]:     at trim_prefix (/opt/mailtrain/server/node_modules/express/lib/router/index.js:315:13)

## Environment
- Mailtrain version: Build 2019-08-01-0745
- Node version: v10.16.1

**Comment by bures** [comment]
Happened to me to when sending out the last campaign. The tricky part is that test send seems to work. It's the regular send which doesn't work. I still have to have a deeper look at it. It seems as if the image URLs were not overwritten or something.

**Comment by priethor** [comment]
Should we have a look at it or do you have a better idea of what it might be? If so, any clues where we could start looking?

**Comment by priethor** [comment]
By the way @bures, I'm a bit embarrassed to ask this, and I don't think it deserves its own issue, but I wanted to ask you what is your recommendation regarding running mailtrain for development. In our organization we do work in node, but are not used to multi-service projects like mailtrain, so we don't have a clear procedure on how to run it with --inspect-brk, and at the moment most of the debugging is being done mainly with big ol' console logging. Any recommendations? That would make bugfixing and further development so much easier! Thanks!

**Comment by priethor** [comment]
@Charlo270398 has found the source issues: in server/models/links.js, linea 25, the last parameter `isTest` has the default value `true`. Should it be `false` by default or should the calling function pass the right `isTest` value?

**Comment by bures** [comment]
Which file do you have in mind? I can't find `isTest` in https://github.com/Mailtrain-org/mailtrain/blob/a17ee3d9bfb5c9b6529092807ac3e26d3a0549f9/server/models/links.js#L25.

**Comment by Charlo270398** [comment]
It was an error, the correct file is server/models/subscriptions.js line 249

**Comment by Charlo270398** [comment]
But that function should pass an isTest value

**Comment by bures** [comment]
Yes. Indeed. That's an error. The default value of isTest should be `false`. Good catch. Please fix it and try it out. It might indeed be our culprit. Thanks.

**Comment by Charlo270398** [comment]
Ok :+1:

**Comment by Charlo270398** [comment]
The getByCid function before getByCidTx has the same issue, should I fix it too?

**Comment by bures** [comment]
yes please. thanks.

**Comment by priethor** [comment]
Fixed!
