### ISSUE TITLE
v2: "subscriptions is not defined" on GET /api/subscriptions/:listCid

### ISSUE THREAD

**Issue by Riches** [Mailtrain-org/mailtrain#690]
I am trying to use the undocumented API `GET /api/subscriptions/:listCid`.

I am using the latest Docker image with the Image ID 69332658baa1.

Each time I make a request, e.g:
`curl -XGET 'https://example.com/api/subscriptions/nq7soh1sj?access_token=bcee94c8e0670638512d58b2aa87e80514e255f6'`

I get the error 
`{"error":"subscriptions is not defined","data":[]}%`

Other requests such as:
`curl -XPOST 'https://example.com/api/subscribe/nq7soh1sj?access_token=bcee94c8e0670638512d58b2aa87e80514e255f6' \
--data 'EMAIL=test@example.com&MERGE_CHECKBOX=yes&REQUIRE_CONFIRMATION=yes'`

Are still working correctly:
`{"data":{"id":"n-PTSQcP5"}}%`

It's difficult to understand if I am doing something wrong, or if this is indeed a bug due to the limited documentation on this endpoint. Any guidance on this issue would be very helpful, thanks in advance.

**Comment by bures** [comment]
Indeed. I just pushed a fix for the problem. It will take the DockerHub about 10 minutes to rebuild the docker image now. Then you can try it.
