### ISSUE TITLE
V2: Italian localization

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#692]
hi, I would like to help maintain the italian localization. is there anything I could test and/or translate? as an added question, how can I add it_IT to the available languages? if I add anything to the enabled languages, even if the files exist, mailtrain does not start. 
M

**Comment by bures** [comment]
Thanks for the offer. If you like to make the translation, I can setup the language for you. You can then only change the strings under `locales`. OK? 

Just please count with the fact that Mailtrain v2 is under active development, so some translations will have to be updated if we roll out changes.

**Comment by GadisDEV** [comment]
Yes ok,

I imagine that there will be extra strings added to the language file which would not be translated. Are there any localization services in use like poeditor.com (which is used for mosaico), or shall I simply send an updated and translated file by some intricate git procedure J

 

Michel Renders

 

Gadis Tourist Service Italia Srl 

Località Bra 1, 18021 Borgomaro (IM) – Italia

T. +39 0183 548 248 – F. +39 0183 548 222 

E-mail:  <mailto:michel@gadis.it> michel@gadis.it – Web:  <http://www.gadis.it/> www.gadis.it 
SDI: SUBM70N - PEC:  <mailto:git@pec.gadis.it> git@pec.gadis.it

P.IVA IT01134150083 - Privacy:  <http://www.gadis.it/privacy> www.gadis.it/privacy

 

 

Da: Tomas Bures [mailto:notifications@github.com] 
Inviato: lunedì 26 agosto 2019 10:02
A: Mailtrain-org/mailtrain
Cc: MGadis; Author
Oggetto: Re: [Mailtrain-org/mailtrain] V2: Italian localization (#692)

 

Thanks for the offer. If you like to make the translation, I can setup the language for you. You can then only change the strings under locales. OK?

Just please count with the fact that Mailtrain v2 is under active development, so some translations will have to be updated if we roll out changes.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
