### ISSUE TITLE
Sub-segmentation

### ISSUE THREAD

**Issue by manoaratefy** [Mailtrain-org/mailtrain#694]
Good morning,

I need sub-segmentation for my marketing emails.

Example : I have 100 000 emails. I have a first segment who has all peoples purchased one of a specific product (let's says, they purchased a VPS or a dedicated server). Then I need segment this segment to choose those who are speaking French. So, the sub-segment is "Peoples having VPS or dedicated servers but speaking french".

How to achieve this on Mailtrain?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
