### ISSUE TITLE
V2: Message links are generated incorrectly when using a non-root URL base

### ISSUE THREAD

**Issue by Riches** [Mailtrain-org/mailtrain#696]
When the config constant `publicUrlBase` is set to a non-root path:

e.g. `https://example.org/email-marketing/`

and `path` is passed into `getPublicUrl` prepended with a forward slash as it is in `getMessageLinks`:

e.g.
`result.LINK_UNSUBSCRIBE = getPublicUrl('/subscription/' + list.cid + '/unsubscribe/' + subscription.cid + '?c=' + campaign.cid);`

 it removes the path provided in `publicUrlBase` and appends the given `path` to the root (`/`) of the domain as defined in `publicUrlBase`.

Which leaves you with:
https://example.org/subscription/07g6GJR8P/unsubscribe/BzjndRhDt?c=IRiyViLBp
instead of the intended:
https://example.org/email-marketing/subscription/07g6GJR8P/unsubscribe/BzjndRhDt?c=IRiyViLBp

I believe the fix here is to remove the forward slash (`/`) as it is defined in `getMessageLinks` e.g.

 `result.LINK_UNSUBSCRIBE = getPublicUrl('subscription/' + list.cid + '/unsubscribe/' + subscription.cid + '?c=' + campaign.cid);`

Many thanks in advance for any assistance in this matter.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
