### ISSUE TITLE
Error: The migration directory is corrupt, the following files are missing: 20190726150000_shorten_field_column_names.js

### ISSUE THREAD

**Issue by gkisdaroczi** [Mailtrain-org/mailtrain#697]
I don't know what is the problem, but the development branch's docker-compose-local.yml is not enough good to build a docker container. :/
I got an error and the mailtrain container cannot start. The other 3 of 4 service is running, without the GUI. 

The log show this:
mailtrain_1  | info Using local auth 
mailtrain_1  | info sql Database check completed
mailtrain_1  | ERR! Error: The migration directory is corrupt, the following files are missing: 20190726150000_shorten_field_column_names.js
mailtrain_1  | ERR!     at validateMigrationList (/app/server/node_modules/knex/lib/migrate/Migrator.js:341:11)
mailtrain_1  | ERR!     at migrationListResolver.listAllAndCompleted.tap.value (/app/server/node_modules/knex/lib/migrate/Migrator.js:77:91)
mailtrain_1  | ERR!     at PassThroughHandlerContext.finallyHandler (/app/server/node_modules/bluebird/js/release/finally.js:57:23)
mailtrain_1  | ERR!     at PassThroughHandlerContext.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:517:31)
mailtrain_1  | ERR!     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:574:18)
mailtrain_1  | ERR!     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:619:10)
mailtrain_1  | ERR!     at Promise._settlePromises (/app/server/node_modules/bluebird/js/release/promise.js:699:18)
mailtrain_1  | ERR!     at Promise._fulfill (/app/server/node_modules/bluebird/js/release/promise.js:643:18)
mailtrain_1  | ERR!     at PromiseArray._resolve (/app/server/node_modules/bluebird/js/release/promise_array.js:126:19)
mailtrain_1  | ERR!     at PromiseArray._promiseFulfilled (/app/server/node_modules/bluebird/js/release/promise_array.js:144:14)
mailtrain_1  | ERR!     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:579:26)
mailtrain_1  | ERR!     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:619:10)
mailtrain_1  | ERR!     at Promise._settlePromises (/app/server/node_modules/bluebird/js/release/promise.js:699:18)
mailtrain_1  | ERR!     at _drainQueueStep (/app/server/node_modules/bluebird/js/release/async.js:138:12)
mailtrain_1  | ERR!     at _drainQueue (/app/server/node_modules/bluebird/js/release/async.js:131:9)
mailtrain_1  | ERR!     at Async._drainQueues (/app/server/node_modules/bluebird/js/release/async.js:147:5)
mailtrain_1  | ERR!     at Immediate.Async.drainQueues [as _onImmediate] (/app/server/node_modules/bluebird/js/release/async.js:17:14)
mailtrain_1  | ERR!     at runCallback (timers.js:705:18)
mailtrain_1  | ERR!     at tryOnImmediate (timers.js:676:5)
mailtrain_1  | ERR!     at processImmediate (timers.js:658:5)
mailtrain_1  | ERR!     at process.topLevelDomainCallback (domain.js:120:23)
mailtrain_1  | ERR!  { Error: The migration directory is corrupt, the following files are missing: 20190726150000_shorten_field_column_names.js
mailtrain_1  | ERR!     at validateMigrationList (/app/server/node_modules/knex/lib/migrate/Migrator.js:341:11)
mailtrain_1  | ERR!     at migrationListResolver.listAllAndCompleted.tap.value (/app/server/node_modules/knex/lib/migrate/Migrator.js:77:91)
mailtrain_1  | ERR!     at PassThroughHandlerContext.finallyHandler (/app/server/node_modules/bluebird/js/release/finally.js:57:23)
mailtrain_1  | ERR!     at PassThroughHandlerContext.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)
mailtrain_1  | ERR!     at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:517:31)
mailtrain_1  | ERR!     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:574:18)
mailtrain_1  | ERR!     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:619:10)
mailtrain_1  | ERR!     at Promise._settlePromises (/app/server/node_modules/bluebird/js/release/promise.js:699:18)
mailtrain_1  | ERR!     at Promise._fulfill (/app/server/node_modules/bluebird/js/release/promise.js:643:18)
mailtrain_1  | ERR!     at PromiseArray._resolve (/app/server/node_modules/bluebird/js/release/promise_array.js:126:19)
mailtrain_1  | ERR!     at PromiseArray._promiseFulfilled (/app/server/node_modules/bluebird/js/release/promise_array.js:144:14)
mailtrain_1  | ERR!     at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:579:26)
mailtrain_1  | ERR!     at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:619:10)
mailtrain_1  | ERR!     at Promise._settlePromises (/app/server/node_modules/bluebird/js/release/promise.js:699:18)
mailtrain_1  | ERR!     at _drainQueueStep (/app/server/node_modules/bluebird/js/release/async.js:138:12)
mailtrain_1  | ERR!     at _drainQueue (/app/server/node_modules/bluebird/js/release/async.js:131:9)
mailtrain_1  | ERR!     at Async._drainQueues (/app/server/node_modules/bluebird/js/release/async.js:147:5)
mailtrain_1  | ERR!     at Immediate.Async.drainQueues [as _onImmediate] (/app/server/node_modules/bluebird/js/release/async.js:17:14)
mailtrain_1  | ERR!     at runCallback (timers.js:705:18)
mailtrain_1  | ERR!     at tryOnImmediate (timers.js:676:5)
mailtrain_1  | ERR!     at processImmediate (timers.js:658:5)
mailtrain_1  | ERR!     at process.topLevelDomainCallback (domain.js:120:23)
mailtrain_1  | ERR!   stack:
mailtrain_1  | ERR!    'Error: The migration directory is corrupt, the following files are missing: 20190726150000_shorten_field_column_names.js\n    at validateMigrationList (/app/server/node_modules/knex/lib/migrate/Migrator.js:341:11)\n    at migrationListResolver.listAllAndCompleted.tap.value (/app/server/node_modules/knex/lib/migrate/Migrator.js:77:91)\n    at PassThroughHandlerContext.finallyHandler (/app/server/node_modules/bluebird/js/release/finally.js:57:23)\n    at PassThroughHandlerContext.tryCatcher (/app/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/server/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/server/node_modules/bluebird/js/release/promise.js:699:18)\n    at Promise._fulfill (/app/server/node_modules/bluebird/js/release/promise.js:643:18)\n    at PromiseArray._resolve (/app/server/node_modules/bluebird/js/release/promise_array.js:126:19)\n    at PromiseArray._promiseFulfilled (/app/server/node_modules/bluebird/js/release/promise_array.js:144:14)\n    at Promise._settlePromise (/app/server/node_modules/bluebird/js/release/promise.js:579:26)\n    at Promise._settlePromise0 (/app/server/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/app/server/node_modules/bluebird/js/release/promise.js:699:18)\n    at _drainQueueStep (/app/server/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/app/server/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/app/server/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/app/server/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:705:18)\n    at tryOnImmediate (timers.js:676:5)\n    at processImmediate (timers.js:658:5)\n    at process.topLevelDomainCallback (domain.js:120:23)' }

The development-tb branch also not working for me. :/
It is better, because the webserver service is working, but I only got blank/white screens. :/

Appreciate any help.

Edit: It's a brand new install/build. Try to remove images/containers/etc but nothing help.

**Comment by bures** [comment]
There was a problem with migration `20190726150000_shorten_field_column_names.js`. If your DB contains it, you have to manually execute a fix. See #665.

**Comment by gkisdaroczi** [comment]
> There was a problem with migration `20190726150000_shorten_field_column_names.js`. If your DB contains it, you have to manually execute a fix. See #665.

Thank you, for your reply. :) I going to try.
