### ISSUE TITLE
V2: TypeError: The operator "campaign_links.subscription" is not permitted

### ISSUE THREAD

**Issue by mikpel123** [Mailtrain-org/mailtrain#701]
Restarting service:

`systemctl restart mailtrain`

Gives out following error:

```
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers TypeError: The operator "campaign_links.subscription" is not permitted
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Formatter.operator (/opt/mailtrain/server/node_modules/knex/lib/formatter.js:186:13)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.onBasic (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:531:70)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.join (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:294:41)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at components.map.component (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:67)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Array.map (<anonymous>)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.select (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:35)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.toSQL (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:50:29)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Builder.toSQL (/opt/mailtrain/server/node_modules/knex/lib/query/builder.js:72:44)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at /opt/mailtrain/server/node_modules/knex/lib/runner.js:37:34
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:517:31)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:574:18)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:619:10)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromises (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:699:18)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._fulfill (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:643:18)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at PromiseArray._resolve (/opt/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:126:19)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at PromiseArray._promiseFulfilled (/opt/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:144:14)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:579:26)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:619:10)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromises (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:699:18)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers  { TypeError: The operator "campaign_links.subscription" is not permitted
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Formatter.operator (/opt/mailtrain/server/node_modules/knex/lib/formatter.js:186:13)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.onBasic (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:531:70)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.join (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:294:41)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at components.map.component (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:67)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Array.map (<anonymous>)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.select (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:35)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at QueryCompiler_MySQL.toSQL (/opt/mailtrain/server/node_modules/knex/lib/query/compiler.js:50:29)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Builder.toSQL (/opt/mailtrain/server/node_modules/knex/lib/query/builder.js:72:44)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at /opt/mailtrain/server/node_modules/knex/lib/runner.js:37:34
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at /opt/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at tryCatcher (/opt/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromiseFromHandler (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:517:31)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromise (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:574:18)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromise0 (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:619:10)
Sep 11 06:57:07 server1 node[1343]: ERR! Triggers     at Promise._settlePromises (/opt/mailtrain/server/node_modules/bluebird/js/release/promise.js:699:18)
```

**Comment by landif** [comment]
Same error... It appears this error is causing triggers to fail....
`Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers TypeError: The operator "campaign_links.subscription" is not permitted
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Formatter.operator (/var/local/mailtrain/server/node_modules/knex/lib/formatter.js:186:13)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.onBasic (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:531:70)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.join (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:294:41)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at components.map.component (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:67)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Array.map (<anonymous>)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.select (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:35)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.toSQL (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:50:29)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Builder.toSQL (/var/local/mailtrain/server/node_modules/knex/lib/query/builder.js:72:44)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at /var/local/mailtrain/server/node_modules/knex/lib/runner.js:37:34
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at tryCatcher (/var/local/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at /var/local/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at tryCatcher (/var/local/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromiseFromHandler (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise0 (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromises (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:729:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._fulfill (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:673:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at PromiseArray._resolve (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:127:19)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at PromiseArray._promiseFulfilled (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:145:14)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:609:26)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise0 (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromises (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:729:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers  { TypeError: The operator "campaign_links.subscription" is not permitted
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Formatter.operator (/var/local/mailtrain/server/node_modules/knex/lib/formatter.js:186:13)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.onBasic (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:531:70)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.join (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:294:41)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at components.map.component (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:67)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Array.map (<anonymous>)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.select (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:35)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at QueryCompiler_MySQL.toSQL (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:50:29)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Builder.toSQL (/var/local/mailtrain/server/node_modules/knex/lib/query/builder.js:72:44)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at /var/local/mailtrain/server/node_modules/knex/lib/runner.js:37:34
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at tryCatcher (/var/local/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at /var/local/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at tryCatcher (/var/local/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromiseFromHandler (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise0 (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromises (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:729:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._fulfill (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:673:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at PromiseArray._resolve (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:127:19)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at PromiseArray._promiseFulfilled (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:145:14)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:609:26)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromise0 (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers     at Promise._settlePromises (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:729:18)
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers   stack:
Jun 01 18:58:11 mailtrain node[2364]: ERR! Triggers    'TypeError: The operator "campaign_links.subscription" is not permitted\n    at Formatter.operator (/var/local/mailtrain/server/node_modules/knex/lib/formatter.js:186:13)\n    at QueryCompiler_MySQL.onBasic (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:531:70)\n    at QueryCompiler_MySQL.join (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:294:41)\n    at components.map.component (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:67)\n    at Array.map (<anonymous>)\n    at QueryCompiler_MySQL.select (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:96:35)\n    at QueryCompiler_MySQL.toSQL (/var/local/mailtrain/server/node_modules/knex/lib/query/compiler.js:50:29)\n    at Builder.toSQL (/var/local/mailtrain/server/node_modules/knex/lib/query/builder.js:72:44)\n    at /var/local/mailtrain/server/node_modules/knex/lib/runner.js:37:34\n    at tryCatcher (/var/local/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)\n    at /var/local/mailtrain/server/node_modules/bluebird/js/release/using.js:185:26\n    at tryCatcher (/var/local/mailtrain/server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:729:18)\n    at Promise._fulfill (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:673:18)\n    at PromiseArray._resolve (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:127:19)\n    at PromiseArray._promiseFulfilled (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise_array.js:145:14)\n    at Promise._settlePromise (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:609:26)\n    at Promise._settlePromise0 (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/var/local/mailtrain/server/node_modules/bluebird/js/release/promise.js:729:18)' }
`

**Comment by tstrg** [comment]
I'm facing the same after restarting, did you find the resolution?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
