### ISSUE TITLE
Muli-Domain Options

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#705]
It would be nice if there was a way to setup mailtrain for mailing across multiple domains. Is there any possibility or desire to configure mailtrain with a more comprehensive whitelisting process? Perhaps you could configure multiple domains with custom addresses, DKIM, SMTP configurations. 

*Pseudo configuration:*
```
{
  "domain1.com": {
    "relay": "smtp.sendgrid.net",
    "user": "apikey",
     "pass": "abcd1234",
     "from": "noreply@domain1.com"
  },
  "domain2.com": {
    "relay": "SES",
    "user": "key",
    "pass": "secret",
    "from": "noreply@domain2.com"
  }
}
```

If we stored relay and other info by brand, we could then choose to have lists or campaigns that are associated with different brands. Is there anything like this in the works or is the current choice simply that you should run 1 instance of mailtrain for each sending domain?

**Comment by hiyukoim** [comment]
+1 :) That's a good idea, too!

**Comment by bures** [comment]
Implemented in v2 beta. It's called "send configuration".

**Comment by ericuldall** [comment]
I had a follow up question on this. I've been using the development build and the send configurations look good so far. One more thing i'm wondering...is there some way to use custom pixels/click links for each send configuration?

Essentially I'd like to be able to white label any links, images, etc... in the email to the sending domain to allow the highest fidelity brand management possible.

**Comment by ericuldall** [comment]
@bures Can you verify if what I've asked above is possible?

I'm thinking it could be as simple as allowing multiple hostnames per installation and then allowing customization of link urls.

Thoughts?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
