### ISSUE TITLE
V2 - Local or Docker Setup - Pages not loading after clean install

### ISSUE THREAD

**Issue by rlburkey** [Mailtrain-org/mailtrain#707]
Recently followed documentation for a local install and the Docker install for V2 on a clean Ubuntu 18.04 server.  Both had the same result, when going to http://ip-address-of-server:3000 I get a blank page, and when I goto :3003 and 3004 I receive the error "Cannot GET /"

Help is appreciated!

**Comment by bures** [comment]
Check the webbrowser console. My guess is that you didn't configure the URL bases.

**Comment by rlburkey** [comment]
Good Evening!

Thank you for the response, you were absolutely right!  I reinstalled using
Docker and used my reverse proxy and it works perfectly.

Quick second question, let me know if I should open a new incident.  I'm
trying to add email addresses using the API.  Using the string below it
adds the email address, but does not add the first or last names, is there
something else I'm missing?

curl -XPOST 'https://mailtrain.example.com/api/subscribe/kS653QEyJ?access_token={{AccessToken}}’
\

--data 'EMAIL=test.account@email.com
&FIRST_NAME=Test&LAST_NAME=Account&TIMEZONE=EST&MERGE_CHECKBOX=yes'



Thanks!

~R

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
