### ISSUE TITLE
V2: Can't edit campaign content

### ISSUE THREAD

**Issue by balping** [Mailtrain-org/mailtrain#708]
I installed the latest available version with Docker. All domain names are correctly set up.

If I create a new campaign, the editor doesn't show up when editing the content. This is true for all editors, including the plain code editor.

Debug console:

```
window.controllers/Controllers is deprecated. Do not use it for UA detection. root.js line 2582 > eval:1362
```

![a](https://user-images.githubusercontent.com/5840038/65391729-981cc080-dd64-11e9-9764-c9f41d642def.png)

**Comment by BennyAZ** [comment]
Mine does the same thing.

**Comment by balping** [comment]
Out of curiosity, today I upgraded to the latest docker version, the issue still persists.

**Comment by forgeOneHQ** [comment]
@balping that looks to me that the connection to the sandbox is not working properly. Please try to install the latest version and if you are still struggling please open a new issue and provide all configuration information etc. for making the investigation easier.
