### ISSUE TITLE
V2: Charset mismatch in MySQL

### ISSUE THREAD

**Issue by Naruto-kyun** [Mailtrain-org/mailtrain#710]
Hi

Using docker image, i got this error:

`ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='.
ERR! Senders Sending message to 2:707 failed with error: select `id`, `cid` from `links` where `campaign` = 22 and `url` = 'https://SOME-URL' limit 1`

To fix it I had to changer charset of links.url to utf8mb4_general_ci

**Comment by forgeOneHQ** [comment]
@Naruto-kyun please try the latest version v2 and open a new issue if it still exists.
