### ISSUE TITLE
V2: Create docker-config, which allows to use external MYSQL-database

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#713]
I would like to use a mysql-database, which is on the same machine as docker is running. This would cause less overhead by installing another sql-database via docker, which has to be backuped separately, etc.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
