### ISSUE TITLE
Disable fonts loaded from fonts.googleapis.com

### ISSUE THREAD

**Issue by bit** [Mailtrain-org/mailtrain#718]
The "Please Confirm Subscription" currently loads Lato from fonts.googleapis.com.
This results in a warning in Thunderbird:
 To protect your privacy, Thunderbird has blocked remote content in this message.

there does not seam to be a way to not include font links to fonts.googleapis.com

**Comment by saschafoerster** [comment]
I would also be very happy, if all external references, especially Google fonts, could be completely removed from the source code. Google fonts is not good for privacy and not recommended to use in Europe without cookie warning as data is transferred to the US: https://www.golem.de/news/landgericht-muenchen-einbindung-von-google-fonts-ist-rechtswidrig-2202-162826.html

**Comment by jonathanmmm** [comment]
@saschafoerster @bit look at my pull request, until this is through, try the description about the layout for a fast fix and tell if it works.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
