### ISSUE TITLE
Some parameters not saved using API

### ISSUE THREAD

**Issue by inkhey** [Mailtrain-org/mailtrain#727]
Hello !

Using v2 Beta docker.
i'm using API to add subscription to a list:

```
> http post 'http://localhost:3000/api/subscribe/XXXX?access_token=XXXX' EMAIL='toto@toto.toto' FIRST_NAME='Toto' LAST_NAME='TOTO'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 27
Content-Type: application/json; charset=utf-8
Date: Fri, 11 Oct 2019 13:08:37 GMT
ETag: W/"1b-C8e0kiIVjF1MJBZZLpkOKAeg26Q"
Vary: Accept-Encoding

{
    "data": {
        "id": "K4JyXSJt-"
    }
}
```
It's working but i get this in edit view for subscription:

![Capture du 2019-10-11 15-19-13](https://user-images.githubusercontent.com/7851652/66654474-91ce8580-ec3a-11e9-89bf-c95d69ec4656.png)

 FIRST_NAME and LAST_NAME are not handled correctly.

**Comment by inkhey** [comment]
It's seems to work with Merge tag MERGE_FIRST_NAME.
Documentation is not correct as it say to use FIRST_NAME which doesn't work.

**Comment by l4b4r4b4b4** [comment]
@inkhey  thx a lot. That hint took me a step further. Though the names seem to be lowercased.

Any suggestions on how to fix that? @bures maybe?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
