### ISSUE TITLE
V2 - Permission denied for Unsubscribe, Preferences and View in Browser

### ISSUE THREAD

**Issue by 0nlyP2P** [Mailtrain-org/mailtrain#729]
I have installed the version 2, but unsubscribing, managing and view in browser are not working.

The links are generated with the newsletter id, the campaign id and the subscribers id, but even with new emails I cant access those links, always results in Permission denied.

The first time I subscribed and unsubscribed it worked, but even restarting mailtrain a few times didnt change the result

**Comment by bures** [comment]
That sounds strange. Could it be that you public URL endpoint is misconfigured?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
