### ISSUE TITLE
[ QUESTION ] V2 or V1?

### ISSUE THREAD

**Issue by dgulias** [Mailtrain-org/mailtrain#734]
Hello dear comunity,

First of all, I want to thank you everybody that work hard to mantain this amazing project.

I have a question about what version to install.

I had a MailChimp account with about 5 different websites email lists (but all little lists). I always deleted useless/non engagement emails to not get to the next list level and increase the monthly plan cost. Today the total (from all lists) is less then 2000 subscribers.

I'm tired of this and start to build a simple self-host bulk email service to send newsletter and use automation like MailChimp and other providers, but just to my websites (from now, at least).

For now I can't spend too much so my VM is Linode: Ubuntu 18.04 LTS, Nanode 1GB: 1 CPU, 25GB Storage, 1GB RAM.

Do you think it is possible to use this Linode server with Haraka (or ZoneMTA) + Redis + MailTrain V2 so i can send newsletter from those 5 different lists senders little websites?

My concern is the 2-CPU and 2GB RAM recommendation. But I'm not sending over 200.000 email monthly (i'm far from that for now).

 

Cheers

**Comment by GadisDEV** [comment]
hi, i use a hyperv vm, centos 4gb and it seems quite oversized for the 6000+ addresses we manage.
using V2 wich has some quirks but is otherwise veeerrry nice.

**Comment by dgulias** [comment]
Thank you for the information. I'll try the V2 and I put the feedback later for anyone interested in this information.

**Comment by dgulias** [comment]
> 
> 
> hi, i use a hyperv vm, centos 4gb and it seems quite oversized for the 6000+ addresses we manage.
> using V2 wich has some quirks but is otherwise veeerrry nice.

Thank you for the information. I'll try the V2 and I put the feedback later for anyone interested in this information.

**Comment by tcurdt** [comment]
Is there somewhere a comparison of v1 vs v2?
I am currently also looking into installing `mailtrain` - but not sure which version.

I am a little surprised there are not official docker images.

**Comment by forgeOneHQ** [comment]
@dgulias  please install v2, v1 is EOL.
