### ISSUE TITLE
Lets Encrypt Error during install on Ubuntu 18.04

### ISSUE THREAD

**Issue by baylf2000** [Mailtrain-org/mailtrain#736]
Hi there,

There is currently an error occurring during installation on Ubuntu 18.04 using the specified install script "setup/install-ubuntu1804-https.sh". Lets Encrypt install is failing with the following message:

`The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.`

**Comment by baylf2000** [comment]
This seems related.

https://bugs.launchpad.net/ubuntu/+source/python-certbot/+bug/1847776

**Comment by baylf2000** [comment]
OK, doing the following before starting the install script seems to solve the problem. It replaces the old, outdated ubuntu certbot packages with more updated versions from developers of certbot.

`sudo add-apt-repository ppa:certbot/certbot
sudo apt update
sudo apt upgrade`

If you've already run the installer and it failed, you can do the above and just re-run the install again.

**Comment by forgeOneHQ** [comment]
@baylf2000 an ansible-playbook will fix that. I just need to combine it for a full installation playbook since I have most of the roles already finished.
