### ISSUE TITLE
How to uninstall and reinstall? 

### ISSUE THREAD

**Issue by Itsmesri** [Mailtrain-org/mailtrain#738]
After installing everything at the end of installation at DNS resolve it failed. I fixed my dns now and I am able to ping **mailtrain.mydomain.info, lists.mydomain.info and sbox.mailtrain.mydomain.info.**

Now I need to redo everything from beginning install. I tried bash command again but it did go through well like my previous install. Is there anyway I can do reinstall or remove and install again

**Comment by bures** [comment]
If you purge the database - ie. remove the Mailtrain DB and the Mailtrain user - you should be able to rerun the install script.

**Comment by forgeOneHQ** [comment]
In v2 you have the option to remove the necessary modules by running delete-modules.sh

Databases can be easily dropped, same for users. I think about to add it to an ansible-playbook as soon as it is ready.
