### ISSUE TITLE
maximum number of subscribers in a campaign

### ISSUE THREAD

**Issue by gilsimjo** [Mailtrain-org/mailtrain#743]
Hello,

I have a list with 80.930 subscribers. I have sent a campaign to this list yesterday, but not everybody has received the email, I'm not sure but I think that the email has been received by 13000 subscribers more or less. My questions are:

1.-Is there any maximum number of subscribers per campaign? Can I modify this number? or I have to create different lists and send the email to each list.

2.-My campaign has finished of sending emails one our ago, do you think that mailtrain is still sending emails and the rest of subscribers will receive the email later?

3.- Can this be a problem from my email provider??

Thanks for your help.

**Comment by bures** [comment]
Is it Mailtrain V1 or V2?

**Comment by gilsimjo** [comment]
Hi is the last version of the github repository. (https://github.com/Mailtrain-org/mailtrain) according to the readme file is v1.24.0

**Comment by forgeOneHQ** [comment]
@gilsimjo please try to use v2 and also that you correctly configured your spf record and optional also dkim to your domains.
