### ISSUE TITLE
V2: translation to IT

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#744]
i have opened a poedit project for the italian translation:
https://poeditor.com/join/project/U7eqwdyQjl
and paid for automatic translation which is actually quite good. 
i am halfway correcting the translations.

**Comment by GadisDEV** [comment]
Hello,

For a project to qualify it needs to have the official translation on POEditor and the request must be submitted by a maintainer.
If the Mailtrain community decides to localize with POEditor, we'll be happy to host them.

Best regards,
Adrian Basalic
POEditor.com

On Wed, Oct 23, 2019 at 2:08 PM POEditor <noreply@poeditor.com> wrote:
New Open Source Project Request!
Request by: Michel (michel@***.it)

Project: mailtrain 
Project License: GPLv3 
Project URL: https://github.com/Mailtrain-org/mailtrain/tree/development 
Project Description: 
Mailtrain is a self hosted newsletter application built on Node.js (v10+) and MySQL (v8+) or MariaDB (v10+).

**Comment by finefilm** [comment]
I would gladly localize Mailtrain v2 to Hungarian on POEditor.

**Comment by GadisDEV** [comment]
ok I accepted you. I do not know if you can buy AT credits for automatic translation yourself. please advise.

**Comment by GadisDEV** [comment]
I have paid 6 months of PoEdit on this project. The limit is 1000 strings but the languages are unlimited. this means I have truncated the list. 
So If anyone wants to help with translation, pease do so by requesting access, and you should be able to use the poedit tools.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
