### ISSUE TITLE
Allow configuration of SMTP using toml or env variables

### ISSUE THREAD

**Issue by tuaris** [Mailtrain-org/mailtrain#745]
Currently the outbound SMTP configuration is stored in the database.  It would be useful to allow these value to be configured using the `config/production.toml` file instead or by an environmental variable.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
