### ISSUE TITLE
V2: Dynamic Subject Lines?

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#746]
Is it possible to use merge tags in the subject line? I've tried something like `[MERGE_FIRST_NAME], we have an email for you` but that doesn't seem to work.

Is this possible or coming soon?

**Comment by bures** [comment]
It should be possible. But I have probably never tested it.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
