### ISSUE TITLE
Export List

### ISSUE THREAD

**Issue by luisacamara** [Mailtrain-org/mailtrain#75]
Hello, how can I export the list from mailtrain please?

**Comment by andris9** [comment]
Right now there is no export function in Mailtrain. You need to export subscribers from MySQL database directly. All required fields can be found from table `subscription__{ID}` where `{ID}` is the numeric ID of the list. If you have found out the numeric ID, then you can query all subscribers from the database like this (assuming that list ID is 2):

    SELECT last_name, first_name, email FROM subscription__2 WHERE status=1 ORDER BY last_name, first_name, email

**Comment by luisacamara** [comment]
many thanks for your help.



Kind regards/ Saludos,


[image: Logo XML Travelgate] <http://www.xmltravelgate.com/>

Luisa Camara

Optimization Executive - XML Travelgate

Tel: + 34 871 968 181 | Ext: 104

lcamara@xmltravelgate.com | www.xmltravelgate.com

<https://www.facebook.com/XmlTravelgate>
<https://twitter.com/XMLTravelgate>
<http://www.linkedin.com/company/xml-travelgate>
<https://plus.google.com/+Xmltravelgate/posts>

**Comment by programster** [comment]
@andris9 this looks like a really useful feature to have (I could do with having it right now). Would you like me to have a whack at creating a pull request for it at some point or are you already working on it or deliberately don't want this feature in the app?

**Comment by andris9** [comment]
If you could work on a PR it would great. I don't know that anyone would be already working on this and I'm not very active currently with Mailtrain myself, mostly just review pull requests etc.

**Comment by programster** [comment]
@andris9 sounds good. It would probably come at the weekend depending when I get the time.

**Comment by bures** [comment]
@programster  See the new "Reports" functionality. It allows generating a "CSV" report, which can be used to export a list. There is a sample Report template for that purpose there.

Any feedback welcome. Thanks.

**Comment by programster** [comment]
Hey @bures I'm being really thick and can't find the reports functionality although I can clearly see there is a reports.js view and stuff. What would the url be like? e.g. if I go to my-site.org/reports I get a not found message. Perhaps it's hidden or an API request I need to make?

**Comment by programster** [comment]
Just realized that I misunderstood your message. Your pointing out how I should start on the feature, not telling me that you have gone and done it.  :)

**Comment by bures** [comment]
Sorry, it's quite new, so there is no howto to it yet. They have to be activated in the config. We keep it disabled by default because it allows executing custom Javascript code specified by the adminitrator through the UI. As long as you have your Mailtrain instance just for yourself or you share it with trusted people, it should be OK.

To enable the reports, add something like this to your config/production.toml file.

```
[reports]
enabled=true
```

And configure the user to access DB from the custom Javascript code. This can be found under reports workers/reports/config. You can either create a new mysql user that has only SELECT privileges on mailtrain.* or you can just use the existing mailtrain db user. 

```
[log]
level="error"
[mysql]
user="mailtrain"
password="XXXXXXX"
```

That should do the trick. If you would like to make it more secure, you can configure less privileged users to run the report generation. If you combine it with restricting access to "config" directory, this effectively prevents the custom javascript code in the report to modify any files on the disk. This is done by adding this at the beginning of the production.toml. Note that his requires running mailtrain as root (so that it can run things under a less privileged user and you have to have posix module installed. This should happen automatically during "npm install" if you have gcc-c++ package on your system.)

```
rouser="nobody"
rogroup="nobody"
```

Let me know if you need any more help.

**Comment by bures** [comment]
Actually, it is really implemented. See the screenshots here: https://github.com/Mailtrain-org/mailtrain/pull/207

**Comment by programster** [comment]
@bures awesome! looking into it now. So I had understood correctly the first time and incorrectly second-guessed myself :)

**Comment by githubber** [comment]
You can actually just copy the tables viewed on the page for a given list, and then paste those into an Excel sheet. Timing consuming if your list is huge, but not too bad for a small list.

**Comment by yeswetap** [comment]
Hello. I also need to export the contacts but I don't know my database name. How can I know it?

Thanks

**Comment by ganeshkrishnan1** [comment]
If anyone wants to export the lists and do not want to enable reports you can use the API to download the lists as JSON and then convert it to CSV.

What I did was:

`curl -XGET 'https://my_mail_train.com/api/subscriptions/<LISTINGID>?access_token=<ACCESS_TOKEN>&limit=1000&start=0'  |  jq '.data.subscriptions[]| [.email,.status, .firstName, .lastName] | @csv' > exported_data.csv`

You might have to install jq to convert JSON to csv with

`sudo apt install jq`

Change the number of fields in the jq parameter or number of results in limit

**Comment by rikmendes** [comment]
> If anyone wants to export the lists and do not want to enable reports you can use the API to download the lists as JSON and then convert it to CSV.
> 
> What I did was:
> 
> `curl -XGET 'https://my_mail_train.com/api/subscriptions/<LISTINGID>?access_token=<ACCESS_TOKEN>&limit=1000&start=0' | jq --raw-output '.data.subscriptions[]| [.email,.status, .firstName, .lastName] | @csv' > exported_data.csv`
> 
> You might have to install jq to convert JSON to csv with
> 
> `sudo apt install jq`
> 
> Change the number of fields in the jq parameter or number of results in limit

I get : Cannot index array with string "subscriptions" when I execute this curl command.
I have of course replaced the domain, api key and list filed with appropriate settings but I can't get this work.. @ganeshkrishnan1 any hint ?

**Comment by christiangenco** [comment]
@ganeshkrishnan1 Thank you! Your command worked perfectly for me.

If you're looking for your mailtrain `access_token`, you can find it by clicking `Admin => API`, or visiting `https://your_mailtrain_url.com/users/api`.

If you just need to export `name` and `email`, you can concatenate fields in `jq` by using parenthesis, like `(.firstName + " " + .lastName)`. 

If you'd like to filter out people on your list that have unsubscribed, you can use `jq`'s `select(.status == 1)`

All together, my command to export my subscribers from mailtrain looks like this:

```bash
curl -XGET 'https://mailtrain_url.com/api/subscriptions/LIST_ID?access_token=ACCESS_TOKEN&limit=1000&start=0' | \ 
jq --raw-output '.data.subscriptions[] | select(.status == 1) | [.email, (.firstName + " " + .lastName)] | @csv' \
> exported_data.csv
```

**Comment by forgeOneHQ** [comment]
Export is available in v2. Please upgrade to it.

**Comment by culakmar-bistudio** [comment]
> ]

Thank you for sharing this! It worked, unfortunately I overloaded our server with the request, but at least I learned something today :D

**Comment by katiesoklee** [comment]
I realize I'm jumping onto this old thread. I've inherited a bit of a cluster with our current Mailtrain setup. I'm looking to export our two mailing lists into .csv (via Reports) but have the subscriber's subscription status and custom fields we've created included in the .csv generated through Reports. For reference, I'm fairly certain we're on v1. Any advice is appreciated.
