### ISSUE TITLE
V2: Allow option to ignore null values on import

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#750]
It would be nice to have an option to only update fields that have data rather than remove data you already have in your list.

Example in List:
email, first_name, last_name
john@example.com, John, Smith

Example in import csv:
email, first_name, last_name
john@example.com, , Smith

In this case I would like to preserve John's first_name value in the list, but currently there is no way to do that, unless I completely ignore that column. It would be nice to have a check box or something at import time that would say `only update value if not null` or something like that.

**Comment by bures** [comment]
Makes sense. I just don't have time now to implement it.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
