### ISSUE TITLE
Triggers don't work in V2

### ISSUE THREAD

**Issue by heroic** [Mailtrain-org/mailtrain#752]
https://github.com/Mailtrain-org/mailtrain/blob/3a2d1512ab22472ba92c8adff2a09a918a4cbba0/server/services/triggers.js#L68

I think it's because this should be trigger.source_campaign instead of `campaign.id`. `campaign.id` if the triggered campaign the trigger belongs to, and has yet to sent.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
