### ISSUE TITLE
Triggers don't execute because of last_check time

### ISSUE THREAD

**Issue by heroic** [Mailtrain-org/mailtrain#755]
https://github.com/Mailtrain-org/mailtrain/blob/3a2d1512ab22472ba92c8adff2a09a918a4cbba0/server/services/triggers.js#L143-L145

If a trigger is to be executed in 4 days, this segment, updates the last check every 30 seconds, and thus, when the trigger should fire, it looks at campaign_messages that were created in the last 30 seconds, finds none, and trigger fails. This check should be removed, or:

https://github.com/Mailtrain-org/mailtrain/blob/3a2d1512ab22472ba92c8adff2a09a918a4cbba0/server/services/triggers.js#L170

this should be done, only if any subscribers were found to execute.

**Comment by bures** [comment]
Thanks. Will you please issue a PR? There is also some PR on triggers that I have not processed yet. Is it related?

**Comment by notz** [comment]
I think #741 fixes this problem. We have this working with several different trigger delays.

**Comment by Pistus** [comment]
This works for me after the #741 fix.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
