### ISSUE TITLE
What is the mysql version you people used for mailtrain-v2 ..?

### ISSUE THREAD

**Issue by saiprasadMolagavalli143** [Mailtrain-org/mailtrain#756]

**Comment by saiprasadMolagavalli143** [comment]
@bures  
I want to know the version of mysql for mailtrain-v2.  
I mean which mysql version you people used for mailtrain-v2..
It's very urgent ..

**Comment by GadisDEV** [comment]
hi, I'm using 
Server version: 5.5.64-MariaDB MariaDB Server

**Comment by saiprasadMolagavalli143** [comment]
@GadisDEV  I'm using mysql it will not support while using , is mandetory can i use mariadb or mysql also works  .. 

But i saw in code like they used mysql ..
i saw these lines in server config/default.yml file..
mysql:
  host: localhost
  user: mailtrain
  password: mailtrain
  database: mailtrain
  port: 3306
  charset: utf8mb4
  timezone: local

and if i run my server in my aws account it says like :+1: 
{"message":"ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client","error":{}}
if i created new user and and if i click on list i got above issue , 

So you have any solution for this issue ?? 
can you please let me know here. It's very urgent..

**Comment by GadisDEV** [comment]
https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/ says, mysql 5.5 and mariadb 5.5 should work as drop-in replacements. 

in the install functions however, the commands are for mariadb as I see it

**Comment by saiprasadMolagavalli143** [comment]
@GadisDEV 

So, I'm going to uninstall mysql and install mariadb, it should work right ??

And also , it's possible to connect for custom db using mysql connection or i need to connect mariadb connection.. 

I mean can i do this : 
const mariadb = require('mariadb');
const conn = mariadb.createConnection({
     host: 'mydb.com', 
     user:'myUser', 
     password: 'myPassword',
    database : 'databasename',
});
( or )
 var con = mysql.createConnection({
      host: "localhost",
      user: "mailtrain",
      password: "mailtrain",
      database: "mailtrain"
    });

can you please send the installation link for mariadb ..
