### ISSUE TITLE
V2: Add precedence header

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#757]
I need to be able to send the Precedence header as it is recommended by Gmail for best inboxing
https://winning.email/help/precedence-email-header

It would be nice if this was setup similar to From email. We can add it to the send configuration with an option to override at the campaign level.

**Comment by ericuldall** [comment]
Might be best to allow any custom headers from the UI

**Comment by bures** [comment]
I guess this should go to sender configuration. I think it's good to include the options for precedence header there. Are you gonna implement it and create a PR? Thanks.

**Comment by ericuldall** [comment]
This is lower on my wishlist. I'll definitely work on it when I have time.

**Comment by ericuldall** [comment]
Revisiting this and I'm thinking a bit more on how this could/should be implemented. I think at the send configuration level is not granular enough, because you can only have one send configuration per campaign yet there may be multiple headers required and these may change from one campaign to another, even if those share a send configuration.

 I'll use sendgrid as an example but other services have similar tagging mechanisms. 

https://sendgrid.com/docs/for-developers/sending-email/categories/
Sendgrid allows you to tag each email sent with an smtp header to add it to a category for statistical analysis. This is really helpful for instance if you have data being engaged from multiple sources and you want to track how each source performs.

For instance:
- Data from organic sign ups
- Data from an ad campaign (Google ads, etc...)
- Data from a partner offer

So ideally we could set API headers at the campaign level based on data from the list.

User | Tracking ID  |
|-----|-------------|
joe@test.com | site |
john@test.com | ad-123456 |
jane@test.com | partner-abcd |

Then when creating a campaign you could add a headers (as many as you want in theory):
Header Type | Header Key | Header Value
|-------------|-------------|--------------|
| Static            | X-SMPTAPI | { category: "test" }
| Dynamic.      | X-SMTPAPI | { category: "[MERGE_TRACKING_ID]" }

In the event of a static header it would be the same for all users in a campaign and dynamic would populate from the relevant list data at prep time. I don't believe this would add any significant overhead during send time as the list data is available for template population anyway.

Any thoughts on this @bures ?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
