### ISSUE TITLE
Fix error logging

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#760]
The error logging in the application isn't very helpful. We see very general errors like:
```
ERR! Senders Sending message to 1:1393 failed with error: Cannot read property 'id' of undefined.
```

It would be nice to see more info. Maybe the original message object sent to that function. The line of what file the error was thrown. As of now I basically have to search the code for an error that looks like that and then work backwards to find where it's being thrown.

**Comment by bures** [comment]
Fully agreed. Just enhance the error report here and submit a PR. Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
