### ISSUE TITLE
V2: Double sending

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#761]
I believe this application is double sending mail. I'm seeing database entries with 250 OK responses from the smtp server and status = 5.

**Comment by ericuldall** [comment]
I'm seeing tons of this in my logs:
```
ERR! Senders Sending message to 1:2698 failed with error: Cannot read property 'id' of undefined.
```

**Comment by ericuldall** [comment]
I beefed up my MySQL instance and it seems to be improving the double send issue. I'm still seeing the id errors, but not seeing any sent mail status 5 now. However, this is all indicative of some issue in the software. I'm going to triage this some more. I'll update any other findings here.

**Comment by ericuldall** [comment]
Here is the line throwing the id error:

> verb TypeError: Cannot read property 'id' of undefined at MessageSender._sendMessage (/app/server/lib/message-sender.js:321:59)
```
list = this.listsById.get(listId);
```

**Comment by bures** [comment]
Really strange. Is it happening deterministically? So that I can test it myself?

**Comment by ericuldall** [comment]
I'm still trying to find a root cause. What I can tell is the list is missing from the listsById Map.

**Comment by ericuldall** [comment]
I am having an issue with an email that is stuck on another campaign...and the list from the campaign that is stuck shows in the Map, but not the list from the campaign I'm looking at now.

**Comment by ericuldall** [comment]
I'm adding extra logging to see at what point the list is not being added and perhaps that will turn something up.

**Comment by bures** [comment]
Thanks. This part of Mailtrain is really complex. It's very likely there is some bug there.

**Comment by ericuldall** [comment]
So I forced the old campaign into status 3 (the one that had the broken message), then I restarted the instance. Now my big campaign has the correct listById data in the map for the current campaign and seems to be running normally.

We definitely need to dig deeper here, I don't understand what went wrong. It seems to be related to my previous campaign being stuck in sending status but it was not able to send that last message.

**Comment by ericuldall** [comment]
Perhaps a simple fix could be:
```
if (our list isn't in the map) {
  just grab it from mysql and add it anyway
}
```

**Comment by bures** [comment]
No problem to do it, but unless we understand what is happening, I'm reluctant to add fixes that address only the symptoms. This could also be just a tip of an iceberg of some much worse problem.

**Comment by ericuldall** [comment]
Yes, I agree. I'm going to keep digging on this for sure. I'm going to be gone tomorrow for one week, so probably have to dig more when I get back.

**Comment by bures** [comment]
Thanks.

**Comment by ericuldall** [comment]
Hey @bures ,

It seems the issue is being caused by the following error:
```
ERR! Senders Sending message to 1:2185 failed with error: Error: socket hang up.
```

I'm not sure why there is a socket hang up, but I saw that happening on the campaign that was failing before and now it's happening on this one and the campaign has stalled.

Any thoughts here? I'm currently using the SendGrid SMTP API (not sure if that's releveant) and they shouldn't have any issue with the current load.

**Comment by ericuldall** [comment]
More detailed error:
```
verb RequestError: Error: socket hang up at new RequestError (/app/server/node_modules/request-promise-core/lib/errors.js:14:15) at Request.plumbing.callback (/app/server/node_modules/request-promise-core/lib/plumbing.js:87:29) at Request.RP$callback [as _callback] (/app/server/node_modules/request-promise-core/lib/plumbing.js:46:31) at self.callback (/app/server/node_modules/request/request.js:185:22) at Request.emit (events.js:198:13) at Request.EventEmitter.emit (domain.js:448:20) at Request.onRequestError (/app/server/node_modules/request/request.js:881:8) at ClientRequest.emit (events.js:198:13) at ClientRequest.EventEmitter.emit (domain.js:448:20) at Socket.socketOnEnd (_http_client.js:426:9) at Socket.emit (events.js:203:15) at Socket.EventEmitter.emit (domain.js:448:20) at endReadableNT (_stream_readable.js:1143:12) at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ericuldall** [comment]
It seems whatever the socket hang up is, it's a fatal error that the application is not able to recover from. Perhaps it would be best for now to let that bubble all the way to the top and crash the process. In my case that's ideal as kubernetes will immediately spawn a new pod and continue working, but I assume for many users on monolithic infrastructure this wouldn't be ideal....but perhaps better than an application stuck in an irreconcilable state.

**Comment by ericuldall** [comment]
More findings:

When the socket hangup happens it leaves the message record in a weird state...
status = 1 but it has not response message, so it seems this error is happening before the send. 

This campaign is using a source url... I'm wondering if that request is timing out and not being handled properly. I believe for the source url we should set a reasonable (or configurable) timeout and make sure the message tries again. OR, perhaps we can allow the content generating service to decide what the campaign should do.

```
if (status between 200 and 400) {
    use the returned content
}
if (status between 400 and 500) {
   we can't return content based on your request and never will, stop trying to send that message
}

if (status >= 500) {
   something went wrong generating the content and you should try again
}
```

**Comment by bures** [comment]
That could be connected to the source URL. I think I never properly tested with the reworked sending architecture.

**Comment by ericuldall** [comment]
I'm running some more tests on that feature. It's possible my endpoint doesn't like some of the data it's receiving and it's never closing the connection.

**Comment by bures** [comment]
Good catch.

**Comment by ericuldall** [comment]
So now I'm handling the bad events on my content api and making it return a 500 and that is solving the socket hang up issue. 

@bures Do you know how long it should retry or if there is some way currently to just give up on message that return bad content from the url?

**Comment by ericuldall** [comment]
I believe this was also happening as a result of https://github.com/Mailtrain-org/mailtrain/issues/769

All campaign numbers seem good now.
