### ISSUE TITLE
V2: Getting difficult to properly install from scratch.

### ISSUE THREAD

**Issue by dgulias** [Mailtrain-org/mailtrain#762]
Hello everybody,

I deleted the V1 version and I'm trying to install V2 from scratch.

Different from V1, i'm getting a the error Nginx 502 Bad Gateway, but before that i'm getting a more relevant error when I try to put the "mailtrain.service" to work.

I didnt´find "mailtrain.service" file in the v2 repository, so i had to take it from the v1 installation to make a copy.

The file content is:

```
[Unit]
Description=Mailtrain server
Requires=mysql.service
After=syslog.target network.target

[Service]
Environment="NODE_ENV=production"
WorkingDirectory=/opt/mailtrain
ExecStart=/usr/bin/node index.js
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
#Alias=mailtrain.service
```

And so, when i try to see this service status I get the following error:

```
root@host:/opt/mailtrain# systemctl status mailtrain.service
● mailtrain.service - Mailtrain server
   Loaded: loaded (/etc/systemd/system/mailtrain.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2019-10-31 23:07:26 WET; 1s
  Process: 30657 ExecStart=/usr/bin/node index.js (code=exited, status=1/FAILURE)
 Main PID: 30657 (code=exited, status=1/FAILURE)

Oct 31 23:07:26 host systemd[1]: mailtrain.service: Main process exited, code=exited, status
Oct 31 23:07:26 host systemd[1]: mailtrain.service: Failed with result 'exit-code'.
```
 
Help me, please.

**Comment by bures** [comment]
There is a setup script for centos and ubuntu. Just use it.

**Comment by bures** [comment]
Alternatively, use the docker compose.

**Comment by dgulias** [comment]
Thank you for the answer and sorry for the noob question. 

I did this installation: "Installation on fresh CentOS 7 or Ubuntu 18.04 LTS (public website secured by SSL)"

The rest i did a miscellaneous with this article: https://computingforgeeks.com/how-to-install-mailtrain-newsletter-application-on-ubuntu-18-04-lts/ (that is for v1)

I got V1 to work properly, but I'm having problem to understand where is the v2 "mailtrain.service file" when i install it according to the insctructions I said above.

**Comment by dgulias** [comment]
I'm using Ubuntu 18.04 LTS - with Nginx and Haraka.

I didnt try to learn how to use docker because, acording to this article: https://www.linuxbabe.com/ubuntu/install-mailtrain-ubuntu-18-04 - without docker the server save some cpu usage/ram memory. And my VM server is not so powerfull right now.

**Comment by dgulias** [comment]
I'm traying a lot of configs and still get this error:
'''
mailtrain.service - Mailtrain server
   Loaded: loaded (/etc/systemd/system/mailtrain.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-11-05 01:48:50 WET; 4s ag
  Process: 1066 ExecStart=/usr/bin/node index.js (code=exited, status=1/FAILURE)
 Main PID: 1066 (code=exited, status=1/FAILURE)
'''

Help please

**Comment by talheim-it** [comment]
@dgulias what is journalctl -xe showing up?

The error message is not helping really much.

**Comment by dgulias** [comment]
> 
> 
> @dgulias what is journalctl -xe showing up?
> 
> The error message is not helping really much.

Thank you for the reply.

Follow bellow the result:

´´´
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Support: http://www.ubuntu.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is RESULT.
Nov 08 17:56:56 MYHOSTNAME systemd[1798]: Reached target Default.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is RESULT.
Nov 08 17:56:56 MYHOSTNAME systemd[1798]: Startup finished in 57ms.
-- Subject: User manager start-up is now complete
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The user manager instance for user 1000 has been started. All services queued
-- for starting have been started. Note that other services might still be start
-- up or be started at any later time.
--
-- Startup of the manager took 57294 microseconds.
lines 5045-5067/5067 (END)
-- Support: http://www.ubuntu.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is RESULT.
Nov 08 17:56:56 MYHOSTNAME systemd[1798]: Reached target Default.
-- Subject: Unit UNIT has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit UNIT has finished starting up.
--
-- The start-up result is RESULT.
Nov 08 17:56:56 MYHOSTNAME systemd[1798]: Startup finished in 57ms.
-- Subject: User manager start-up is now complete
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The user manager instance for user 1000 has been started. All services queued
-- for starting have been started. Note that other services might still be starting
-- up or be started at any later time.
--
-- Startup of the manager took 57294 microseconds.

´´´

**Comment by joker-x** [comment]
If you had clone the repository in /opt/mailtrain the WorkingDirectory would be /opt/mailtrain**/server**:

```
[Unit]
Description=Servidor Mailtrain
After=syslog.target network.target mariadb.service redis-server.service mongod.service

[Service]
User=mailtrain
Environment="NODE_ENV=production"
WorkingDirectory=/opt/mailtrain/server
ExecStart=/usr/bin/node index.js
Type=simple
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Don't forget install all modules wit ``ǹpm install`` in server, client, shared, etc subdirectories before start the service.

**Comment by dgulias** [comment]
> 
> 
> If you had clone the repository in /opt/mailtrain the WorkingDirectory would be /opt/mailtrain**/server**:
> 
> ```
> [Unit]
> Description=Servidor Mailtrain
> After=syslog.target network.target mariadb.service redis-server.service mongod.service
> 
> [Service]
> User=mailtrain
> Environment="NODE_ENV=production"
> WorkingDirectory=/opt/mailtrain/server
> ExecStart=/usr/bin/node index.js
> Type=simple
> Restart=always
> RestartSec=10
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Don't forget install all modules wit `ǹpm install` in server, client, shared, etc subdirectories before start the service.

Thank you for the answer. 

I didn't try your tip because at the end I deleted everything and installed from scratch on a CentOS 7. Everything is working fine.

But thank you for the reply, certainly will help someone.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
