### ISSUE TITLE
Installation problems on Plesk

### ISSUE THREAD

**Issue by synflex68** [Mailtrain-org/mailtrain#764]
Hi, I state that I am not a developer, and I have only partial knowledge of node.js and the programming languages that go around it. Having said that, I tried to install Mailtrain on Plesk, but I get the following errors:

npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated bcrypt-nodejs@0.0.3: bcrypt-nodejs is no longer actively maintained. Please use bcrypt or bcryptjs. See https://github.com/kelektiv/node.bcrypt.js/wiki/bcrypt-vs-brypt.js to learn more about these two options
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated graceful-fs@1.1.14: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > core-js@2.6.9 postinstall /var/www/vhosts/mydomain.com/.npm/_cacache/tmp/git-clone-de5a7927/node_modules/core-js
npm ERR! prepareGitDep > node scripts/postinstall || echo "ignore"
npm ERR! prepareGitDep
npm ERR! prepareGitDep ignore
npm ERR! prepareGitDep
npm ERR! prepareGitDep > elliptic@6.5.1 prepare /var/www/vhosts/mydomain.com/.npm/_cacache/tmp/git-clone-de5a7927
npm ERR! prepareGitDep > grunt dist
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN lifecycle npm is using /opt/plesk/node/10/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
npm ERR! prepareGitDep sh: node: command not found
npm ERR! prepareGitDep /usr/bin/env: node: No such file or directory
npm ERR! prepareGitDep npm ERR! file sh
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno ENOENT
npm ERR! prepareGitDep npm ERR! syscall spawn
npm ERR! prepareGitDep npm ERR! elliptic@6.5.1 prepare: `grunt dist`
npm ERR! prepareGitDep npm ERR! spawn ENOENT
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the elliptic@6.5.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR! /var/www/vhosts/mydomain.com/.npm/_logs/2019-11-02T00_17_01_012Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close
npm ERR! A complete log of this run can be found in:
npm ERR! /var/www/vhosts/mydomain.com/.npm/_logs/2019-11-02T00_17_03_711Z-debug.log

The server setup is as follows:

Plesk: Obsidian v18.0.20_build1800191029.11,
O.S.: CentOS 6.10 (Final)
Node.js: 10.16.0
Php: 5.6.402
Mysql: 5.7.28-1.el6

Any idea how to solve it?
Thanks in advance

**Comment by paulmartimx** [comment]
@synflex68 I had the same problem and solved it like this:

1. Connect with SSH and navigate to your Application Root
2. Run the command...

/opt/plesk/node/8/bin/npm config set scripts-prepend-node-path auto

Here I'm using version 8 of npm... but yours could be 10 or 12... so replace that if that's your case.

3. Install normally:
/opt/plesk/node/8/bin/npm install --production

Ready!
