### ISSUE TITLE
mailtrain2 login with admin

### ISSUE THREAD

**Issue by pokernet** [Mailtrain-org/mailtrain#767]
new install from git
on centos7

web gui login 
admin:test
not let me login ,allways return me back to login screen ?

**Comment by martialblog** [comment]
You got any errors in the backend? Or maybe Browser plugins active (blocking JS e.g.)?

**Comment by martialblog** [comment]
Random guess: Did you try accessing it by IP and not localhost?

**Comment by forgeOneHQ** [comment]
@pokernet I close the ticket. If you still run into the issue you can for example run journalctl -u mailtrain.service (-f) to check live any issues.
