### ISSUE TITLE
V2: zone-mta invalid HELO 

### ISSUE THREAD

**Issue by futrix** [Mailtrain-org/mailtrain#768]
Hi, I am using built in Zone MTA configuration. When sending mail it sets HELO to hostname (or just mailtrain word), not a FQDN as it should. Is there a way to fix this?

https://www.mail-tester.com/ gives me -3pts for that it cannot get A record for just 'mailtrain'.

I've tried setting default pool in config files inside /opt/mailtrain/zone-mta/config - it did not help.

**Comment by forgeOneHQ** [comment]
@futrix since I am not seeing if v1 or v2 please try again with the latest v2 version and if you still have the same issue, you are welcome to open a new one.
