### ISSUE TITLE
V2 : "default value" of fields is ignored

### ISSUE THREAD

**Issue by TheoDel** [Mailtrain-org/mailtrain#770]
Hello,
When editing a Field of a List, I tried to use the "Default Value" input, because I would like to add some pre-checked checkboxes in my subscription form.
However, it doesn't apply in the subscription form, and it doesn't seem to work with the other types of Fields (such as "text") either

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
