### ISSUE TITLE
V2: Redis-Server password protection not working

### ISSUE THREAD

**Issue by talheim-it** [Mailtrain-org/mailtrain#774]
Since v2, the option password="" for redis is not working anymore.

To write password:"<Pass>" is not recognized correctly.

Needs to be fixed to work in the production.yaml.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
