### ISSUE TITLE
/api/lists/:email endpoint should return cid instead of id

### ISSUE THREAD

**Issue by Pistus** [Mailtrain-org/mailtrain#778]
All api calls are based on a lists `cid` and not the `id`. However the /api/lists/:email endpoint which returns a list of the email lists an email is on returns the id value. This makes it impossible to use the list to for example verify that an email is on a list before updating the subscription.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
