### ISSUE TITLE
Separate subscriber api endpoints for create and update 

### ISSUE THREAD

**Issue by Pistus** [Mailtrain-org/mailtrain#779]
The `POST /api/subscribe/:listId` endpoint does an upsert (update or insert). This should be separated to allow for scenarios of only inserting new entries and only updating. I am facing an scenario where I only want to update existing users and never add users that do not already exist. 

**Workaround:**
This could be handled by checking the lists of the email, but this would require two steps to what feels like should be possible with one and the `/api/lists/:email` endpoint does not return the needed data at the moment - ref #778 .

**Suggested fix**
Looks like the api is trying to keep to GET / POST verbs instead of using the verbs PUT for update, DELETE for delete, etc. If that is a requirement I would suggest to make an update endpoint that fails for non-existing subscribers.

- [ ] Add api endpoint `/api/update/listId/` that update existing subscriber and fail with a 404 if the email passed as argument does not exist.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
