### ISSUE TITLE
ERR! Mail Error: Mail command failed: 442 Invalid status code 404

### ISSUE THREAD

**Issue by ghost** [Mailtrain-org/mailtrain#782]
Hi. I am unable to send emails. This is the error in the syslog: 

> Nov 14 17:28:46 test zone-mta[21023]: (SMTP/feeder/21023) Connection from [127.0.0.1]:47498
> Nov 14 17:28:46 test zone-mta[21023]: (SMTP/feeder/21023) Authenticated "mailtrain" from [127.0.0.1][127.0.0.1] using PLAIN
**> Nov 14 17:28:46 test zone-mta[21023]: (Plugins) "HTTP Sender Config" for "smtp:mail_from" failed with: Invalid status code 404
> Nov 14 17:28:46 test node[20825]: ERR! Mail Error: Mail command failed: 442 Invalid status code 404**
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at SMTPConnection._formatError (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at SMTPConnection._actionMAIL (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:1370:34)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at SMTPConnection._responseActions.push.str (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:857:18)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at SMTPConnection._processResponse (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at SMTPConnection._onData (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at TLSSocket._socket.on.chunk (/opt/mailtrain/node_modules/nodemailer/lib/smtp-connection/index.js:710:55)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at TLSSocket.emit (events.js:198:13)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at TLSSocket.EventEmitter.emit (domain.js:448:20)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at addChunk (_stream_readable.js:287:12)
> Nov 14 17:28:46 test node[20825]: ERR! Mail     at readableAddChunk (_stream_readable.js:268:11)
>

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
