### ISSUE TITLE
How we can send the campaigns templates to subscribers..

### ISSUE THREAD

**Issue by Saiprasad2021** [Mailtrain-org/mailtrain#784]

**Comment by saiprasadMolagavalli143** [comment]
I want to know once we click on send subscribers  
like given below screenshot
![Screenshot from 2019-11-26 17-12-13](https://user-images.githubusercontent.com/53864113/69627064-f2414700-106f-11ea-82ab-610a967a831f.png)
how it will going to send the mails with campaign templates to subscribers.. 

can you please give me the hint what is the flow once we click on send subscribers button

which api call is going to be call and how it will send the template to subscirbers.. 
It's calling /campaign-start/campaignId api but here i din't get anyting how it gonna send the campaign to subscribers..

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
