### ISSUE TITLE
V2: Allow segmentation by Subscription Status

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#785]
Currently there's no way to filter segments by the users subscription status (subscribed, unsubscribed,..). I know that unsubscribed users will not get mailed, however, when trying to estimate how many users will be mailed I'm filtering by that segment in the list, but the count includes all of the unsubscribed users, so it's unclear how many users will get mailed until I start a campaign.

Would this be pretty simple to add?

**Comment by bures** [comment]
I think it would be relatively easy to add. I guess it makes sense as a way to filter users when displaying them.
