### ISSUE TITLE
New Docker Instance - mailtrain_1 not starting

### ISSUE THREAD

**Issue by rlburkey** [Mailtrain-org/mailtrain#786]
Good Morning!

I spun up a new instance of Mailtrain in docker and wasn't able to access the login page.  After some brief investigation,  it looks like it creates the mailtrain_1 container, but doesn't start it.  Any help is appreciated.

**Running docker-compose up -d**
Creating network "mailtrain_default" with the default driver
Creating mailtrain_redis_1     ... done                                                                                                          Creating mailtrain_mysql_1     ... done                                                                                                          Creating mailtrain_mongo_1     ... done                                                                                                          Creating mailtrain_mailtrain_1 ... done 

**Running docker ps**
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
523c2a13ea3e        mongo:4-xenial      "docker-entrypoint.s…"   About a minute ago   Up About a minute   27017/tcp           mailtrain_mongo_1
f6131c702538        mariadb:10.4        "docker-entrypoint.s…"   About a minute ago   Up About a minute   3306/tcp            mailtrain_mysql_1
b412fd375ab7        redis:5             "docker-entrypoint.s…"   About a minute ago   Up About a minute   6379/tcp            mailtrain_redis_1

**Comment by bures** [comment]
Is it v1 or v2? How long did you wait? As far as I remember, the first run takes surprisingly long.

**Comment by rlburkey** [comment]
Its running V2.  I launched it days ago, and the container for the core app
(ports 3000,3003,3004) never starts, the mariadb, redis, and mongo
containers are all running (or so says docker ps).

**Comment by forgeOneHQ** [comment]
@rlburkey can you please try it again with the latest version of v2 and reopen the issue when it still exists.
