### ISSUE TITLE
ExecStart=/usr/bin/node index.js (code=exited, status=200/CHDIR)

### ISSUE THREAD

**Issue by kyouran38** [Mailtrain-org/mailtrain#787]
Hi i am trying to install mailtrain on my server but i have this message when i try to start it :

sudo systemctl status mailtrain.service
● mailtrain.service - Mailtrain server
   Loaded: loaded (/etc/systemd/system/mailtrain.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-12-01 16:06:27 CET; 9s ago
  Process: 15142 ExecStart=/usr/bin/node index.js (code=exited, status=200/CHDIR)
 Main PID: 15142 (code=exited, status=200/CHDIR)

systemd[1]: mailtrain.service: Main process exited, code=exited, status=200/CHDIR
systemd[1]: mailtrain.service: Failed with result 'exit-code'.
systemd[1]: mailtrain.service: Service hold-off time over, scheduling restart.
systemd[1]: mailtrain.service: Scheduled restart job, restart counter is at 49.
systemd[1]: Stopped Mailtrain server.
systemd[1]: Started Mailtrain server.
systemd[15800]: mailtrain.service: Changing to the requested working directory failed: No such file or directory
systemd[15800]: mailtrain.service: Failed at step CHDIR spawning /usr/bin/node: No such file or directory
systemd[1]: mailtrain.service: Main process exited, code=exited, status=200/CHDIR
systemd[1]: mailtrain.service: Failed with result 'exit-code'.

Is anyone can help me ?

Thanks a lot

Regards

**Comment by bures** [comment]
Is it v1 or v2?

**Comment by forgeOneHQ** [comment]
@kyouran38 please install the latest version of mailtrain v2 and let us know if you still struggle with the situation.

**Comment by ghost** [comment]
The way this was closed out makes it tough for those of us that have the same problem and found this through a search.  I understand this is a two year old issue that needed to be closed.
