### ISSUE TITLE
TimeoutOverflowWarning: 2338257931 does not fit into a 32-bit signed integer.

### ISSUE THREAD

**Issue by belqit** [Mailtrain-org/mailtrain#788]
![image](https://user-images.githubusercontent.com/44238749/69955520-bdad0f80-14f5-11ea-9100-8c0bbec65669.png)
I can't get rid of these errors... they appears more than once per second

**Comment by martialblog** [comment]
Can you give us some details on the system you're using?

**Comment by belqit** [comment]
Ubuntu 16.04.6
v10.17.0

**Comment by bures** [comment]
I don't think we tested it on Ubunt 16.04. As far as I remember, in addition to Docker, we support only Centos 7 and Ubuntu 18.04.

**Comment by belqit** [comment]
Ok thanks for the advice
