### ISSUE TITLE
V2: endless send error loop

### ISSUE THREAD

**Issue by alangecker** [Mailtrain-org/mailtrain#790]
on my instance mailtrain tries forever to send a mail to a non-existing mailbox:

#### Log (endless loop, mutliple times per second)
```
info Mail Created new pool resource #2
info Mail Secure connection established to ******:465
info Mail User "kontakt@*****.de" authenticated
info Mail Sending message <84fb40fe-7e0c-5cd6-0826-d7391c1d431e@bounces.******.org> using #2 to <no-existing@*****.de>
info Mail Connection #2 was closed
ERR! Mail Pool Error for #2: Can't send mail - all recipients were rejected: 550 5.1.1 <no-existing@example.com>: Recipient address rejected: User unknown in virtual mailbox table
ERR! Mail Send Error: Can't send mail - all recipients were rejected: 550 5.1.1 <no-existing@example.com>: Recipient address rejected: User unknown in virtual mailbox table
ERR! Senders Sending message to 1:8 failed with error: Can't send mail - all recipients were rejected: 550 5.1.1 <no-existing@example.com>: Recipient address rejected: User unknown in virtual mailbox table.
info Mail Created new pool resource #2
info Mail Secure connection established to ******:465
info Mail User "kontakt@*****.de" authenticated
info Mail Sending message <debed2f5-3008-c475-7ef5-12a749e736b4@bounces.******.org> using #2 to <no-existing@example.com>
info Mail Connection #2 was closed
ERR! Mail Pool Error for #2: Can't send mail - all recipients were rejected: 550 5.1.1 <no-existing@*****.de>: Recipient address rejected: User unknown in virtual mailbox table
ERR! Mail Send Error: Can't send mail - all recipients were rejected: 550 5.1.1 <no-existing@example.com>: Recipient address rejected: User unknown in virtual mailbox table
ERR! Senders Sending message to 1:8 failed with error: Can't send mail - all recipients were rejected: 550 5.1.1 <no-existing@example.com>: Recipient address rejected: User unknown in virtual mailbox table.
```

#### relevant code
https://github.com/Mailtrain-org/mailtrain/blob/development/server/services/sender-worker.js#L16
```js

async function processCampaignMessages(campaignId, messages) {
    [...]

    for (const campaignMessage of messages) {
        try {
            await cs.sendRegularCampaignMessage(campaignMessage);

            await activityLog.logCampaignTrackerActivity(CampaignTrackerActivityType.SENT, campaignId, campaignMessage.list, campaignMessage.subscription);

            log.verbose('Senders', 'Message sent and status updated for %s:%s', campaignMessage.list, campaignMessage.subscription);
        } catch (err) {

            if (err instanceof mailers.SendConfigurationError) {
                log.error('Senders', `Sending message to ${campaignMessage.list}:${campaignMessage.subscription} failed with error: ${err.message}. Will retry the message if within retention interval.`);
                withErrors = true;
                break;

            } else {
                log.error('Senders', `Sending message to ${campaignMessage.list}:${campaignMessage.subscription} failed with error: ${err.message}.`);
                log.verbose(err.stack);
            }
        }
    }
    [...]
    sendToMaster('messages-processed', { withErrors });
}

```

### analysis
seems like the information, that the mailbox is not available, is just displayed, but ignored beyond that.

I can imagine working on that, but i don't quite understand, how a proper solution could look like. any ideas?

**Comment by bures** [comment]
I'm afraid this is hard for me to reproduce without knowing the exact details of the setup including the target email address that fails.

**Comment by acgourley** [comment]
I have a similar issue, in my case I have emails with invalid characters which SES rejects, and that rejection causes a retry to be queued on mailtrain. This loops forever and prevents the sending of other emails. Is there no mechanism to stop trying to send a message if it has failed a certain number of times?

**Comment by acgourley** [comment]
I dug into my error a bit more. 

1. This isn't stopping any campaigns, it seems the behavior is to continue on with the campaign and come back to these failed sends later, so that effectively the campaign does finish but then it spends a bunch of time at the end trying to resend to these last failed emails. And if the error is of the type where retrying may succeed, this is exactly the behavior we want. 

2. There is code in place to not waste time on errors which cannot be recovered from. See https://github.com/Mailtrain-org/mailtrain/blob/7209e97175dee5043ad08acbcce38e43ee9cf8cc/server/lib/message-sender.js#L456

If we change that from `if (err.responseCode >= 500)` to `if (err.responseCode >= 500 || !err.retryable)` it will be more likely to not retry certain classes of errors. For my, my err from amazon SES looked like this: 

```
{"cause":{"message":"Local address contains control or whitespace","code":"InvalidParameterValue","time":"2020-12-20T19:17:48.736Z","requestId":
"0ad1a60a-1248-4d8a-8e1e-ee1763e8bc59","statusCode":400,"retryable":false,"retryDelay":95.70589303604318},"isOperational":true,"code":"InvalidParameterValue","time":"2020-12-20T19:17:48.736Z","requestId":"0ad1a60a-1248-4d8a-8e1e-
ee1763e8bc59","statusCode":400,"retryable":false,"retryDelay":95.70589303604318}
```

So this check is working well for me right now. My question for the primary contributors is if this check makes sense or if it might inadvertently catch errors we do want to retry on.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
