### ISSUE TITLE
Unable to configure behind Apache without root path

### ISSUE THREAD

**Issue by paspiz85** [Mailtrain-org/mailtrain#791]
I need to configure Mailtrain behind Apache Reverse Proxy but without use root path. If configure with a different path, it doesn't work.

My Apache configuration will be something like this:
`
<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass        "/mailtrain/" "http://127.0.0.1:3000/"
    ProxyPassReverse "/mailtrain/" "http://127.0.0.1:3000/"
    ServerName mailtrain.org
    ServerAlias www.mailtrain.org
</VirtualHost>
`

**Comment by bures** [comment]
Have you set the url bases correctly in Mailtrain configuration? However, I should say we never tested running it under a specific path.

**Comment by forgeOneHQ** [comment]
@paspiz85 that is the wrong way to configure. If you need help with it you are welcome to reopen a new issue if you still need help. I would use nginx instead, I also can provide the configuration for this. I plan to create an ansible-playbook for  this.
