### ISSUE TITLE
V2 - request 4 feature - obligatory field in subscription 

### ISSUE THREAD

**Issue by pangea-org** [Mailtrain-org/mailtrain#793]
Hello,
we pass you a request for feature: 
in **subscription forms** certain users want to be able to mark some **fields** as **obligatory** and so if a new subscribers doesn't mark any option, there would be an error message and the subscription request would not be submitted. 

I add a proposal to give some idea.

The error message shall be translatable by users from Custom Forms menu, just as any other error.

_Rationale / use case:_
Providing  Mailtrain v2 to our users we can facilitate mailtrain translation to official languages. Nevertheless, users shall be able to create their forms in any other language they use, easily.

![subscription](https://user-images.githubusercontent.com/58551859/70235488-57c5bf80-1763-11ea-8e58-fd41ee4ea487.png)

**Comment by GadisDEV** [comment]
this is like #312 

possible to check with javascript in the custom forms of the list:

in this case I added a MERGE_PRIVACY_GDPR custom field, wich should be required to register.

I added this code to the custom form 'layout' template

```
<mj-raw>
    {{#if isWeb}}
        <script type="text/javascript">
            // Needed for IE only, but all browsers accept it
            var forEach = function (array, callback, scope) {
                for (var i = 0; i < array.length; i++) {
                    callback.call(scope, i, array[i]);
                }
            };

            var mainForm = document.querySelector('form');

            // Override each input field with the required tag, that is needed
            mainForm.querySelector('input[name=MERGE_FIRST_NAME]').required = false;
            mainForm.querySelector('input[name=MERGE_LAST_NAME]').required = false;
            mainForm.querySelector('input[name=MERGE_PRIVACY_GDPR]').required = true;

            forEach(document.querySelectorAll('a[href="#submit"]'), function(i, a) {
                a.onclick = function() {
                    var form = document.getElementById('main-form');
                    if(!form.checkValidity()) {
                        // IE does not support the reportValidity method, all other browsers do
                        if(form.reportValidity != undefined) {
                            form.reportValidity();
                        } else {
                            alert('Please fill out all necessary fields.');
                        }
                    } else {
                        form.submit();
                    }
                    return false;
                };
            });
        </script>
    {{/if}}
</mj-raw>
```

**Comment by GadisDEV** [comment]
the nice thing is that the validation is done in the browser language, which means it will be already translated..

**Comment by elitzer2** [comment]
@bures I am looking to implement this and I have a required checkbox added to the custom fields in the DB. I am curious why the `<button type="submit">` in the template [here](https://github.com/Mailtrain-org/mailtrain/blob/development/server/views/subscription/partials/subscription-subscribe-form.hbs#L17) is not used but rather an `<a>` tag is added with `href=#submit`? HTML5 can do form validation for free when using that button. Was it purposeful to avoid front-end validations?

**Comment by bures** [comment]
No. I just adopted it from v1, which dates back to time when the HTML5 and validation were not much supported I guess. Just update it to the state of the art. Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
