### ISSUE TITLE
[BUG] V2: Sending email to test user fails.

### ISSUE THREAD

**Issue by rjrodriguezalvarez97** [Mailtrain-org/mailtrain#794]
Hey there!
Trying to send a campaign to a single test user from a list failed with the following error:
![alt](https://i.imgur.com/2YJqYqv.png). As we can see the query is missing the table where the values are going to be inserted. I tried to reproduce this on local but I couldn't. The most I could do was tracing it down to this [line](https://github.com/Mailtrain-org/mailtrain/blob/ed2655b78e9be22e79f1b935a1011390de49a440/server/lib/message-sender.js#L571).
I'm not sure but I think the table is missing there

**Comment by bures** [comment]
Thank you. I'm afraid that as long as we don't have a scenario where the error is reliably reproduced, there is little one can do.

**Comment by heruscoder** [comment]
I had a similar problems. Resolved upgrading MySQL 5.7 to 8.0

**Comment by rjrodriguezalvarez97** [comment]
Thanks for your reply.
Talking from my ignorance in the line that I pointed out `knex` is expecting a table name isn't it? Maybe that's why the table is missing in the error.

**Comment by forgeOneHQ** [comment]
@rjrodriguezalvarez97 I am not seeing the issue to sent test mails to test users in the latest v2 version. if this happens again you are welcome to open a new ticket for investigation.
