### ISSUE TITLE
V2 - Sending message to 1:1 failed with error: Missing region in config.

### ISSUE THREAD

**Issue by heruscode** [Mailtrain-org/mailtrain#798]
Trying to send a campaign using Amazon SES fails with log error:

**ERR! Senders Sending message to 1:1 failed with error: Missing region in config.**

Steps to reproduce:
1. Create new send configuration with Amazon SES, without changing the region ( default US-EAST-1)
2. Try to send a campaign

Steps to fix:
1. Edit the send configuration changing the region to another one (US-WEAST-2 for example)
2. Try to send a campaign and see new errors popping in logs
3. Edit the send configuration back to US-EAST-1
4. Sending campaigns now works

**Comment by forgeOneHQ** [comment]
@heruscode please try again with the latest version of mailtrain v2 and if you still have the same issue please provide all informations:
1.) How did you deploy mailtrain
2.) Your configuration
3.) Provide all log files for investigation via journactl -u mailtrain (-f)
