### ISSUE TITLE
What is the redis role for mailtrain?

### ISSUE THREAD

**Issue by heruscode** [Mailtrain-org/mailtrain#799]
Hello,

I am deploying mailtrain in kubernetes and for high-availability reasons i want to deploy more than 2 replicas. I am using Amazon SES.

Does redis is used for mail send queue? 
Can i scale-up and scale-down mailtrain containers without racing-conditions on senders jobs? ( by having the send queue in redis )

**Comment by bures** [comment]
No. I'm afraid horizontal scaling or HA is not supported.

**Comment by heruscoder** [comment]
Is redis used only for caching?
The send queue is created on mailtrain memory?

**Comment by bures** [comment]
Redid is used to keep client authorization tokens. The send queue is in DB, but cached in Mailtrain memory.

**Comment by heruscoder** [comment]
Ok, i understand. 

I still want to run mailtrain on kubernetes though, all our new apps right now are running as containers. Even if its only 1 replica.

What would happen if in the middle of a campaign send, the container dies. When he spawns in another machine, does the send queue starts running again from the moment it broke? Or we need to start sending the campaign again manually?

**Comment by bures** [comment]
It should normally recover. All State is persisted in the DB. In the very worst case it will drop an email message if the shutdown happens immediately after it logs sending and just befo the message is handed over to MTA. No message shall be delivered twice.

**Comment by heruscoder** [comment]
Nice, thanks

**Comment by kedarnok** [comment]
Could you share your deployment.yaml for kubernetes?

**Comment by heruscoder** [comment]
> Could you share your deployment.yaml for kubernetes?

https://github.com/noknox/mailtrain/tree/feat/kubernetes/helm

**Comment by kedarnok** [comment]
> https://github.com/noknox/mailtrain/tree/feat/kubernetes/helm
Thank you. I did't see this link before :) I was working on stable version not beta till now.
Switching to beta, thanks.

**Comment by linelect** [comment]
I would like to run two instances of Mailtrain v1 on the same server for different users. DB will be different, Mailtrain apps will use different ports.

@bures Can I use somehow one instance of Redis for both Mailtrain apps without any issue or I should run different instances of Redis for every Mailtrain app?
