### ISSUE TITLE
Uninstall Mailtrain

### ISSUE THREAD

**Issue by felipebatista** [Mailtrain-org/mailtrain#800]
hello everybody,

I have just installed Mailtrain (branch `development`) on my local Ubuntu machine with the following script

```
bash setup/install-ubuntu1804-local.sh
```

how do I totally remove it?

thanks

**Comment by talheim-it** [comment]
@felipebatista just remove the folders and uninstall all packages which are not needed anymore.
Like mongodb, redis-server, etc.

**Comment by felipebatista** [comment]
hello @talheim-it 

my problem is exactly with these _etc_ packages. it would be nice to have an exhaustive list of packages that I should remove

**Comment by talheim-it** [comment]
@felipebatista 

If you want to remove it:

- NPM
- MongoDB
- MariaDB
- Redis-Server
- Apache/Nginx (Depends on if you use the Install http Script)
- Letsencrypt

The services have files in /usr/share, /etc, /var/lib, /usr/lib, /usr/lib64

And then just the cloned mailtrain folder from github.

That should do the trick.

**Comment by eperrotta** [comment]
@felipebatista 
The exhaustive list you're looking for is indeed the `install-ubuntu1804-local.sh` script itself

**Comment by talheim-it** [comment]
@bures I think you can close this issue since all sources and where to find were communicated.
