### ISSUE TITLE
Can you please show how did you manage to handle this large project from scratch?

### ISSUE THREAD

**Issue by cyantarek** [Mailtrain-org/mailtrain#802]
Hi,

I want to know, how did you approach to develop this project from scratch? How did you identify what 
 features to build? And how did you prioritize them?

It will be lot useful for us.

Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
