### ISSUE TITLE
MailtrainV2 Update - How to

### ISSUE THREAD

**Issue by talheim-it** [Mailtrain-org/mailtrain#808]
Is there any option to update the development branch or just exchange file and copy the config files?

**Comment by bures** [comment]
What specifically are you trying to achieve? If you installed the development branch, then updating it just means to do a git pull, do npm install everywhere where needed, recompile the client (npm run build in client dir), and restart the server.

**Comment by talheim-it** [comment]
Thanks, worked now:

Solution:
How to:
1.) Backup everything including mysql
2.) git pull latest dev branch
3.) /opt/mailtrain/setup/reinstall-modules.sh
4.) Fix errors (if possible for depencies of packages) and update packages
5.) /opt/mailtrain/client/ > npm run build
6.) Restart the server > systemctl restart mailtrain.service
