### ISSUE TITLE
V2: send fail with number field

### ISSUE THREAD

**Issue by antn9x** [Mailtrain-org/mailtrain#809]
I got this message `ERR! Senders Sending message to 2:1 failed with error: value.replace is not a function. Dropping the message.` when send `[MERGE_SCORE]` custom NUMBER field.
Can you check this?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
