### ISSUE TITLE
VERP failing when campaign cid starts with "-"

### ISSUE THREAD

**Issue by priethor** [Mailtrain-org/mailtrain#810]
When one of my campaigns cid starts with a hyphen, if I activate VERP in the send configuration, some recipient servers reject the mail because of un illegrall address syntax of the sender:

> Dec 16 09:12:31 server postfix/smtpd[32636]: warning: Illegal address syntax from XXX.com[A.B.C.D] in MAIL command: <-NR_vvx2w.r1NMEQeyX.HJ-Q4mlJQ@XXX.com>

We have checked many possibilities and it just happens with VERP and when the campaign cid starts with "-", as just by cloning the affected campaigns solves the issue.

There are 2 ways I can see to fix this issue:
- Not allowing newly created campaign cids to start with "-", regenerating them if requried.
- Always adding to the VERP mail addresses some static prefix, but this might not be as easy as it sounds if it is fully handled by ZoneMTA.

**Comment by pangea-org** [comment]
Confirmed in here too, successfully reproduced.
Mailtrain log says : 
  
Error: Mail command failed: 501 5.1.7 Bad sender address syntax

**Comment by priethor** [comment]
This bug is currently reproducing in other parts of the application, such us links failing when the campaign starts with "-", although I cannot reproduce in a consisten way (links don't always fail)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
