### ISSUE TITLE
V2: Cannot send with api

### ISSUE THREAD

**Issue by antn9x** [Mailtrain-org/mailtrain#811]
When I send test with api: `http://localhost:3000/api/templates/3/send?access_token=`
then get error: `"error": "tx is not defined",`
It seem like in line: 678 (message-sender.js)

**Comment by renewooller** [comment]
see https://github.com/Mailtrain-org/mailtrain/issues/181

**Comment by dlecan** [comment]
> see #181

What does that mean @renewooller? Is it an issue? Not implemented?

**Comment by renewooller** [comment]
sorry - I misread that - have removed the link

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
