### ISSUE TITLE
[BUG] V2 - Unable to delete list with custom field

### ISSUE THREAD

**Issue by pangea-org** [Mailtrain-org/mailtrain#812]
Morning,
On Mailtrian v.2 after customizing _name_ fields and creating a new field in a list, I cannot delete the list itself.

Error:
```
alter table `subscription__45` drop `custom_first_name_yzqer6p_6` -
ER_CANT_DROP_FIELD_OR_KEY: Can't DROP COLUMN `custom_first_name_yzqer6p_6`;
check that it exists

```

Error from mysql side:
```
delete from lists where id='45';
ERROR 1451 (23000): Cannot delete or update a parent row: 
a foreign key constraint fails 
(`mailtrain`.`custom_fields`, CONSTRAINT `custom_fields_list_foreign` FOREIGN KEY (`list`) REFERENCES `lists` (`id`))
```

Workaround: move the list to another, unused namespace.

Thanks :)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
