### ISSUE TITLE
V2 - ER_TOO_MUCH_AUTO_TIMESTAMP_COLS: Incorrect table definition;

### ISSUE THREAD

**Issue by ZnapGaming** [Mailtrain-org/mailtrain#816]
Hi,
while saving a new list this error appears 'ER_TOO_MUCH_AUTO_TIMESTAMP_COLS: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON'.

According to our research this is due to multible defining of the 'DEFAULT' timestamp in the Code.

Any workarounds to that yet? Help is verry much appreciated!

Thanks
Znap

**Comment by sacovo** [comment]
You can try to upgrade your mysql-databse to version 5.6 or higher, this should fix the error.

See here: https://stackoverflow.com/questions/4489548/why-there-can-be-only-one-timestamp-column-with-current-timestamp-in-default-cla/17498167#17498167
