### ISSUE TITLE
How Set Date Format [RSS_ENTRY_DATE], and include a default featured image?

### ISSUE THREAD

**Issue by martinmurciego** [Mailtrain-org/mailtrain#817]
Greetings and congratulations, I think it is a very good tool. I was investigating how to implement a tool to manage newsletters that listen to updates on the rss of a particularly wordpress site.

But I don't have two questions: 
a) How do I set the other date format **[RSS_ENTRY_DATE]** in the email templates maybe dd / mm / yyyy? 

b) How do I include or make the image of a new post appear but before or after the entry summary?
Is it to use with some configuration the [RSS_ENTRY_IMAGE_URL] tag is not otherwise? Whenever I include this tag it shows me the word undefined.
Being more specific in my question b) how do I include in the email template the **default featured image** of the wordpress blog post or news?

**Comment by martinmurciego** [comment]
I could see that in the Mailtrain tool that uses this module: it includes the featured image along with the summary when I use a Wordpress plugin to include it in the RSS Feed.
`	<item>
		<title>El 18 de febrero se realizará la Jornada Internacional de Enfermería Familiar y Comunitaria</title>
		<link>https://salud.misiones.gob.ar/el-18-de-febrero-se-realizara-la-jornada-internacional-de-enfermeria-familiar-y-comunitaria/</link>
				<pubDate>Mon, 10 Feb 2020 16:44:22 +0000</pubDate>
		<dc:creator><![CDATA[Jonatan]]></dc:creator>
				<category><![CDATA[Noticias]]></category>

		<guid isPermaLink="false">https://salud.misiones.gob.ar/?p=15464</guid>
				<description><![CDATA[<img width="150" height="150" src="https://salud.misiones.gob.ar/wp-content/uploads/2020/02/jornadas-internacional-de-enfermeria-1-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" style="display: block; margin-bottom: 5px; clear:both;max-width: 100%;" link_thumbnail="" />El 18 de febrero, a partir de las 8 horas, se realizará la Jornada Internacional de Enfermería Familiar y Comunitaria en el salón auditorio de la Escuela de Enfermería de la UNaM. En este encuentro disertaran las Enfermeras Ana Romero García, Residente de Enfermería Familiar y Comunitaria de la Unidad Docente de Girona ICS- España. [&#8230;]]]></description>`

**Comment by martinmurciego** [comment]
It still did not solve the problem that the date that does not let me format it: **Mon Feb 10 2020 13:42:05 GMT-0300 (-03)**

Nor is the problem that sends emails for each new entry instead of scheduling a shipment of several new entries in a single mail. But the latter seems to be codified. If you tell me how to modify to include a [rss_erntries] tag. It would be good if they commit to give better support to the community since their tool is not mature enough.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
