### ISSUE TITLE
Api routs has no binded method for create new list

### ISSUE THREAD

**Issue by PForever** [Mailtrain-org/mailtrain#820]
I want to be able to create subscribers' list of user's category (if not exist) in runtime. Routs has base way to do that manually: 
```
router.post('/create', passport.parseForm, passport.csrfProtection, (req, res) => {
    lists.create(req.body, (err, id) => {
        if (err || !id) {
            req.flash('danger', err && err.message || err || _('Could not create list'));
            return res.redirect('/lists/create?' + tools.queryParams(req.body));
        }
        req.flash('success', _('List created'));
        res.redirect('/lists/view/' + id);
    });
});
```
But in my case I need to do it into remote program by Rest

**Comment by renewooller** [comment]
see https://github.com/Mailtrain-org/mailtrain/issues/181

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by igor-ganov** [comment]
Unfortunately, I don't work with it anymore, but thanks for information anyway :)
