### ISSUE TITLE
find login user in view?

### ISSUE THREAD

**Issue by Itsmesri** [Mailtrain-org/mailtrain#822]
Is there any way to find login user information in view? 
Example I want to show below button html to particular login email address, not to others. 

So I need a login information user id to check and show or hide based on it. Possible to check?

 <button type="submit" form="subscriber-delete" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> {{#translate}}Delete Subscription{{/translate}}</button>

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
