### ISSUE TITLE
[BUG] V2: ReferenceError: os is not definedt

### ISSUE THREAD

**Issue by finefilm** [Mailtrain-org/mailtrain#824]
Mailtrain server won’t start on fresh Ubuntu install with latest development codebase.

## Expected Behavior
Server should start as expected.

## Current Behavior
Mailtrain service fail to start. 

## Possible Solution
The problem is generated with this commit:
a950d511ec8de13668ef7137cb6432691ff24f24

Include the following line in `server/lib/builtin-zone-mta.js`:
`const os = require('os')`

## Steps to Reproduce
1. Fresh install of Ubuntu 18.04.2 LTS
2. Install Mailtrain as described [here](https://github.com/Mailtrain-org/mailtrain/blob/development/README.md)
3. Try to start service

## Context (Environment)
- Ubuntu 18.04.2 LTS
- RamNode Cloud Instance

## Detailed Description

<img width="1366" alt="Screenshot 2020-01-01 at 18 07 31" src="https://user-images.githubusercontent.com/28742944/71644112-ad8a7a80-2cc3-11ea-9aae-47f9b1ca40d5.png">

**Comment by talheim-it** [comment]
@finefilm what errors Are showing up?
Did you Follow the Installation process correctly?

**Comment by finefilm** [comment]
> @finefilm what errors Are showing up?
> Did you Follow the Installation process correctly?

Yes, I think so. I updated my issue description.
(my keyboard just gone crazy when I submitted the issue unfinished :) )

**Comment by talheim-it** [comment]
@finefilm great.

Did you run install all Modules? Run npm build too?

**Comment by finefilm** [comment]
@talheim-it Yes, but as you see the problem is generated with this commit:
a950d511ec8de13668ef7137cb6432691ff24f24

Include the following line in `server/lib/builtin-zone-mta.js`:
`const os = require('os')`

and the server is starting without a problem.

**Comment by JoseDinis1** [comment]
have exactly the same problem, new install in Ubuntu 18.04.2 LTS.
Thanks

**Comment by bures** [comment]
Thank you for spotting it. I included your fix in the development branch. It should be fine now.
