### ISSUE TITLE
V2: attachment name with unicode characters does not send messages

### ISSUE THREAD

**Issue by GadisDEV** [Mailtrain-org/mailtrain#826]
I attachted a file with name "Frühlingsgefühle_in_Kalabrien_w.pdf"  to a campaign
the test message did not arrive. 
error message in the logs: 

Jan  7 18:06:08 mailer node: ERR! Senders Sending message to 2:6 failed with error: insert into  (`data`, `id`, `send_configuration`, `type`) values ('{\"campaignId\":18,\"subject\":\"Frischgebackene Reiseideen: Frühlingsgefühle in Kalabrien 2020! [Test]\",\"attachments\":[{\"filename\":\"Frühlingsgefühle_in_Kalabrien_w.pdf\",\"path\":\"/opt/mailtrain/server/files/campaign/attachment/18/b51ec73ebe8b36e4c8315a69509fec56\",\"id\":12}],\"listId\":2,\"subscriptionId\":6}', 1, 3, 2) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(`data`, `id`, `send_configuration`, `type`) values ('{\"campaignId\":18,\"subje' at line 1. Dropping the message.

**Comment by forgeOneHQ** [comment]
@GadisDEV would be helpful to not just to send us the logs, we are missing the infos how you deployed mailtrain (docker or directly on ubuntu or centos), configuration and versions of the packages. Maybe it works with a newer MariaDB version.

Try this again and if the issue still is up please provide us all infos for this.
