### ISSUE TITLE
V2: plain-text only messages

### ISSUE THREAD

**Issue by sacovo** [Mailtrain-org/mailtrain#831]
Is it possible to send plain-text only messages in v2?

The way described in #128 does not work anymore, deleting the html content does still send the empty html message. It would be nice if it was possible to send plain-text mails on a per template/campaign base.

**Comment by bures** [comment]
I'm not sure. This use-case was never part of my requirements. You can try it out, but I guess it send the HTML. 

I'm afraid this feature is not on my high-priority list. However if you want to create a PR, I'll be happy to check it and include it if it fits. I believe the right way would be to create another template type (see client/src/templates/helpers.js). This template type would provide only ACEEditor for the text, no HTML. It would set HTML to null. Then we would have to make sure that the sender does not crash if HTML is null and the the preview and archive can work with text if no HTML is present.

**Comment by sacovo** [comment]
Thanks, I'll try it.

**Comment by Coriolan-Bataille** [comment]
Hello, 
I'm also interested in plain text only message.
Do you know if it will be schedule/build one day?
Thx for this awesome project (I'm currently trying the V2)

**Comment by forgeOneHQ** [comment]
@sacovo I am not thinking that plaintext is a necessary part at the moment. 

We can rethink of it again if there is any practiable reason to do it. Otherwise anyone who wants to support and develope it is welcome to participate on this :)
