### ISSUE TITLE
different images shown in mosaico editor and sent test email (wrong links)

### ISSUE THREAD

**Issue by magiruuvelvet** [Mailtrain-org/mailtrain#832]
I'm experiencing a weird problems with images being different in the editor and the sent email. The actual problem is that old links to other emails are being saved in the new templates, rather than links to the new uploaded ones. Hacking around in the database doesn't reflect changes in the sent emails and I'm out of ideas what to do.

Replacing the image files inside the `static` directory affects older email too so this option is not ideal. What is weird is that the editor shows the correct image, but once sent it links older unrelated images instead.

A college of me already wasted weeks debugging this problem and I'm stuck now too why Mailtrain would do this. Anyone experienced the same problem?

**Comment by nicksellen** [comment]
Maybe I experienced this problem. I had a template, and the test send from the template page showed the correct content, but the test send from a campaign that used the template had a previous revision of the content.

I resolved it by re-saving the template (literally just opening it and pressing save). After that, the test send from the campaign showed the correct content.

I found the frontend is responsible for creating the HTML from the mosaico template and saving it to the backend, in the `html` field, so I think it can happen that the HTML content does not reflect the latest changes in the mosaico template. The backend is presumably just using the `html` field, and it doesn't know that it's not been updated.

As a precaution I would ensure I've saved, reloaded, saved, etc, a few times after updating the template content, and make sure to use the campaign test send (not just the template test send).

(I'm currently using development branch version at commit 665a0d061460394b4b42ce09b5f00b82112f491e)
