### ISSUE TITLE
V2 File Upload Fail

### ISSUE THREAD

**Issue by moose999** [Mailtrain-org/mailtrain#833]
Hi,

Whenever I try to upload an image to Mosaico it fails. In the browser console I can see fileuploadfail errors. The error is "Internal Server Error":
![fileuploadfail](https://user-images.githubusercontent.com/22505336/72468478-2f56c980-37d5-11ea-9d30-2f07be0a36f6.PNG)

I believe this is permissions related. I had to set the permissions on a couple of folders in order to upload a .csv file for list import.

I am getting similar errors to https://github.com/Mailtrain-org/mailtrain/issues/721 

I am using Ubuntu 18.04, Mailtrain 2 beta Build 2019-01-12-1254

Should I look at Mailtrain logs for further info? What's the best way to do that?

**Comment by moose999** [comment]
Is anyone lese having trouble with images in Mosaico?

**Comment by g1smo** [comment]
I had the same issue and stumbled upon #515. `chown -R mailtrain:mailtrain /opt/mailtrain` has helped solve the issue.

**Comment by forgeOneHQ** [comment]
I am thinking about preparing an ansible playbook to handle it a bit easier.

Please try again with the latest version.
