### ISSUE TITLE
I want to translate the app to Swedish.  How do I do that?

### ISSUE THREAD

**Issue by johanoloflindberg** [Mailtrain-org/mailtrain#835]
I want to translate the app to Swedish.  

1. How do I do that? 
2. Is it possible to translate using file type .po / .mo? 

Best regards
Johan Lindberg

**Comment by GadisDEV** [comment]
yes, I have used poeditor to make an italian translation, but on poeditor.com the project would need to be funded to update and add more strings. 
https://poeditor.com/join/project/U7eqwdyQjl
I will happily accept donations, but even better I would contribute to some other hosted form of translation for this project. I could do Italian.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
