### ISSUE TITLE
Add API endpoints to list, add and delete lists

### ISSUE THREAD

**Issue by andresmrm** [Mailtrain-org/mailtrain#837]
The API page in the administration doesn't display endpoints to list, add or delete lists. I need them in my project... Do they exist but aren't documented? If not, would a PR adding them be accepted?

**Comment by bures** [comment]
Can you post a screenshot? Your API page should look like this:

![image](https://user-images.githubusercontent.com/1729239/73067362-c6441580-3ea8-11ea-92c5-c38ddb8aadaa.png)

**Comment by andresmrm** [comment]
It seems the same to me. Full page screenshot below. But I see no endpoint add or delete a list, or to list all lists in a namespace (these are the ones I need). Did I miss something?

![image](https://user-images.githubusercontent.com/937689/73067681-3fd80580-3ea1-11ea-91cf-28225ecc83bc.png)

**Comment by bures** [comment]
Sorry. I was reading it too quickly. Yes, you are right. There is no endpoint at the moment. Please, feel free to add it and post a PR.

**Comment by renewooller** [comment]
see https://github.com/Mailtrain-org/mailtrain/issues/181

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
