### ISSUE TITLE
Document endpoint /subscriptions/:listCid

### ISSUE THREAD

**Issue by andresmrm** [Mailtrain-org/mailtrain#839]
It seems `/subscriptions/:listCid` endpoint isn't documented.
Implementation:
https://github.com/Mailtrain-org/mailtrain/blob/master/routes/api.js#L230
Can't find it here:
https://github.com/Mailtrain-org/mailtrain/blob/development/client/src/account/API.js

It was added here, and maybe the doc was forgotten when converting the pages to React. 
https://github.com/Mailtrain-org/mailtrain/pull/348/files

---

Talking about the API docs, what is the correct format for the endpoints? I mean, the ` /api/subscribe/:listId` is first inside a card, and then without a card and with more information. The other endpoints are all without cards.
Should all endpoints be documented inside cards? Or should we just delete that first card with repeated information?
![image](https://user-images.githubusercontent.com/937689/73122234-7a61a100-3f7a-11ea-9463-e2dde609a840.png)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
