### ISSUE TITLE
Unsubscribed wrongly shows 0% in Campaign Statistics view

### ISSUE THREAD

**Issue by perborgen** [Mailtrain-org/mailtrain#841]
My "Campaign Statistics" dashboard claims that "Unsubscribed" is at 0% on every single campaign, which I know for a fact not to be true, as we're getting unsubscribes on every single campaign (they're even updated in MailTrain if I check the user manually).

The "Bounced" and "Complaints" are also at 0%, but I'm suspecting that's caused by some kind of lack of communication between SES and MailTrain.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
