### ISSUE TITLE
v2: No ip v6 only setup possible?

### ISSUE THREAD

**Issue by schleiftier** [Mailtrain-org/mailtrain#845]
Hi,

currently I am trying to setup mailtrain v2 in docker using ip v6 only. Most problems I faced were on the docker side, but now I am also facing a problem with the mailtrain container.

In my setup, I am using SMTP with an external mail server to deliver the mails. The problem is now that the name resolution inside the container still defaults to the ip v4 of the mail server, even though the mail server is perfectly reachable using ip v6. Since the host has no ip v4, the container will find no route to the mail server using ip v4 and the mail is dropped. 

Any idea how I would need to configure either mailtrain, nodejs or the container so that ip v6 is used instead?

The error message I am facing looks like this:
```
ERR! Senders Sending message to 2:220 failed with error: connect ENETUNREACH XXX.YYY.ZZZ.QQQ:465. Dropping the message.
```

I am grateful for any suggestions.

Thanks, Frederic

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
