### ISSUE TITLE
V2: Seeing issue with campaigns send counts and stalled campaigns at large volume

### ISSUE THREAD

**Issue by ericuldall** [Mailtrain-org/mailtrain#848]
I'm not sure exactly how to reproduce this other than run Mailtrain with very large lists. We have multiple lists with 2MM+ users and overall we're mailing around 8MM records a day.

Occasionally we see issues that show up in the following way:

1. A running campaign seems to be working okay. It may show total count 1MM and delivered count 100k
2. At some point then total count number is for some reason recalculated and shows closer to the delivered count (if not exactly the same). This is the point where the campaign stalls and will just be stuck in sending status but make no further progress.
3. To fix this I have to pause the campaign (however, the pause process will never actually work, so I have to go into the DB and manually set each affected campaign status to 1).
4. Then I start the campaign again...maybe it works all the way to the end or repeats back to step 2.

Is anyone else experiencing similar behavior?

I'm opening this to start the discussion as there seems to be something very difficult to debug happening at this scale. I don't see any red flags in the logs.

Other things I notice as list sizes increase:
1. Seems slow to load send configuration data on the campaign page
2. Seems slow to load total mail number on the campaign statistics page (maybe it makes more sense to calculate this as an aggregate number in the campaign table, then it can be used to verify campaign stability).
3. campaign_messages table will actually change, so it seems that for some reason when the campaign stalls it may be removing rows from that table somehow.

I will continue to debug and update any new findings here.

**Comment by ericuldall** [comment]
I just saw what I believe is the culprit in the logs. I'm seeing lock wait timeouts from innodb when trying to update the campaign_messages table. I'm wondering if this is due to that table becoming quite large. 

I will try to delete some old campaigns and see if that resolves the issue for now.

**Comment by ericuldall** [comment]
There's a few practices that seem inefficient in the way data is being stored that I think could be supported by allowing some basic prune functionality (configurable by users).

Total campaign messages can be tracked as an aggregate in the campaign table. Once a campaign is done campaign_messages table can be pruned after x days, links after y days, etc... Perhaps this should be configurable globally and per list/campaign. 

Also, I think we can get rid of file_import tables in  a similar manner.

**Comment by misterioss** [comment]
@ericuldall Hi Eric. I know it's a bit late. Could you please share your hardware configuration and software (db version) if possible? Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
