### ISSUE TITLE
html-to-text is not working

### ISSUE THREAD

**Issue by Akatana** [Mailtrain-org/mailtrain#850]
Hi, 
since the newest update I am no longer able to convert HTML to text.
I am getting a 500 Error code because /editorapi/html-to-text?editor=mosaico is not accessible.
I also tried the other editors but none is working.

Thanks for the help
Akatana

**Comment by gustavdz** [comment]
I have the same issue when I try to get the text from the HTML I got this error: "Unexpected token < in JSON at position 0"

**Comment by elitzer2** [comment]
Looks like they took down the API, see https://github.com/Mailtrain-org/mailtrain/issues/943

**Comment by bures** [comment]
Yeah. I guess they did. Any fix would be welcome.

**Comment by elitzer2** [comment]
Fixed. Can close this issue.
