### ISSUE TITLE
FEATURE REQUEST - Add Telephone to Campaign Defaults

### ISSUE THREAD

**Issue by TimesEnemy** [Mailtrain-org/mailtrain#852]
It would be slightly helpful if a telephone field was included as a campaign default variable.  Yes, I can add custom fields, but it seems a bit useful, especially given a telephone number can be linked via a tel:########### type of anchor link.

**Comment by forgeOneHQ** [comment]
@TimesEnemy can you provide infos what you exactly mean? Since you can edit the footer of the campaign to show your phone number, that user add their phone number is not really common in newsletters.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
