### ISSUE TITLE
No Automation Tab

### ISSUE THREAD

**Issue by Jdcabrera10** [Mailtrain-org/mailtrain#856]
I cant find the automation tab. Someone else installed Mailtrain for us and I’m testing it but cant find the Automation Tab. 

Do you know if I need to install something else?

![F163735A-6B5E-4078-B3BE-9E6DBE91E71A](https://user-images.githubusercontent.com/61258251/74979668-b3aff400-53f4-11ea-8eea-61ba9ec209fe.jpeg)

**Comment by boehlke** [comment]
Hi, the Automation tab should always be present since version 1.24.1 (mid 2016). See commit
https://github.com/Mailtrain-org/mailtrain/commit/b16209f23e530f3408610ffebe2c420bf5bdea74#diff-a59faefe3e35b862bc30ed9c465a1df5R120
Which version are you running?

**Comment by raneri** [comment]
Hello, I'm experiencing the same problem. I'm using Build 2021-05-25-0915
No "automation" tab. What can I do?

Thank you in advance.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
