### ISSUE TITLE
Role-based addresses like postmaster@example.com are blocked when importing

### ISSUE THREAD

**Issue by stardothosting** [Mailtrain-org/mailtrain#863]
Hello,

I am curious if there is any way to bypass the blocking of role-based addresses when importing into a list. I am migrating from another newsletter service and all emails are double opt-in. I dont see anything in the settings nor in the configuration to bypass this restriction.

**Comment by forgeOneHQ** [comment]
Since it is not clear if v1 or v2, please download the latest v2 version and try again :)

If you have troubles you are welcome to open a new issue.
