### ISSUE TITLE
302 on URL based template

### ISSUE THREAD

**Issue by aleray** [Mailtrain-org/mailtrain#864]
Hello,

I get a `Received status code 302 from <url>` when trying to use a URL based template for my campaign.

it seems to be prevent any mail from being delivered. 

However making a POST request to this URL from a browser or cURL does return a `200` code.

Any idea?

Thanks

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
