### ISSUE TITLE
One Click Integrations with SAAS & Open Source Projects

### ISSUE THREAD

**Issue by manjeshpv** [Mailtrain-org/mailtrain#865]
How to build simple ui driven integration with Mailtrain and other softwares

similar to https://mailchimp.com/integrations

Please share If any architectural plans

Example:
- Zammad - https://github.com/zammad/zammad
- Erxes - https://github.com/erxes/erxes

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
