### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by eperrotta** [Mailtrain-org/mailtrain#868]
Hello! 
Is this project still maintained?

Thanks! :)

**Comment by talheim-it** [comment]
@eperrotta , actually yes.

V2 is in development but still in testing. 

Yours,
Mathias

**Comment by gramakri** [comment]
Is there any info on the development status of the v2 branch? Would also be great to know how it's different from v1. Is it a rewrite (if so, what was bad before?)?

Thanks!

**Comment by talheim-it** [comment]
@gramakri , role based management, tree, etc.

a fully changelog is missing at the moment. But only @andris9 or @bures can give you some info on that. The mail I wrote to them never got answered.

**Comment by gramakri** [comment]
@bures Is the dev branch in some semi-stable/alpha state? If so, if you could make a release, we could help out testing. Thanks!

**Comment by forgeOneHQ** [comment]
I close this issue. I will update the packages and config and create a pull request.
