### ISSUE TITLE
href in mj-button gets prefixed with [URL_BASE]/mosaico/templates/:id/

### ISSUE THREAD

**Issue by alexeychikk** [Mailtrain-org/mailtrain#870]
I have the following code in a **mosaico** template:
```html
<mj-button href="{{@root.appUrl}}{{webVars.link}}" target="_blank">Bla bla</mj-button>
```
It is compiled to 
```html
<a href="{{@root.appUrl}}{{webVars.link}}">Bla bla</a>
```
Everything is ok at this stage.

BUT

When I create a template from this mosaico template then it is compiled to
```html
<a href="[URL_BASE]/mosaico/templates/5/{{@root.appUrl}}{{webVars.link}}">Bla bla</a>
```

How to disable this prefixing?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by talheim-it** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
