### ISSUE TITLE
Subscription Widget Templete

### ISSUE THREAD

**Issue by Zetanova** [Mailtrain-org/mailtrain#871]
The subscription widget template is not editable under "custom form".

I would need to edit the widget template that gets rendered with:
https://mydomain/subscription/xxx33345/widget?fid=2

**Comment by Zetanova** [comment]
In following route:
https://github.com/Mailtrain-org/mailtrain/blob/3b365701bb153aa93b14e830480ccfe475751a17/routes/subscription.js#L314

The fid query param with the regular web-subscription  get used,
but the cache branch is not taking the fid query param into account. 

It is only caching by request path.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
