### ISSUE TITLE
Not pulling config from production.toml

### ISSUE THREAD

**Issue by dfector** [Mailtrain-org/mailtrain#872]
I can't seem to get the site to notice anything in the config/production.toml. I've even tried rebuilding the docker image.

Specifically, I've set `https=true` and given different file names to the cert and key. It still shows that https is false and the file names are still cert.pem and key.pem.

I've resorted to changing the code in the index.js, which is obviously not the right way to customize.

**Comment by Linch1** [comment]
Actually i also had this issue, Intially i was trying to change the `.toml` files in `/config` and rebuild/removing the image with the `--no-cache` flag but didn't work, after i while I saw that there was a docker volume called `mailtrain-node-config` so I stopped the image, deleted the volume and restarted the image, finally that worked.

```
docker-compose down
docker volume rm mailtrain_mailtrain-node-config
docker-compose build --no-cache mailtrain
docker-compose up -d
```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
