### ISSUE TITLE
problems while adding images in to mosaico editor

### ISSUE THREAD

**Issue by kfam-marcink** [Mailtrain-org/mailtrain#874]
I have the 1.22.0 version installed (not the beta) and during creation of a new template I can't add images.
Well the image appears for few seconds and disappears, in the gallery I have only some blank rectangles, and in the the template question mark on blue screen.
The image even if it is added and appears, disappears after save, leave the template and re-enter.
Also if I send it - no image.
What can I do to add the graphics with mosaico editor?
BR
Marcin

**Comment by forgeOneHQ** [comment]
@kfam-marcink  please install v2 and try again. V1 is EOL.
