### ISSUE TITLE
Problem saving a template 

### ISSUE THREAD

**Issue by LucBarry** [Mailtrain-org/mailtrain#877]
When you want to save a template in mailtrain, you click on button "save" the message "Template updated" appear but if you do multiple save without close the window, when you reopen it, the save didn't work.

![template](https://user-images.githubusercontent.com/39124679/78677207-bf457480-78e7-11ea-84c2-781e53544953.png)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
