### ISSUE TITLE
custom fields in lists and own scripts

### ISSUE THREAD

**Issue by kfam-marcink** [Mailtrain-org/mailtrain#878]
Hello,
I'm wondering how to insert in the custom form Template pane some code to run a js script or how to add in the {{{body}}} some text. I've added some GDPR statement and would like to add a checkbox that if checked will enable submission of the form, or if that is not possible to add some text that "by the submission you accept the GDPR".
How can that be done?
```
<mj-raw>
                {{#if isWeb}}
                    {{> subscription_flash_messages}}
                {{/if}}
            </mj-raw>
                        {{{body}}}
            <mj-section padding-top="0">
```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
