### ISSUE TITLE
QUESTIONS: SMTP vs AWS SES configuration for Mailtrain

### ISSUE THREAD

**Issue by sasadangelo** [Mailtrain-org/mailtrain#880]
Hi,

I have a newsletter of about 5000 subscribers and I need to know which is the best approach to configure my SMTP server. I would like to spend as less as possible so I think these solutions are for me ok from an affordable point of view:
1. Postfix to configure locally
2. AWS SES, I have until 65000 send monthly for free that is enough for me.

In the beginning, I only want to send emails from my mac. I imported my subscribers from my previous email list on Aweber I do not want to add a Subscription form on my website. Is Postfix a good solution? My fear is that it cannot handle bounces and spam. What do you think?

In a couple of months, I will need a Subscription form so I need to move my deployment on a hosting to be reachable via IP and always alive.

What is the minimum number of Subscribers for which a switch to AWS SES is required?

**Comment by sasadangelo** [comment]
Hi again, no one can help?

**Comment by linelect** [comment]
Your Mailtrain app on laptop cannot handle bounces. 
I suggest using Aamzon SES, because your local version of postfix without good settings will send emails to spam folder.

**Comment by equilibrium123** [comment]
You can also use the the zonemta that comes with mailtrain when you set up mailtrain a a VPS server.
AWS smtp is plug and play. To use postfix, you will need other add ons , else it will not deliver after sometime.

**Comment by p-w** [comment]
Hi @sasadangelo,

we're using Mailtrain right now do mail to more than 800k subscribers every week.
We've used AWS SES (in Frankfurt EU central specifically) and did migrate to Postfix over two months ago.

To answer your request: if you don't have a static IP connected to your Mac or another VPS or dedicated server that you can use, go for AWS SES. To ensure that your emails actually land in inboxes and are not filtered you have to watch your IP reputation. This is barely possible on a dial-up connection.

And since you have that free volume in SES already, use it until you hit the quota. Once you have to pay for your emails think about hosting a dedicated server that's running a Postfix installation that you then can configure with SSL, DKIM, DMARC and more.

![pw-lists](https://user-images.githubusercontent.com/1020226/87284691-f171fe00-c4f6-11ea-8b6a-2127ba6a3f56.jpg)

Happy Mailin'

**Comment by vibhoo** [comment]
@p-w I have postfix and mailtrain running on my server. I cannot figure out how to connect both of them so that I can use Mailtrain UI to send emails. Can you please help me in setting up both properly ?

**Comment by p-w** [comment]
Sure, @vibhoo, just head to the "Settings" page from the menu on the upper right and scroll down to SMTP settings:

![mailtrain-postfix-server-connection](https://user-images.githubusercontent.com/1020226/87429424-0bd5d580-c5e4-11ea-9cab-28fe3d92755c.jpg)

There you need to enter your SMTP-server connection, configure if you're using an encrypted connection and enter the user account details, usually email address and password.

**Comment by vibhoo** [comment]
@p-w Thanks, One more question I'm running postfix and mailtrain on the same server with the static IP and have configured the postfix as send only and have added certificate also. So what would be my hostname and port

**Comment by p-w** [comment]
@vibhoo did you map a domain (dynamic dns or registered domain) to your IP address? If not, you should start there and set the according MX records to your IP.
For example: mydomain.com should point the MX records to your IP address that's running postfix.

**Comment by vibhoom** [comment]
@p-w I have sorted it out earlier. Thanks for your help.

**Comment by sasadangelo** [comment]
Thank you everyone for reply.

**Comment by sasadangelo** [comment]
Hi, 
I was able to run Mailtrain locally on my machine configured with Amazon SES. It is very easy but having a local installation has some limitations like you cannot track clicks. In fact, this feature masks all the email links with a link to the domain where Maintrain is installed and cannot be localhost:3000.
Another limitation is that you can send emails to already collected emails, but you need an installation on the web (i.e. a VPS) to let other people register.
Bounces and Delivery feature work properly and this is good.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
