### ISSUE TITLE
v2 plain-text doesn't get send

### ISSUE THREAD

**Issue by ox-coi-at-pro-ite** [Mailtrain-org/mailtrain#882]
Hi, 
we use Mailtrain 2 beta, Build 2019-01-12-1254

As you can see in the pic, we add plain-text to this Template content (plain text). In the sent mails, we cannot find any of these. Is it a known bug?

![mailtrain-v2beta-template-plain-text2020-04-16 22-14-58](https://user-images.githubusercontent.com/52569560/79718461-6a88fd00-82dc-11ea-963f-7e5471f38faa.png)

**Comment by bures** [comment]
Nothing I would be aware of. Can you provide exact steps to replicate this issue?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
