### ISSUE TITLE
How we pass custom field data in template send api

### ISSUE THREAD

**Issue by kamalsamra** [Mailtrain-org/mailtrain#884]
Hi,

I am using v2 and i have FIRST NAME field and its merge tag is MERGE_FIRST_NAME and i have created a template with content

Test simple [MERGE_FIRST_NAME]

so can anyone tell me how i pass data to this field in /api/templates/:templateid/send  api

**Comment by li5tun** [comment]
+1

**Comment by li5tun** [comment]
looks like tags: {'MERGE_FIRST_NAME': 'Jack'} don't work.

**Comment by li5tun** [comment]
curl -XPOST 'https://mailtrain.dfscrunch.com/api/templates/1/send?access_token=531df8baa713bdef5c9e500755cd0dca7758990b' \
--data 'EMAIL=test@example.com&SUBJECT=Test&TAGS[FOO]=bar&TAGS[TEST]=example'

**Comment by li5tun** [comment]
@kamalsamra I think the issue can be closed.

you might have these problem for this API:

- merge tag must be: TAGS[MERGE_FIRST_NAME]
- templateid must be the id from url (a number, e.g. 3)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
