### ISSUE TITLE
customize attach files

### ISSUE THREAD

**Issue by giorgioUnimi** [Mailtrain-org/mailtrain#885]
Is there a way to tie the attachments to the recipient? I would like to make sure that when sending the mail MailTrain does not attach all attachments but only one per email based on a rule, for example that the file in attach contains the name of the recipient. I looked at the code and saw that in services / sender.js it contains a function called getAttachments: is it the one that takes care of returning the files uploaded by the user in the campaign as attach files? If I change that I will achieve my goal or there are other points to intervene.
Thanks

**Comment by bures** [comment]
I'm afraid this is not on my near future plan. If there are only a few attachments that each should be delivered to a number of recipients, I would suggest creating multiple campaigns.
