### ISSUE TITLE
v2 API delete subscription gives http 500 error

### ISSUE THREAD

**Issue by mapidentity** [Mailtrain-org/mailtrain#890]
When deleting a subscriber through the api (POST /api/delete/:listId – Delete subscription), the subscriber is successfully deleted, but the response is 500 (internal server error). Expected is a 200 (ok) response.

Root cause is the router function (server/routes/api.js, '/delete/:listCid') tries to return a value from subscriptions.removeByEmailAndGet(...). This function however returns void thus causing an error.

### Reproduction steps:

- [ ] create a list
- [ ] add one or more subscribers to the list (e.g., POST /api/subscribe/:listId)
- [ ] Try to remove a subscriber by email (POST /api/delete/:listId)

**Comment by bures** [comment]
Yep. You are right. There seems to be a bug in removeByEmailAndGet.

I'll changed it to the following:

```
async function removeByEmailAndGet(context, listId, email) {
    return await knex.transaction(async tx => {
        const existing = await tx(getSubscriptionTableName(listId)).where('hash_email', hashEmail(email)).first();
        await _removeAndGetTx(tx, context, listId, existing);
        return existing;
    });
}
```

If you think this is right, I'll make it a part of my next push.

**Comment by bures** [comment]
I had a closer look and decided to change the _removeAndGetTx to return it. The removeByEmailAndGet can thus stay as it was.

```
async function _removeAndGetTx(tx, context, listId, existing) {
    await shares.enforceEntityPermissionTx(tx, context, 'list', listId, 'manageSubscriptions');

    if (!existing) {
        throw new interoperableErrors.NotFoundError();
    }

    await tx(getSubscriptionTableName(listId)).where('id', existing.id).del();

    if (existing.status === SubscriptionStatus.SUBSCRIBED) {
        await tx('lists').where('id', listId).decrement('subscribers', 1);
    }

    return existing;
}
```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
