### ISSUE TITLE
Error deploying in Firebase

### ISSUE THREAD

**Issue by iskconjaipur** [Mailtrain-org/mailtrain#891]
@bures  
Can you help me with this? Have scrambled my brain trying to figure this out. Have tried to install in CentoOS 7, Ubuntu 18.04 LTS, Windows, Docker. No luck so far. I know I must be doing something wrong, but can't seem to figure it out;

Mailtrain is not properly deploying to Firebase Hosting
![Capture4](https://user-images.githubusercontent.com/64528003/81399489-b515d080-9148-11ea-9a42-1a2286bd238b.PNG)

The log file is here:
[2020-05-08T10_30_16_819Z-debug.log](https://github.com/Mailtrain-org/mailtrain/files/4598554/2020-05-08T10_30_16_819Z-debug.log)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
