### ISSUE TITLE
Nodemailer SMTP How to change SMTP Port address

### ISSUE THREAD

**Issue by ashleyfooo** [Mailtrain-org/mailtrain#894]
I'm getting this error when i send an email using mailgun smtp as documented in this link
https://github.com/nodemailer/nodemailer/issues/165

I checked the code and saw at file config default.yaml specify port 5587. How can I change the port to 587 or 465 to fix the problem. 

Thanks, 
Ming

**Comment by bures** [comment]
Is this v1 or v2? What exactly is the problem?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
