### ISSUE TITLE
new release planned? 

### ISSUE THREAD

**Issue by ezzra** [Mailtrain-org/mailtrain#897]
is there a new release planned? because version 1.24.1 is quite old. And there is a wrong version number in the package of 1.24.1: https://github.com/Mailtrain-org/mailtrain/blob/v1.24.1/package.json#L4

**Comment by talheim-it** [comment]
@ezzra dev branch. V2 is in beta.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
