### ISSUE TITLE
v2: Tracking broadcast emails

### ISSUE THREAD

**Issue by bharatkashyap** [Mailtrain-org/mailtrain#899]
Mailtrain has built-in support for tracking mails sent as part of a campaign; for our use case, however, we need to be able to track mails sent as broadcast mails at arbitrary points in time, not necessarily as part of any specific campaign. 

Has anyone faced any success in being able to implement this feature?

As an aside, the v2 issues need a v2 label - willing to sift through the issues and add this so as to be able to help anyone searching in the future.

**Comment by bures** [comment]
Thanks a lot for offering the help with labeling the v2 issue. Please go ahead. I'm not guaranteeing that all the issue will get my attention, but it will help getting an overview anyway.

Regarding the the email, what exactly do you mean by "broadcast" emails? In Mailtrain things that go to a defined set of subscribers have to be sent as a campaign. Think of the campaign as of an email to multiple subscribers.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
