### ISSUE TITLE
Glitch (% added) in subscription confirmation email subject

### ISSUE THREAD

**Issue by SamirSaidani** [Mailtrain-org/mailtrain#902]
Using Mailtrain 1.24.1 and language="fr_FR"

When receiving the subscription confirmation email, the email subject is :
- in english: "mylist@mydomain.com: Please Confirm Subscription"
- in french: "%: Merci de confirmer l'abonnement mylist@mydomain.com"

There is a % (percentage) in the beginning of the translation.

My guess is that there is a "%s" somewhere in the code messing with the email subject.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
