### ISSUE TITLE
GET /lists/:email should return unsubscribed

### ISSUE THREAD

**Issue by Nigui** [Mailtrain-org/mailtrain#903]
Hello,
I want to know through API if an email has unsubscribed but it seems impossible for now.
Could we add this feature ?
Sincerely.

**Comment by bures** [comment]
Is this Mailtrain v1 or v2?

**Comment by Nigui** [comment]
v2

**Comment by Sanqui** [comment]
Indeed, this makes it impossible to easily check via the API whether an email is currently subscribed to a list or not. That's quite annoying.  (I'm using v1 at the moment)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
