### ISSUE TITLE
The partial tracking_scripts could not be found

### ISSUE THREAD

**Issue by cesarizu** [Mailtrain-org/mailtrain#905]
I'm getting this error randomly. Sometimes the same page will fail and some other times work correctly.

I'm running from git hash 3b365701bb153aa93b14e830480ccfe475751a17 with passenger and Apache on a shared host.

Does anybody has an idea why this might be happening?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
