### ISSUE TITLE
hashEmail and normalizeEmail helper functions puzzle me

### ISSUE THREAD

**Issue by wschopohl** [Mailtrain-org/mailtrain#906]
Hi, looking at `server/lib/helper.js` I find the following code:

```
function normalizeEmail(email) {
    const emailParts = email.split(/@/);
    if (emailParts.length !== 2) {
        return email;
    }
    const username = emailParts[0];
    const domain = emailParts[1].toLowerCase();
    return username + '@' + domain;
}

function hashEmail(email) {
    return crypto.createHash('sha512').update(normalizeEmail(email)).digest("base64");
}
```
So as far as I understand the hashed Email is the original email address where the part before the @ sign (username) is left as is and the part after the @ sign (the domain) is written in lower case.

This procedure seems overly complex and at the same time still doesn't catch scenarios, where the same email address is written slightly different. For example User@gmail.com and user@gmail.com.

So I just wondered if there is any reason for this, that I don't see right now? Otherwise I would make a PR to simplify the function to this:

```
function normalizeEmail(email) {
    return email.toLowerCase();
}
```

**Comment by bures** [comment]
This is because User@example.com and user@example.com is two different emails. The user name is case-sensitive. As this difference is very minor, Gmail implements some additional rules (such as <dot> is username is ignored, usernames are case-insensitive, etc.). However, this is specific to Gmail.

**Comment by wschopohl** [comment]
Oh I see, never gave that too much thought I guess. Thanks for explaining!
