### ISSUE TITLE
Type error: e is undefined, sending test email

### ISSUE THREAD

**Issue by julmulticonv** [Mailtrain-org/mailtrain#912]
Hi, I have an issue when I try to send a test email from templates editor.
I recently try locally with docker for development.
This is the console output for the error:
Uncaught TypeError: e is undefined
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    x http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    x http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    append http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    updateContent http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    m http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    v http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    h http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    trigger http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    set http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    setContent http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    run http://localhost:3000/grapejs/dist/js/grapesjs-mjml.min.js?v=0.0.27:69
    callRun http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    updateActive http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    m http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    v http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    h http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    trigger http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    set http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    toogleActive http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    clicked http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    I http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    i http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    w http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
grapes.min.js:3:5770
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    x http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    x http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    z http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    append http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    updateContent http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    m http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    v http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    h http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    trigger http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    set http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    setContent http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    run http://localhost:3000/grapejs/dist/js/grapesjs-mjml.min.js?v=0.0.27:69
    callRun http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    updateActive http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    m http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    v http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    h http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    trigger http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    set http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    toogleActive http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    clicked http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:3
    I http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    i http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2
    w http://localhost:3000/grapejs/dist/js/grapes.min.js?v=0.14.25:2

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
