### ISSUE TITLE
Can't delete RSS Campain

### ISSUE THREAD

**Issue by Britaliope** [Mailtrain-org/mailtrain#915]
### Description
I am not able to remove a RSS campaign which already have subcampaigns created (it works if no subcampains are created). After the confirmation popin, there is an error "contect is not defined"

As "conte**c**t" is clearly a typo, I've corrected it locally (`server/models/campaigns.js:653`), but now i have another error : "This campaign cannot be removed by user." (the action is performed with Global Master role)

### Mailtrain version
`develop` branch, last commit: `commit 564c83720b8f72b5b20daa8f6a90f8a2444a8b62` (july 18 2020)

### Steps to reproduce

- Connect using default Administrator account
- Create a RSS campaign with feed "https://lorem-rss.herokuapp.com/feed?interval=5&length=5"
- Check that subcampaigns are created
- return to campaign list page
- click on the delete button
- confirm action and read the error message

### (Dirty) workaround
(My campaigns page is a mess because of all the tests made that i can't delete)
- open `server/models/campaigns.js` in a text editor
- l.653, `s/contect/context` 😁
- comment line 649
- restart mailtrain container

**Comment by bures** [comment]
Perfect. Thanks for details. I'll check it.

**Comment by bures** [comment]
Check it now please and reopen the issue if still persists.

**Comment by Britaliope** [comment]
The fix worked. Thanks !
