### ISSUE TITLE
RSS-created subcampaigns created but never sent

### ISSUE THREAD

**Issue by Britaliope** [Mailtrain-org/mailtrain#916]
### Description

I've created a RSS campaign using https://lorem-rss.herokuapp.com/feed?interval=5&length=5 test feed. I can send test messages to test contacts, but the subcampaigns are not sent. The subcampaigns are correctly displayed in the RSS Entries
tab of the status page of the campaign, but they all stay in "Scheduled" status and the emails are never sent

### Mailtrain version
`develop` branch, last commit: `commit 564c83720b8f72b5b20daa8f6a90f8a2444a8b62` (july 18 2020)

### Steps to reproduce

- Connect using default Administrator account
- Create a RSS campaign with feed "https://lorem-rss.herokuapp.com/feed?interval=5&length=5"
- Check that subcampaigns are created
- Sub-campaigns are locked in "scheduled" state and no email is sent

**Comment by bures** [comment]
Perfect. Thanks for details. I'll check it.

**Comment by bures** [comment]
Check it now please and reopen the issue if still persists.

**Comment by Britaliope** [comment]
The fix worked. Thanks !
