### ISSUE TITLE
Import Sync (v2)

### ISSUE THREAD

**Issue by Wolfwood07** [Mailtrain-org/mailtrain#917]
Hi is there a way to process an updated list of subscribers without doing a full new CSV import?
I seem to be missing something as the system looks that is or should be a feature with the possibility to re run the import but i find no way to update the import list. The upload csv gets locked even in edit and checking the folder structure and database i see the file is not saved at all and is actually converted to a table in the database. That scenario is certainly an issue as making a new import with a system that do not even automatically maps fields with the same name is not practical.
I there a way around this? I like Mailtrain v2 over several other alternatives mainly because of the potential of the new permission system, something that even very mature solutions fails miserably. But without a practical way to update subscribers from external source i cannot advance.

**Comment by bures** [comment]
I'm afraid, you cannot update the CSV, but you can do a new CSV import. It will merge the subscribers who are already there. For instance if they unsubscribed, it won't change theirs status. So it is safe to import the same CSV (with updates) over and over again. It should not be too much a headache unless you have a lot of custom fields for which you have to specify the mapping.

**Comment by bures** [comment]
I should also say, I agree with you that the ability to re-open the import and upload a new CSV file while preserving the mapping is a good feature request. I'll look into it once I have a bit more time. Thanks for the suggestion. Of course, if you wanted to fix it yourself, I'll be happy to accept a PR.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
