### ISSUE TITLE
Questions regarding new upcoming release

### ISSUE THREAD

**Issue by trymeouteh** [Mailtrain-org/mailtrain#918]
Hello, I had some questions regarding Mailtrain.

1. Top my understanding, Mailtrain allows those who subscribe to a newsletter to optionally use PGP and have it so the newsletter is sent to the subscriber encrypted with PGP? Am I understanding this correctly?

2. With PGP emails, will the subject be encrypted also when sent to a subscriber?

3. With PGP emails, will the email address be generic and not specific to the newsletter, for example if I subscribed to a newsletter called "Cooking Tips" and the email it was sent from was cookingtips@mailtrain.org, will the email address for PGP encrypted emails come from newsletters@mailtrain.org which is more generic and not expose the newsletter itself when it is sent?

4. Can I create a newsletter on mailtrain.org without having to self host it?

5. Can anyone self host Mail Train and allow anyone to signup to their Mail Train instance and create newsletter on the instance. For example, if I self hosted Mail Train on digialfeed.com, could I have it setup so anyone can create an account on digitalfeed.com and create their own newsletters and possible pay digitialfeed.com for certain features?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
