### ISSUE TITLE
Not All emails sent

### ISSUE THREAD

**Issue by Louisias** [Mailtrain-org/mailtrain#919]
Howdy,
I am testing mailtrain on Centos7 / postfix /mailcatcher.
I have a list with over 11000 recipients and when I try to send a campain the maximum I can send is roughly 3000-4000 emails, sometimes 400...

The application simply stops without any apparent error messages in maintrain or postfix.

The config + settings look alight to me 
Is there something I can do, check, change ? Has anyone had the same issue ?
Thanks,
Vince

**Comment by bures** [comment]
You have to be more specific as what version of Mailtrain you use, what your setup looks like, etc. I would recommend to try Mailtrain v2 with the built-in Zone MTA. That's a setup to get started.

**Comment by Louisias** [comment]
Dear Tomas,
Thanks for your quick reply. After posting this message I increased the RAM of the server (from 4Gb to 8) and it worked !!!
![mailtrain](https://user-images.githubusercontent.com/15248697/88149205-0853d700-cc00-11ea-8c04-dae823e12806.jpg)

I have an other question though, is it possible to resume sending a campain when not all emails have been sent ?

Thanks again,
Vince
