### ISSUE TITLE
[suggestion] Synchronize Mailtrain permissions (shares) with an external reference.

### ISSUE THREAD

**Issue by Britaliope** [Mailtrain-org/mailtrain#921]
## Feature request

Mailtrain version : v2

### Description

I would like to synchronize Mailtrain permissions (shares) with an external reference.

I think that the simplest solution is to have a schedueled task that : 
- List users from Mailtrain, compare it with the external reference
- Generate a SQL script that update the shares_* tables according to the permissions described in the external reference
- Apply the SQL script directly in the database and make an API request to refresh the permission cache. 

The only change needed in Mailtrain app would be to implement the API route to refresh permission cache. 

A "cleaner" solution (without inserting directly in database) would be to implement an api route "import permissions" features which reads csv/json/yaml/??? and apply the changes, but this would probably need more development

What do you think of these options ?

**Comment by bures** [comment]
An API route for this would be better. Indeed. If you like to do it. I'll be happy to accept a PR. As for the permissions needed to do the API call, I would suggest a new global permission "synchronizePermissions".

**Comment by Britaliope** [comment]
> An API route for this would be better. Indeed. If you like to do it. I'll be happy to accept a PR. As for the permissions needed to do the API call, I would suggest a new global permission "synchronizePermissions".

Thanks for your feedback. The solution i'll implement will depend on the time my company allows me to spend on this (given the fact that i'm not familiar with Node and js in general). In any case i'll send a PR

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
