### ISSUE TITLE
Polish translation for v2

### ISSUE THREAD

**Issue by kikakuarta** [Mailtrain-org/mailtrain#924]
Hi,

I would like to contribute a Polish translation for v2. I will do it using the EN version file. My understanding is that I need to fork the repo, commit the changes to my fork, and create a pull request to the development branch of the original repo. Is that correct? This will be my first GitHub contribution ever, so any guidance is much appreciated.

Thanks!

**Comment by bures** [comment]
Yes. Pretty much. Thanks.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
