### ISSUE TITLE
V2 API Improvements

### ISSUE THREAD

**Issue by c-seeger** [Mailtrain-org/mailtrain#925]
Hello,

first of thanks for this awesome project it works like charm! Great work.

Since i needed a go client for your API i build one [mailtrain-go-api](https://github.com/Virtomize/mailtrain-go-api), feel free to use and share it if you want to.

While Implementing i found out a few issues when it comes to the API:

- The documentation sometimes refrences different path in the title and the curl example
  - e.g: `DELETE /api/lists/:listId – Delete List` and `curl -XDELETE 'https://mailtrain.virtomize.com/api/list/B16uVTdW?access_token=4798aa8a8ff3485e83f27c06edd8c74491b7af5f'` (see lists vs list)
- The usage of listID and listCID is not consistent as sometimes the responses give back the listID and the requests use listCID which can be a bit confusing sometimes
- `POST /api/blacklist/delete – Delete email from blacklist` is a Delete so when implementing strict REST this should use http DELETE Method resulting in a change of the path to `/api/blacklist/delete/:email`? or maybe using delete as an action verb `api/blacklist/:email/delete` since email is has no ID using the email itself in the url is a bit uncommon - so this one is just an idea to think about if that may or may not make sence
- same as above for `POST /api/delete/:listId – Delete subscription`
- the fieldnames are uppercased in the documentation but when using against the API lowercase version properly works maybe this could also be changed in the documentation
- the API documentation lacks of return types, would be awesome to have them there so no reverse engineering is needed :P

HTH to make this great project even better!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
