### ISSUE TITLE
(V2) SQL error when typing accentuated characters in some search field

### ISSUE THREAD

**Issue by Britaliope** [Mailtrain-org/mailtrain#928]
### Description

In some of the "Search" fields of the app, unicode characters (i've tried €, é, è, ç, à, §, µ ) and if one of them is typed in the search field the following error apprear: 
```
select count(*) as `recordsFiltered` from (select `lists`.`id` from `lists` inner join `namespaces` on `namespaces`.`id` = `lists`.`namespace` inner join (select distinct `entity` from `permissions_list` where `user` = 4 and `operation` in ('view')) as `permitted__list` on `permitted__list`.`entity` = `lists`.`id` where (`lists`.`name` like '%€%' or `lists`.`cid` like '%€%' or `lists`.`subscribers` like '%€%' or `lists`.`description` like '%€%' or `namespaces`.`name` like '%€%')) as `records` limit 1 - ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (ascii_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation 'like'
```

For some reason, the bug is not present when searching on Reports, Send configurations, Channels, or templates but it's there when searching on lists or campaigns

### Mailtrain version
`develop` branch, last commit: `commit 8dab13d903e8f19e8d69887977993e84c7768b0b` (Sat Jul 25 10:24:34 2020)

### Steps to reproduce
- Go on Lists page
- type "€" in the search field

**Comment by bures** [comment]
Just check if it still fits in the index. I adopted quite a lot of the schema from v1, so I don't really know the reason for ASCII charset. But I noticed in some occasions that sometimes there were issues with the length of the keys in the index. So maybe that was the reason. Keep in mind that going from ASCII to utf8mb4 is the key length * 4.

**Comment by joker-x** [comment]
Make sense, but issues with the length of the keys in utf8m4 can be solve in configuration of mysql/mariadb server and in recent versions i think works by default.

**Comment by Britaliope** [comment]
I've ran the script suggested by @joker-x and have no index issues
