### ISSUE TITLE
Edit subject / change subject language in subscription mails

### ISSUE THREAD

**Issue by chris02061996** [Mailtrain-org/mailtrain#931]
Hello,

we have two lists to subscribe, one in English and one in German. We have set the global mailtrain language to English. Thus for English subscribers there is no problem, but if a German user subscribe to our German list he/she receives mails (e.g. for confirm subscription) with an English subject.

Is there a way that German subscribers can receive a mail with German subject?

I have also a suggestion for an approach for changes in the code:

- expand the model 'lists' with the property 'language' (sql upgrade)
- upgrade view for editing list with a dropdown of available languages
- update subscription-mail-helpers.js (translate subject for list.language)

Would that work?

**Comment by c-seeger** [comment]
i have the same problem when editing the custom forms i can only change the body but not the subject line.
Also i did not find a way to change the form titles.

**Comment by lmalsch** [comment]
Is there any progess on this topic?

**Comment by l4b4r4b4b4** [comment]
I guess we'll probably have to dive into the code. :)

Where can I set the general language though? Would love to change it to German and fix English later since it's an edge case for me xD

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
