### ISSUE TITLE
ERR! DB ER_NOT_SUPPORTED_AUTH_MODE: 

### ISSUE THREAD

**Issue by carweb99** [Mailtrain-org/mailtrain#933]
Installed Mailtrain on my Contabo VPS server a couple of weeks ago by clone git and run npm install. Did some change in config for start on my domain. Run Mysql 8. Started to use it and manage to send emails with campaigns .

The install script doesn't work on centos7.8 with mysql but also a lot of other problems when installing ssl, htppd and more. 

But my VPS did an upgrade on mysql and then i got this problem with mailtrain
ERR! DB ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client.
I have set using plugin for mysql_native_password for both root and mailtrain database owner/user as suggested everywhere restarted mysql no effect.
Cant go back to mysql 5 !

**Comment by bures** [comment]
Is this Mailtrain v1 or v2? If it's v1, consider giving a try to v2.

**Comment by carweb99** [comment]
Its v2 just tried again with a fresh install using mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)
ERR! DB ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailtrain@1.24.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mailtrain@1.24.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/specialwc99/.npm/_logs/2020-08-16T14_11_14_007Z-debug.log
ERROR LOG ***************************************************************************
12 info lifecycle mailtrain@1.24.0~start: Failed to exec start script
13 verbose stack Error: mailtrain@1.24.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mailtrain@1.24.0
15 verbose cwd /home/specialwc99/public_html/mailtrain
16 verbose Linux 3.10.0-1127.18.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "start"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error mailtrain@1.24.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the mailtrain@1.24.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by carweb99** [comment]
Running centos 7.8

**Comment by carweb99** [comment]
I forgott one thing on the new installation on my other cpanel. I can create my own cpanel accounts so i will try to add a new mailtrain user and change properties on that new user and try to start the server . Let you know results later today

**Comment by bures** [comment]
If the install does not work for you, try the Docker image.

**Comment by carweb99** [comment]
I never used Docker so then i have to du some learning :)

**Comment by carweb99** [comment]
Little embarrassing but i had forgot to set environment production that points to the right configuration file ,
Closing this 
/Carsten

**Comment by carweb99** [comment]
Hi it was awhile ago, but i skipped the installer. Cloned the git project
to my host and did npm install or was it yarn and the running it with
forever, then no problem with mysql dont use mariedb . I havent used it for
a while but it worked ok. Im using mautic instead because its not listbased
but else mailtrain works fine
best Carsten

Den tis 13 okt. 2020 17:25huayolia <notifications@github.com> skrev:
