### ISSUE TITLE
(v2) Custom field type Date don't save in database

### ISSUE THREAD

**Issue by joker-x** [Mailtrain-org/mailtrain#936]
When edit a subscription and fill a custom field of type Date (in eu format) and save, mysql show this error:

```
ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '1980-07-05T00:00:00.000Z' for column `mailtrain`.`subscription__3`.`custom_fecha_de_nacimiento_697jipxjn` at row 1
```

Neither works when import a csv.

**Comment by joker-x** [comment]
Adding ``sql_mode=NO_ENGINE_SUBSTITUTION`` to my.cnf and restart mariadb server solve this problem.

But with the sql_mode by default in recent version don't work. Can we fix in the mailtrain code?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
