### ISSUE TITLE
(v2) Question: Hide Menu Items

### ISSUE THREAD

**Issue by elitzer2** [Mailtrain-org/mailtrain#940]
Hello! I see that the Reports menu item can be disabled but it seems like the others are hardcoded.

1. I would like to remove the Channels menu item as we won't be using Channels.
 a) Are Channels really for pre-filling some information that you'd otherwise manually fill out in a regular campaign? Meaning if I go to create a regular campaign and choose a Channel should it pre-fill the information that's in the Channel? Not sure if there's a bug or if I'm not entirely understanding the purpose/use of a Channel.
2. Additionally, I'd like to remove the API under administration as I don't want normal users to be able to use/generate API tokens.
3. I would also like to remove the Triggered/RSS options for campaigns for the time being.

Any thoughts on how I could do these? Thanks!

**Comment by joker-x** [comment]
Have you try to remove 'view' permission over 'channel' entity for the rol of the users?

**Comment by elitzer2** [comment]
> Have you try to remove 'view' permission over 'channel' entity for the rol of these users?

Yeah I did try removing the createChannels from [here](https://github.com/Mailtrain-org/mailtrain/blob/development/server/config/default.yaml#L316) and [here](https://github.com/Mailtrain-org/mailtrain/blob/development/server/config/default.yaml#L327) as well as making the channel config itself an empty array [here](https://github.com/Mailtrain-org/mailtrain/blob/development/server/config/default.yaml#L327). Looking at the React code there doesn't seem to be a way to define the channel menu item via config and doesn't seem like it's dynamic based on a channel view permission.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
