### ISSUE TITLE
(v2) Change email address label dynamically

### ISSUE THREAD

**Issue by elitzer2** [Mailtrain-org/mailtrain#951]
@bures So I've got a weird use case where I'd like to change the email address label on subscription forms but since it's not an actual field that can be edited, I can't. We have certain lists that we will be collecting University and Permanent email addresses so would like to clarify that on the default email address field (and make it say University Email Address). How do you think I should approach this? I'd like it on a list-by-list basis, so how do you feel about adding the email field to the custom fields and the ability to edit the label there? Can you think of any other options? Thanks!

**Comment by bures** [comment]
If this is a rather rare case (which I believe it is), I would suggest you go with custom forms. It means no changes to Mailtrain codebase itself.

Should this be a frequent issue, we have essentially two options, neither of which is perfect. One option is to add an "email label" to list settings. From the UX perspective, this is rather counterintuitive. Another option is to have email show up in custom fields. However, at many places, we count with having the field email. So you would have to make sure that it can't be deleted, etc. etc. In my view, this is very difficult to do right and capture all the corner-cases.

So the bottom line, go with custom forms. The subscription form includes subscription-custom-fields, which you can find in `server/views/subscription/partials/subscription-custom-fields.hbs`. Just copy it there and adjust as necessary. Alternatively, you can hardcode the fields if you use it only for a single list.

**Comment by elitzer2** [comment]
Awesome I’ll try that out later and close this if it works, thanks!

**Comment by elitzer2** [comment]
Ok the custom form should be sufficient. I worry about keeping the forms all up-to-date when I pull new updates in but I can manage. Would rather not have to change the codebase for it. It would be nice if you could edit the partials directly so I didn't have to make three forms (web subscribe, manage, and widget).

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
