### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by RachL** [Mailtrain-org/mailtrain#952]
Hi Mailtrain team!

I'm deeply sorry if this is the wrong place to ask, but has the Mailtrain community already a user guide?

Even just a wiki on how to use the main options?

Thanks for you feedback and congrats on this awesome tool!

**Comment by mjmayer** [comment]
Hey @RachL, I'm new to Mailtrain as well. I noticed the install guides were decent, but there wasn't much in the way of how to use the Mailtrain.

Is there something a task you want to complete? Maybe I could answer a question and add some contents to the wiki.

**Comment by RachL** [comment]
hey @mjmayer thanks for your answer. Yes I'd be happy to contribute to a wiki if that's the best place to do it. How do you propose we do it?

**Comment by mjmayer** [comment]
@bures What is the current location for documentation of mailtrain? It seems like there are pieces in `/README.md` `/docs/README.md` and the wiki.

**Comment by micmegacomm** [comment]
REMOVE

September 3, 2020 2:39 AM, "Rachel Arnould" <notifications@github.com (mailto:notifications@github.com?to=%22Rachel%20Arnould%22%20<notifications@github.com>)> wrote:
	hey @mjmayer (https://github.com/mjmayer) thanks for your answer. Yes I'd be happy to contribute to a wiki if that's the best place to do it. How do you propose we do it?

**Comment by pangea-org** [comment]
Morning!
At our association we use mailtrain v2 and we have made this [guide](https://pangea.org/wp-content/uploads/2020/03/guia_Mailtrain_maquetada_deff.pdf) for our users and we are happy to share it!
It is in catalan language and with information proper to our organization, but if you want to reuse it we will be more than happy to pass you editable version :)

Let us know if there is anything else we can do to contribute back.
Take care.

**Comment by pangea-org** [comment]
Morning!
At our association we use mailtrain v2 and we have made this [guide](https://pangea.org/wp-content/uploads/2020/03/guia_Mailtrain_maquetada_deff.pdf) for our users and we are happy to share it!
It is in catalan language and with information proper to our organization, but if you want to reuse it we will be more than happy to pass you editable version :)

Let us know if there is anything else we can do to contribute back.
Take care.

**Comment by pangea-org** [comment]
Morning!
At our association we use mailtrain v2 and we have made this [guide](https://pangea.org/wp-content/uploads/2020/03/guia_Mailtrain_maquetada_deff.pdf) for our users and we are happy to share it!
It is in catalan language and with information proper to our organization, but if you want to reuse it we will be more than happy to pass you editable version :)

Let us know if there is anything else we can do to contribute back.
Take care.

**Comment by pangea-org** [comment]
Morning!
At our association we use mailtrain v2 and we have made this [guide](https://pangea.org/wp-content/uploads/2020/03/guia_Mailtrain_maquetada_deff.pdf) for our users and we are happy to share it!
It is in catalan language and with information proper to our organization, but if you want to reuse it we will be more than happy to pass you editable version :)

Let us know if there is anything else we can do to contribute back.
Take care.

**Comment by pangea-org** [comment]
Morning!
At our association we use mailtrain v2 and we have made this [guide](https://pangea.org/wp-content/uploads/2020/03/guia_Mailtrain_maquetada_deff.pdf) for our users and we are happy to share it!
It is in catalan language and with information proper to our organization, but if you want to reuse it we will be more than happy to pass you editable version :)

Let us know if there is anything else we can do to contribute back.
Take care.

**Comment by pangea-org** [comment]
Morning!
At our association we use mailtrain v2 and we have made this [guide](https://pangea.org/wp-content/uploads/2020/03/guia_Mailtrain_maquetada_deff.pdf) for our users and we are happy to share it!
It is in catalan language and with information proper to our organization, but if you want to reuse it we will be more than happy to pass you editable version :)

Let us know if there is anything else we can do to contribute back.
Take care.

**Comment by nirjhar** [comment]
I am hoping to have a user guide too. I am really lost here. There is no definition of the interfaces and the usages. Googled and found all the entries related to how to set up or install it on the server. Is there any guide?

**Comment by lapor-kris** [comment]
> Morning! At our association we use mailtrain v2 and we have made this [guide](https://pangea.org/wp-content/uploads/2020/03/guia_Mailtrain_maquetada_deff.pdf) for our users and we are happy to share it! It is in catalan language and with information proper to our organization, but if you want to reuse it we will be more than happy to pass you editable version :)
> 
> Let us know if there is anything else we can do to contribute back. Take care.

Thanks for the user guide. You wouldn't have it in the English, would you? If you could share the editable version, I could make a translation (with help of the internet, because I don't know Catalan) :)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
