### ISSUE TITLE
Mailtrain local installation paired with gmail

### ISSUE THREAD

**Issue by ejovrh2** [Mailtrain-org/mailtrain#957]
Is it possible to install Mailtrain locally somehow paired with gmail account (os win10)? So it means mail will be send via personal gmail account. Like you edit sendmail in xampp to send from localhost via gmail.

If it is possible, how to configure file "production.toml"? I already did configuration with mysql.

Thanks in advance for any advice.

p.s. Sorry it is not issue, but I don't know where to ask.

**Comment by bures** [comment]
You can always setup Gmail as your SMTP server in Mailtrain. However, very likely you will soon hit quotas imposed by Gmail.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
