### ISSUE TITLE
standalone zone-mta docker container

### ISSUE THREAD

**Issue by Per0x** [Mailtrain-org/mailtrain#959]
Is there a zone-mta docker container to be able to run zone-mta independently on another server on Docker? (=zone-mta on docker without mailtrain)
Not being familiar with the creation of containers, I searched for examples on newer versions of zone-mta but without success.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
