### ISSUE TITLE
Updated E-Mails on import

### ISSUE THREAD

**Issue by estebanbianchi** [Mailtrain-org/mailtrain#962]
Hello, i've been a happy user of mailtrain for 6+ months now but I need to know if there is a way for existing contacts to be incorporated in every list they're imported into.

Example:

> Contact **a@a.com** is imported into List **Customers** and starts receiving e-mails from that list but i also would like to import him into the list **Best Customers** to send him mails that are only for that list. 
> 
> Now what I find is that if I import a csv into the second list containing the contact **a@a.com** it doesn't get included in the list and on the imports report only appears as updated.

Is there a configuration i'm missing or something?

Thanks!

**Comment by bures** [comment]
This is a typical case for one list with multiple segments.

**Comment by estebanbianchi** [comment]
Yes, i understand that and i'm a big fan of segments.
 I listed that as an example (maybe a bad one) but have many use cases for a user being in two lists at the same time (events signups for example).

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
