### ISSUE TITLE
Reply to All?

### ISSUE THREAD

**Issue by gebseng** [Mailtrain-org/mailtrain#965]
Hi there and sorry for misusing this as a support forum.
Is there a way to switch a mailtrain list from "Reply to List" to "Reply to All" (similar to mailman's "Group Reply" option)?

thanks, geb

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
