### ISSUE TITLE
Feature Request: Subscription to a list via email

### ISSUE THREAD

**Issue by saschafoerster** [Mailtrain-org/mailtrain#966]
I only know this feature from mailing-lists: you sent an e-mail to a defined e-mail-adress and then get subscribed to this mailinglist. Is it possible to realize this with mailtrain (of course with double opt-in as option). Or do we have only the API as an option?

**Comment by bures** [comment]
No, not at the moment. If you wanted to implement it, I would suggest you take a look at `server/services/verp-server.js`.

**Comment by saschafoerster** [comment]
As I am not really a programmer I have to wait till some one picks it up as a good idea :)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
