### ISSUE TITLE
Get custom fields on costumer forms templates v1

### ISSUE THREAD

**Issue by NunoAzevedo17** [Mailtrain-org/mailtrain#967]
Its possible to get the custom fields on costumer forms templates?

**Example**

![image](https://user-images.githubusercontent.com/34900095/94005295-fe805880-fd95-11ea-9adc-6f98095e003e.png)

![image](https://user-images.githubusercontent.com/34900095/94005400-2374cb80-fd96-11ea-907f-bc7d6846577c.png)

**Comment by tmlopes** [comment]
+ 1
