### ISSUE TITLE
not able to run docker-compose following the readme

### ISSUE THREAD

**Issue by changchichung** [Mailtrain-org/mailtrain#968]
here are my steps

```
2020-09-26 09:46:47 [min@s013 docker]$ git clone git://github.com/Mailtrain-org/mailtrain.git
Cloning into 'mailtrain'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15360 (delta 3), reused 2 (delta 0), pack-reused 15346
Receiving objects: 100% (15360/15360), 25.49 MiB | 5.92 MiB/s, done.
Resolving deltas: 100% (10640/10640), done.
2020-09-26 09:47:04 [min@s013 docker]$ cd mailtrain/
2020-09-26 09:47:28 [min@s013 mailtrain]$ ls
app.js        docker-compose.override.yml.tmpl  docs          lib           protected  services  views
BACKERS.md    docker-compose.yml                Gruntfile.js  LICENSE       public     setup     workers
CHANGELOG.md  docker-entrypoint.sh              index.js      meta.json     README.md  tasks
config        Dockerfile                        languages     package.json  routes     test
2020-09-26 09:47:29 [min@s013 mailtrain]$ cp docker-compose.yml docker-compose.yml.bak
2020-09-26 09:47:41 [min@s013 mailtrain]$ cp docker-compose.override.yml.tmpl docker-compose.yml
2020-09-26 09:48:01 [min@s013 mailtrain]$ docker-compose up -d
ERROR: The Compose file is invalid because:
Service mysql has neither an image nor a build context specified. At least one must be provided.
2020-09-26 09:48:09 [min@s013 mailtrain]$
```
how to fix the docker-compose.yml ?

**Comment by terdinatore** [comment]
You deleted the actual docker-compose.yml file. It seems you do not understand the docker-compose override mechanism. Basically, with an `docker-compose.override.yml` you can add additional instructions/attributes to an existing docker-compose.yml. This was introduced to be used in situations in which you should not or cannot change the content of the `docker-compose.yml` file. For more information see: [Making sense of docker-compose overrides](https://medium.com/it-dead-inside/making-sense-of-docker-compose-overrides-efb757460d64)

To fix your issue restore the compose files with `git reset --hard`

**PS**: You should generally google a problem before opening an issue on Github: [LMGTFY](https://lmgtfy.app/?q=Service+mysql+has+neither+an+image+nor+a+build+context+specified.+At+least+one+must+be+provided.)
