### ISSUE TITLE
ERR! DB Could not access the database. Check MySQL config and authentication credentials

### ISSUE THREAD

**Issue by killua-eu** [Mailtrain-org/mailtrain#97]
Hi, I installed mailtrain but so far am unable to make it start. The problem is the following:

```
root@mailtrain:/opt/mailtrain# node index.js 
info Using local auth 
ERR! DB Could not access the database. Check MySQL config and authentication credentials
```

i tested the username/pass to mysql over command line and it works:

`mysql --host=localhost -u root --password='************' --protocol=tcp --port=3306`

when mailtrain does the same, it fails. I'm not very fluent in debugging node apps, and after 2 hours of trying everything, including giving mailtrain the root login/pass to mysql I'm at loss on what the problem may be. Any help/pointers appreciated.

Cheers, Pavel

p.s. here the config/production.toml file:

```
root@mailtrain:/opt/mailtrain/config# cat production.toml 
user="mailtrain"
group="mailtrain"
[log]
level="error"
[www]
port=80
secret="********"
[mysql]
host="localhost"
#user="mailtrain"
#password="***************"
user="root"
password="***************"
database="mailtrain"
# Some installations, eg. MAMP can use a different port (8889)
# MAMP users should also turn on "Allow network access to MySQL" otherwise MySQL might not be accessible
port=3306
charset="utf8mb4"
timezone="local"
[redis]
enabled=true
[verp]
enabled=true
```

p.p.s.: yep, the database is there:

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mailtrain          |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.00 sec)

```

**Comment by andris9** [comment]
How do you start Mailtrain? You should have NODE_ENV environment variable set to "production", eg like this:

    $ NODE_ENV=production node index.js

**Comment by fredluhamaa** [comment]
I had similar problem in Centos 7, solved it by adding mysql user with host "%" instead of "localhost".

**Comment by renatonascalves** [comment]
I'm having the same problem! Even adding $ NODE_ENV=production 

I tested on Windows, Ubuntu 14, Ubuntu 16. :(

**Comment by inuvalogic** [comment]
this happen to me too, last week everything is fine, but now always get this error

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mailtrain@1.19.1~prestart: mailtrain@1.19.1
6 silly lifecycle mailtrain@1.19.1~prestart: no script for prestart, continuing
7 info lifecycle mailtrain@1.19.1~start: mailtrain@1.19.1
8 verbose lifecycle mailtrain@1.19.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle mailtrain@1.19.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/proplio/mailtrain/node_modules/.bin:/home/proplio/bin:/home/proplio/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle mailtrain@1.19.1~start: CWD: /home/proplio/mailtrain
11 silly lifecycle mailtrain@1.19.1~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle mailtrain@1.19.1~start: Returned: code: 1  signal: null
13 info lifecycle mailtrain@1.19.1~start: Failed to exec start script
14 verbose stack Error: mailtrain@1.19.1 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid mailtrain@1.19.1
16 verbose cwd /home/proplio/mailtrain
17 error Linux 4.4.0-45-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v7.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error mailtrain@1.19.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the mailtrain@1.19.1 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mailtrain package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mailtrain
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mailtrain
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by killua-eu** [comment]
This problem doesn't pop up any more for me. I noticed that sometimes mysql has problems when localhost is referred to with multiple IPs. So access to a user has to be granted to **all** local addresses a machine has, i.e., from: localhost, 127.0.0.1 and 127.0.1.1. I'm closing this as I can't reproduce any more.
