### ISSUE TITLE
Invalid SMTP setting

### ISSUE THREAD

**Issue by Podolyan98** [Mailtrain-org/mailtrain#970]
I have deployed the application using Docker, but I cannot configure SMPT. What am I doing wrong?

![image](https://user-images.githubusercontent.com/68119338/94900630-fa42f200-049d-11eb-86ce-a0567dbf0fdc.png)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
