### ISSUE TITLE
(v2) viewFiles and manageFiles permission block campaign creation

### ISSUE THREAD

**Issue by Britaliope** [Mailtrain-org/mailtrain#971]
## General
To create a campaign from a template, a user needs to have the `viewFile` permission on the template, and the `manageFiles` permissions on campaigns. 

I think that a user should be able to create campaigns without this permissions, without being able to see the "files" tabs, which is the behaviour when "viewAttachements" and "manageAttachements" are disabled. 

## Steps to reproduce

- Default mailtrain config, open `server/config/default.yaml` and remove `viewFiles` and `manageFiles` of your test user profile on campaigns and templates
- Reboot app
- try to create a campaign

Following errors appear in console, depending on which permission is disabled: 
```
info Denying permission template.9 viewFiles
info HTTP POST /rest/campaigns 403 63.362 ms - 73
---
info Denying permission campaign.86 manageFiles
info HTTP POST /rest/campaigns 403 53.379 ms - 73
```

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
