### ISSUE TITLE
Where is the signup form?

### ISSUE THREAD

**Issue by stoplion** [Mailtrain-org/mailtrain#974]
Where in the UI can you view the form to sign up for newsletter?

**Comment by talheim-it** [comment]
@stoplion can you explain it?

Do you want a preview or the registration form to join a newsletter?

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
