### ISSUE TITLE
DB login error during installation

### ISSUE THREAD

**Issue by huayolia** [Mailtrain-org/mailtrain#975]
Good Morning,
  I have been trying to install Mailtrain for the past few days but got stuck in one step. If I may, please give me a guidance. 
  Let me list my working environment here first.
   * System: Oracle linux 7
   * Node: Node v12
   * DB: Mysql 8
   * Redis: installed
   * Source of Mailtrain: git clone https://github.com/Mailtrain-org/mailtrain.git
     (From error messages, I guess that's mailtrian@1.24.0, but I hope it would be mailtrain V2)

  Installation instruction:
     https://www.howtoforge.com/tutorial/how-to-install-mailtrain-newsletter-application-on-centos-7/
By exactly following the steps from the link above. I met a DB connection error shown as below. Through similar installation pages, I got the same error as well. Also, I have tried several different attempts to solve it, but none of them is actually working.
Let me attach all the information about this at hand here, please give me a hand on keep working on this.
-----
Error information
node_env=production npm start

> mailtrain@1.24.0 start /opt/mailtrain
> node index.js

info Using local auth 
(node:124166) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
**ERR! DB ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mailtrain@1.24.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mailtrain@1.24.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-13T14_16_47_303Z-debug.log

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
