### ISSUE TITLE
(v2) Cannot create a new list with fresh install on centos 7, timestamp sql error

### ISSUE THREAD

**Issue by evanm** [Mailtrain-org/mailtrain#976]
While this is an issue which might merit a fix, I also welcome workarounds :D

---

Fresh install on CentOS 7 using Development branch

Attempting to create a new list using the Mailtrain UI, I (and our two other users so far) encounter this error

```
CREATE TABLE `subscription__6` ( `id` int(10) unsigned NOT NULL AUTO_INCREMENT, `cid` varchar(255) CHARACTER SET ascii NOT NULL, `email` varchar(255) CHARACTER SET utf8 DEFAULT NULL, `hash_email` varchar(255) CHARACTER SET ascii NOT NULL, `source_email` int(11) DEFAULT NULL, `opt_in_ip` varchar(100) DEFAULT NULL, `opt_in_country` varchar(2) DEFAULT NULL, `tz` varchar(100) CHARACTER SET ascii DEFAULT NULL, `status` tinyint(4) unsigned NOT NULL DEFAULT '1', `is_test` tinyint(4) unsigned NOT NULL DEFAULT '0', `status_change` timestamp NULL DEFAULT NULL, `unsubscribed` timestamp NULL DEFAULT NULL, `latest_open` timestamp NULL DEFAULT NULL, `latest_click` timestamp NULL DEFAULT NULL, `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `hash_email` (`hash_email`), UNIQUE KEY `cid` (`cid`), KEY `email` (`email`), KEY `status` (`status`), KEY `subscriber_tz` (`tz`), KEY `is_test` (`is_test`), KEY `latest_open` (`latest_open`), KEY `latest_click` (`latest_click`), KEY `created` (`created`), KEY `updated` (`updated`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; - ER_TOO_MUCH_AUTO_TIMESTAMP_COLS: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```

The important bit is 

`- ER_TOO_MUCH_AUTO_TIMESTAMP_COLS: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause`

We would love to move forward with using this development branch, as it contains some key features which are important to us. I'm happy to report more setup info if needed.

The CentOS setup functions specify mariadb-server, and that appears to be what is being used.

**Comment by pokernet** [comment]
I have the same problem !!!

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
