### ISSUE TITLE
postfixbounce service doesn't start / dies immediately after start

### ISSUE THREAD

**Issue by evanm** [Mailtrain-org/mailtrain#980]
This is a docker-based setup of v1.24.1 off `master`

I have a config file at `config/production.toml` (and it shows in the docker volume) with contents

```
[mysql]
host="mysql"

[redis]
enabled=true
host="redis"

[reports]
enabled=true

[postfixbounce]
enabled=true
port=5699
host="127.0.0.1"
```

I see that the logs for startup of the service include 

```
info POSTFIXBOUNCE Server listening on port 5699
info Service All services started
```

But the service isn't running

```
root@7abfec0cae27:/app# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl    0:02 mailtrain    
   16 ?        Sl     0:00 /usr/local/bin/node /app/services/executor.js
   22 ?        Sl     0:01 /usr/local/bin/node /app/services/sender.js
   32 pts/0    Ss+    0:00 /bin/bash
   37 pts/1    Ss     0:00 /bin/bash
   42 pts/1    R+     0:00 ps ax
```

I don't see any other logging. This setup was done following https://github.com/Mailtrain-org/mailtrain/tree/master/docs#simple-install-docker

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
