### ISSUE TITLE
Possibility for Conditional Content based on field values?

### ISSUE THREAD

**Issue by Roopesh-DMahanthi** [Mailtrain-org/mailtrain#983]
Will there be any possibility of enabling conditional email content based on field values of subscriber?

**Comment by galq5** [comment]
Hi Roopesh-DMahanth, 

You can achieve it by sending campaign only to a selected segment [ segment created by the value of X field ].

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
