### ISSUE TITLE
(v2) Posibility to skip record in list import if value is wrong.

### ISSUE THREAD

**Issue by galq5** [Mailtrain-org/mailtrain#986]
Is there a posiblity to skip record if it doesn't match validation. It would be good if user could control if skip one row that doesn't match validation or to skip whole process and throw error.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
