### ISSUE TITLE
(v2) Reports - list of the methods that are allowed to use and all JSON elements

### ISSUE THREAD

**Issue by galq5** [Mailtrain-org/mailtrain#987]
I cannot find anywhere documented list of the js methods I can use to create new report template.
Same with list of the fields I can gather in JSON to be used as input - Is there one?

Also can I make reports per whole channel or it is per campaign only?

Thank you in advance.

**Comment by saschafoerster** [comment]
I am also searching for this. :) +1

**Comment by tstrg** [comment]
I'm searching for the same :) +1

**Comment by xword9009** [comment]
Same +1

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
