### ISSUE TITLE
Dockered setup displays white screen?

### ISSUE THREAD

**Issue by pgruener** [Mailtrain-org/mailtrain#988]
Hi,

I started using the provided compose file and configurred the dns records as described.

This part isnt clear to me:

> To make this publicly accessible, you should add reverse proxy that makes these endpoints publicly available over HTTPS. If using the proxy, you also need to set the URL bases and --withProxy parameter via MAILTRAIN_SETTING as shown below.

There is nothing "shown belown".

I googled for this parameter and ended up with setting it like this in my compose file:

```
environment:
- ....
- MAILTRAIN_SETTING=--trustedUrlBase https://mailtrain.my-domain.de --sandboxUrlBase https://sbox.mailtrain.my-domain.de --publicUrlBase https://lists.my-domain.de --withProxy

```
When I started it now, the server gave me the error, that "MAILTRAIN_SETTING shouldnt be used anymore as noted in README.md" .. But also I cannot find anything for it. Even not how to make it correct.

I then used those parameters within the command property

`command: --trustedUrlBase https://mailtrain.my-domain.de --sandboxUrlBase https://sbox.mailtrain.my-domain.de --publicUrlBase https://lists.my-domain.de --withProxy`

This is appended to the entrypoint's call, but doesnt help.

In the services log all seems fine:

`mailtrain.1.y1x5kyfb88on@h4    | info Triggers Starting trigger check service
mailtrain.1.y1x5kyfb88on@h4    | info GDPR Starting GDPR cleanup service
mailtrain.1.y1x5kyfb88on@h4    | info ReportProcessor Trying to start worker because runningWorkersCount=0 maxWorkersCount=1
mailtrain.1.y1x5kyfb88on@h4    | info ReportProcessor No more reports to start a worker for
mailtrain.1.y1x5kyfb88on@h4    | info Service All services started
mailtrain.1.y1x5kyfb88on@h4    | info HTTP GET / **200** 46.893 ms - -`

Especially the requests I'm doing in the browser are received. And theyre also returning something.

BUT 

The sourcefiles within the returned html dont follow the domain names, that I tried to provide:

```
...
<script src="http://localhost:3000/static-npm/jquery.min.js"></script>
<script src="http://localhost:3000/static-npm/popper.min.js"></script>
<script src="http://localhost:3000/static-npm/bootstrap.min.js"></script>
<script src="http://localhost:3000/static-npm/coreui.min.js"></script>
...
```

I think that's a minor issue, at least in the docs, how to correctly declare the endpoints with mailtrain/mailtrain:latest .

Hope you can help.. if I left anything, just let me know.

Thanks alot!

**Comment by pgruener** [comment]
Ok, finally I got it using the right environment variables - just in case any other people might run into the same problems:
```
    environment:
      ...
      - URL_BASE_TRUSTED=https://mailtrain.my-domain.de
      - URL_BASE_SANDBOX=https://sbox.mailtrain.my-domain.de
      - URL_BASE_PUBLIC=https://lists.my-domain.de

```

Anyways I'd think it would be correct, to remove the information about "--withProxy parameter via MAILTRAIN_SETTING" if it's right, that it isnt used anymore and could lead to misinterpretation.

Or did I just misunderstand?

**Comment by jeff-h** [comment]
Thanks for your followup post, it got me going :) Personally, the `URL_BASE_*` instructions didn't seem entirely clear to me — I didn't realise these need to be the *external* (proxied) domains as opposed to the docker networking container names.

I also added the following to your above environment variables in my docker-compose.yml:

```yaml
    environment:
      - WWW_PROXY=true
```

Not sure if it's needed as it sounds like you don't have it. But it works for me :)

**Comment by bures** [comment]
Glad that you resolved it. --withProxy is no longer user, but WWW_PROXY is. It is needed if you put Mailtrain behind HTTPD or similar. If you don't put it there, the IPs in the campaign statistics will be wrong.

If you feel the documentation is misleading and should be fixed/amended, please do so. I'll be happy to accept a constructive imporovement as a PR. Thanks.

**Comment by jeff-h** [comment]
Ha, turns out it's easier to complain that to word up something that fixes it :) Anyway, I have attempted it: https://github.com/Mailtrain-org/mailtrain/pull/1090
