### ISSUE TITLE
[V2] German translation not beeing loaded

### ISSUE THREAD

**Issue by taenzerme** [Mailtrain-org/mailtrain#989]
https://github.com/Mailtrain-org/mailtrain/blob/7209e97175dee5043ad08acbcce38e43ee9cf8cc/server/lib/translate.js#L17

The german translation is currently not loaded, which explains why it's not working ;-)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
