### ISSUE TITLE
Mailtrain v2 beta: SMTP Test mail tries to send to Amazon

### ISSUE THREAD

**Issue by jcalfee** [Mailtrain-org/mailtrain#991]
Mailtrain picked up my SMTP `username` but instead of using SMTP `hostname` it used Amazon.

I created a SMTP configuration and enabled logging (in the UI: "Log SMTP transactions") and configured it to use smtp.sendgrid.net (a host other than Amazon) then sent a campaign to a test user.

This is using the latest image from Docker, which is a build from the last commit to the `development` branch.

```
mailtrain_1  | info HTTP PUT /rest/restricted-access-token 200 6.042 ms - -
mailtrain_1  | info Mail Created new pool resource #1
mailtrain_1  | info HTTP POST /rest/permissions-check 200 25.660 ms - 94
mailtrain_1  | info Mail Secure connection established to **54.160.61.157**:465
mailtrain_1  | info Mail User "YXBpa2V5" **failed to authenticate**
mailtrain_1  | info Mail Connection #1 was closed
mailtrain_1  | ERR! Mail Pool Error for #1: Invalid login: 535 Authentication failed: Bad username / password
mailtrain_1  | ERR! Mail Send Error: Invalid login: 535 Authentication failed: Bad username / password
mailtrain_1  | info Mail Connection closed
mailtrain_1  | ERR! Senders Sending message to 1:1 failed with error: Invalid login: 535 Authentication failed: Bad username / password. Dropping the message.
```

The mail user "YXBpa2V5" is correct.  However, the issue is, the IP address `54.160.61.157` resolves to Amazon:
```bash
$ nslookup 54.160.61.157
157.61.160.54.in-addr.arpa	name = ec2-54-160-61-157.compute-1.amazonaws.com.
```

The `send_configurations` table has the correct hostname.

mailer_type  | mailer_settings
------------ | -------------
generic_smtp | {"maxConnections":5,"throttling":100,"logTransactions":true,"hostname":"smtp.sendgrid.net","port":0,"encryption":"TLS","useAuth":true,"user":"YXBpa2V5","password":"***","allowSelfSigned":false,"maxMessages":100}

Here are the same settings in the UI:

![image](https://user-images.githubusercontent.com/204121/101243795-2c541880-36c8-11eb-8ade-0d8eedcd2a8c.png)

**Comment by jcalfee** [comment]
Sending the campaign worked, it sent through sendgrid.  

```bash
mailtrain_1  | info Mail Created new pool resource #1
mailtrain_1  | info Mail Secure connection established to 3.234.124.254:465
mailtrain_1  | info Mail User "apikey" authenticated
mailtrain_1  | info Mail Sending message <d3ae0a5e-6e49-4ded-cd61-8d98f509045d@my-domain.com> using #1 to <test_user@another-domain.com>
mailtrain_1  | info Mail <10915 bytes encoded mime message (source size 10746 bytes)>
```
Note: I realized I did not need to base64 encode the username.

However, shortly after an aborted connection showed up in the log:

```
mysql_1      | 2020-12-05 13:31:39 30 [Warning] Aborted connection 30 to db: 'mailtrain' user: 'mailtrain' host: '172.23.0.2' (Got timeout reading communication packets)
```

**Comment by jcalfee** [comment]
It seemed to snapped out of it at some point after I sent a test email from a campaign editor.  I went back and re-tested, the Campaign "Test" works now too.  I probably should leave this open though, I noticed this issue on basically a fresh install.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
