### ISSUE TITLE
Manual Bounce Handling with Power MTA SMTP

### ISSUE THREAD

**Issue by equilibrium123** [Mailtrain-org/mailtrain#996]
Is there any better way to handling bounce email addresses? I use an external smtp server which I built using power mta. I collect bounce from the powermta server and want to make the emails an bounce in my mailtrain platform.

A workaround I have been using is to collect the bounce emails and upload them in mailtrain list and mark them as unsubscribe when uploading as csv file.  There is no feature to upload bulk emails as bounce except by adding one after the other, which might be time consuming. 

Anybody have experience on this too?

**Comment by xword9009** [comment]
Did you ever get a solution to this? I'm facing a similar problem, my - as yet untested - workaround is to haul the data from the raw bounce messages with awk and generate an sql update query.

**Comment by equilibrium123** [comment]
I think the best solution could be VERP handling in mailtrain. This should pick all bounces and mark them in the list

**Comment by xword9009** [comment]
I'm lazy and was hoping for a shortcut :-D. It was for a past campaign so was a bit of a longshot; it shouldn't be insurmountable to match up addresses with the results after the fact. I have VERP enabled now so current/future campaigns aren't a problem.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.

**Comment by talheim-it** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
