### ISSUE TITLE
mailtrain v2 beta api

### ISSUE THREAD

**Issue by jsjonas** [Mailtrain-org/mailtrain#998]
Hi

I want to execute a request i took from the API tab, from my computer to the mail server and it gives me an error:
get request : 
https://mailer1.marketing66.com/api/subscriptions/P5wKkz-e7?access_token=c5307ece2415b203c48fcbfdc8c97bf07a4bb884

error: 
{
    "error": "Permission denied",
    "data": []
}

i have 2 namespace on the root, i setted all configs properly i dont undestand why it doesnt gives me authorization

**Comment by l4b4r4b4b4** [comment]
Make sure the given Id P5wKkz-e7 exists as list. By default mailtrain does not give you an example command with an existing list id from your installation.

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
