### ISSUE TITLE
mailtrain.org down?

### ISSUE THREAD

**Issue by Jean-Cote** [Mailtrain-org/mailtrain#999]
I cannot access [mailtrain.org](https://mailtrain.org) (linked in the Readme). [Uptrends](https://www.uptrends.com/tools/uptime?toolRequestGuid=549d147a-10b1-4805-80be-bcc9d177f4ff) also thinks that it is offline. Could you please check? Thanks! 🙏

**Comment by allenfuller** [comment]
Noticing that as well.

**Comment by talheim-it** [comment]
@andris9 @bures do you know anything about it?

Also do we have any status for the project? Since I saw not much activity here since October (merge wise)

**Comment by bures** [comment]
It was hosted on someone's server. I'm not exactly sure anymore which one it was. I guess, we can just setup something on github.io and route the domain there. I guess there is not much more needed than the README.md. I can then update the DNS. Any volunteer? Thanks.

**Comment by talheim-it** [comment]
@bures I can also offer to host the page of mailtrain.org on one of my servers. Let me know how can I help and I will do!

**Comment by bures** [comment]
That would be great. Last time, we just had a dummy Mailtrain instance and served the public page. But maybe this time, we can just have an HTTP redirect to Mailtrain's github. If you could set up that redirect for mailtrain.org domain, I just setup the DNS to point to your server. Thanks. 

Of course, if you wanted to give a try to a full fledge website, I'm not against. I just don't have time to do it. Should we have a full-fledge website, I would suggest we use GitHub pages for that.

Thank you.

**Comment by talheim-it** [comment]
I can offer to build website with https://gohugo.io or https://wagtail.io

We could host the code in mailtrain-org too for Hugo.

So maybe we get more competitors for the website too for translation.

**Comment by bures** [comment]
Sounds good to me. Thanks. Once you are done, please let me know the IP I should point the mailtrain.org A-record to.

**Comment by talheim-it** [comment]
@bures I setup a new server for hugo at the weekend and let you know the IP as soon as it is up.

**Comment by agustingianni** [comment]
I think email is down now, I've tried to send a security report but the emails bounced. Is there a way to reach one of the maintainers? Thanks.

**Comment by ClassyCodingClara** [comment]
I saw  #1204 so I suppose that we will have a website and demo instance this year? 🥳

**Comment by forgeOneHQ** [comment]
@ClassyCodingClara yes, I installed a server and just need to finish the installation. Just a lack of time from my side but the plan is to implement the option that the community can help to work on the documentation with hugo :)

**Comment by forgeOneHQ** [comment]
We are going to start with the development and testing of mailtrain v3 in the next weeks.

You are welcome to help us with the testing as soon as the first release candidate is available.
